name: Create and Upload Combined Report
description: Create and upload a combined CI report
inputs:
  workflow_config:
    description: "Workflow config"
    required: true
  final:
    description: "Control whether the report is final or a preview"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Create workflow config
      shell: bash
      run: |
        mkdir -p ./ci/tmp
        cat > ./ci/tmp/workflow_config.json << 'EOF'
        ${{ inputs.workflow_config }}
        EOF

    - name: Create and upload workflow report
      env:
        PR_NUMBER: ${{ github.event.pull_request.number || 0 }}
        ACTIONS_RUN_URL: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
        COMMIT_SHA: ${{ steps.set_version.outputs.commit_sha || github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        FINAL: ${{ inputs.final }}
      shell: bash
      run: |
        pip install clickhouse-driver==0.2.8 numpy==1.26.4 pandas==2.0.3 jinja2==3.1.5

        CMD="python3 .github/actions/create_workflow_report/create_workflow_report.py"
        ARGS="--actions-run-url $ACTIONS_RUN_URL --known-fails tests/broken_tests.json --cves --pr-number $PR_NUMBER"

        set +e -x
        if [[ "$FINAL" == "false" ]]; then
          REPORT_LINK=$($CMD $ARGS --mark-preview)
        else
          REPORT_LINK=$($CMD $ARGS)
        fi

        echo $REPORT_LINK

        if [[ "$FINAL" == "true" ]]; then
          IS_VALID_URL=$(echo $REPORT_LINK | grep -E '^https?://')
          if [[ -n $IS_VALID_URL ]]; then
            echo "Workflow Run Report: [View Report]($REPORT_LINK)" >> $GITHUB_STEP_SUMMARY
          else
            echo "Error: $REPORT_LINK" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
        fi
