#
# Makefile
#
# $Id: //poco/Main/template/sample.make#4 $
#
# Makefile for Poco download
#

include $(POCO_BASE)/build/rules/global

objects = ifconfig

target         = ifconfig
target_version = 1
target_libs    = PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/exec
