#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/md5/Makefile#1 $
#
# Makefile for Poco md5
#

include $(POCO_BASE)/build/rules/global

objects = md5

target         = md5
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
