#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/NotificationQueue/Makefile#1 $
#
# Makefile for Poco NotificationQueue
#

include $(POCO_BASE)/build/rules/global

objects = NotificationQueue

target         = NotificationQueue
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
