self-hosted-runner:
  labels:
    - altinity-builder
    - altinity-func-tester
    - altinity-func-tester-aarch64
    - fuzzer-unit-tester
    - altinity-style-checker
    - altinity-style-checker-aarch64
    - release-maker
