stages:
  - build
build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker build -t yandex/clickhouse-builder ./docker/builder
  script:
    - docker run --rm -v ./docker/builder/build.sh:/build.sh -v ./:/server yandex/clickhouse-builder
    - docker push yandex/clickhouse
  tags:
    - docker