stages:
  - build
build:
  stage: build
  services:
    - docker:dind
  before_script:
    - cd ./docker/builder
    - docker info
    - docker build -t yandex/clickhouse-builder .
  script:
    - docker run --rm -v $(realpath ../..):/server yandex/clickhouse-builder
  tags:
    - docker