stages:
  - build
build:
  stage: build
  script:
    - cd ./docker/builder
    - docker build -t yandex/clickhouse-builder .
    - docker run --rm -v $(realpath ../..):/server -it yandex/clickhouse-builder
