stages:
  - builder
  - build
builder:
  stage: builder
  when: manual
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab -p nopasswd $CI_REGISTRY
    - docker build -t yandex/clickhouse-builder ./docker/builder
  script:
    - docker tag yandex/clickhouse-builder $CI_REGISTRY/yandex/clickhouse-builder
    - docker push $CI_REGISTRY/yandex/clickhouse-builder
  tags:
    - docker
build:
  stage: build
  when: manual
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab -p nopasswd $CI_REGISTRY
    - docker pull $CI_REGISTRY/yandex/clickhouse-builder
    - ls ${CI_PROJECT_DIR}
  script:
    - docker run --rm --volumes-from "${HOSTNAME}-build" --workdir "${CI_PROJECT_DIR}" --command "${CI_PROJECT_DIR}/docker/builder/build_gitlab_ci.sh" $CI_REGISTRY/yandex/clickhouse-builder
  artifacts:
    paths:
      - ./build/
  tags:
    - docker