stages:
  - build
build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab -p nopasswd $CI_REGISTRY
    - docker build -t yandex/clickhouse-builder ./docker/builder
  script:
    - docker push yandex/clickhouse-builder
    - docker run --rm --volumes-from "${HOSTNAME}-build" -v $(pwd)/docker/builder/build.sh:/build.sh -v $(pwd):/server yandex/clickhouse-builder
    - docker tag yandex/clickhouse $CI_REGISTRY/yandex/clickhouse
    - docker push $CI_REGISTRY/yandex/clickhouse
  tags:
    - docker