stages:
  - builder
  - build
variables:
  GIT_SUBMODULE_STRATEGY: recursive
builder:
  stage: builder
  when: manual
  services:
    - docker:dind
  before_script:
    - docker info
    - apk add --no-cache git binutils ca-certificates
    - docker login -u gitlab -p nopasswd $CI_REGISTRY
    - docker build -t yandex/clickhouse-builder ./docker/builder
  script:
    - docker tag yandex/clickhouse-builder $CI_REGISTRY/yandex/clickhouse-builder
    - docker push $CI_REGISTRY/yandex/clickhouse-builder
  tags:
    - docker
build:
  stage: build
  when: manual
  services:
    - docker:dind
  before_script:
    - apk add --no-cache git binutils ca-certificates
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - docker info
    - docker login -u gitlab -p nopasswd $CI_REGISTRY
    - docker pull $CI_REGISTRY/yandex/clickhouse-builder
    - ls ${CI_PROJECT_DIR}
  script:
    - docker run --rm --volumes-from "${HOSTNAME}-build" --workdir "${CI_PROJECT_DIR}" --env CI_PROJECT_DIR=${CI_PROJECT_DIR} $CI_REGISTRY/yandex/clickhouse-builder /build_gitlab_ci.sh
  artifacts:
    paths:
      - ./dbms/src/Server/clickhouse
  tags:
    - docker