stages:
  - builder
  - build
builder:
  stage: builder
  when: manual
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab -p nopasswd $CI_REGISTRY
    - docker build -t yandex/clickhouse-builder ./docker/builder
  script:
    - docker tag yandex/clickhouse-builder $CI_REGISTRY/yandex/clickhouse-builder
    - docker push $CI_REGISTRY/yandex/clickhouse-builder
  tags:
    - docker
build:
  stage: build
  when: manual
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab -p nopasswd $CI_REGISTRY
    - docker pull $CI_REGISTRY/yandex/clickhouse-builder
  script:
    - docker run --rm --volumes-from "${HOSTNAME}-build" -v $(pwd)/docker/builder/build.sh:/build.sh -v $(pwd):/server $CI_REGISTRY/yandex/clickhouse-builder
  artifacts:
    paths:
      - ./build/
  tags:
    - docker