stages:
  - build
build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
    - docker build -t yandex/clickhouse-builder ./docker/builder
  script:
    - docker run --rm -v $CI_PROJECT_DIR/docker/builder/build.sh:/build.sh -v $CI_PROJECT_DIR:/server yandex/clickhouse-builder
    - docker push yandex/clickhouse
  tags:
    - docker