pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#status-failure=0"
      - "base=master"
    actions:
      merge:
        method: merge
