pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "#status-failure=0"
      - "base=master"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - "author~=^dependabot(|-preview).*$"
      - "#status-failure=1" # Description check
      - "base=master"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: Automatic close for Dependabot pull requests
    conditions:
      - "author~=^dependabot(|-preview).*$"
      - "#status-failure>1"
      - "base=master"
    actions:
      merge:
        method: close
pull_request_rules:
  - name:Aautomatic merge for ImgBot pull requests
    conditions:
      - "author=imgbot[bot]"
      - "#status-failure=1" # Description check
      - "base=master"
    actions:
      merge:
        method: merge
