pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - "status-success=Marker check"
      - "#status-failure=0"
      - "base=master"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - "author~=^dependabot(|-preview).*$"
      - "#status-failure=1" # Description check
      - "base=master"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: Automatic close for Dependabot pull requests
    conditions:
      - "author~=^dependabot(|-preview).*$"
      - "#status-failure>1"
      - "base=master"
    actions:
      merge:
        method: close
pull_request_rules:
  - name: Automatic merge for ImgBot pull requests
    conditions:
      - "author=imgbot[bot]"
      - "#status-failure=1" # Description check
      - "base=master"
    actions:
      merge:
        method: merge
pull_request_rules:
  - name: Automatic add pr-documentation label via description
    conditions:
      - "body~=- Documentation"
    actions:
      label:
        add: ["pr-documentation"]
pull_request_rules:
  - name: Automatic add pr-feature label
    conditions:
      - "body~=- New Feature"
    actions:
      label:
        add: ["pr-feature", "doc-alert"]
pull_request_rules:
  - name: Automatic add pr-bugfix label
    conditions:
      - "body~=- Bug Fix"
    actions:
      label:
        add: ["pr-bugfix", "no-docs-needed"]
pull_request_rules:
  - name: Automatic add pr-improvement label
    conditions:
      - "body~=- Improvement"
    actions:
      label:
        add: ["pr-improvement"]
pull_request_rules:
  - name: Automatic add pr-performance label
    conditions:
      - "body~=Performance Improvement"
    actions:
      label:
        add: ["pr-performance", "no-docs-needed"]
pull_request_rules:
  - name: Automatic add pr-build label
    conditions:
      - "body~=Build.*Improvement"
    actions:
      label:
        add: ["pr-build", "no-docs-needed"]
pull_request_rules:
  - name: Automatic add pr-non-significant label
    conditions:
      - "body~=- Non-significant"
    actions:
      label:
        add: ["pr-non-significant", "no-docs-needed"]
