[tool.pylint.BASIC]
max-module-lines=2000
# due to SQL
max-line-length=200
# Drop/decrease them one day:
max-branches=50
max-nested-blocks=10
max-statements=200

[tool.pylint.FORMAT]
#ignore-long-lines = (# )?<?https?://\S+>?$

[tool.pylint.'MESSAGES CONTROL']
          # pytest.mark.parametrize is not callable (not-callable)
disable = '''
          bare-except,
          broad-except,
          cell-var-from-loop,
          fixme,
          invalid-name,
          missing-docstring,
          redefined-outer-name,
          too-few-public-methods,
          too-many-arguments,
          too-many-instance-attributes,
          too-many-locals,
          too-many-public-methods,
          wildcard-import,
          '''

[tool.isort]
profile = "black"
src_paths = ["src", "tests/ci", "tests/sqllogic", "tests/queries", "tests/integration"]

[tool.black]
required-version = 24

[tool.pylint.SIMILARITIES]
# due to SQL
min-similarity-lines=1000
