DROP TABLE IF EXISTS t;
DROP TABLE IF EXISTS mv;
DROP TABLE IF EXISTS `.inner.mv`;

CREATE TABLE t (x UInt8) ENGINE = Null;
CREATE VIEW IF NOT EXISTS mv AS SELECT * FROM t;

DROP TABLE t;
DROP TABLE mv;
