DROP TABLE IF EXISTS null;

CREATE TABLE null (x UInt8) ENGINE = Null;
DESCRIBE TABLE null;

ALTER TABLE null ADD COLUMN y String, MODIFY COLUMN x Int64 DEFAULT toInt64(y);
DESCRIBE TABLE null;

DROP TABLE null;
