DROP TABLE IF EXISTS mergetree;

CREATE TABLE mergetree (x UInt64) ENGINE = MergeTree ORDER BY x;
INSERT INTO mergetree VALUES (1);

SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM mergetree WHERE x IN (SELECT * FROM numbers(10000000))))))))))));

SET force_primary_key = 1;

SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM (SELECT * FROM mergetree WHERE x IN (SELECT * FROM numbers(10000000))))))))))));

DROP TABLE mergetree;
