[package]
edition = "2021"
name = "_ch_rust_prql"
version = "0.1.0"

[dependencies]
anstream = {version = "0.6.12"}
prqlc = {version = "0.11.3", default-features = false}
serde_json = "1.0"

[lib]
crate-type = ["staticlib"]
