from testflows.core import *

@TestFeature
@Name("syntax")
def feature(self):
    Feature(run=load("rbac.tests.syntax.create_user", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.alter_user", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.drop_user", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_create_user", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.create_role", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.alter_role", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.drop_role", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_create_role", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.grant_role", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.grant_privilege","feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_grants", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.revoke_role", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.revoke_privilege","feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.create_row_policy", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.alter_row_policy", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.drop_row_policy", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_create_row_policy", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_row_policies", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.create_quota", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.alter_quota", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.drop_quota", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_create_quota", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_quotas", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.create_settings_profile", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.alter_settings_profile", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.drop_settings_profile", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.show_create_settings_profile", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.set_default_role", "feature"), flags=TE)
    Feature(run=load("rbac.tests.syntax.set_role","feature"), flags=TE)