from testflows.core import *

@TestFeature
@Name("syntax")
def feature(self):
    Feature(run=load("syntax.create_user", "feature"), flags=TE)
    Feature(run=load("syntax.alter_user", "feature"), flags=TE)
    Feature(run=load("syntax.drop_user", "feature"), flags=TE)
    Feature(run=load("syntax.show_create_user", "feature"), flags=TE)
    Feature(run=load("syntax.create_role", "feature"), flags=TE)
    Feature(run=load("syntax.alter_role", "feature"), flags=TE)
    Feature(run=load("syntax.drop_role", "feature"), flags=TE)
    Feature(run=load("syntax.show_create_role", "feature"), flags=TE)
    Feature(run=load("syntax.grant_role", "feature"), flags=TE)
    Feature(run=load("syntax.grant_privilege","feature"), flags=TE)
    Feature(run=load("syntax.show_grants", "feature"), flags=TE)
    Feature(run=load("syntax.revoke_role", "feature"), flags=TE)
    Feature(run=load("syntax.revoke_privilege","feature"), flags=TE)
    Feature(run=load("syntax.create_row_policy", "feature"), flags=TE)
    Feature(run=load("syntax.alter_row_policy", "feature"), flags=TE)
    Feature(run=load("syntax.drop_row_policy", "feature"), flags=TE)
    Feature(run=load("syntax.show_create_row_policy", "feature"), flags=TE)
    Feature(run=load("syntax.show_row_policies", "feature"), flags=TE)
    Feature(run=load("syntax.create_quota", "feature"), flags=TE)
    Feature(run=load("syntax.alter_quota", "feature"), flags=TE)
    Feature(run=load("syntax.drop_quota", "feature"), flags=TE)
    Feature(run=load("syntax.show_create_quota", "feature"), flags=TE)
    Feature(run=load("syntax.show_quotas", "feature"), flags=TE)
    Feature(run=load("syntax.create_settings_profile", "feature"), flags=TE)
    Feature(run=load("syntax.alter_settings_profile", "feature"), flags=TE)
    Feature(run=load("syntax.drop_settings_profile", "feature"), flags=TE)
    Feature(run=load("syntax.show_create_settings_profile", "feature"), flags=TE)
    Feature(run=load("syntax.set_default_role", "feature"), flags=TE)
    Feature(run=load("syntax.set_role","feature"), flags=TE)