name: CheckWorkflowResults

description: Check overall workflow status and post error to slack if any

inputs:
  needs:
    description: github needs context as a json string
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Check Workflow
      shell: bash
      run: |
        export WORKFLOW_RESULT_FILE="/tmp/workflow_results.json"
        cat > "$WORKFLOW_RESULT_FILE" << 'EOF'
        ${{ inputs.needs }}
        EOF
        python3 ./tests/ci/ci_buddy.py --check-wf-status
