#!/usr/bin/env python3
"""
Guard for the autogenerated regions of docs pages.

Reference pages under ``docs/`` embed machine-generated content between
``{/*AUTOGENERATED_START*/}`` and ``{/*AUTOGENERATED_END*/}`` markers (the MDX
comment form; the generators also emit prefixed variants such as
``AUTOGENERATED_METRICS_START``). That region is produced from the
documentation embedded in the ClickHouse source (``system.documentation``) by
``autogenerate/autogenerate_docs.py`` and is overwritten on every run -- so a
hand-edit to it is silently lost at the next regeneration.

This check fails a pull request that changes any line inside those markers.
Everything else stays editable: adding or removing whole pages, changing
frontmatter, and editing prose outside the markers are all allowed.

For each changed ``.mdx`` page it locates the marker regions (line ranges) in
the page at HEAD and asks whether any line the pull request touched falls
inside one. A newly added page is left alone -- its whole body is "new", and
adding pages is allowed; only an edit to an existing page's region is a
violation.

The docs-autogen bot, which commits regenerated regions, is exempted by the
``pr-autogenerated-docs`` label (handled by the CI wrapper, not here).
"""

import argparse
import re
import subprocess
import sys

# MDX comment markers only. Legacy Markdown pages used the HTML-comment form
# (``<!--AUTOGENERATED_START-->``); those pages are being removed, so this guard
# matches the MDX form exclusively. ``AUTOGENERATED[A-Z_]*_START`` also covers
# prefixed variants like ``AUTOGENERATED_METRICS_START``.
START_RE = re.compile(r"\{/\*\s*AUTOGENERATED[A-Z_]*_START\s*\*/\}")
END_RE = re.compile(r"\{/\*\s*AUTOGENERATED[A-Z_]*_END\s*\*/\}")

_HUNK_RE = re.compile(r"^@@ -\d+(?:,\d+)? \+(\d+)(?:,(\d+))? @@")


def find_marker_regions(text):
    """Return marker regions as inclusive 1-based ``(start_line, end_line)``.

    ``start_line`` is the line holding the START marker and ``end_line`` the
    line holding the matching END marker, so the range covers both the markers
    and everything between them. An unbalanced trailing START (no following
    END) is ignored.
    """
    regions = []
    start_line = None
    for lineno, line in enumerate(text.splitlines(), start=1):
        if start_line is None:
            if START_RE.search(line):
                start_line = lineno
        elif END_RE.search(line):
            regions.append((start_line, lineno))
            start_line = None
    return regions


def parse_changed_lines(diff_text):
    """Return the set of new-file line numbers a ``git diff`` hunk touches.

    Parses ``--unified=0`` hunk headers. An added/modified run of ``n`` lines
    starting at ``s`` contributes ``s .. s+n-1``; a pure deletion (new count 0)
    contributes its anchor line ``s`` so that removing lines inside a region is
    still caught.
    """
    changed = set()
    for line in diff_text.splitlines():
        m = _HUNK_RE.match(line)
        if not m:
            continue
        new_start = int(m.group(1))
        new_count = 1 if m.group(2) is None else int(m.group(2))
        if new_count == 0:
            changed.add(new_start)
        else:
            changed.update(range(new_start, new_start + new_count))
    return changed


def region_touched(regions, changed_lines):
    """True if any changed line falls within any (inclusive) region range."""
    return any(
        start <= line <= end for start, end in regions for line in changed_lines
    )


def find_violations(changed_files, read_head, changed_lines, exists_at_base):
    """Return the sorted list of pages whose autogenerated region was edited.

    ``read_head(path)`` returns the page contents at HEAD (or ``None`` if it was
    deleted), ``changed_lines(path)`` the set of new-file line numbers the pull
    request touched, and ``exists_at_base(path)`` whether the page already
    existed at the base (so newly added pages are skipped).
    """
    violations = []
    for path in changed_files:
        path = path.strip().removeprefix("./")
        if not path.endswith(".mdx"):
            continue
        head_text = read_head(path)
        if head_text is None:
            continue  # Deleted page: removing a whole page is allowed.
        if not exists_at_base(path):
            continue  # Newly added page: adding pages is allowed.
        regions = find_marker_regions(head_text)
        if not regions:
            continue
        if region_touched(regions, changed_lines(path)):
            violations.append(path)
    return sorted(violations)


def format_message(violations):
    lines = [
        "The content between the {/*AUTOGENERATED_START*/} and",
        "{/*AUTOGENERATED_END*/} markers is generated from the ClickHouse",
        "source (system.documentation) and is overwritten on every",
        "regeneration -- edits made to it here are lost.",
        "",
        "Edit the documentation in the defining C++ source instead; the",
        "docs-autogen bot regenerates these regions.",
        "",
        "Pages with edited autogenerated regions:",
    ]
    lines.extend(f"    {f}" for f in violations)
    return "\n".join(lines)


def check_autogenerated_regions(
    changed_files, read_head, changed_lines, exists_at_base
):
    """Return True if no autogenerated region was edited, else False."""
    violations = find_violations(
        changed_files, read_head, changed_lines, exists_at_base
    )
    if not violations:
        print("OK: no edits to autogenerated regions.")
        return True
    print("Edits to autogenerated regions detected:\n")
    print(format_message(violations))
    return False


def _run_git(*args):
    return subprocess.run(["git", *args], capture_output=True, text=True)


def _resolve_base_ref(base_branch):
    """Return the merge-base of HEAD and ``origin/<base_branch>``.

    Raises if the base cannot be resolved so the caller can fail closed rather
    than silently pass a pull request whose base is unknown.
    """
    remote_ref = f"origin/{base_branch}"
    result = _run_git("merge-base", "HEAD", remote_ref)
    if result.returncode != 0:
        raise RuntimeError(
            f"cannot resolve the base ref '{remote_ref}': {result.stderr.strip()}"
        )
    return result.stdout.strip()


def git_readers(base_branch):
    """Build the (read_head, changed_lines, exists_at_base) git-backed callables.

    Diffs against the merge-base of HEAD and ``origin/<base_branch>``; raises
    ``RuntimeError`` if that base cannot be resolved so the caller can fail
    closed.
    """
    base_ref = _resolve_base_ref(base_branch)

    def read_head(path):
        try:
            with open(path, encoding="utf-8") as f:
                return f.read()
        except FileNotFoundError:
            return None

    def changed_lines(path):
        diff = _run_git("diff", "--unified=0", base_ref, "--", path)
        return parse_changed_lines(diff.stdout)

    def exists_at_base(path):
        return _run_git("cat-file", "-e", f"{base_ref}:{path}").returncode == 0

    return read_head, changed_lines, exists_at_base


def _read_changed_files(args):
    if args.changed_file:
        return args.changed_file
    return [line.strip() for line in sys.stdin.read().splitlines() if line.strip()]


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--base-branch",
        required=True,
        help="Pull request base branch; the guard diffs against the merge-base "
        "of HEAD and origin/<base-branch>.",
    )
    p.add_argument(
        "--changed-file",
        action="append",
        default=[],
        help="A changed file path (repeatable). If omitted, newline-separated "
        "paths are read from stdin.",
    )
    args = p.parse_args(argv)
    read_head, changed_lines, exists_at_base = git_readers(args.base_branch)
    ok = check_autogenerated_regions(
        _read_changed_files(args), read_head, changed_lines, exists_at_base
    )
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())