# test files or test file prefixes that should run sequentially
#  key - file prefix, value - reason to run test cannot be run sequentially
PARALLEL_SKIP_TESTS = {
    "test_atomic_drop_table/": "reason: unknown",
    "test_attach_without_fetching/": "reason: unknown",
    "test_cleanup_dir_after_bad_zk_conn/": "reason: unknown",
    "test_consistent_parts_after_clone_replica/": "reason: unknown",
    "test_crash_log/": "reason: unknown",
    "test_cross_replication/": "reason: unknown",
    "test_ddl_worker_non_leader/": "reason: unknown",
    "test_delayed_replica_failover/": "reason: unknown",
    "test_dictionary_allow_read_expired_keys/": "reason: unknown",
    "test_disabled_mysql_server/": "reason: unknown",
    "test_distributed_respect_user_timeouts/": "reason: unknown",
    "test_dns_cache/": "reason: unknown",
    "test_global_overcommit_tracker/": "reason: unknown",
    "test_grpc_protocol/": "reason: unknown",
    "test_host_regexp_multiple_ptr_records/": "reason: unknown",
    "test_http_failover/": "reason: unknown",
    "test_https_replication/": "reason: unknown",
    "test_insert_into_distributed/": "reason: unknown",
    "test_insert_into_distributed_through_materialized_view/": "reason: unknown",
    "test_keeper_map/": "reason: unknown",
    "test_keeper_multinode_simple/": "reason: unknown",
    "test_keeper_two_nodes_cluster/": "reason: unknown",
    "test_limited_replicated_fetches/": "reason: unknown",
    "test_merge_tree_s3/": "reason: unknown",
    "test_mysql_database_engine/": "reason: unknown",
    "test_parts_delete_zookeeper/": "reason: unknown",
    "test_postgresql_replica_database_engine/": "reason: unknown",
    "test_profile_max_sessions_for_user/": "reason: unknown",
    "test_quorum_inserts_parallel/": "reason: unknown",
    "test_random_inserts/": "reason: unknown",
    "test_replace_partition/": "reason: unknown",
    "test_replicated_database/": "reason: unknown",
    "test_replicated_fetches_timeouts/": "reason: unknown",
    "test_replicated_merge_tree_wait_on_shutdown/": "reason: unknown",
    "test_server_overload/": "reason: unknown",
    "test_server_reload/": "reason: unknown",
    "test_storage_kafka/": "reason: unknown",
    "test_storage_kerberized_kafka/": "reason: unknown",
    "test_storage_rabbitmq/": "reason: unknown",
    "test_storage_s3/": "reason: unknown",
    "test_storage_s3_queue/": "reason: unknown",
    "test_system_flush_logs/": "reason: unknown",
    "test_system_logs/": "reason: unknown",
    "test_system_metrics/": "reason: unknown",
    "test_ttl_move/": "reason: unknown",
    "test_user_ip_restrictions/": "reason: unknown",
    "test_zookeeper_config_load_balancing/": "reason: unknown",
    "test_zookeeper_fallback_session/": "reason: unknown",
    "test_backup_restore_on_cluster/test_concurrency.py": "reason: unknown",
    "test_database_delta/test.py": "reason: unknown",
}

IMAGES_ENV = {
    "clickhouse/dotnet-client": "DOCKER_DOTNET_CLIENT_TAG",
    "clickhouse/integration-helper": "DOCKER_HELPER_TAG",
    "clickhouse/integration-test": "DOCKER_BASE_TAG",
    "clickhouse/kerberos-kdc": "DOCKER_KERBEROS_KDC_TAG",
    "clickhouse/mysql-golang-client": "DOCKER_MYSQL_GOLANG_CLIENT_TAG",
    "clickhouse/mysql-java-client": "DOCKER_MYSQL_JAVA_CLIENT_TAG",
    "clickhouse/mysql-js-client": "DOCKER_MYSQL_JS_CLIENT_TAG",
    "clickhouse/arrowflight-server-test": "DOCKER_ARROWFLIGHT_SERVER_TAG",
    "clickhouse/mysql-php-client": "DOCKER_MYSQL_PHP_CLIENT_TAG",
    "clickhouse/nginx-dav": "DOCKER_NGINX_DAV_TAG",
    "clickhouse/postgresql-java-client": "DOCKER_POSTGRESQL_JAVA_CLIENT_TAG",
    "clickhouse/python-bottle": "DOCKER_PYTHON_BOTTLE_TAG",
    "clickhouse/integration-test-with-unity-catalog": "DOCKER_BASE_WITH_UNITY_CATALOG_TAG",
    "clickhouse/integration-test-with-hms": "DOCKER_BASE_WITH_HMS_TAG",
    "clickhouse/mysql_dotnet_client": "DOCKER_MYSQL_DOTNET_CLIENT_TAG",
}
