import dataclasses
import traceback

from ci.jobs.scripts.cidb_cluster import CIDBCluster
from ci.praktika.info import Info


@dataclasses.dataclass
class TC:
    prefix: str
    is_sequential: bool
    comment: str


TEST_CONFIGS = [
    TC("test_dns_cache/", True, "no idea why i'm sequential"),
    TC("test_global_overcommit_tracker/", True, "no idea why i'm sequential"),
    TC(
        "test_profile_max_sessions_for_user/",
        True,
        "no idea why i'm sequential",
    ),
    TC("test_random_inserts/", True, "no idea why i'm sequential"),
    TC("test_server_overload/", True, "no idea why i'm sequential"),
    TC("test_storage_kafka/", True, "no idea why i'm sequential"),
    TC("test_storage_kerberized_kafka/", True, "no idea why i'm sequential"),
    TC(
        "test_backup_restore_on_cluster/test_concurrency.py",
        True,
        "no idea why i'm sequential",
    ),
    TC("test_storage_iceberg_no_spark/", True, "no idea why i'm sequential"),
    TC("test_storage_iceberg_with_spark_cache/", True, "no idea why i'm sequential"),
    TC("test_storage_iceberg_concurrent/", True, "no idea why i'm sequential"),
]

IMAGES_ENV = {
    "clickhouse/dotnet-client": "DOCKER_DOTNET_CLIENT_TAG",
    "clickhouse/integration-helper": "DOCKER_HELPER_TAG",
    "clickhouse/integration-test": "DOCKER_BASE_TAG",
    "clickhouse/kerberos-kdc": "DOCKER_KERBEROS_KDC_TAG",
    "clickhouse/test-mysql80": "DOCKER_TEST_MYSQL80_TAG",
    "clickhouse/test-mysql57": "DOCKER_TEST_MYSQL57_TAG",
    "clickhouse/mysql-golang-client": "DOCKER_MYSQL_GOLANG_CLIENT_TAG",
    "clickhouse/mysql-java-client": "DOCKER_MYSQL_JAVA_CLIENT_TAG",
    "clickhouse/mysql-js-client": "DOCKER_MYSQL_JS_CLIENT_TAG",
    "clickhouse/arrowflight-server-test": "DOCKER_ARROWFLIGHT_SERVER_TAG",
    "clickhouse/mysql-php-client": "DOCKER_MYSQL_PHP_CLIENT_TAG",
    "clickhouse/nginx-dav": "DOCKER_NGINX_DAV_TAG",
    "clickhouse/postgresql-java-client": "DOCKER_POSTGRESQL_JAVA_CLIENT_TAG",
    "clickhouse/python-bottle": "DOCKER_PYTHON_BOTTLE_TAG",
    "clickhouse/integration-test-with-unity-catalog": "DOCKER_BASE_WITH_UNITY_CATALOG_TAG",
    "clickhouse/integration-test-with-hms": "DOCKER_BASE_WITH_HMS_TAG",
    "clickhouse/mysql_dotnet_client": "DOCKER_MYSQL_DOTNET_CLIENT_TAG",
    "clickhouse/s3-proxy": "DOCKER_S3_PROXY_TAG",
}


# collected by
"""
SELECT
    splitByString('::', test_name)[1] AS test_file,
    round(median(test_duration_ms)) AS dur
FROM checks
WHERE 1
  AND check_name LIKE 'Integration tests%'
  and check_start_time > now() - interval 5 hour
  and test_duration_ms!=0 and test_status!='SKIPPED' and test_status!='FAIL'
GROUP BY test_file
HAVING test_file != ''
ORDER BY dur desc
"""

RAW_TEST_DURATIONS = """
test_lost_part_during_startup/test.py	333151
test_s3_aws_sdk_has_slightly_unreliable_behaviour/test.py	301004
test_storage_kafka/test_batch_slow_5.py	208060
test_storage_kafka/test_batch_slow_2.py	127763
test_storage_s3_queue/test_migration.py	127092
test_system_clusters_actual_information/test.py	120663
test_backward_compatibility/test_convert_ordinary.py	118226
test_storage_kafka/test_batch_slow_4.py	114386
test_storage_iceberg_concurrent/test_concurrent_reads.py	109824
test_max_bytes_ratio_before_external_order_group_by_for_server/test.py	99804
test_ddl_worker_replicas/test.py	82885
test_backup_restore_on_cluster/test_concurrency.py	74561
test_keeper_incorrect_config/test.py	71576
test_concurrent_ttl_merges/test.py	71082
test_store_cleanup/test.py	70238
test_modify_engine_on_restart/test_ordinary.py	69669
test_keeper_password/test.py	67986
test_distributed_directory_monitor_split_batch_on_failure/test.py	67944
test_storage_kafka/test_batch_slow_1.py	66948
test_cluster_discovery/test_auxiliary_keeper.py	56543
test_keeper_nodes_remove/test.py	56292
test_keeper_force_recovery/test.py	54612
test_attach_without_fetching/test.py	53863
test_keeper_invalid_digest/test.py	53668
test_cluster_discovery/test_dynamic_clusters.py	53617
test_limited_replicated_fetches/test.py	52381
test_storage_kafka/test_produce_http_interface.py	50032
test_keeper_mntr_pressure/test.py	48017
test_backward_compatibility/test_functions.py	47108
test_transposed_metric_log/test.py	45788
test_backward_compatibility/test_aggregate_function_state.py	43334
test_backup_restore_new/test_shutdown_wait_backup.py	43024
test_async_insert_memory/test.py	42023
test_zookeeper_config/test_secure.py	41588
test_storage_kafka/test_batch_slow_6.py	41232
test_database_delta/test.py	41220
test_keeper_snapshot_small_distance/test.py	41090
test_replicated_database_recover_digest_mismatch/test.py	40158
test_keeper_nodes_add/test.py	39970
test_storage_s3_queue/test_2.py	39408
test_keeper_force_recovery_single_node/test.py	37292
test_dictionaries_all_layouts_separate_sources/test_mongo_uri.py	36870
test_distributed_type_object/test.py	36092
test_replicated_mutations/test.py	35876
test_keeper_block_acl/test.py	35796
test_file_schema_inference_cache/test.py	35786
test_lost_part/test.py	35580
test_keeper_reconfig_replace_leader_in_one_command/test.py	35434
test_old_parts_finally_removed/test.py	35264
test_log_query_probability/test.py	34777
test_named_collections_if_exists_on_cluster/test.py	34664
test_restore_db_replica/test.py	34025
test_dictionaries_all_layouts_separate_sources/test_executable_cache.py	33398
test_replicated_database_cluster_groups/test.py	33210
test_keeper_nodes_move/test.py	32182
test_modify_engine_on_restart/test.py	32171
test_acme_tls/test_multi_node.py	31229
test_crash_log/test.py	31218
test_ddl_on_cluster_stop_waiting_for_offline_hosts/test.py	30919
test_keeper_disks/test.py	30760
test_storage_kerberized_kafka/test.py	30704
test_keeper_snapshot_on_exit/test.py	30612
test_consistant_parts_after_move_partition/test.py	29754
test_keeper_three_nodes_start/test.py	29724
test_keeper_three_nodes_two_alive/test.py	28789
test_jbod_balancer/test.py	28384
test_recompression_ttl/test.py	27773
test_keeper_max_append_byte_size/test.py	27150
test_on_cluster_timeouts/test.py	27056
test_system_logs_recreate/test.py	26894
test_merges_memory_limit/test.py	25510
test_plain_rewritable_backward_compatibility/test.py	25502
test_version_update_after_mutation/test.py	25500
test_consistent_parts_after_clone_replica/test.py	25139
test_storage_kafka/test_batch_slow_0.py	25050
test_atomic_drop_table/test.py	24838
test_storage_s3_queue/test_1.py	24829
test_backward_compatibility/test_vertical_merges_from_compact_parts.py	24678
test_undrop_query/test.py	24206
test_mutations_with_merge_tree/test.py	24030
test_delayed_replica_failover/test.py	23923
test_warning_broken_tables/test.py	23827
test_keeper_session_refuse_stale_server/test.py	23593
test_keeper_s3_snapshot/test.py	23442
test_backup_restore_keeper_map/test.py	23308
test_keeper_internal_secure/test.py	23004
test_replicated_merge_tree_wait_on_shutdown/test.py	22816
test_async_load_databases/test.py	22796
test_asynchronous_metrics_pk_bytes_fields/test.py	22558
test_scheduler_cpu_preemptive/test.py	22254
test_storage_iceberg_with_spark/test_system_iceberg_metadata.py	22040
test_replicated_access/test.py	21798
test_dictionaries_config_reload/test.py	21568
test_executable_user_defined_functions_config_reload/test.py	21476
test_memory_limit_observer/test.py	21392
test_move_ttl_broken_compatibility/test.py	21365
test_storage_delta/test_cdf.py	21074
test_random_inserts/test.py	20998
test_storage_iceberg_with_spark/test_partition_pruning.py	20864
test_keeper_broken_logs/test.py	20625
test_distributed_respect_user_timeouts/test.py	20483
test_jbod_ha/test.py	20367
test_keeper_feature_flags_config/test.py	19952
test_kafka_bad_messages/test.py	19858
test_system_merges/test.py	19700
test_keeper_reconfig_replace_leader/test.py	19511
test_ttl_multilevel_group_by/test.py	19499
test_dictionaries_all_layouts_separate_sources/test_mysql.py	19383
test_dictionaries_all_layouts_separate_sources/test_mongo.py	19312
test_remove_stale_moving_parts/test.py	19184
test_dictionaries_wait_for_load/test.py	19166
test_dictionaries_all_layouts_separate_sources/test_file.py	19094
test_dictionaries_redis/test.py	19007
test_keeper_reconfig_remove_many/test.py	18956
test_storage_kafka/test_intent_sizes.py	18889
test_concurrent_queries_restriction_by_query_kind/test.py	18880
test_merge_tree_load_parts/test.py	18857
test_inserts_with_keeper_retries/test.py	18795
test_temporary_data_in_cache/test.py	18604
test_restore_external_engines/test.py	18266
test_backup_restore_on_cluster/test_huge_concurrent_restore.py	18144
test_config_reloader_interval/test.py	18122
test_sql_roles_for_xml_users/test.py	18073
test_replicated_merge_tree_compatibility/test.py	18069
test_storage_iceberg_schema_evolution/test_map_evolved_nested.py	17918
test_cancel_freeze/test.py	17910
test_replicated_fetches_bandwidth/test.py	17882
test_dictionaries_all_layouts_separate_sources/test_clickhouse_local.py	17616
test_reload_zookeeper/test.py	17402
test_shutdown_wait_unfinished_queries/test.py	17309
test_replicated_table_attach/test.py	17300
test_secure_socket/test.py	17236
test_MemoryTracking/test.py	17114
test_dictionaries_all_layouts_separate_sources/test_clickhouse_remote.py	16997
test_storage_iceberg_with_spark/test_minmax_pruning.py	16840
test_dictionaries_all_layouts_separate_sources/test_https.py	16619
test_keeper_map_retries/test.py	16585
test_jemalloc_global_profiler/test.py	16424
test_dictionaries_all_layouts_separate_sources/test_http.py	16399
test_dictionaries_all_layouts_separate_sources/test_executable_hashed.py	16346
test_parts_delete_zookeeper/test.py	16014
test_read_only_table/test.py	15921
test_replicated_fetches_timeouts/test.py	15809
test_dictionaries_update_and_reload/test.py	15744
test_kafka_bad_messages/test_1.py	15510
test_library_bridge/test_exiled.py	15414
test_postgresql_replica_database_engine/test_2.py	15380
test_storage_s3_queue/test_3.py	15358
test_restore_replica/test.py	15115
test_suggestions/test.py	15060
test_server_overload/test.py	15044
test_backup_restore_on_cluster/test_cancel_backup.py	14970
test_acme_tls/test_single_node.py	14956
test_keeper_zookeeper_converter/test.py	14778
test_https_replication/test_change_ip.py	14769
test_modify_engine_on_restart/test_storage_policies.py	14701
test_startup_scripts/test.py	14683
test_backup_restore_new/test_cancel_backup.py	14506
test_force_restore_data_flag_for_keeper_dataloss/test.py	14496
test_drop_replica/test.py	14314
test_alter_moving_garbage/test.py	14252
test_storage_s3_queue/test_5.py	14137
test_keeper_persistent_watches/test.py	13758
test_enable_user_name_access_type/test.py	13518
test_keeper_snapshots_multinode/test.py	13516
test_zookeeper_config/test_password.py	13428
test_storage_iceberg_no_spark/test_writes_statistics_by_minmax_pruning.py	13415
test_storage_iceberg_schema_evolution/test_evolved_schema_simple.py	13364
test_group_array_element_size/test.py	13358
test_keeper_reconfig_remove/test.py	13285
test_s3_plain_rewritable_rotate_tables/test.py	13102
test_storage_iceberg_schema_evolution/test_array_evolved_nested.py	12945
test_reload_auxiliary_zookeepers/test.py	12932
test_keeper_persistent_log_multinode/test.py	12821
test_disk_access_storage/test.py	12694
test_overcommit_tracker/test.py	12688
test_kafka_bad_messages/test_mv_target_missing.py	12664
test_dictionaries_redis/test_long.py	12605
test_interserver_dns_retires/test.py	12552
test_user_defined_object_persistence/test.py	12462
test_keeper_remove_acl/test.py	12326
test_storage_iceberg_with_spark/test_cluster_table_function.py	12309
test_config_xml_full/test.py	12246
test_always_fetch_merged/test.py	12245
test_postpone_failed_tasks/test.py	12157
test_named_collections_encrypted/test.py	12055
test_dictionary_ddl_on_cluster/test.py	12016
test_distributed_ddl_parallel/test.py	12008
test_keeper_znode_time/test.py	11915
test_storage_kafka/test_compression_codec.py	11863
test_postgresql_replica_database_engine/test_1.py	11813
test_storage_kafka/test_schema_registry_skip_bytes.py	11686
test_dictionary_asynchronous_metrics/test.py	11485
test_s3_storage_conf_proxy/test.py	11347
test_recovery_time_metric/test.py	11338
test_ddl_worker_non_leader/test.py	11318
test_s3_storage_conf_new_proxy/test.py	11247
test_distributed_load_balancing/test.py	11200
test_https_s3_table_function_with_http_proxy_no_tunneling/test.py	11088
test_replication_without_zookeeper/test.py	11040
test_config_yaml_merge_keys/test.py	11014
test_backward_compatibility/test_block_marshalling.py	10998
test_s3_table_function_with_https_proxy/test.py	10981
test_s3_table_function_with_http_proxy/test.py	10930
test_zookeeper_connection_log/test.py	10926
test_distributed_ddl/test_replicated_alter.py	10892
test_modify_engine_on_restart/test_zk_path_exists.py	10854
test_distributed_default_database/test.py	10776
test_modify_engine_on_restart/test_mv.py	10753
test_async_metrics_in_cgroup/test.py	10735
test_s3_plain_rewritable/test.py	10720
test_force_deduplication/test.py	10550
test_host_regexp_multiple_ptr_records/test.py	10509
test_storage_hudi/test.py	10434
test_scheduler_query/test.py	10420
test_azure_blob_storage_plain_rewritable/test.py	10385
test_dictionaries_dependency_xml/test.py	10252
test_keeper_mntr_data_size/test.py	10160
test_dictionaries_dependency/test.py	10086
test_rename_column/test.py	9948
test_startup_scripts_execution_state/test.py	9934
test_hedged_requests_parallel/test.py	9801
test_hedged_requests/test.py	9783
test_parallel_replicas_invisible_parts/test.py	9773
test_config_decryption/test_wrong_settings_zk.py	9646
test_search_orphaned_parts/test.py	9588
test_memory_limit/test.py	9570
test_storage_policies/test.py	9569
test_system_ddl_worker_queue/test.py	9528
test_config_xml_yaml_mix/test.py	9514
test_trace_log_build_id/test.py	9470
test_match_process_uid_against_data_owner/test.py	9458
test_parallel_replicas_snapshot_from_initiator/test.py	9424
test_dictionary_allow_read_expired_keys/test_dict_get.py	9379
test_drop_is_lock_free/test.py	9372
test_dictionary_allow_read_expired_keys/test_default_reading.py	9354
test_filesystem_cache_uninitialized/test.py	9342
test_dictionary_allow_read_expired_keys/test_dict_get_or_default.py	9310
test_statistics_cache/test.py	9270
test_storage_kafka_sasl/test.py	9229
test_config_yaml_main/test.py	9205
test_keeper_two_nodes_cluster/test.py	9150
test_storage_iceberg_schema_evolution/test.py	9080
test_userspace_page_cache/test_incorrect_limits.py	8938
test_detached_parts_metrics/test.py	8931
test_backup_restore_on_cluster/test_disallow_concurrency.py	8888
test_backup_log/test.py	8880
test_storage_rabbitmq/test_failed_connection.py	8864
test_system_detached_tables/test.py	8808
test_storage_iceberg_with_spark/test_explicit_metadata_file.py	8807
test_drop_replica_with_auxiliary_zookeepers/test.py	8702
test_cleanup_after_start/test.py	8607
test_extreme_deduplication/test.py	8593
test_storage_kafka/test_batch_fast.py	8550
test_move_partition_to_volume_async/test.py	8542
test_keeper_restore_from_snapshot/test_disk_s3.py	8493
test_refreshable_mv/test.py	8438
test_keeper_profiler/test.py	8418
test_keeper_map/test.py	8355
test_database_hms/test.py	8314
test_join_set_family_s3/test.py	8289
test_config_yaml_full/test.py	8277
test_permissions_drop_replica/test.py	8266
test_broken_projections/test.py	8261
test_storage_iceberg_with_spark/test_position_deletes.py	8218
test_modify_engine_on_restart/test_args.py	8176
test_modify_engine_on_restart/test_unusual_path.py	8125
test_version_update/test.py	8091
test_recovery_replica/test.py	8073
test_keeper_restore_from_snapshot/test.py	8066
test_dns_cache/test.py	8064
test_session_settings_table/test.py	8054
test_mutations_with_projection/test.py	8026
test_config_xml_main/test.py	7951
test_userspace_page_cache/test.py	7948
test_keeper_reconfig_add/test.py	7884
test_ttl_move/test.py	7869
test_compression_nested_columns/test.py	7803
test_storage_iceberg_with_spark/test_schema_evolution_with_time_travel.py	7628
test_throttling/test.py	7622
test_temporary_data/test.py	7610
test_cross_replication/test.py	7553
test_replica_is_active/test.py	7500
test_zookeeper_fallback_session/test.py	7468
test_rocksdb_read_only/test.py	7436
test_cluster_discovery/test.py	7388
test_format_cannot_allocate_thread/test.py	7309
test_postgresql_replica_database_engine/test_0.py	7306
test_http_handlers_config/test.py	7274
test_storage_s3_queue/test_4.py	7236
test_covered_by_broken_exists/test.py	7229
test_quorum_inserts_parallel/test.py	7195
test_backup_restore_on_cluster/test_slow_rmt.py	7162
test_mark_cache_profile_events/test.py	7064
test_backward_compatibility/test_ip_types_binary_compatibility.py	7046
test_storage_delta/test_imds.py	7042
test_keeper_4lw_reconfiguration/test.py	7039
test_backward_compatibility/test_rocksdb_upgrade.py	7008
test_scheduler/test.py	7008
test_rocksdb_options/test.py	7000
test_check_table_name_length_2/test.py	6934
test_profile_events_s3/test.py	6825
test_named_collections/test.py	6814
test_fix_metadata_version/test.py	6800
test_aliases_in_default_expr_not_break_table_structure/test.py	6790
test_storage_iceberg_with_spark/test_metadata_file_format_with_uuid.py	6784
test_alter_on_mixed_type_cluster/test.py	6783
test_trace_collector_serverwide/test.py	6778
test_variant_escaping_merge_tree_compatibility/test.py	6736
test_storage_iceberg_with_spark/test_restart_broken_s3.py	6674
test_distributed_insert_backward_compatibility/test.py	6628
test_backup_restore/test.py	6547
test_storage_iceberg_with_spark/test_metadata_file_selection.py	6530
test_refreshable_mv_skip_old_temp_table_ddls/test.py	6515
test_insert_distributed_async_send/test.py	6509
test_hot_reload_storage_policy/test.py	6480
test_database_backup/test.py	6435
test_parallel_replicas_custom_key_load_balancing/test.py	6424
test_merge_tree_s3_failover/test.py	6400
test_ddl_worker_with_loopback_hosts/test.py	6364
test_force_drop_table/test.py	6347
test_replace_partition/test.py	6342
test_insert_distributed_async_extra_dirs/test.py	6315
test_storage_iceberg_with_spark_cache/test_metadata_cache.py	6269
test_s3_cluster_restart/test.py	6257
test_reload_max_table_size_to_drop/test.py	6213
test_storage_iceberg_with_spark/test_bucket_partition_pruning.py	6194
test_system_logs_comment/test.py	6188
test_check_table/test.py	6132
test_drop_if_empty/test.py	6122
test_compressed_marks_restart/test.py	6078
test_table_db_num_limit/test.py	5995
test_distributed_ddl_password/test.py	5972
test_s3_table_functions/test.py	5971
test_parallel_replicas_failover/test.py	5969
test_replicated_merge_tree_encrypted_disk/test.py	5938
test_alter_codec/test.py	5916
test_limit_materialized_view_count/test.py	5911
test_prometheus_protocols/test_write_read.py	5869
test_part_uuid/test.py	5840
test_multi_access_storage_role_management/test.py	5824
test_log_lz4_streaming/test.py	5811
test_plain_rewr_legacy_layout/test.py	5779
test_transactions/test.py	5772
test_distributed_async_insert_for_node_changes/test.py	5685
test_cleanup_dir_after_bad_zk_conn/test.py	5681
test_replicated_merge_tree_with_auxiliary_zookeepers/test.py	5659
test_storage_kafka/test_batch_slow_7.py	5644
test_mutation_fetch_fallback/test.py	5636
test_reload_client_certificate/test.py	5616
test_fetch_partition_should_reset_mutation/test.py	5614
test_parallel_replicas_over_distributed/test.py	5612
test_backward_compatibility/test_parallel_replicas_protocol.py	5602
test_runtime_configurable_cache_size/test.py	5590
test_dictionary_allow_read_expired_keys/test_default_string.py	5582
test_system_start_stop_listen/test.py	5556
test_storage_iceberg_schema_evolution/test_array_evolved_with_struct.py	5538
test_restart_with_unavailable_azure/test.py	5506
test_read_temporary_tables_on_failure/test.py	5488
test_storage_iceberg_no_spark/test_writes_multiple_files.py	5452
test_distributed_index_analysis/test.py	5423
test_storage_iceberg_schema_evolution/test_evolved_schema_complex.py	5408
test_scheduler_cpu/test.py	5390
test_lightweight_updates/test.py	5295
test_git_import/test.py	5242
test_server_start_and_ip_conversions/test.py	5184
test_manipulate_statistics/test.py	5159
test_storage_iceberg_with_spark/test_writes_mutate_update.py	5108
test_storage_iceberg_with_spark/test_iceberg_snapshot_reads.py	5104
test_keeper_persistent_log/test.py	5094
test_reloading_storage_configuration/test.py	5078
test_parameterized_view/test.py	5061
test_storage_iceberg_with_spark/test_delete_files.py	5017
test_async_connect_to_multiple_ips/test.py	5015
test_multiple_disks/test.py	5004
test_threadpool_readers/test.py	4976
test_quorum_inserts/test.py	4927
test_analyzer_compatibility/test.py	4925
test_select_access_rights/test_from_system_tables.py	4895
test_tmp_policy/test.py	4886
test_storage_delta_disks/test.py	4854
test_no_merges_volume_ttl/test.py	4834
test_replicated_merge_tree_thread_schedule_timeouts/test.py	4818
test_metdata_cache_memory_leak/test.py	4775
test_storage_delta/test.py	4754
test_sharding_key_from_default_column/test.py	4701
test_parallel_replicas_insert_select/test.py	4684
test_storage_iceberg_schema_evolution/test_tuple_evolved_nested.py	4660
test_ddl_config_hostname/test.py	4656
test_database_disk_setting/test.py	4638
test_disk_configuration/test.py	4614
test_attach_partition_using_copy/test.py	4600
test_attach_partition_with_large_destination/test.py	4594
test_default_compression_in_mergetree_settings/test.py	4585
test_storage_s3_queue/test_parallel_inserts.py	4532
test_asynchronous_metric_log_table/test.py	4528
test_storage_iceberg_with_spark/test_optimize.py	4524
test_server_startup_and_shutdown_logs/test.py	4505
test_lazy_database/test.py	4502
test_build_sets_from_multiple_threads/test.py	4488
test_fetch_memory_usage/test.py	4484
test_stop_insert_when_disk_close_to_full/test.py	4447
test_broken_part_during_merge/test.py	4447
test_dictionaries_replace/test.py	4380
test_shutdown_static_destructor_failure/test.py	4378
test_replicated_database/test.py	4362
test_cgroup_limit/test.py	4303
test_default_compression_codec/test.py	4279
test_matview_union_replicated/test.py	4270
test_naive_bayes_bad_models/test.py	4257
test_merge_tree_s3/test.py	4232
test_keeper_memory_soft_limit/test.py	4228
test_trace_log_memory_context/test.py	4194
test_optimize_on_insert/test.py	4182
test_system_metrics/test.py	4134
test_async_insert_adaptive_busy_timeout/test.py	4120
test_user_directories/test.py	4109
test_keeper_watches/test.py	4102
test_filesystem_layout/test.py	4098
test_replication_credentials/test.py	4060
test_backup_restore_on_cluster/test_two_shards_two_replicas.py	4001
test_storage_iceberg_with_spark/test_writes_schema_evolution.py	3980
test_parallel_replicas_custom_key_failover/test.py	3963
test_access_for_functions/test.py	3963
test_ttl_replicated/test.py	3937
test_alter_database_on_cluster/test.py	3935
test_default_database_on_cluster/test.py	3914
test_merge_tree_check_part_with_cache/test.py	3878
test_user_valid_until/test.py	3870
test_drop_no_local_path/test.py	3870
test_cow_policy/test.py	3860
test_keeper_multinode_simple/test.py	3855
test_move_partition_to_disk_on_cluster/test.py	3853
test_alter_settings_on_cluster/test.py	3850
test_arrowflight_interface/test_ticket_expiration.py	3844
test_drop_database_replica/test.py	3841
test_storage_alias_replicated/test.py	3816
test_backward_compatibility/test_memory_bound_aggregation.py	3810
test_input_format_parallel_parsing_memory_tracking/test.py	3798
test_cluster_discovery/test_password.py	3785
test_log_levels_update/test.py	3757
test_keeper_snapshots/test.py	3752
test_distributed_storage_configuration/test.py	3748
test_codec_encrypted/test.py	3735
test_restart_server/test.py	3708
test_ddl_alter_query/test.py	3699
test_storage_iceberg_with_spark_cache/test_filesystem_cache.py	3688
test_materialized_view_restart_server/test.py	3651
test_storage_s3_queue/test_0.py	3648
test_replicated_merge_tree_encryption_codec/test.py	3644
test_allow_feature_tier/test.py	3643
test_alternative_keeper_config/test.py	3634
test_mutations_in_partitions_of_merge_tree/test.py	3626
test_replicated_database_interserver_host/test.py	3626
test_storage_iceberg_with_spark/test_read_in_order.py	3622
test_backup_restore_on_cluster/test_different_versions.py	3621
test_storage_iceberg_with_spark/test_writes_mutate_delete.py	3620
test_global_overcommit_tracker/test.py	3613
test_insert_into_distributed_through_materialized_view/test.py	3599
test_parallel_replicas_distributed_skip_shards/test.py	3598
test_deduplicated_attached_part_rename/test.py	3594
test_intersecting_parts/test.py	3558
test_replicated_database_alter_modify_order_by/test.py	3538
test_max_rows_to_read_leaf_with_view/test.py	3534
test_keeper_dynamic_log_level/test.py	3502
test_postgresql_replica_database_engine/test_3.py	3498
test_system_logs_hostname/test_replicated.py	3490
test_max_suspicious_broken_parts_replicated/test.py	3480
test_backup_restore_s3/test.py	3461
test_disk_name_virtual_column/test.py	3457
test_globs_in_filepath/test.py	3449
test_s3_access_headers/test.py	3442
test_parallel_replicas_increase_error_count/test.py	3431
test_storage_iceberg/test.py	3415
test_library_bridge/test.py	3408
test_system_reconnect_zookeeper/test.py	3378
test_dremio_engine/test.py	3376
test_storage_s3/test_invalid_env_credentials.py	3344
test_string_aggregation_compatibility/test.py	3324
test_truncate_database/test_replicated.py	3324
test_validate_only_initial_alter_query/test_replicated_database.py	3316
test_polymorphic_parts/test.py	3278
test_alter_comment_on_cluster/test.py	3258
test_refreshable_mat_view/test.py	3236
test_settings_constraints_distributed/test.py	3219
test_storage_nats/test.py	3205
test_send_request_to_leader_replica/test.py	3184
test_jemalloc_percpu_arena/test.py	3179
test_sql_user_defined_functions_on_cluster/test.py	3170
test_storage_rabbitmq/test.py	3157
test_tcp_handler_connection_limits/test.py	3154
test_disk_checker/test.py	3150
test_storage_iceberg_with_spark/test_minmax_pruning_with_null.py	3132
test_zookeeper_config/test.py	3130
test_grant_and_revoke/test_without_table_engine_grant.py	3086
test_os_thread_nice_value/test.py	3071
test_disabled_access_control_improvements/test_select_from_system_tables.py	3052
test_attach_without_checksums/test.py	3051
test_backup_restore_on_cluster/test.py	3025
test_reload_clusters_config/test.py	3007
test_storage_iceberg_with_spark/test_schema_inference.py	2960
test_checking_s3_blobs_paranoid/test.py	2960
test_mysql_database_engine/test.py	2943
test_backup_restore_on_cluster_with_checksum_data_file_name/test.py	2942
test_disk_over_web_server/test.py	2940
test_http_failover/test.py	2920
test_attach_table_from_s3_plain_readonly/test.py	2903
test_create_query_constraints/test.py	2903
test_system_queries/test.py	2902
test_max_suspicious_broken_parts/test.py	2852
test_truncate_database/test_distributed.py	2836
test_mysql57_database_engine/test.py	2764
test_system_logs/test_system_logs.py	2758
test_storage_iceberg_schema_evolution/test_full_drop.py	2740
test_replicated_merge_tree_s3/test.py	2728
test_storage_iceberg_with_spark/test_explanation.py	2726
test_dictionary_custom_settings/test.py	2706
test_storage_iceberg_with_spark/test_metadata_file_selection_from_version_hint.py	2659
test_storage_iceberg_no_spark/test_read_in_order_with_pyiceberg.py	2641
test_insert_distributed_load_balancing/test.py	2600
test_storage_iceberg_with_spark/test_writes_create_table.py	2594
test_system_flush_logs/test.py	2592
test_dotnet_client/test.py	2586
test_distributed_ddl/test.py	2572
test_user_zero_database_access/test_user_zero_database_access.py	2556
test_ddl_worker_retry_when_dropping_db_failed/test.py	2539
test_merge_tree_prewarm_cache/test.py	2510
test_dot_in_user_name/test.py	2505
test_replicated_merge_tree_replicated_db_ttl/test.py	2492
test_allowed_url_from_config/test.py	2480
test_failed_async_inserts/test.py	2474
test_aggregation_memory_efficient/test.py	2448
test_zookeeper_config_load_balancing/test.py	2443
test_fetch_partition_with_outdated_parts/test.py	2439
test_send_crash_reports/test.py	2431
test_storage_iceberg_disks/test.py	2427
test_role/test.py	2425
test_mask_sensitive_info/test.py	2421
test_distributed_format/test.py	2412
test_system_reload_async_metrics/test_async_metrics_invalid_settings.py	2411
test_prefer_global_in_and_join/test.py	2407
test_filesystem_cache/test.py	2402
test_log_family_s3/test.py	2395
test_attach_with_different_projections_or_indices/test.py	2385
test_backup_restore_new/test.py	2374
test_parallel_replicas_custom_key/test.py	2355
test_merge_tree_s3_with_cache/test.py	2340
test_concurrent_queries_for_all_users_restriction/test.py	2332
test_backward_compatibility/test_aggregation_with_out_of_order_buckets.py	2306
test_storage_iceberg_with_spark/test_partition_pruning_with_subquery_set.py	2295
test_validate_threadpool_writer_pool_size/test.py	2282
test_storage_iceberg_with_spark/test_writes_drop_table.py	2260
test_concurrent_threads_soft_limit/test.py	2256
test_ytsaurus/test_dictionaries.py	2255
test_storage_iceberg_no_spark/test_writes_multiple_threads.py	2248
test_session_log/test.py	2246
test_config_decryption/test_wrong_settings.py	2235
test_groupBitmapAnd_on_distributed/test_groupBitmapAndState_on_distributed_table.py	2220
test_storage_iceberg_with_spark/test_writes_with_partitioned_table.py	2220
test_replicated_s3_zero_copy_drop_partition/test.py	2174
test_storage_iceberg_with_spark/test_writes_create_version_hint.py	2164
test_storage_dict/test.py	2148
test_row_policy/test.py	2122
test_enabling_access_management/test.py	2121
test_backward_compatibility/test_normalized_count_comparison.py	2120
test_backward_compatibility/test_short_strings_aggregation.py	2111
test_table_functions_access_rights/test.py	2110
test_s3_cluster_insert_select/test.py	2108
test_keeper_auth/test.py	2102
test_remote_blobs_naming/test_backward_compatibility.py	2100
test_text_log_level/test.py	2094
test_sql_user_impersonate/test.py	2090
test_ytsaurus/test_tables.py	2085
test_mutations_hardlinks/test.py	2081
test_backward_compatibility/test_select_aggregate_alias_column.py	2076
test_grant_and_revoke/test_with_table_engine_grant.py	2064
test_non_default_compression/test.py	2047
test_storage_kafka/test_zookeeper_locks.py	2004
test_grpc_protocol_ssl/test.py	2001
test_https_replication/test.py	1998
test_replicated_detach_table/test.py	1993
test_backup_restore_azure_blob_storage/test.py	1992
test_storage_iceberg_with_spark/test_writes_multiple_threads.py	1964
test_groupBitmapAnd_on_distributed/test.py	1955
test_refreshable_mat_view_replicated/test.py	1947
test_attach_table_normalizer/test.py	1947
test_backward_compatibility/test_aggregate_fixed_key.py	1944
test_encrypted_disk_replication/test.py	1940
test_keeper_max_request_size/test.py	1934
test_projection_rebuild_with_required_columns/test.py	1895
test_storage_iceberg_with_spark/test_multiple_iceberg_file.py	1886
test_fetch_partition_from_auxiliary_zookeeper/test.py	1858
test_system_reload_async_metrics/test.py	1856
test_distributed_ddl_on_cross_replication/test.py	1856
test_merge_tree_settings_constraints/test.py	1844
test_default_role/test.py	1828
test_sync_replica_on_cluster/test.py	1827
test_distributed_system_query/test.py	1809
test_replicated_database/test_settings_recover_lost_replica.py	1806
test_encrypted_disk/test.py	1797
test_replicated_engine_arguments/test.py	1792
test_dictionaries_access/test.py	1792
test_storage_iceberg_no_spark/test_time_travel_bug_fix_validation.py	1786
test_s3_low_cardinality_right_border/test.py	1760
test_backup_restore_storage_policy/test.py	1756
test_disabled_access_control_improvements/test_row_policy.py	1753
test_partition/test.py	1749
test_distributed_config/test.py	1739
test_access_control_on_cluster/test.py	1727
test_storage_iceberg_with_spark/test_writes_from_zero.py	1717
test_placement_info/test.py	1706
test_storage_iceberg_with_spark/test_writes_complex_type.py	1686
test_prometheus_endpoint/test.py	1670
test_storage_s3_intelligent_tier/test.py	1642
test_database_iceberg_lakekeeper_catalog/test.py	1642
test_storage_mysql/test.py	1638
test_composable_protocol_without_global_ssl/test.py	1634
test_keeper_four_word_command/test_allow_list.py	1616
test_freeze_table/test.py	1616
test_format_schema_source/test.py	1608
test_executable_user_defined_function/test.py	1596
test_insert_into_distributed_sync_async/test.py	1568
test_backup_restore_s3/test_throttling.py	1552
test_storage_iceberg_with_spark/test_types.py	1540
test_concurrent_queries_for_user_restriction/test.py	1534
test_database_disk/test.py	1531
test_dictionaries_ddl/test.py	1524
test_storage_iceberg_schema_evolution/test_correct_column_mapper_is_chosen.py	1512
test_disabled_mysql_server/test.py	1486
test_reloading_settings_from_users_xml/test.py	1486
test_postgresql_database_engine/test.py	1484
test_inherit_multiple_profiles/test.py	1477
test_storage_azure_blob_storage/test_check_after_upload.py	1477
test_merge_tree_empty_parts/test.py	1476
test_storage_iceberg_with_spark/test_partition_by.py	1476
test_s3_imds/test_simple.py	1474
test_config_corresponding_root/test.py	1462
test_merge_tree_azure_blob_storage/test.py	1456
test_keeper_http_control/test.py	1449
test_create_user_and_login/test.py	1444
test_s3_imds/test_session_token.py	1441
test_prometheus_protocols/test_different_table_engines.py	1430
test_azure_blob_storage_native_copy/test.py	1422
test_compatibility_merge_tree_settings/test.py	1416
test_disable_insertion_and_mutation/test.py	1416
test_database_iceberg/test.py	1405
test_settings_profile/test.py	1388
test_explain_estimates/test.py	1376
test_settings_constraints/test.py	1373
test_quota/test.py	1372
test_dictionaries_null_value/test.py	1327
test_database_glue/test.py	1311
test_external_cluster/test.py	1297
test_ldap_external_user_directory/test.py	1287
test_executable_table_function/test.py	1276
test_database_replicated_settings/test.py	1275
test_alter_update_cast_keep_nullable/test.py	1260
test_config_hide_in_preprocessed/test.py	1256
test_storage_s3/test_sts.py	1248
test_config_substitutions/test.py	1230
test_reload_query_masking_rules/test.py	1212
test_parallel_replicas_all_marks_read/test.py	1196
test_storage_iceberg_with_spark/test_writes.py	1176
test_storage_iceberg_with_spark/test_writes_different_path_format_error.py	1174
test_replicated_user_defined_functions/test.py	1170
test_executable_udf_names_in_system_query_log/test.py	1170
test_storage_redis/test.py	1165
test_storage_iceberg_with_spark/test_writes_field_partitioning.py	1162
test_storage_iceberg_with_spark/test_writes_create_partitioned_table.py	1162
test_zero_copy_expand_macros/test.py	1162
test_merge_tree_load_marks/test.py	1147
test_storage_mongodb/test.py	1147
test_storage_s3/test.py	1146
test_http_connection_drain_before_reuse/test.py	1134
test_server_reload/test.py	1133
test_database_iceberg_nessie_catalog/test.py	1121
test_storage_iceberg_with_spark/test_compressed_metadata.py	1115
test_check_table_name_length/test.py	1113
test_part_log_table/test.py	1110
test_replicated_merge_tree_config/test.py	1110
test_select_access_rights/test_main.py	1109
test_dictionaries_mysql/test.py	1103
test_s3_with_https/test.py	1065
test_storage_postgresql/test.py	1065
test_parallel_replicas_no_replicas/test.py	1063
test_custom_dashboards/test.py	1062
test_scram_sha256_password_with_replicated_zookeeper_replicator/test.py	1061
test_zookeeper_info/test.py	1061
test_settings_from_server/test.py	1060
test_attach_backup_from_s3_plain/test.py	1047
test_wrong_db_or_table_name/test.py	1046
test_user_ip_restrictions/test.py	1022
test_reload_certificate/test.py	1021
test_storage_iceberg_with_spark/test_single_iceberg_file.py	1020
test_backward_compatibility/test_nullable_sparse_compatibility.py	1012
test_insert_into_distributed/test.py	1000
test_s3_style_link/test.py	998
test_jbod_load_balancing/test.py	996
test_shard_names/test.py	995
test_s3_non_deterministic_partition_by/test.py	988
test_storage_iceberg_with_spark/test_pruning_nullable_bug.py	984
test_storage_iceberg_no_spark/test_writes_with_compression_metadata.py	961
test_format_schema_on_server/test.py	958
test_catboost_evaluate/test.py	928
test_storage_numbers/test.py	897
test_backup_s3_storage_class/test.py	897
test_storage_iceberg_no_spark/test_writes_nullable_bugs2.py	895
test_max_authentication_methods_per_user/test.py	895
test_insert_over_http_query_log/test.py	872
test_dictionaries_postgresql/test.py	854
test_replicated_parse_zk_metadata/test.py	854
test_s3_storage_class/test.py	846
test_block_structure_mismatch/test.py	845
test_password_constraints/test.py	841
test_range_hashed_dictionary_types/test.py	840
test_memory_profiler_min_max_borders/test.py	824
test_settings_randomization/test.py	797
test_endpoint_macro_substitution/test.py	796
test_internal_queries_not_counted/test.py	796
test_executable_dictionary/test.py	796
test_storage_url/test.py	795
test_distributed_inter_server_secret/test.py	795
test_dictionaries_select_all/test.py	794
test_allowed_client_hosts/test.py	778
test_server_keep_alive/test.py	765
test_composable_protocols/test.py	756
test_keeper_path_acl/test.py	754
test_backward_compatibility/test.py	746
test_arrowflight_storage/test.py	732
test_parallel_replicas_protocol/test.py	728
test_storage_iceberg_with_spark/test_relevant_iceberg_schema_chosen.py	714
test_storage_azure_blob_storage/test.py	712
test_custom_settings/test.py	706
test_timezone_config/test.py	694
test_authentication/test.py	684
test_storage_azure_blob_storage/test_cluster.py	682
test_merge_table_over_distributed/test.py	680
test_replicated_users/test.py	680
test_disks_app_func/test.py	678
test_server_initialization/test.py	672
test_backward_compatibility/test_const_node_optimization.py	667
test_odbc_interaction/test.py	662
test_peak_memory_usage/test.py	647
test_table_function_redis/test.py	639
test_storage_iceberg_no_spark/test_writes_create_table_bugs.py	631
test_buffer_profile/test.py	631
test_passing_max_partitions_to_read_remotely/test.py	630
test_storage_iceberg_with_spark/test_minmax_pruning_for_arrays_and_maps_subfields_disabled.py	628
test_relative_filepath/test.py	620
test_storage_iceberg_with_spark/test_cluster_table_function_with_partition_pruning.py	614
test_keeper_four_word_command/test.py	606
test_profile_max_sessions_for_user/test.py	606
test_jdbc_bridge/test.py	590
test_s3_cluster/test.py	587
test_parallel_replicas_skip_shards/test.py	582
test_unknown_column_dist_table_with_alias/test.py	581
test_storage_iceberg_no_spark/test_graceful_error_not_configured_iceberg_metadata_log.py	580
test_backward_compatibility/test_cte_distributed.py	556
test_storage_url_with_proxy/test.py	536
test_profile_settings_and_constraints_order/test.py	531
test_replica_can_become_leader/test.py	531
test_config_decryption/test.py	531
test_backward_compatibility/test_insert_profile_events.py	530
test_file_cluster/test.py	530
test_prometheus_protocols/test_evaluation.py	523
test_structured_logging_json/test.py	502
test_old_versions/test.py	502
test_table_function_mongodb/test.py	480
test_graphite_merge_tree/test.py	466
test_graphite_merge_tree_typed/test.py	458
test_ssl_cert_authentication/test.py	456
test_keeper_session/test.py	444
test_external_http_authenticator/test.py	410
test_keeper_back_to_back/test.py	397
test_disks_app_other_disk_types/test.py	387
test_dictionaries_with_invalid_structure/test.py	366
test_storage_url_http_headers/test.py	353
test_keeper_availability_zone/test.py	334
test_storage_nats/test_nats_jet_stream.py	327
test_geoparquet/test.py	318
test_delayed_remote_source/test.py	315
test_unambiguous_alter_commands/test.py	315
test_user_grants_from_config/test.py	315
test_remote_function_view/test.py	315
test_backward_compatibility/test_old_client_with_replicated_columns.py	315
test_replicating_constants/test.py	315
test_shard_level_const_function/test.py	315
test_disk_types/test.py	315
test_remote_prewhere/test.py	315
test_storage_nats/test_nats_core.py	315
test_cluster_all_replicas/test.py	294
test_kerberos_auth/test.py	292
test_keeper_metrics_only/test.py	271
test_keeper_secure_client/test.py	267
test_mysql_protocol/test.py	266
test_keeper_compression/test_with_compression.py	266
test_config_decryption/test_zk.py	265
test_config_decryption/test_zk_secure.py	265
test_union_header/test.py	265
test_accept_invalid_certificate/test.py	265
test_async_logger_metrics/test.py	265
test_parquet_page_index/test.py	265
test_ssh_keys_authentication/test.py	265
test_keeper_and_access_storage/test.py	265
test_keeper_compression/test_without_compression.py	265
test_logs_level/test.py	265
test_distributed_over_distributed/test.py	265
test_render_log_file_name_templates/test.py	262
test_arrowflight_interface/test.py	253
test_format_avro_confluent/test.py	216
test_case_insensitive_disk/test.py	192
test_http_and_readonly/test.py	182
test_ssh/test.py	148
test_tlsv1_3/test.py	131
test_http_native/test.py	131
test_host_regexp_hosts_file_resolution/test.py	125
test_postgresql_protocol/test.py	109
test_disks_app_interactive/test.py	108
test_keeper_ipv4_fallback/test.py	107
test_ssh/test_options_propagation_enabled.py	64
test_keeper_http_storage_control/test.py	55
test_tcp_handler_http_responses/test_case.py	54
test_grpc_protocol/test.py	44
test_keeper_http_control_readiness/test.py	9
test_keeper_client/test.py	8
test_tcp_handler_interserver_listen_host/test_case.py	4
"""


def _parse_raw_durations(raw: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for line in raw.strip().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Accept both tab- and space-separated formats; last token is duration
        parts = line.split()
        try:
            duration = int(parts[-1])
        except Exception:
            continue
        path = " ".join(parts[:-1])
        out[path] = duration
    return out


TEST_DURATIONS: dict[str, int] = _parse_raw_durations(RAW_TEST_DURATIONS)


def get_tests_execution_time(info: Info, job_options: str) -> dict[str, int]:
    assert info.updated_at
    start_time_filter = f"parseDateTimeBestEffort('{info.updated_at}')"

    build = job_options.split(',', 1)[0]

    query = f"""
        SELECT
            file,
            round(sum(test_duration_ms)) AS file_duration_ms
        FROM
        (
            SELECT
                splitByString('::', test_name)[1] AS file,
                median(test_duration_ms) AS test_duration_ms
            FROM checks
            WHERE (check_name LIKE 'Integration tests%')
                AND (check_name LIKE '%{build}%')
                AND (check_start_time >= ({start_time_filter} - toIntervalDay(20)))
                AND (check_start_time <= ({start_time_filter} - toIntervalHour(5)))
                AND ((head_ref = 'master') AND startsWith(head_repo, 'ClickHouse/'))
                AND (file != '')
                AND (test_status != 'SKIPPED')
                AND (test_status != 'FAIL')
            GROUP BY test_name
        )
        GROUP BY file
        ORDER BY ALL
        SETTINGS use_query_cache = 1, query_cache_ttl = 432000, query_cache_nondeterministic_function_handling = 'save', query_cache_share_between_users = 1
        FORMAT JSON
    """

    client = CIDBCluster()
    print(query)
    try:
        res = client.do_select_query(query, retries=5, timeout=20)
    except Exception as e:
        print(e)
        print(traceback.format_exc())
        return {}

    if not res:
        return {}
    try:
        import json
        data = json.loads(res)
        return {row["file"]: int(row["file_duration_ms"]) for row in data["data"]}
    except Exception as e:
        print(f"ERROR: Failed to parse CIDB response: {e}")
        return {}

def get_optimal_test_batch(
    tests: list[str],
    total_batches: int,
    batch_num: int,
    num_workers: int,
    job_options: str,
    info: Info = None,
) -> tuple[list[str], list[str]]:
    """
    @tests - all tests to run
    @total_batches - total number of batches
    @batch_num - current batch number
    @num_workers - number of parallel workers in a batch
    returns optimal subset of parallel tests for batch_num and optimal subset of sequential tests for batch_num, based on data in TEST_DURATIONS.
    Test files not present in TEST_DURATIONS will be distributed by round robin.
    The function optimizes tail latency of batch with num_workers parallel workers.
    The function works in a deterministic way, so that batch calculated on the other machine with the same input generates the same result.
    """
    # parallel_skip_prefixes sanity check
    for test_config in TEST_CONFIGS:
        assert any(
            test_file.removeprefix("./").startswith(test_config.prefix)
            for test_file in tests
        ), f"No test files found for prefix [{test_config.prefix}] in [{tests}]"

    sequential_test_modules = [
        test_file
        for test_file in tests
        if any(test_file.startswith(test_config.prefix) for test_config in TEST_CONFIGS)
    ]
    parallel_test_modules = [
        test_file for test_file in tests if test_file not in sequential_test_modules
    ]

    if batch_num > total_batches:
        raise ValueError(f"batch_num must be in [1, {total_batches}], got {batch_num}")

    # Helper: group tests by their top-level directory (prefix)
    #  same prefix tests are grouped together to minimize docker pulls in test fixtures in each job batch
    def group_by_prefix(items: list[str]) -> dict[str, list[str]]:
        groups: dict[str, list[str]] = {}
        for it in sorted(items):
            prefix = it.split("/", 1)[0]
            groups.setdefault(prefix, []).append(it)
        return groups

    # Parallel groups and Sequential groups separated to allow distinct packing
    parallel_groups = group_by_prefix(parallel_test_modules)
    sequential_groups = group_by_prefix(sequential_test_modules)

    durations = TEST_DURATIONS

    # Compute group durations as sum of known test durations within the group
    # TODO: fix in private
    #   ERROR: Failed to get secret [PRIVATE_CI_DB_URL]
    if info and not info.is_local_run:
        durations = get_tests_execution_time(info, job_options)
        if not durations:
            print("WARNING: CIDB durations not found, using static TEST_DURATIONS")
            durations = TEST_DURATIONS

    def groups_with_durations(groups: dict[str, list[str]]):
        known_groups: list[tuple[str, int]] = []  # (prefix, duration)
        unknown_groups: list[str] = []  # prefixes with zero known duration
        for prefix, items in sorted(groups.items()):
            dur = sum(durations.get(t, 0) for t in items)
            if dur > 0:
                known_groups.append((prefix, dur))
            else:
                unknown_groups.append(prefix)
        # Sort known by (-duration, prefix) for deterministic LPT
        known_groups.sort(key=lambda x: (-x[1], x[0]))
        # Sort unknown prefixes to make RR deterministic
        unknown_groups.sort()
        return known_groups, unknown_groups

    p_known, p_unknown = groups_with_durations(parallel_groups)
    s_known, s_unknown = groups_with_durations(sequential_groups)

    # Sequential batches: start from scaled parallel weights to account for worker concurrency
    sequential_batches: list[list[str]] = [[] for _ in range(total_batches)]
    sequential_weights: list[int] = [0] * total_batches

    # LPT assign known-duration sequential groups
    for prefix, dur in s_known:
        idx = min(range(total_batches), key=lambda i: (sequential_weights[i], i))
        # prefix, dur sorted in s_known starting with longest duration - keep the order in batches to decrease tail latency
        sequential_batches[idx].extend(sequential_groups[prefix])
        sequential_weights[idx] += dur

    # Round-robin assign unknown-duration sequential groups
    for i, prefix in enumerate(s_unknown):
        idx = i % total_batches
        sequential_batches[idx].extend(sequential_groups[prefix])

    # Prepare batch containers and weights
    parallel_batches: list[list[str]] = [[] for _ in range(total_batches)]
    parallel_weights: list[int] = [w * num_workers for w in sequential_weights]

    # LPT assign known-duration parallel groups
    for prefix, dur in p_known:
        idx = min(range(total_batches), key=lambda i: (parallel_weights[i], i))
        # prefix, dur sorted in p_known starting with longest duration - keep the order in batches to decrease tail latency
        parallel_batches[idx].extend(parallel_groups[prefix])
        parallel_weights[idx] += dur

    # Sort tests within each batch by duration (longest first) to minimize tail latency
    # when tests are picked by workers from the queue
    for idx in range(total_batches):
        parallel_batches[idx].sort(key=lambda x: (-durations.get(x, 0), x))

    # Round-robin assign unknown-duration parallel groups
    for i, prefix in enumerate(p_unknown):
        idx = i % total_batches
        parallel_batches[idx].extend(parallel_groups[prefix])

    print(
        f"Batches parallel weights: [{[weight // num_workers // 1000 for weight in parallel_weights]}]"
    )
    print(f"Batches weights: [{[weight // 1000 for weight in sequential_weights]}]")

    # Sanity check (non-fatal): ensure total test count preserved
    total_assigned = sum(len(b) for b in parallel_batches) + sum(
        len(b) for b in sequential_batches
    )
    assert total_assigned == len(tests)

    return parallel_batches[batch_num - 1], sequential_batches[batch_num - 1]
