#
# Makefile
#
# $Id: //poco/Main/Data/SQLite/testsuite/Makefile#1 $
#
# Makefile for Poco SQLite testsuite
#

include $(POCO_BASE)/build/rules/global

objects = SQLiteTestSuite Driver \
	SQLiteTest

target         = testrunner
target_version = 1
target_libs    = PocoDataSQLite PocoData PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
