#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/StringTokenizer/Makefile#1 $
#
# Makefile for Poco StringTokenizer
#

include $(POCO_BASE)/build/rules/global

objects = StringTokenizer

target         = StringTokenizer
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
