#!/usr/bin/env python3
"""
Fully-generated page-per-item groups for domains that have no hand-written
reference pages: data skipping index types (`system.data_skipping_index_types`)
and disk types (`system.disk_types`).

Each item gets a page built purely from the system table row (Description /
Syntax / Examples / Introduced in / Related sections, empty ones omitted),
plus a generated overview page, in a navigation group of its own. The pages
carry a "fully autogenerated" header comment and are safe to overwrite on
every run.
"""

import catalog
import introspect

HEADER_COMMENT = (
    "{/* This page is fully autogenerated from the ClickHouse source by"
    " ci/jobs/scripts/docs/autogenerate -- do not edit; change the"
    " documentation embedded in the source instead. */}"
)

COLUMNS = "name, description, syntax, examples, introduced_in, related"

DOMAINS = [
    {
        "family": "skipping-indexes",
        "source_table": "system.data_skipping_index_types",
        "query": f"SELECT {COLUMNS} FROM system.data_skipping_index_types ORDER BY name",
        "dir": "reference/engines/table-engines/mergetree-family/skipping-indexes",
        "slug_prefix": "/engines/table-engines/mergetree-family/skipping-indexes",
        "title": "{name} skipping index",
        "index_title": "Data skipping indexes",
        "index_intro": (
            "Data skipping indexes are secondary indexes on `MergeTree`-family"
            " tables that let queries skip granules that provably cannot"
            " match. See the [`MergeTree` documentation]"
            "(/reference/engines/table-engines/mergetree-family/mergetree#table_engine-mergetree-data_skipping-indexes)"
            " for how indexes are declared and used, and [ALTER TABLE ... ADD"
            " INDEX](/reference/statements/alter/skipping-index) for managing"
            " them. The available index types:"
        ),
        "nav_parent": ["Engines", "Table Engines", "MergeTree Family"],
        "nav_group": "Data Skipping Indexes",
        "nav_after": None,  # appended at the end of the parent group
    },
    {
        "family": "disk-types",
        "source_table": "system.disk_types",
        "query": f"SELECT {COLUMNS} FROM system.disk_types ORDER BY name",
        "dir": "reference/disks",
        "slug_prefix": "/operations/disk-types",
        "title": "{name} disk",
        "index_title": "Disk types",
        "index_intro": (
            "Disks define where ClickHouse stores data: local filesystems,"
            " object storage, caches, or encrypted wrappers. They are declared"
            " in the [server configuration or with the `disk` function]"
            "(/concepts/features/configuration/server-config/storing-data),"
            " and shown in the"
            " [`system.disks`](/reference/system-tables/disks) table. The"
            " available disk types:"
        ),
        "nav_parent": [],
        "nav_group": "Disk Types",
        "nav_after": "Settings",
    },
]


def _item_page(domain, row, names):
    name = row["name"]
    title = domain["title"].format(name=name)
    fm = "\n".join([
        "---",
        f"description: {catalog.yaml_quote(catalog.first_sentence(row['description']))}",
        f"sidebarTitle: {catalog.yaml_quote(name)}",
        f"slug: {domain['slug_prefix']}/{name}",
        f"title: {catalog.yaml_quote(title)}",
        "doc_type: 'reference'",
        "---",
    ])
    parts = [fm, "", catalog.badge(domain["source_table"]), "",
             HEADER_COMMENT, "", row["description"].strip()]
    if row.get("syntax"):
        parts += ["", "## Syntax {#syntax}", "", "```sql",
                  row["syntax"].strip(), "```"]
    if row.get("examples"):
        parts += ["", "## Examples {#examples}", "", row["examples"].strip()]
    if row.get("introduced_in"):
        parts += ["", "## Introduced in {#introduced-in}", "",
                  f"v{row['introduced_in']}"]
    related = [r for r in row.get("related") or []]
    if related:
        parts += ["", "## Related {#related}", ""]
        for rel in related:
            if rel in names:
                parts.append(f"- [`{rel}`]({domain['dir'].replace('reference', '/reference', 1)}/{rel})")
            else:
                parts.append(f"- `{rel}`")
    return "\n".join(parts) + "\n"


def _index_page(domain, rows):
    fm = "\n".join([
        "---",
        f"description: {catalog.yaml_quote(domain['index_title'])}",
        f"sidebarTitle: {catalog.yaml_quote(domain['index_title'])}",
        f"slug: {domain['slug_prefix']}/",
        f"title: {catalog.yaml_quote(domain['index_title'])}",
        "doc_type: 'reference'",
        "---",
    ])
    lines = [fm, "", catalog.badge(domain["source_table"]), "",
             HEADER_COMMENT, "", domain["index_intro"], "",
             "| Type | Description |", "|-----|-----|"]
    base = domain["dir"].replace("reference", "/reference", 1)
    for row in rows:
        description = " ".join(row["description"].split()).replace("|", "\\|")
        lines.append(f"| [`{row['name']}`]({base}/{row['name']}) | {description} |")
    return "\n".join(lines) + "\n"


def build_generators(binary, docs_dir):
    gens = []
    for domain in DOMAINS:
        rows = introspect.fetch_rows(binary, domain["query"])
        names = {row["name"] for row in rows}
        page_ids = [f"{domain['dir']}/index"] + sorted(
            f"{domain['dir']}/{row['name']}" for row in rows
        )
        for row in rows:
            gens.append({
                "name": f"{domain['family']}:{row['name']}",
                "content": _item_page(domain, row, names),
                "dest": f"docs/{domain['dir']}/{row['name']}.md",  # unused
                "dest_rel": f"{domain['dir']}/{row['name']}.mdx",
                "method": "overwrite",
                "no_transform": True,
            })
        gens.append({
            "name": f"{domain['family']}:index",
            "content": _index_page(domain, rows),
            "dest": f"docs/{domain['dir']}/index.md",  # unused
            "dest_rel": f"{domain['dir']}/index.mdx",
            "method": "overwrite",
            "no_transform": True,
            # The whole navigation group is owned by this generator.
            "nav_group": {
                "parent_path": domain["nav_parent"],
                "group": domain["nav_group"],
                "root": f"{domain['dir']}/index",
                "pages": page_ids,
                "after_group": domain["nav_after"],
            },
        })
    return gens
