#!/usr/bin/env bash

set -e

# We check only our code, that's why we skip contrib
GIT_ROOT=$(git rev-parse --show-cdup)
GIT_ROOT=${GIT_ROOT:-.}
tmp=$(mktemp)
# Find all *.py files in the repo except the contrib directory
find_cmd=(find "$GIT_ROOT" -name '*.py' -not -path "$GIT_ROOT/contrib/*")
if ! "${find_cmd[@]}" -exec black --diff {} + 1>"$tmp" 2>&1; then
  # Show the result only if some files need formatting
  cat "$tmp"
  # Automatically add changed files to stage
  "${find_cmd[@]}" -exec git add -u {} +
fi
rm "$tmp"
