name: Setup
description: Setup environment
runs:
  using: "composite"
  steps:
    - name: Configure docker proxy and dataset mirror host
      shell: bash
      run: |
          proxy_host=dockerhub-proxy.dockerhub-proxy-zone
          if ! timeout 5 getent ahostsv4 "$proxy_host" >/dev/null; then
            echo "65.108.242.32 $proxy_host" | sudo tee -a /etc/hosts
          fi
    - name: Setup zram
      shell: bash
      run: |
          # Skip if zram swap is already active
          if grep -q '/dev/zram0' /proc/swaps; then
            echo "/dev/zram0 swap already configured, skipping zram setup."
            exit 0
          fi

          sudo modprobe zram
          MemTotal=$(grep -Po "(?<=MemTotal:)\s+\d+" /proc/meminfo) # KiB
          Percent=200
          ZRAM_SIZE=$(($MemTotal / 1024 / 1024 * $Percent / 100)) # Convert to GiB
          .github/retry.sh 30 2 sudo zramctl --size ${ZRAM_SIZE}GiB --algorithm zstd /dev/zram0
          sudo mkswap /dev/zram0 && sudo swapon -p 100 /dev/zram0
          sudo sysctl vm.swappiness=200
    - name: Install awscli
      shell: bash
      run: |
          .github/retry.sh 10 30 sudo apt-get install -y awscli
