name: Setup
description: Setup environment
runs:
  using: "composite"
  steps:
    - name: Setup zram
      shell: bash
      run: |
          sudo modprobe zram
          MemTotal=$(grep -Po "(?<=MemTotal:)\s+\d+" /proc/meminfo) # KiB
          Percent=200
          ZRAM_SIZE=$(($MemTotal / 1024 / 1024 * $Percent / 100)) # Convert to GiB
          .github/retry.sh 30 2 sudo zramctl --size ${ZRAM_SIZE}GiB --algorithm zstd /dev/zram0
          sudo mkswap /dev/zram0 && sudo swapon -p 100 /dev/zram0
          sudo sysctl vm.swappiness=200
    - name: Install awscli
      shell: bash
      run: |
          .github/retry.sh 10 30 sudo apt-get install -y awscli
