/* WARNING: do not edit! */
/* Generated by Makefile from include/crypto/dso_conf.h.in */
/*
 * Copyright 2016-2021 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the Apache License 2.0 (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef OSSL_CRYPTO_DSO_CONF_H
# define OSSL_CRYPTO_DSO_CONF_H
# pragma once

/* ClickHouse: this header is shared by all the platforms we build for. Windows has no
 * `dlfcn.h`; the equivalent `LoadLibrary`-based loader lives in `crypto/dso/dso_win32.c`,
 * which is already in the source list and is selected by `DSO_WIN32`. */
# if defined(_WIN32)
#  define DSO_WIN32
#  define DSO_EXTENSION ".dll"
# else
#  define DSO_DLFCN
#  define HAVE_DLFCN_H
#  define DSO_EXTENSION ".so"
# endif
#endif
