#
# Makefile
#
# $Id$
#
# Makefile for Poco MongoDB SQLToMongo
#

include $(POCO_BASE)/build/rules/global

objects = SQLToMongo

target         = SQLToMongo
target_version = 1
target_libs    = PocoMongoDB PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/exec
