#!/bin/sh

if [ -n "$CCACHEDIR" ]; then
    mkdir -p $CCACHEDIR || true
    chown -R $BUILDUSERID:$BUILDUSERID $CCACHEDIR || true
    chmod -R a+rwx $CCACHEDIR || true
fi

ccache --show-stats
ccache -M ${CCACHE_SIZE:=32G}
