#!/usr/bin/env bash
set -e
set -x

for PKG in $(ls /tmp/buildd/*.deb | sed -e's,.*/,,;s,_.*,,' ); do
    apt-get install -y --force-yes "$PKG" || true
    apt-get remove -y "$PKG" || true
done

dpkg -i /tmp/buildd/*.deb || true
apt install -y -f --allow-downgrades


# Some test references uses specific timezone
ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
echo 'Europe/Moscow' > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

mkdir -p /etc/clickhouse-server/config.d /etc/clickhouse-client/config.d

TEST_SSL=${TEST_SSL=1}
if  [ "${TEST_SSL}" ]; then
    echo "<yandex><https_port>8443</https_port><tcp_ssl_port>9440</tcp_ssl_port></yandex>" > /etc/clickhouse-server/config.d/ssl.xml
    echo "<yandex><openSSL><client><verificationMode>none</verificationMode><invalidCertificateHandler><name>AcceptCertificateHandler</name></invalidCertificateHandler></client></openSSL></yandex>" > /etc/clickhouse-client/config.d/ssl.xml

    openssl dhparam -out /etc/clickhouse-server/dhparam.pem 256
    openssl req -subj "/CN=localhost" -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /etc/clickhouse-server/server.key -out /etc/clickhouse-server/server.crt
fi

service clickhouse-server start
sleep 3

# TODO: remove me or make only on error:
tail -n100 /var/log/clickhouse-server/*

clickhouse-client -q "SELECT * from system.build_options;"
clickhouse-client ${CLIENT_ADD} -q "SELECT toDateTime(1);"


( [ "${TEST_RUN}" ] && clickhouse-test --queries /usr/share/clickhouse-test/queries --tmp /tmp/clickhouse-test/ ${TEST_OPT} ) || ${TEST_TRUE:=true}


service clickhouse-server stop

# Test debug symbols
# gdb -ex quit --args /usr/bin/clickhouse-server
