#!/usr/bin/env bash
set -e 
set -x

for PKG in $(ls /tmp/buildd/*.deb | sed -e's,.*/,,;s,_.*,,' ); do
    apt-get install -y --force-yes "$PKG" || true 
    apt-get remove -y "$PKG" || true 
done

dpkg -i /tmp/buildd/*.deb || true
apt install -y -f --allow-downgrades


service clickhouse-server start
sleep 3


clickhouse-client -q "SELECT * from system.build_options;"

# --no-shard because default server listen only :: and 127.0.0.1
[ -n "$TEST_RUN" ] && clickhouse-test --no-shard --queries /usr/share/clickhouse-test/queries --tmp /tmp/clickhouse-test/ || true


service clickhouse-server stop
