#
# Makefile
#
# $Id: //poco/1.4/NetSSL_OpenSSL/samples/Makefile#2 $
#
# Makefile for Poco NetSSL Samples
#

.DEFAULT all:
	$(MAKE) -C HTTPSTimeServer $(MAKECMDGOALS)
	$(MAKE) -C download $(MAKECMDGOALS)
	$(MAKE) -C Mail $(MAKECMDGOALS)
	$(MAKE) -C TwitterClient $(MAKECMDGOALS)
