#
# Makefile
#
# $Id: //poco/svn/Util/samples/SampleServer/Makefile#1 $
#
# Makefile for Poco SampleServer
#

include $(POCO_BASE)/build/rules/global

objects = Units

target         = Units
target_version = 1
target_libs    = 

include $(POCO_BASE)/build/rules/exec
