-- SQL-statement documentation generator.
-- Usage: one page per statement, selected by the registered statement name:
--   clickhouse --param_statement='SELECT' --queries-file generate-statements.sql
--
-- system.statements.description holds the complete Markdown body of the
-- statement's reference page. The Python generator inserts it verbatim between
-- the page's AUTOGENERATED markers.
SELECT description
FROM system.statements
WHERE name = {statement:String}
  AND notEmpty(description)
LIMIT 1
INTO OUTFILE 'temp-statement.md' TRUNCATE FORMAT LineAsString
