name: Sanitizer alert
description: Potential issue has been found by special code instrumentation
labels: ["testing"]
body:
  - type: markdown
    attributes:
      value: |
        > (you don't have to strictly follow this form)
  - type: textarea
    attributes:
      label: Describe the bug
      description: A link to the report.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      description: Try to reproduce the report and copy the tables and queries involved.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Error message and/or stacktrace
      description: You can find additional information in server logs.
    validations:
      required: false
