#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/hmacmd5/Makefile#1 $
#
# Makefile for Poco hmacmd5
#

include $(POCO_BASE)/build/rules/global

objects = hmacmd5

target         = hmacmd5
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
