#
# Makefile
#
# $Id: //poco/Main/Data/samples/TypeHandler/Makefile#1 $
#
# Makefile for Poco Data TypeHandler sample
#

include $(POCO_BASE)/build/rules/global

objects = TypeHandler

target         = TypeHandler
target_version = 1
target_libs    = PocoDataSQLite PocoData PocoFoundation 

include $(POCO_BASE)/build/rules/exec
