find_library (TERMCAP_LIBRARY tinfo)
if (NOT TERMCAP_LIBRARY)
    find_library (TERMCAP_LIBRARY ncurses)
endif()
if (NOT TERMCAP_LIBRARY)
    find_library (TERMCAP_LIBRARY termcap)
endif()
if (NOT TERMCAP_LIBRARY)
    message (${RECONFIGURE_MESSAGE_LEVEL} "Can't find tinfo, ncurses or termcap library")
endif()
message (STATUS "Using termcap: ${TERMCAP_LIBRARY}")
