#!/usr/bin/env bash

for i in $(seq 1 100); do
    clickhouse-client --query "SELECT * FROM system.one" 1>/dev/null 2>/dev/null;
    [[ $? -eq 0 ]] && break
    [[ $(pgrep -l clickhouse-s | wc -l) -lt 1 ]] && echo "Error" && exit -1
    sleep 1
done

