#
# Makefile
#
# $Id$
#
# Makefile for Poco MongoDB testsuite
#

include $(POCO_BASE)/build/rules/global

objects = Driver MongoDBTest MongoDBTestSuite

target         = testrunner
target_version = 1
target_libs    = PocoMongoDB PocoFoundation PocoNet CppUnit

include $(POCO_BASE)/build/rules/exec
