#
# Makefile
#
# $Id: //poco/1.4/Zip/testsuite/Makefile#1 $
#
# Makefile for Poco Zip testsuite
#

include $(POCO_BASE)/build/rules/global

objects = ZipTestSuite Driver \
	ZipTest	CompressTest PartialStreamTest

target         = testrunner
target_version = 1
target_libs    = PocoZip PocoNet PocoFoundation CppUnit

include $(POCO_BASE)/build/rules/exec
