/// Only edit the `.in` file, as it is the source for autogeneration by CMake

const char * auto_config_build[]
{
    "VERSION_FULL", "ClickHouse 26.7.1.1",
    "VERSION_DESCRIBE", "v26.7.1.1-testing",
    "VERSION_INTEGER", "26007001",
    "VERSION_NAME", "ClickHouse",
    "VERSION_MAJOR", "26",
    "VERSION_MINOR", "7",
    "VERSION_PATCH", "1",
    "VERSION_STRING", "26.7.1.1",
    "VERSION_STRING_SHORT", "26.7",
    "VERSION_OFFICIAL", "",
    "SYSTEM", "Linux",
    "VERSION_GITHASH", "d5846cd8b28736322e10fa5f4158d542224fd16d",
    "VERSION_REVISION", "54512",
    "BUILD_TYPE", "RelWithDebInfo",
    "SYSTEM_PROCESSOR", "aarch64",
    "CMAKE_VERSION", "4.2.3",
    "C_COMPILER", "/usr/local/bin/clang",
    "C_COMPILER_VERSION", "21.1.8",
    "CXX_COMPILER", "/usr/local/bin/clang++",
    "CXX_COMPILER_VERSION", "21.1.8",
    "C_FLAGS", " --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-aarch64 --no-default-config -fdiagnostics-color=always  -pipe -march=armv8.2-a+simd+crypto+dotprod+ssbs+rcpc+bf16 -fasynchronous-unwind-tables -fdebug-compilation-dir=. -ffile-prefix-map=./= -falign-functions=64 -falign-loops=32 -ffunction-sections -fdata-sections -faddrsig -ffp-contract=off -fno-math-errno  -fdiagnostics-absolute-paths -fPIC -fxray-instrument -fxray-modes=none -fxray-instrumentation-bundle=function -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-return-type-c-linkage -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++20-compat -Wno-sign-conversion -Wno-deprecated-declarations -Wno-documentation-unknown-command -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-unsafe-buffer-usage -Wno-switch-default -Wno-nrvo -Wno-missing-noreturn -Wno-c2y-extensions -Wno-c23-extensions -O2 -g -DNDEBUG -O3 -g -gdwarf-aranges ",
    "CXX_FLAGS", " --gcc-toolchain=./cmake/linux/../../contrib/sysroot/linux-aarch64 --no-default-config -fdiagnostics-color=always  -pipe -march=armv8.2-a+simd+crypto+dotprod+ssbs+rcpc+bf16 -fasynchronous-unwind-tables -fdebug-compilation-dir=. -ffile-prefix-map=./= -falign-functions=64 -falign-loops=32 -ffunction-sections -fdata-sections -faddrsig -ffp-contract=off -fno-math-errno  -fdiagnostics-absolute-paths -fstrict-vtable-pointers -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST -fPIC -fxray-instrument -fxray-modes=none -fxray-instrumentation-bundle=function -Wall -Wextra -Wframe-larger-than=65536 -Weverything -Wpedantic -Wno-return-type-c-linkage -Wno-zero-length-array -Wno-c++98-compat-pedantic -Wno-c++20-compat -Wno-sign-conversion -Wno-deprecated-declarations -Wno-documentation-unknown-command -Wno-exit-time-destructors -Wno-float-equal -Wno-global-constructors -Wno-missing-variable-declarations -Wno-padded -Wno-switch-enum -Wno-undefined-func-template -Wno-unused-template -Wno-weak-template-vtables -Wno-weak-vtables -Wno-thread-safety-negative -Wno-unsafe-buffer-usage -Wno-switch-default -Wno-nrvo -Wno-missing-noreturn -Wno-c2y-extensions -Wno-c23-extensions -O2 -g -DNDEBUG -O3 -g -gdwarf-aranges ",
    "LINK_FLAGS", " --no-default-config --ld-path=/usr/local/bin/ld.lld -Wl,--no-export-dynamic -Wl,--gc-sections -Wl,--icf=all -Wl,--build-id=sha1 -Wl,-u,logf -Wl,-u,powf -Wl,-u,expf -Wl,-u,exp2f -Wl,-u,log2f -Wl,-u,log -Wl,-u,pow -Wl,-u,exp -Wl,-u,exp2 -Wl,-u,log2 -Wl,--whole-archive ./contrib/compiler-rt-cmake/libclang_rt_builtins.a -fno-xray-link-deps ./contrib/compiler-rt-cmake/libclang_rt_xray.a -Wl,--no-whole-archive -Wl,-u,memcpy -Wl,-u,memmove -Wl,-u,memset -Wl,-u,memcmp ",
    "USE_EMBEDDED_COMPILER", "ON",
    "USE_GLIBC_COMPATIBILITY", "ON",
    "USE_JEMALLOC", "1",
    "USE_ICU", "1",
    "USE_H3", "1",
    "USE_MYSQL", "1",
    "USE_RDKAFKA", "1",
    "USE_CAPNP", "1",
    "USE_SIMDUTF", "1",
    "USE_HDFS", "1",
    "USE_SNAPPY", "1",
    "USE_PARQUET", "1",
    "USE_PROTOBUF", "1",
    "USE_BROTLI", "1",
    "USE_LIBDEFLATE", "1",
    "USE_SSL", "1",
    "OPENSSL_VERSION", "3.5.7",
    "USE_VECTORSCAN", "1",
    "USE_SIMDJSON", "1",
    "USE_GRPC", "1",
    "USE_LDAP", "1",
    "TZDATA_VERSION", "2025a",
    "USE_KRB5", "1",
    "USE_FILELOG", "1",
    "USE_BZIP2", "1",
    "USE_AMQPCPP", "1",
    "USE_ROCKSDB", "1",
    "USE_NURAFT", "1",
    "USE_NLP", "1",
    "USE_LIBSTEMMER", "1",
    "USE_LIBURING", "1",
    "USE_SQLITE", "1",
    "USE_LIBPQXX", "1",
    "USE_AZURE_BLOB_STORAGE", "1",
    "USE_AWS_S3", "1",
    "USE_GOOGLE_CLOUD", "1",
    "USE_CASSANDRA", "1",
    "USE_YAML_CPP", "1",
    "USE_DATASKETCHES", "1",
    "USE_AVRO", "1",
    "USE_ARROW", "1",
    "USE_ORC", "1",
    "USE_MSGPACK", "1",
    "USE_DELTA_KERNEL_RS", "1",
    "USE_XRAY", "1",
    "USE_WASMEDGE", "1",
    "USE_WASMTIME", "1",
    "WITH_COVERAGE", "OFF",
    "WITH_COVERAGE_DEPTH", "OFF",
    "CLICKHOUSE_CLOUD", "0",
    "GIT_HASH", "96188b3b043fa265e0d1369ebf5a5267fe441a63",
    "GIT_BRANCH", R"IRjaNsZIL9Yh7FQ4(native-gcs)IRjaNsZIL9Yh7FQ4",
    "GIT_DATE", "2026-07-20 07:25:22 +0000",
    "GIT_COMMIT_SUBJECT", R"Gi17KJMlbGCjErEN(Carry the full `gcs` reference page body in both registration branches)Gi17KJMlbGCjErEN",

    nullptr, nullptr
};
