LIBRARY()

PEERDIR(
    clickhouse/contrib/croaring
    clickhouse/contrib/pcg-random
    clickhouse/dbms/src/Common
)

SRCS(
    AggregateFunctionAggThrow.cpp
    AggregateFunctionArray.cpp
    AggregateFunctionAvg.cpp
    AggregateFunctionAvgWeighted.cpp
    AggregateFunctionBitwise.cpp
    AggregateFunctionBoundingRatio.cpp
    AggregateFunctionCategoricalInformationValue.cpp
    AggregateFunctionCombinatorFactory.cpp
    AggregateFunctionCount.cpp
    AggregateFunctionEntropy.cpp
    AggregateFunctionFactory.cpp
    AggregateFunctionForEach.cpp
    AggregateFunctionGroupArray.cpp
    AggregateFunctionGroupArrayInsertAt.cpp
    AggregateFunctionGroupArrayMoving.cpp
    AggregateFunctionGroupBitmap.cpp
    AggregateFunctionGroupUniqArray.cpp
    AggregateFunctionHistogram.cpp
    AggregateFunctionIf.cpp
    AggregateFunctionMaxIntersections.cpp
    AggregateFunctionMerge.cpp
    AggregateFunctionMinMaxAny.cpp
    AggregateFunctionMLMethod.cpp
    AggregateFunctionNull.cpp
    AggregateFunctionOrFill.cpp
    AggregateFunctionQuantile.cpp
    AggregateFunctionResample.cpp
    AggregateFunctionRetention.cpp
    AggregateFunctionSequenceMatch.cpp
    AggregateFunctionSimpleLinearRegression.cpp
    AggregateFunctionState.cpp
    AggregateFunctionStatistics.cpp
    AggregateFunctionStatisticsSimple.cpp
    AggregateFunctionSum.cpp
    AggregateFunctionSumMap.cpp
    AggregateFunctionTimeSeriesGroupSum.cpp
    AggregateFunctionTopK.cpp
    AggregateFunctionUniqCombined.cpp
    AggregateFunctionUniq.cpp
    AggregateFunctionUniqUpTo.cpp
    AggregateFunctionWindowFunnel.cpp
    parseAggregateFunctionParameters.cpp
    registerAggregateFunctions.cpp
    UniqCombinedBiasData.cpp
    UniqVariadicHash.cpp
)

END()
