# Source files for LLVMScalarOpts
set(LLVMSCALAROPTS_SOURCES
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/ADCE.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/AlignmentFromAssumptions.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/AnnotationRemarks.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/BDCE.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/CallSiteSplitting.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/ConstantHoisting.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/ConstraintElimination.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/CorrelatedValuePropagation.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/DCE.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/DeadStoreElimination.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/DFAJumpThreading.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/DivRemPairs.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/DropUnnecessaryAssumes.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/EarlyCSE.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/FlattenCFGPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/Float2Int.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/GuardWidening.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/GVN.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/GVNHoist.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/GVNSink.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/InductiveRangeCheckElimination.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/IndVarSimplify.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/InferAddressSpaces.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/InferAlignment.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/InstSimplifyPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/IVUsersPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/JumpTableToSwitch.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/JumpThreading.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LICM.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopAccessAnalysisPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopBoundSplit.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopDataPrefetch.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopDeletion.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopDistribute.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopFlatten.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopFuse.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopIdiomRecognize.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopInstSimplify.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopInterchange.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopLoadElimination.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopPassManager.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopPredication.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopRotation.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopSimplifyCFG.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopSink.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopStrengthReduce.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopTermFold.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopUnrollAndJamPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopUnrollPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LoopVersioningLICM.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LowerAtomicPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LowerConstantIntrinsics.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LowerExpectIntrinsic.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LowerGuardIntrinsic.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LowerMatrixIntrinsics.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/LowerWidenableCondition.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/MakeGuardsExplicit.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/MemCpyOptimizer.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/MergedLoadStoreMotion.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/MergeICmps.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/NaryReassociate.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/NewGVN.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/PartiallyInlineLibCalls.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/PlaceSafepoints.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/Reassociate.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/Reg2Mem.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/RewriteStatepointsForGC.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/Scalar.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/ScalarizeMaskedMemIntrin.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/Scalarizer.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/SCCP.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/SeparateConstOffsetFromGEP.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/SimpleLoopUnswitch.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/SimplifyCFGPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/Sink.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/SpeculativeExecution.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/SROA.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/StraightLineStrengthReduce.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/StructurizeCFG.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/TailRecursionElimination.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Scalar/WarnMissedTransforms.cpp
)
