# Source files for LLVMAnalysis
set(LLVMANALYSIS_SOURCES
    ${LLVM_SOURCE_DIR}/lib/Analysis/AliasAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/AliasAnalysisEvaluator.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/AliasSetTracker.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/Analysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/AssumeBundleQueries.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/AssumptionCache.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/BasicAliasAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/BlockFrequencyInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/BlockFrequencyInfoImpl.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/BranchProbabilityInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CallGraph.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CallGraphSCCPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CallPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CaptureTracking.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CFG.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CFGPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CFGSCCPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CGSCCPassManager.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CmpInstAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CodeMetrics.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ConstantFolding.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ConstraintSystem.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CostModel.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CtxProfAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/CycleAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DDG.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DDGPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/Delinearization.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DemandedBits.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DependenceAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DependenceGraphBuilder.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DevelopmentModeInlineAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DomConditionCache.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DominanceFrontier.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DomPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DomTreeUpdater.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DXILMetadataAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/DXILResource.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/EphemeralValuesCache.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/FloatingPointPredicateUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/FunctionPropertiesAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/GlobalsModRef.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/GuardUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/HashRecognize.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/HeatUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ImportedFunctionsInliningStatistics.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/IndirectCallPromotionAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/InlineAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/InlineCost.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/InlineOrder.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/InstCount.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/InstructionPrecedenceTracking.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/InstructionSimplify.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/InteractiveModelRunner.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/IR2Vec.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/IRSimilarityIdentifier.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/IVDescriptors.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/IVUsers.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/KernelInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LastRunTrackingAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LazyBlockFrequencyInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LazyBranchProbabilityInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LazyCallGraph.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LazyValueInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/Lint.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/Loads.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/Local.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LoopAccessAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LoopAnalysisManager.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LoopCacheAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LoopInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LoopNestAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LoopPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/LoopUnrollAnalyzer.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MemDerefPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MemoryBuiltins.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MemoryDependenceAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MemoryLocation.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MemoryProfileInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MemorySSA.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MemorySSAUpdater.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MLInlineAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ModelUnderTrainingRunner.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ModuleDebugInfoPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ModuleSummaryAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/MustExecute.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/NoInferenceModelRunner.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ObjCARCAliasAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ObjCARCAnalysisUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ObjCARCInstKind.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/OptimizationRemarkEmitter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/OverflowInstAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/PHITransAddr.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/PhiValues.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/PostDominators.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ProfileSummaryInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/PtrUseVisitor.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/RegionInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/RegionPass.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/RegionPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ReplayInlineAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/RuntimeLibcallInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ScalarEvolutionAliasAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ScalarEvolution.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ScalarEvolutionDivision.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ScalarEvolutionNormalization.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ScopedNoAliasAA.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/StackLifetime.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/StackSafetyAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/StaticDataProfileInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/StructuralHash.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/SyntheticCountsUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/TargetLibraryInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/TargetTransformInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/TensorSpec.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/TFLiteUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/Trace.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/TrainingLogger.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/TypeBasedAliasAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/TypeMetadataUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/UniformityAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ValueLattice.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ValueLatticeUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/ValueTracking.cpp
    ${LLVM_SOURCE_DIR}/lib/Analysis/VectorUtils.cpp
)
