# Source files for LLVMCodeGen
set(LLVMCODEGEN_SOURCES
    ${LLVM_SOURCE_DIR}/lib/CodeGen/AggressiveAntiDepBreaker.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/AllocationOrder.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/Analysis.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/AssignmentTrackingAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/AtomicExpandPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BasicBlockPathCloning.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BasicBlockSections.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BasicBlockSectionsProfileReader.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BasicBlockMatchingAndInference.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BasicTargetTransformInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BranchFolding.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BranchRelaxation.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/BreakFalseDeps.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CalcSpillWeights.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CallBrPrepare.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CallingConvLower.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CFGuardLongjmp.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CFIFixup.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CFIInstrInserter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CodeGenCommonISel.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CodeGen.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CodeGenPrepare.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CodeGenTargetMachineImpl.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CommandFlags.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ComplexDeinterleavingPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/CriticalAntiDepBreaker.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/DeadMachineInstructionElim.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/DetectDeadLanes.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/DFAPacketizer.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/DroppedVariableStatsMIR.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/DwarfEHPrepare.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/EarlyIfConversion.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/EdgeBundles.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/EHContGuardTargets.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ExecutionDomainFix.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ExpandIRInsts.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ExpandMemCmp.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ExpandPostRAPseudos.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ExpandReductions.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ExpandVectorPredication.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/FaultMaps.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/FEntryInserter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/FinalizeISel.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/FixupStatepointCallerSaved.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/FuncletLayout.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/GCEmptyBasicBlocks.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/GCMetadata.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/GCMetadataPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/GCRootLowering.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/GlobalMerge.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/GlobalMergeFunctions.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/HardwareLoops.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/IfConversion.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ImplicitNullChecks.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/IndirectBrExpandPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/InitUndef.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/InsertCodePrefetch.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/InlineSpiller.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/InterferenceCache.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/InterleavedAccessPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/InterleavedLoadCombinePass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/IntrinsicLowering.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/JMCInstrumenter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/KCFI.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LatencyPriorityQueue.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LazyMachineBlockFrequencyInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LexicalScopes.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LibcallLoweringInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveDebugValues/InstrRefBasedImpl.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveDebugValues/LiveDebugValues.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveDebugValues/VarLocBasedImpl.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveDebugVariables.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveIntervalCalc.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveInterval.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveIntervals.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveIntervalUnion.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LivePhysRegs.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveRangeCalc.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveRangeEdit.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveRangeShrink.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveRegMatrix.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveRegUnits.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveStacks.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LiveVariables.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LocalStackSlotAllocation.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LoopTraversal.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LowerEmuTLS.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/LowLevelTypeUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineBasicBlock.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineBlockFrequencyInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineBlockHashInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineBlockPlacement.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineBranchProbabilityInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineCFGPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineCheckDebugify.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineCombiner.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineConvergenceVerifier.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineCopyPropagation.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineCSE.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineCycleAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineDebugify.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineDominanceFrontier.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineDominators.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineDomTreeUpdater.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineFrameInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineFunctionAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineFunction.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineFunctionPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineFunctionPrinterPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineFunctionSplitter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineInstrBundle.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineInstr.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineLateInstrsCleanup.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineLICM.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineLoopInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineLoopUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineModuleInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineModuleInfoImpls.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineModuleSlotTracker.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineOperand.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineOptimizationRemarkEmitter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineOutliner.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachinePassManager.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachinePipeliner.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachinePostDominators.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineRegionInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineRegisterInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineScheduler.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineSink.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineSizeOpts.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineSSAContext.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineSSAUpdater.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineStableHash.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineStripDebug.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineTraceMetrics.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineUniformityAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MachineVerifier.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MacroFusion.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MBFIWrapper.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRCanonicalizerPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRFSDiscriminator.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIR2Vec.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRNamerPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRPrintingPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRSampleProfile.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRVRegNamerUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MIRYamlMapping.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MLRegAllocEvictAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MLRegAllocPriorityAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ModuloSchedule.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/MultiHazardRecognizer.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/NonRelocatableStringpool.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/OptimizePHIs.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PatchableFunction.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PeepholeOptimizer.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PHIElimination.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PHIEliminationUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PostRAHazardRecognizer.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PostRASchedulerList.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PreISelIntrinsicLowering.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ProcessImplicitDefs.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PrologEpilogInserter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PseudoProbeInserter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/PseudoSourceValue.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RDFGraph.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RDFLiveness.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RDFRegisters.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ReachingDefAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocBase.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocBasic.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocEvictionAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocFast.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocGreedy.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocPBQP.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocPriorityAdvisor.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegAllocScore.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegisterBank.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegisterBankInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegisterClassInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegisterCoalescer.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegisterPressure.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegisterScavenging.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegisterUsageInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegUsageInfoCollector.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RegUsageInfoPropagate.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RemoveLoadsIntoFakeUses.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RemoveRedundantDebugValues.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/RenameIndependentSubregs.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ReplaceWithVeclib.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ResetMachineFunctionPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SafeStack.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SafeStackLayout.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SanitizerBinaryMetadata.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ScheduleDAG.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ScheduleDAGInstrs.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ScheduleDAGPrinter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ScoreboardHazardRecognizer.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SelectOptimize.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ShadowStackGCLowering.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ShrinkWrap.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SjLjEHPrepare.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SlotIndexes.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SpillPlacement.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SplitKit.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StackColoring.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StackFrameLayoutAnalysisPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StackMapLivenessAnalysis.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StackMaps.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StackProtector.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StackSlotColoring.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StaticDataAnnotator.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/StaticDataSplitter.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SwiftErrorValueTracking.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/SwitchLoweringUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TailDuplication.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TailDuplicator.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetFrameLoweringImpl.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetInstrInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetLoweringBase.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetLoweringObjectFileImpl.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetOptionsImpl.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetPassConfig.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetRegisterInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetSchedule.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TargetSubtargetInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TwoAddressInstructionPass.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/TypePromotion.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/UnreachableBlockElim.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/ValueTypes.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/VirtRegMap.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/VLIWMachineScheduler.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/WasmEHPrepare.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/WindowScheduler.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/WindowsSecureHotPatching.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/WinEHPrepare.cpp
    ${LLVM_SOURCE_DIR}/lib/CodeGen/XRayInstrumentation.cpp
)
