# Source files for LLVMTransformUtils
set(LLVMTRANSFORMUTILS_SOURCES
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/AddDiscriminators.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/AMDGPUEmitPrintf.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/ASanStackFrameLayout.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/AssumeBundleBuilder.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/BasicBlockUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/BreakCriticalEdges.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/BuildLibCalls.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/BypassSlowDivision.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CallGraphUpdater.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CallPromotionUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CanonicalizeAliases.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CanonicalizeFreezeInLoops.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CloneFunction.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CloneModule.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CodeExtractor.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CodeLayout.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CodeMoverUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/ControlFlowUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CountVisits.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/CtorUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/Debugify.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/DebugSSAUpdater.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/DeclareRuntimeLibcalls.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/DemoteRegToStack.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/DXILUpgrade.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/EntryExitInstrumenter.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/EscapeEnumerator.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/Evaluator.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/FixIrreducible.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/FlattenCFG.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/FunctionComparator.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/FunctionImportUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/GlobalStatus.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/GuardUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/HelloWorld.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/InjectTLIMappings.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/InlineFunction.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/InstructionNamer.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/Instrumentation.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/IntegerDivision.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/IRNormalizer.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LCSSA.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LibCallsShrinkWrap.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/Local.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopConstrainer.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopPeel.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopRotationUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopSimplify.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopUnrollAndJam.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopUnroll.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopUnrollRuntime.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LoopVersioning.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LowerAtomic.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LowerGlobalDtors.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LowerIFunc.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LowerInvoke.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LowerMemIntrinsics.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LowerSwitch.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/LowerVectorIntrinsics.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/MatrixUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/Mem2Reg.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/MemoryOpRemark.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/MemoryTaggingSupport.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/MetaRenamer.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/MisExpect.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/ModuleUtils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/MoveAutoInit.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/NameAnonGlobals.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/PredicateInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/ProfileVerify.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/PromoteMemoryToRegister.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/RelLookupTableConverter.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SampleProfileInference.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SampleProfileLoaderBaseUtil.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SanitizerStats.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/ScalarEvolutionExpander.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SCCPSolver.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SimplifyCFG.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SimplifyIndVar.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SimplifyLibCalls.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SizeOpts.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SplitModule.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SplitModuleByCategory.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SSAUpdaterBulk.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SSAUpdater.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/StripGCRelocates.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/StripNonLineTableDebugInfo.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/SymbolRewriter.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/UnifyFunctionExitNodes.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/UnifyLoopExits.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/Utils.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/ValueMapper.cpp
    ${LLVM_SOURCE_DIR}/lib/Transforms/Utils/VNCoercion.cpp
)
