-- Tags: no-parallel

DROP TABLE IF EXISTS trips SYNC;
CREATE TABLE trips (vendor_id UInt8,passenger_count UInt8,trip_distance Float32,payment_type UInt8,total_amount Float32) ENGINE = MergeTree ORDER BY vendor_id;
INSERT INTO trips VALUES(1,1,2.3,1,10.5),(2,2,5.1,2,20.0);
DROP TABLE IF EXISTS test_vector SYNC;
CREATE TABLE test_vector(id Float32, vector Array(Float32), CONSTRAINT vector_len CHECK length(vector) = 3) engine=MergeTree primary key id SETTINGS index_granularity=1024;
INSERT INTO test_vector SELECT number, [number, number + 3, number + 1] FROM numbers(1000);
DROP TABLE if EXISTS test_vector_invert_join SYNC;
CREATE TABLE test_vector_invert_join (id UInt64,vector Array(Float32),doc String,INDEX inv_idx(doc) TYPE text(tokenizer = 'splitByNonAlpha') GRANULARITY 1,CONSTRAINT vector_len CHECK length(vector) = 3) ENGINE = MergeTree ORDER BY id settings index_granularity=2;
INSERT INTO test_vector_invert_join VALUES (0,[0,0,0],'Ancient empires rise and fall, shaping history''s course.'),(1,[1,1,1],'Artistic expressions reflect diverse cultural heritages.'),(2,[2,2,2],'Social movements transform societies, forging new paths.'),(3,[3,3,3],'Economies fluctuate, reflecting the complex interplay of global forces.'),(4,[4,4,4],'Strategic military campaigns alter the balance of power.'),(5,[5,5,5],'Quantum leaps redefine understanding of physical laws.'),(6,[6,6,6],'Chemical reactions unlock mysteries of nature.'), (7,[7,7,7],'Philosophical debates ponder the essence of existence.'),(8,[8,8,8],'Marriages blend traditions, celebrating love''s union.'),(9,[9,9,9],'Explorers discover uncharted territories, expanding world maps.'),(10,[10,10,10],'Innovations in technology drive societal progress.'),(11,[11,11,11],'Environmental conservation efforts protect Earth''s biodiversity.'),(12,[12,12,12],'Diplomatic negotiations seek to resolve international conflicts.'),(13,[13,13,13],'Ancient philosophies provide wisdom for modern dilemmas.'),(14,[14,14,14],'Economic theories debate the merits of market systems.'),(15,[15,15,15],'Military strategies evolve with technological advancements.'),(16,[16,16,16],'Physics theories delve into the universe''s mysteries.'),(17,[17,17,17],'Chemical compounds play crucial roles in medical breakthroughs.'),(18,[18,18,18],'Philosophers debate ethics in the age of artificial intelligence.'),(19,[19,19,19],'Wedding ceremonies across cultures symbolize lifelong commitment.');
ALTER TABLE test_vector_invert_join ADD INDEX vec_ind vector TYPE vector_similarity('hnsw', 'cosineDistance', 3) GRANULARITY 1;
DROP TABLE IF EXISTS t_00026 SYNC;
CREATE TABLE t_00026(a int, id UInt64) engine=MergeTree ORDER BY a;
INSERT INTO t_00026 SELECT number, number FROM numbers(10);
INSERT INTO t_00026 SELECT number+10, number FROM numbers(10);
SET enable_reads_from_query_cache = 1;
SET enable_writes_to_query_cache = 1;
SET query_cache_min_query_runs = 1;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 0;
set vector_use_cast = 0;
SET vector_query_plan_cache_only_vector = 0;
SELECT 'no vector_query_plan_cache; no cast; no vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 0;
set vector_use_cast = 1;
SET vector_query_plan_cache_only_vector = 0;
SELECT 'no vector_query_plan_cache; with cast; no vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 1;
set vector_use_cast = 0;
SET vector_query_plan_cache_only_vector = 0;
SELECT 'with vector_query_plan_cache; no cast; no vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 1;
set vector_use_cast = 1;
SET vector_query_plan_cache_only_vector = 0;
SELECT 'with vector_query_plan_cache; with cast; no vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 0;
set vector_use_cast = 0;
SET vector_query_plan_cache_only_vector = 1;
SELECT 'no vector_query_plan_cache; no cast; with vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 0;
set vector_use_cast = 1;
SET vector_query_plan_cache_only_vector = 1;
SELECT 'no vector_query_plan_cache; with cast; with vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 1;
set vector_use_cast = 0;
SET vector_query_plan_cache_only_vector = 1;
SELECT 'with vector_query_plan_cache; no cast; with vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
SYSTEM DROP VECTOR QUERY PLAN CACHE;
SYSTEM DROP QUERY CACHE;
set vector_query_plan_cache = 1;
set vector_use_cast = 1;
SET vector_query_plan_cache_only_vector = 1;
SELECT 'with vector_query_plan_cache; with cast; with vector_query_plan_cache_only_vector';
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT hasToken(doc, 'Artistic') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT hasToken(doc, 'Ancient') as score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [2.,2,2]) as score1, hasToken(t2.doc, 'Social') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, cosineDistance(t2.vector, [1.0,1,1]) as score1, hasToken(t2.doc, 'Ancient') AS score2 FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score1 DESC, score2 ASC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [2.,2,2])) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, [1.0,1,1])) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Social') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, (1 - cosineDistance(t2.vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(t2.doc, 'Ancient') * 0.4 AS score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id ORDER BY score DESC, t1.a LIMIT 5;
SELECT (1 - cosineDistance(vector, [2.,2,2])) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, [1.,1,1])) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[2.,2,2]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Social') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT (1 - cosineDistance(vector, CAST('[1.0,1,1]','Array(Float32)'))) * 0.6 + hasToken(doc, 'Ancient') * 0.4 AS score FROM test_vector_invert_join ORDER BY score DESC LIMIT 5;
SELECT id, L2Distance(vector, [18., 21, 19]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, [8., 11, 9]) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[18., 21, 19]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
SELECT id, L2Distance(vector, CAST('[8., 11, 9]','Array(Float32)')) AS d FROM test_vector ORDER BY d LIMIT 5;
select * from trips where total_amount > 15;
select * from trips where total_amount > 10;
select passenger_count+10 as passenger_count from trips where total_amount > 15;
select passenger_count+15 as passenger_count from trips where total_amount > 10;
select * from trips where total_amount > 15 and passenger_count > 1;
select * from trips where total_amount > 10 and passenger_count > 0;
select * from trips where total_amount > 15 and total_amount > 15;
select * from trips where total_amount > 15 and total_amount > 12;
SELECT t1.id, t1.a, hasToken(doc, 'Artistic') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > 0 ORDER BY score DESC, t1.a LIMIT 5;
SELECT t1.id, t1.a, hasToken(doc, 'Ancient') as score FROM t_00026 as t1 JOIN test_vector_invert_join as t2 ON t1.id = t2.id and t1.id > -1 ORDER BY score DESC, t1.a LIMIT 5;
DROP TABLE IF EXISTS trips SYNC;
DROP TABLE IF EXISTS test_vector SYNC;
DROP TABLE IF EXISTS t_00026 SYNC;
DROP TABLE if EXISTS test_vector_invert_join SYNC;
