#
# Makefile
#
# $Id: //poco/1.4/Net/samples/Mail/Makefile#1 $
#
# Makefile for Poco Mail
#

include $(POCO_BASE)/build/rules/global

objects = Mail

target         = Mail
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
