language: c
compiler:
  - gcc
  - clang
env:
  - BUILDDIR=. TOOL="./configure --zlib-compat"
  - BUILDDIR=../build TOOL="../zlib-ng/configure --zlib-compat"
  - BUILDDIR=. TOOL="./configure --zlib-compat --without-optimizations --without-new-strategies"
  - BUILDDIR=. TOOL="cmake ."
  - BUILDDIR=../build TOOL="cmake ../zlib-ng"
script: mkdir -p $BUILDDIR && cd $BUILDDIR &&
        $TOOL && make && make test
