#
# Makefile
#
# $Id: //poco/1.4/Net/samples/dict/Makefile#1 $
#
# Makefile for Poco dict
#

include $(POCO_BASE)/build/rules/global

objects = dict

target         = dict
target_version = 1
target_libs    = PocoUtil PocoNet PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
