#
# Makefile
#
# $Id: //poco/1.4/Zip/Makefile#1 $
#
# Makefile for Poco Zip
#

include $(POCO_BASE)/build/rules/global

objects = AutoDetectStream Compress Decompress ParseCallback PartialStream \
	SkipCallback ZipArchive ZipArchiveInfo ZipDataInfo \
	ZipFileInfo ZipLocalFileHeader ZipStream ZipUtil ZipCommon ZipException \
	Add Delete Keep Rename Replace ZipManipulator ZipOperation

target         = PocoZip
target_version = $(LIBVERSION)
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/lib
