#
# Makefile
#
# $Id: //poco/Main/Data/samples/RecordSet/Makefile#1 $
#
# Makefile for Poco Data RecordSet sample
#

include $(POCO_BASE)/build/rules/global

objects = RecordSet

target         = RecordSet
target_version = 1
target_libs    = PocoDataSQLite PocoData PocoFoundation 

include $(POCO_BASE)/build/rules/exec
