#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/LineEndingConverter/Makefile#1 $
#
# Makefile for Poco LineEndingConverter
#

include $(POCO_BASE)/build/rules/global

objects = LineEndingConverter

target         = LineEndingConverter
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
