#
# Makefile
#
# $Id: //poco/Foundation/samples/Activity/Makefile#2 $
#
# Makefile for Poco Activity
#

include $(POCO_BASE)/build/rules/global

objects = Activity

target         = Activity
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
