" ";
" ";
" ";
";";


"(" $1 ")";
"(" $1 ", " $2 ")";
"(" $1 ", " $2 ", " $3 ")";

$1 ", " $2 ;
$1 ", " $2 ", " $3 ;
$1 ", " $2 ", " $3 ", " $4 ;
$1 ", " $2 ", " $3 ", " $4 ", " $5 ;

"[" $1 ", " $2 "]";
"[" $1 ", " $2 ", " $3 "]";
"[" $1 ", " $2 ", " $3 ", " $4 "]";
"[" $1 ", " $2 ", " $3 ", " $4 ", " $5 "]";

$0 "(" $1 ")";
$0 "(" $1 ", " $2 ")";
$0 "(" $1 ", " $2 ", " $3 ")";

$1 " as " $2 ;


// TODO: add more clickhouse specific stuff
"SELECT " $1 " FROM " $2 " WHERE " $3 ;
"SELECT " $1 " FROM " $2 " GROUP BY " $3 ;
"SELECT " $1 " FROM " $2 " SORT BY " $3 ;
"SELECT " $1 " FROM " $2 " LIMIT " $3 ;
"SELECT " $1 " FROM " $2 " JOIN " $3 ;
"SELECT " $1 " FROM " $2 " ARRAY JOIN " $3 ;
"SELECT " $1 " FROM " $2 " JOIN " $3 " ON " $4 ;
"SELECT " $1 " FROM " $2 " JOIN " $3 " USING " $5 ;
"SELECT " $1 " INTO OUTFILE " $2 ;

"WITH " $1 " AS " $2 ;

"{" $1 ":" $2 "}";
"[" $1 "," $2 "]";
"[]";


" x ";
"x";
" `x` ";
"`x`";

" \"value\" ";
"\"value\"";
" 0 ";
"0";
"1";
"2";
"123123123123123123";
"182374019873401982734091873420923123123123123123";
"1e-1";
"1.1";
"\"\"";
" '../../../../../../../../../etc/passwd' ";

"/";
"=";
"==";
"!=";
"<>";
"<";
"<=";
">";
">=";
"<<";
"|<<";
"&";
"|";
"||";
"<|";
"|>";
"+";
"-";
"~";
"*";
"/";
"\\";
"%";
"";
".";
",";
",";
",";
",";
",";
",";
"(";
")";
"(";
")";
"(";
")";
"(";
")";
"(";
")";
"(";
")";
"?";
":";
"@";
"@@";
"$";
"\"";
"`";
"{";
"}";
"^";
"::";
"->";
"]";
"[";

" ADD ";
" ADD COLUMN ";
" ADD CONSTRAINT ";
" ADD INDEX ";
" AFTER ";
" AggregateFunction ";
" aggThrow ";
" ALL ";
" ALTER LIVE VIEW ";
" ALTER TABLE ";
" and ";
" ANTI ";
" any ";
" anyHeavy ";
" anyLast ";
" argMax ";
" argMin ";
" array ";
" Array ";
" arrayAll ";
" arrayAUC ";
" arrayCompact ";
" arrayConcat ";
" arrayCount ";
" arrayCumSum ";
" arrayCumSumNonNegative ";
" arrayDifference ";
" arrayDistinct ";
" arrayElement ";
" arrayEnumerate ";
" arrayEnumerateDense ";
" arrayEnumerateDenseRanked ";
" arrayEnumerateUniq ";
" arrayEnumerateUniqRanked ";
" arrayExists ";
" arrayFill ";
" arrayFilter ";
" arrayFirst ";
" arrayFirstIndex ";
" arrayFlatten ";
" arrayIntersect ";
" arrayJoin ";
" ARRAY JOIN ";
" arrayMap ";
" arrayPopBack ";
" arrayPopFront ";
" arrayPushBack ";
" arrayPushFront ";
" arrayReduce ";
" arrayReduceInRanges ";
" arrayResize ";
" arrayReverse ";
" arrayReverseFill ";
" arrayReverseSort ";
" arrayReverseSplit ";
" arraySlice ";
" arraySort ";
" arraySplit ";
" arraySum ";
" arrayUniq ";
" arrayWithConstant ";
" arrayZip ";
" AS ";
" ASC ";
" ASCENDING ";
" ASOF ";
" AST ";
" ATTACH ";
" ATTACH PART ";
" ATTACH PARTITION ";
" avg ";
" avgWeighted ";
" basename ";
" BETWEEN ";
" BOTH ";
" boundingRatio ";
" BY ";
" CAST ";
" categoricalInformationValue ";
" CHECK ";
" CHECK TABLE ";
" CLEAR COLUMN ";
" CLEAR INDEX ";
" COLLATE ";
" COLUMNS ";
" COMMENT COLUMN ";
" CONSTRAINT ";
" corr ";
" corrStable ";
" count ";
" countEqual ";
" covarPop ";
" covarPopStable ";
" covarSamp ";
" covarSampStable ";
" CREATE ";
" CROSS ";
" CUBE ";
" cutFragment ";
" cutQueryString ";
" cutQueryStringAndFragment ";
" cutToFirstSignificantSubdomain ";
" cutURLParameter ";
" cutWWW ";
" D ";
" DATABASE ";
" DATABASES ";
" Date ";
" DATE ";
" DATE_ADD ";
" DATEADD ";
" DATE_DIFF ";
" DATEDIFF ";
" DATE_SUB ";
" DATESUB ";
" DateTime ";
" DateTime64 ";
" DAY ";
" DD ";
" Decimal ";
" Decimal128 ";
" Decimal32 ";
" Decimal64 ";
" decodeURLComponent ";
" DEDUPLICATE ";
" DELETE ";
" DELETE WHERE ";
" DESC ";
" DESCENDING ";
" DESCRIBE ";
" DETACH ";
" DETACH PARTITION ";
" DICTIONARIES ";
" DICTIONARY ";
" DISTINCT ";
" domain ";
" domainWithoutWWW ";
" DROP ";
" DROP COLUMN ";
" DROP CONSTRAINT ";
" DROP DETACHED PART ";
" DROP DETACHED PARTITION ";
" DROP INDEX ";
" DROP PARTITION ";
" emptyArrayToSingle ";
" ENGINE ";
" entropy ";
" Enum ";
" Enum16 ";
" Enum8 ";
" EVENTS ";
" EXCHANGE TABLES ";
" EXISTS ";
" EXTRACT ";
" extractURLParameter ";
" extractURLParameterNames ";
" extractURLParameters ";
" FETCH PARTITION ";
" FETCH PART ";
" FINAL ";
" FIRST ";
" firstSignificantSubdomain ";
" FixedString ";
" Float32 ";
" Float64 ";
" FOR ";
" ForEach ";
" FORMAT ";
" fragment ";
" FREEZE ";
" FROM ";
" FULL ";
" FUNCTION ";
" __getScalar ";
" GLOBAL ";
" GRANULARITY ";
" groupArray ";
" groupArrayInsertAt ";
" groupArrayMovingAvg ";
" groupArrayMovingSum ";
" groupArraySample ";
" groupBitAnd ";
" groupBitmap ";
" groupBitmapAnd ";
" groupBitmapOr ";
" groupBitmapXor ";
" groupBitOr ";
" groupBitXor ";
" GROUP BY ";
" groupUniqArray ";
" has ";
" hasAll ";
" hasAny ";
" HAVING ";
" HH ";
" histogram ";
" HOUR ";
" ID ";
" if ";
" IF EXISTS ";
" IF NOT EXISTS ";
" IN ";
" INDEX ";
" indexOf ";
" INNER ";
" IN PARTITION ";
" INSERT INTO ";
" Int16 ";
" Int32 ";
" Int64 ";
" Int8 ";
" INTERVAL ";
" IntervalDay ";
" IntervalHour ";
" IntervalMinute ";
" IntervalMonth ";
" IntervalQuarter ";
" IntervalSecond ";
" IntervalWeek ";
" IntervalYear ";
" INTO OUTFILE ";
" JOIN ";
" kurtPop ";
" kurtSamp ";
" LAST ";
" LAYOUT ";
" LEADING ";
" LEFT ";
" LEFT ARRAY JOIN ";
" length ";
" LIFETIME ";
" LIKE ";
" LIMIT ";
" LIVE ";
" LOCAL ";
" LowCardinality ";
" LTRIM ";
" M ";
" MATERIALIZED ";
" MATERIALIZE INDEX ";
" MATERIALIZE TTL ";
" max ";
" maxIntersections ";
" maxIntersectionsPosition ";
" Merge ";
" MI ";
" min ";
" MINUTE ";
" MM ";
" MODIFY ";
" MODIFY COLUMN ";
" MODIFY ORDER BY ";
" MODIFY QUERY ";
" MODIFY SETTING ";
" MODIFY TTL ";
" MONTH ";
" MOVE PART ";
" MOVE PARTITION ";
" movingXXX ";
" N ";
" NAME ";
" Nested ";
" NO DELAY ";
" NONE ";
" not ";
" nothing ";
" Nothing ";
" Null ";
" Nullable ";
" NULLS ";
" OFFSET ";
" ON ";
" ONLY ";
" OPTIMIZE TABLE ";
" ORDER BY ";
" OR REPLACE ";
" OUTER ";
" PARTITION ";
" PARTITION BY ";
" path ";
" pathFull ";
" POPULATE ";
" PREWHERE ";
" PRIMARY KEY ";
" protocol ";
" Q ";
" QQ ";
" QUARTER ";
" queryString ";
" queryStringAndFragment ";
" range ";
" REFRESH ";
" RENAME COLUMN ";
" RENAME TABLE ";
" REPLACE PARTITION ";
" Resample ";
" RESUME ";
" retention ";
" RIGHT ";
" ROLLUP ";
" RTRIM ";
" S ";
" SAMPLE ";
" SAMPLE BY ";
" SECOND ";
" SELECT ";
" SEMI ";
" sequenceCount ";
" sequenceMatch ";
" SET ";
" SETTINGS ";
" SHOW ";
" SHOW PROCESSLIST ";
" simpleLinearRegression ";
" skewPop ";
" skewSamp ";
" SOURCE ";
" SQL_TSI_DAY ";
" SQL_TSI_HOUR ";
" SQL_TSI_MINUTE ";
" SQL_TSI_MONTH ";
" SQL_TSI_QUARTER ";
" SQL_TSI_SECOND ";
" SQL_TSI_WEEK ";
" SQL_TSI_YEAR ";
" SS ";
" State ";
" stddevPop ";
" stddevPopStable ";
" stddevSamp ";
" stddevSampStable ";
" STEP ";
" stochasticLinearRegression ";
" stochasticLogisticRegression ";
" String ";
" SUBSTRING ";
" sum ";
" sumKahan ";
" sumMap ";
" sumMapFiltered ";
" sumMapFilteredWithOverflow ";
" sumMapWithOverflow ";
" sumWithOverflow ";
" SUSPEND ";
" TABLE ";
" TABLES ";
" TEMPORARY ";
" TIMESTAMP ";
" TIMESTAMP_ADD ";
" TIMESTAMPADD ";
" TIMESTAMP_DIFF ";
" TIMESTAMPDIFF ";
" TIMESTAMP_SUB ";
" TIMESTAMPSUB ";
" TO ";
" TO DISK ";
" TOP ";
" topK ";
" topKWeighted ";
" topLevelDomain ";
" TO TABLE ";
" TOTALS ";
" TO VOLUME ";
" TRAILING ";
" TRIM ";
" TRUNCATE ";
" TTL ";
" Tuple ";
" TYPE ";
" UInt16 ";
" UInt32 ";
" UInt64 ";
" UInt8 ";
" uniq ";
" uniqCombined ";
" uniqCombined64 ";
" uniqExact ";
" uniqHLL12 ";
" uniqUpTo ";
" UPDATE ";
" URLHierarchy ";
" URLPathHierarchy ";
" USE ";
" USING ";
" UUID ";
" VALUES ";
" varPop ";
" varPopStable ";
" varSamp ";
" varSampStable ";
" VIEW ";
" WATCH ";
" WEEK ";
" WHERE ";
" windowFunnel ";
" WITH ";
" WITH FILL ";
" WITH TIES ";
" WK ";
" WW ";
" YEAR ";
" YY ";
" YYYY ";
