#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/Makefile#1 $
#
# Makefile for Poco Foundation Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C ActiveMethod $(MAKECMDGOALS)
	$(MAKE) -C Activity $(MAKECMDGOALS)
	$(MAKE) -C Timer $(MAKECMDGOALS)
	$(MAKE) -C BinaryReaderWriter $(MAKECMDGOALS)
	$(MAKE) -C LineEndingConverter $(MAKECMDGOALS)
	$(MAKE) -C base64decode $(MAKECMDGOALS)
	$(MAKE) -C base64encode $(MAKECMDGOALS)
	$(MAKE) -C deflate $(MAKECMDGOALS)
	$(MAKE) -C inflate $(MAKECMDGOALS)
	$(MAKE) -C DateTime $(MAKECMDGOALS)
	$(MAKE) -C Logger $(MAKECMDGOALS)
	$(MAKE) -C grep $(MAKECMDGOALS)
	$(MAKE) -C dir $(MAKECMDGOALS)
	$(MAKE) -C md5 $(MAKECMDGOALS)
	$(MAKE) -C hmacmd5 $(MAKECMDGOALS)
	$(MAKE) -C NotificationQueue $(MAKECMDGOALS)
	$(MAKE) -C StringTokenizer $(MAKECMDGOALS)
	$(MAKE) -C URI $(MAKECMDGOALS)
	$(MAKE) -C uuidgen $(MAKECMDGOALS)
