#
# Makefile
#
# $Id: //poco/Main/Data/samples/WebNotifier/Makefile#1 $
#
# Makefile for Poco Data WebNotifier sample
#

include $(POCO_BASE)/build/rules/global

objects = WebNotifier

target         = WebNotifier
target_version = 1
target_libs    = PocoDataSQLite PocoData PocoNet PocoFoundation

include $(POCO_BASE)/build/rules/exec
