#
# Makefile
#
# $Id: //poco/1.4/XML/samples/Makefile#1 $
#
# Makefile for Poco XML Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C DOMParser $(MAKECMDGOALS)
	$(MAKE) -C DOMWriter $(MAKECMDGOALS)
	$(MAKE) -C PrettyPrint $(MAKECMDGOALS)
	$(MAKE) -C SAXParser $(MAKECMDGOALS)
