#pragma once

#define KEEPER_HEARTBEAT_INTERVAL_MS 1000
#define KEEPER_HEARTBEAT_INTERVAL_S ((static_cast<double>(KEEPER_HEARTBEAT_INTERVAL_MS)) / 1000)
#define KEEPER_SESSION_EXPIRE_AT_MS (KEEPER_HEARTBEAT_INTERVAL_MS * 5)
#define KEEPER_SESSION_RETRY_INTERVAL_MS 300
#define KEEPER_SESSION_RETRY_INTERVAL_S ((static_cast<double>(KEEPER_SESSION_RETRY_INTERVAL_MS)) / 1000)
#define KEEPER_CLEANER_ROUND_DURATION_MS 2000
#define KEEPER_CLEANER_ROUND_DURATION_S ((static_cast<double>(KEEPER_CLEANER_ROUND_DURATION_MS)) / 1000)
