#pragma once

#define DBMS_NAME					"ClickHouse"
#define DBMS_VERSION_MAJOR 			0
#define DBMS_VERSION_MINOR 			0

#define DEFAULT_BLOCK_SIZE 			1048576
#define DEFAULT_MAX_QUERY_SIZE 		1048576
#define SHOW_CHARS_ON_SYNTAX_ERROR 	160L
#define DEFAULT_MAX_THREADS 		8
