#pragma once

#define DBMS_NAME					"ClickHouse"
#define DBMS_VERSION_MAJOR 			0
#define DBMS_VERSION_MINOR 			0

#define DBMS_DEFAULT_HOST 			"localhost"
#define DBMS_DEFAULT_PORT 			9000
#define DBMS_DEFAULT_PORT_STR 		"9000"
#define DBMS_DEFAULT_CONNECT_TIMEOUT_SEC	10
#define DBMS_DEFAULT_SEND_TIMEOUT_SEC		300
#define DBMS_DEFAULT_RECEIVE_TIMEOUT_SEC	300

#define DEFAULT_BLOCK_SIZE 			1048576
#define DEFAULT_MAX_QUERY_SIZE 		1048576
#define SHOW_CHARS_ON_SYNTAX_ERROR 	160L
#define DEFAULT_MAX_THREADS 		8
#define DEFAULT_INTERACTIVE_DELAY	100000
