#!/usr/bin/env bash


# Wrapper for jeprof with llvm toolchain (binutils are too slow)
# NOTE: we use objdump over llvm-objdump since later makes function names incorrect
exec jeprof.orig --tools addr2line:$(which llvm-addr2line-$LLVM_VERSION),nm:$(which llvm-nm-$LLVM_VERSION),objdump:$(which objdump),c++filt:$(which llvm-cxxfilt-$LLVM_VERSION) "$@"
