#!/usr/bin/env bash


# Wrapper for jeprof with llvm toolchain (binutils are too slow)
exec jeprof.orig --tools addr2line:$(which llvm-addr2line-$LLVM_VERSION),nm:$(which llvm-nm-$LLVM_VERSION),objdump:$(which llvm-objdump-$LLVM_VERSION),c++filt:$(which llvm-cxxfilt-$LLVM_VERSION) "$@"
