/* Generated by Snowball 2.1.0 - https://snowballstem.org/ */

#ifdef __cplusplus
extern "C" {
#endif

extern struct SN_env * italian_UTF_8_create_env(void);
extern void italian_UTF_8_close_env(struct SN_env * z);

extern int italian_UTF_8_stem(struct SN_env * z);

#ifdef __cplusplus
}
#endif

