#
# Makefile
#
# $Id: //poco/1.4/PageCompiler/samples/Makefile#1 $
#
# Makefile for Poco PageCompiler Samples
#

.PHONY: projects
clean all: projects
projects:
	$(MAKE) -C HTTPTimeServer $(MAKECMDGOALS)
