
SHOW TABLES NOT LIKE '%';

SHOW TABLES;
SELECT '---';
CREATE TABLE test1 (x UInt8) ENGINE = Memory;
CREATE TABLE test2 (x UInt8) ENGINE = Memory;

SHOW TABLES;
SELECT '--';
SHOW TABLES LIKE 'tes%';
SELECT '--';
SHOW TABLES NOT LIKE 'tes%';
SELECT '--';
SHOW TABLES LIKE 'tes%1';
SELECT '--';
SHOW TABLES NOT LIKE 'tes%2';

SELECT '---';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier};
SELECT '--';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} LIKE 'tes%';
SELECT '--';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} NOT LIKE 'tes%';
SELECT '--';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} LIKE 'tes%1';
SELECT '--';
SHOW TABLES FROM {CLICKHOUSE_DATABASE:Identifier} NOT LIKE 'tes%2';

DROP DATABASE {CLICKHOUSE_DATABASE:Identifier};
