
DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE_1:Identifier};
CREATE DATABASE {CLICKHOUSE_DATABASE_1:Identifier};
USE {CLICKHOUSE_DATABASE_1:Identifier};
CREATE TABLE t (x UInt8) ENGINE = Memory;

SELECT * FROM merge('', '');

DROP DATABASE {CLICKHOUSE_DATABASE_1:Identifier};
