#!/usr/bin/env bash

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS s"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS ta"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS tb"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS tc"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS td"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS v1"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS dict_src"
$CLICKHOUSE_CLIENT -q "DROP DICTIONARY IF EXISTS dict"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS dict_tbl"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS hits"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS hits_buffer"

$CLICKHOUSE_CLIENT -q "CREATE TABLE s (n int) ENGINE=Log"
$CLICKHOUSE_CLIENT -q "CREATE TABLE ta (n int) ENGINE=Log"
$CLICKHOUSE_CLIENT -q "CREATE TABLE tb (n int) ENGINE=Log"
$CLICKHOUSE_CLIENT -q "CREATE TABLE tc (n int) ENGINE=Log"
$CLICKHOUSE_CLIENT -q "CREATE TABLE td (n int) ENGINE=Log"
$CLICKHOUSE_CLIENT -q "CREATE VIEW v1 AS SELECT n FROM s WHERE (n IN ta) AND (n NOT IN tb) AND (n GLOBAL IN tc)  AND (n GLOBAL NOT IN td)"

$CLICKHOUSE_CLIENT -q "CREATE TABLE dict_src (n int, m int) ENGINE=MergeTree ORDER BY n"
$CLICKHOUSE_CLIENT -q "CREATE DICTIONARY dict (n int, m int DEFAULT 1) PRIMARY KEY n SOURCE(CLICKHOUSE(HOST 'localhost' PORT tcpPort() TABLE 'dict_src' DB '$CLICKHOUSE_DATABASE')) LAYOUT(FLAT()) LIFETIME(0)"
$CLICKHOUSE_CLIENT -q "CREATE TABLE dict_tbl AS dictionary('$CLICKHOUSE_DATABASE.dict')"

$CLICKHOUSE_CLIENT -q "CREATE TABLE hits (n int, s String) ENGINE=Log"
$CLICKHOUSE_CLIENT -q "CREATE TABLE hits_buffer AS hits ENGINE = Buffer('$CLICKHOUSE_DATABASE', hits, 16, 10, 100, 10000, 1000000, 10000000, 100000000)"

$CLICKHOUSE_CLIENT -q "SELECT table, arraySort(dependencies_table), arraySort(loading_dependencies_table), arraySort(loading_dependent_table) FROM system.tables WHERE database=currentDatabase() ORDER BY table"

$CLICKHOUSE_CLIENT -q "DROP TABLE v1"
$CLICKHOUSE_CLIENT -q "DROP TABLE s"
$CLICKHOUSE_CLIENT -q "DROP TABLE ta"
$CLICKHOUSE_CLIENT -q "DROP TABLE tb"
$CLICKHOUSE_CLIENT -q "DROP TABLE tc"
$CLICKHOUSE_CLIENT -q "DROP TABLE td"
$CLICKHOUSE_CLIENT -q "DROP TABLE dict_tbl"
$CLICKHOUSE_CLIENT -q "DROP DICTIONARY dict"
$CLICKHOUSE_CLIENT -q "DROP TABLE dict_src"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS hits_buffer"
$CLICKHOUSE_CLIENT -q "DROP TABLE IF EXISTS hits"
