SET transform_null_in = 1;

SELECT NULL IN NULL;
SELECT 1 IN NULL;
SELECT 1 IN (1, NULL);
SELECT 1 IN tuple(1, NULL);
SELECT (1, 2) IN (1, NULL);
SELECT (1, 2) IN tuple(1, NULL);
SELECT (1, 2) IN ((1, NULL), (1, 2));
SELECT (1, NULL) IN (1, NULL);
