SELECT ALL 'a';
SELECT DISTINCT 'a';
SELECT ALL * FROM (SELECT 1 UNION ALL SELECT 1);
SELECT DISTINCT * FROM (SELECT 2 UNION ALL SELECT 2);
SELECT ALL DISTINCT 1; -- { clientError 49 }
SELECT DISTINCT ALL 1; -- { clientError 49 }

SELECT sum(number) FROM numbers(10);
SELECT sum(ALL number) FROM numbers(10);
