DROP TABLE IF EXISTS t_v;
DROP TABLE IF EXISTS t;

CREATE TABLE t ( a String ) ENGINE = Memory();
CREATE VIEW t_v AS SELECT * FROM t;
SET output_format_write_statistics = 0;
SELECT * FROM t_v FORMAT JSON SETTINGS extremes = 1;

DROP TABLE IF EXISTS t_v;
DROP TABLE IF EXISTS t;
