SELECT bitAnd(0, inf); -- { serverError 43 }
SELECT bitXor(0, inf); -- { serverError 43 }
SELECT bitOr(0, inf); -- { serverError 43 }
SELECT bitTest(inf, 0); -- { serverError 43 }
SELECT bitTest(0, inf); -- { serverError 43 }
SELECT bitRotateLeft(inf, 0); -- { serverError 43 }
SELECT bitRotateRight(inf, 0); -- { serverError 43 }
SELECT bitShiftLeft(inf, 0); -- { serverError 43 }
SELECT bitShiftRight(inf, 0); -- { serverError 43 }
