DROP TABLE IF EXISTS alter_table;

CREATE TABLE alter_table (a UInt8, b Int16)
ENGINE = MergeTree
ORDER BY a;

ALTER TABLE alter_table
    MODIFY COLUMN `b` DateTime DEFAULT now(([NULL, NULL, NULL, [-2147483648], [NULL, NULL, NULL, NULL, NULL, NULL, NULL]] AND (1048576 AND NULL) AND (NULL AND 1048575 AND NULL AND -2147483649) AND NULL) IN (test_01103.t1_distr.id)); --{serverError UNKNOWN_IDENTIFIER}

SELECT 1;


DROP TABLE IF EXISTS alter_table;
