show create table system.aggregate_function_combinators; -- { serverError 390 }
show create table system.asynchronous_inserts; -- { serverError 390 }
show create table system.asynchronous_metrics; -- { serverError 390 }
show create table system.build_options; -- { serverError 390 }
show create table system.clusters; -- { serverError 390 }
show create table system.collations; -- { serverError 390 }
show create table system.columns; -- { serverError 390 }
show create table system.contributors; -- { serverError 390 }
show create table system.current_roles; -- { serverError 390 }
show create table system.data_skipping_indices; -- { serverError 390 }
show create table system.data_type_families; -- { serverError 390 }
show create table system.databases; -- { serverError 390 }
show create table system.detached_parts; -- { serverError 390 }
show create table system.dictionaries; -- { serverError 390 }
show create table system.disks; -- { serverError 390 }
show create table system.distributed_ddl_queue; -- { serverError 390 }
show create table system.distribution_queue; -- { serverError 390 }
show create table system.enabled_roles; -- { serverError 390 }
show create table system.errors; -- { serverError 390 }
show create table system.events; -- { serverError 390 }
show create table system.formats; -- { serverError 390 }
show create table system.functions; -- { serverError 390 }
show create table system.grants; -- { serverError 390 }
show create table system.graphite_retentions; -- { serverError 390 }
show create table system.licenses; -- { serverError 390 }
show create table system.macros; -- { serverError 390 }
show create table system.merge_tree_settings; -- { serverError 390 }
show create table system.merges; -- { serverError 390 }
show create table system.metrics; -- { serverError 390 }
show create table system.models; -- { serverError 390 }
show create table system.mutations; -- { serverError 390 }
show create table system.numbers; -- { serverError 390 }
show create table system.numbers_mt; -- { serverError 390 }
show create table system.one; -- { serverError 390 }
show create table system.part_moves_between_shards; -- { serverError 390 }
show create table system.parts; -- { serverError 390 }
show create table system.parts_columns; -- { serverError 390 }
show create table system.privileges; -- { serverError 390 }
show create table system.processes; -- { serverError 390 }
show create table system.projection_parts; -- { serverError 390 }
show create table system.projection_parts_columns; -- { serverError 390 }
show create table system.quota_limits; -- { serverError 390 }
show create table system.quota_usage; -- { serverError 390 }
show create table system.quotas; -- { serverError 390 }
show create table system.quotas_usage; -- { serverError 390 }
show create table system.replicas; -- { serverError 390 }
show create table system.replicated_fetches; -- { serverError 390 }
show create table system.replicated_merge_tree_settings; -- { serverError 390 }
show create table system.replication_queue; -- { serverError 390 }
show create table system.rocksdb; -- { serverError 390 }
show create table system.role_grants; -- { serverError 390 }
show create table system.roles; -- { serverError 390 }
show create table system.row_policies; -- { serverError 390 }
show create table system.settings; -- { serverError 390 }
show create table system.settings_profile_elements; -- { serverError 390 }
show create table system.settings_profiles; -- { serverError 390 }
show create table system.stack_trace; -- { serverError 390 }
show create table system.storage_policies; -- { serverError 390 }
show create table system.table_engines; -- { serverError 390 }
show create table system.table_functions; -- { serverError 390 }
show create table system.tables; -- { serverError 390 }
show create table system.time_zones; -- { serverError 390 }
show create table system.user_directories; -- { serverError 390 }
show create table system.users; -- { serverError 390 }
show create table system.warnings; -- { serverError 390 }
show create table system.zeros; -- { serverError 390 }
show create table system.zeros_mt; -- { serverError 390 }
