SELECT 'Const Offset';
select 1, subString(bin('Hello'), 1), bin(bitSlice('Hello', 1));
select 2, subString(bin('Hello'), 2), bin(bitSlice('Hello', 2));
select 3, subString(bin('Hello'), 3), bin(bitSlice('Hello', 3));
select 4, subString(bin('Hello'), 4), bin(bitSlice('Hello', 4));
select 5, subString(bin('Hello'), 5), bin(bitSlice('Hello', 5));
select 6, subString(bin('Hello'), 6), bin(bitSlice('Hello', 6));
select 7, subString(bin('Hello'), 7), bin(bitSlice('Hello', 7));
select 8, subString(bin('Hello'), 8), bin(bitSlice('Hello', 8));
select 9, subString(bin('Hello'), 9), bin(bitSlice('Hello', 9));
select 10, subString(bin('Hello'), 10), bin(bitSlice('Hello', 10));
select 11, subString(bin('Hello'), 11), bin(bitSlice('Hello', 11));
select 12, subString(bin('Hello'), 12), bin(bitSlice('Hello', 12));
select 13, subString(bin('Hello'), 13), bin(bitSlice('Hello', 13));
select 14, subString(bin('Hello'), 14), bin(bitSlice('Hello', 14));
select 15, subString(bin('Hello'), 15), bin(bitSlice('Hello', 15));
select 16, subString(bin('Hello'), 16), bin(bitSlice('Hello', 16));

select -1, subString(bin('Hello'), -1), bin(bitSlice('Hello', -1));
select -2, subString(bin('Hello'), -2), bin(bitSlice('Hello', -2));
select -3, subString(bin('Hello'), -3), bin(bitSlice('Hello', -3));
select -4, subString(bin('Hello'), -4), bin(bitSlice('Hello', -4));
select -5, subString(bin('Hello'), -5), bin(bitSlice('Hello', -5));
select -6, subString(bin('Hello'), -6), bin(bitSlice('Hello', -6));
select -7, subString(bin('Hello'), -7), bin(bitSlice('Hello', -7));
select -8, subString(bin('Hello'), -8), bin(bitSlice('Hello', -8));
select -9, subString(bin('Hello'), -9), bin(bitSlice('Hello', -9));
select -10, subString(bin('Hello'), -10), bin(bitSlice('Hello', -10));
select -11, subString(bin('Hello'), -11), bin(bitSlice('Hello', -11));
select -12, subString(bin('Hello'), -12), bin(bitSlice('Hello', -12));
select -13, subString(bin('Hello'), -13), bin(bitSlice('Hello', -13));
select -14, subString(bin('Hello'), -14), bin(bitSlice('Hello', -14));
select -15, subString(bin('Hello'), -15), bin(bitSlice('Hello', -15));
select -16, subString(bin('Hello'), -16), bin(bitSlice('Hello', -16));


SELECT 'Const Offset, Const Length';
select 1, 1, subString(bin('Hello'), 1, 1), bin(bitSlice('Hello', 1, 1));
select 2, 2, subString(bin('Hello'), 2, 2), bin(bitSlice('Hello', 2, 2));
select 3, 3, subString(bin('Hello'), 3, 3), bin(bitSlice('Hello', 3, 3));
select 4, 4, subString(bin('Hello'), 4, 4), bin(bitSlice('Hello', 4, 4));
select 5, 5, subString(bin('Hello'), 5, 5), bin(bitSlice('Hello', 5, 5));
select 6, 6, subString(bin('Hello'), 6, 6), bin(bitSlice('Hello', 6, 6));
select 7, 7, subString(bin('Hello'), 7, 7), bin(bitSlice('Hello', 7, 7));
select 8, 8, subString(bin('Hello'), 8, 8), bin(bitSlice('Hello', 8, 8));
select 9, 9, subString(bin('Hello'), 9, 9), bin(bitSlice('Hello', 9, 9));
select 10, 10, subString(bin('Hello'), 10, 10), bin(bitSlice('Hello', 10, 10));
select 11, 11, subString(bin('Hello'), 11, 11), bin(bitSlice('Hello', 11, 11));
select 12, 12, subString(bin('Hello'), 12, 12), bin(bitSlice('Hello', 12, 12));
select 13, 13, subString(bin('Hello'), 13, 13), bin(bitSlice('Hello', 13, 13));
select 14, 14, subString(bin('Hello'), 14, 14), bin(bitSlice('Hello', 14, 14));
select 15, 15, subString(bin('Hello'), 15, 15), bin(bitSlice('Hello', 15, 15));
select 16, 16, subString(bin('Hello'), 16, 16), bin(bitSlice('Hello', 16, 16));

select 1, -1, subString(bin('Hello'), 1, -1), bin(bitSlice('Hello', 1, -1));
select 2, -2, subString(bin('Hello'), 2, -2), bin(bitSlice('Hello', 2, -2));
select 3, -3, subString(bin('Hello'), 3, -3), bin(bitSlice('Hello', 3, -3));
select 4, -4, subString(bin('Hello'), 4, -4), bin(bitSlice('Hello', 4, -4));
select 5, -5, subString(bin('Hello'), 5, -5), bin(bitSlice('Hello', 5, -5));
select 6, -6, subString(bin('Hello'), 6, -6), bin(bitSlice('Hello', 6, -6));
select 7, -7, subString(bin('Hello'), 7, -7), bin(bitSlice('Hello', 7, -7));
select 8, -8, subString(bin('Hello'), 8, -8), bin(bitSlice('Hello', 8, -8));
select 9, -9, subString(bin('Hello'), 9, -9), bin(bitSlice('Hello', 9, -9));
select 10, -10, subString(bin('Hello'), 10, -10), bin(bitSlice('Hello', 10, -10));
select 11, -11, subString(bin('Hello'), 11, -11), bin(bitSlice('Hello', 11, -11));
select 12, -12, subString(bin('Hello'), 12, -12), bin(bitSlice('Hello', 12, -12));
select 13, -13, subString(bin('Hello'), 13, -13), bin(bitSlice('Hello', 13, -13));
select 14, -14, subString(bin('Hello'), 14, -14), bin(bitSlice('Hello', 14, -14));
select 15, -15, subString(bin('Hello'), 15, -15), bin(bitSlice('Hello', 15, -15));
select 16, -16, subString(bin('Hello'), 16, -16), bin(bitSlice('Hello', 16, -16));

select -1, 1, subString(bin('Hello'), -1, 1), bin(bitSlice('Hello', -1, 1));
select -2, 2, subString(bin('Hello'), -2, 2), bin(bitSlice('Hello', -2, 2));
select -3, 3, subString(bin('Hello'), -3, 3), bin(bitSlice('Hello', -3, 3));
select -4, 4, subString(bin('Hello'), -4, 4), bin(bitSlice('Hello', -4, 4));
select -5, 5, subString(bin('Hello'), -5, 5), bin(bitSlice('Hello', -5, 5));
select -6, 6, subString(bin('Hello'), -6, 6), bin(bitSlice('Hello', -6, 6));
select -7, 7, subString(bin('Hello'), -7, 7), bin(bitSlice('Hello', -7, 7));
select -8, 8, subString(bin('Hello'), -8, 8), bin(bitSlice('Hello', -8, 8));
select -9, 9, subString(bin('Hello'), -9, 9), bin(bitSlice('Hello', -9, 9));
select -10, 10, subString(bin('Hello'), -10, 10), bin(bitSlice('Hello', -10, 10));
select -11, 11, subString(bin('Hello'), -11, 11), bin(bitSlice('Hello', -11, 11));
select -12, 12, subString(bin('Hello'), -12, 12), bin(bitSlice('Hello', -12, 12));
select -13, 13, subString(bin('Hello'), -13, 13), bin(bitSlice('Hello', -13, 13));
select -14, 14, subString(bin('Hello'), -14, 14), bin(bitSlice('Hello', -14, 14));
select -15, 15, subString(bin('Hello'), -15, 15), bin(bitSlice('Hello', -15, 15));
select -16, 16, subString(bin('Hello'), -16, 16), bin(bitSlice('Hello', -16, 16));

select -1, -16, subString(bin('Hello'), -1, -16), bin(bitSlice('Hello', -1, -16));
select -2, -15, subString(bin('Hello'), -2, -15), bin(bitSlice('Hello', -2, -15));
select -3, -14, subString(bin('Hello'), -3, -14), bin(bitSlice('Hello', -3, -14));
select -4, -13, subString(bin('Hello'), -4, -13), bin(bitSlice('Hello', -4, -13));
select -5, -12, subString(bin('Hello'), -5, -12), bin(bitSlice('Hello', -5, -12));
select -6, -11, subString(bin('Hello'), -6, -11), bin(bitSlice('Hello', -6, -11));
select -7, -10, subString(bin('Hello'), -7, -10), bin(bitSlice('Hello', -7, -10));
select -8, -9, subString(bin('Hello'), -8, -9), bin(bitSlice('Hello', -8, -9));
select -9, -8, subString(bin('Hello'), -9, -8), bin(bitSlice('Hello', -9, -8));
select -10, -7, subString(bin('Hello'), -10, -7), bin(bitSlice('Hello', -10, -7));
select -11, -6, subString(bin('Hello'), -11, -6), bin(bitSlice('Hello', -11, -6));
select -12, -5, subString(bin('Hello'), -12, -5), bin(bitSlice('Hello', -12, -5));
select -13, -4, subString(bin('Hello'), -13, -4), bin(bitSlice('Hello', -13, -4));
select -14, -3, subString(bin('Hello'), -14, -3), bin(bitSlice('Hello', -14, -3));
select -15, -2, subString(bin('Hello'), -15, -2), bin(bitSlice('Hello', -15, -2));
select -16, -1, subString(bin('Hello'), -16, -1), bin(bitSlice('Hello', -16, -1));

select 'Dynamic Offset, Dynamic Length';

select number, number, subString(bin('Hello'), number, number), bin(bitSlice('Hello', number, number)) from numbers(16);
select number, -number, subString(bin('Hello'), number, -number), bin(bitSlice('Hello', number, -number)) from numbers(16);
select -number, -16+number, subString(bin('Hello'), -number, -16+number), bin(bitSlice('Hello', -number, -16+number)) from numbers(16);
select -number, number, subString(bin('Hello'), -number, number), bin(bitSlice('Hello', -number, number)) from numbers(16);
