#!/usr/bin/env bash

CURDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CURDIR"/../shell_config.sh

dir=${CLICKHOUSE_TEST_UNIQUE_NAME}
[[ -d $dir ]] && rm -r $dir
mkdir $dir
$CLICKHOUSE_LOCAL --multiline --path $dir -q """
DROP DATABASE IF EXISTS ${CLICKHOUSE_DATABASE_1};
CREATE DATABASE IF NOT EXISTS ${CLICKHOUSE_DATABASE_1};
USE ${CLICKHOUSE_DATABASE_1};
CREATE TABLE test (id Int32) ENGINE=MergeTree() ORDER BY id;
DROP DATABASE ${CLICKHOUSE_DATABASE_1};
"""

$CLICKHOUSE_LOCAL --multiline -q """
DROP DATABASE IF EXISTS ${CLICKHOUSE_DATABASE_1};
CREATE DATABASE IF NOT EXISTS ${CLICKHOUSE_DATABASE_1};
USE ${CLICKHOUSE_DATABASE_1};
CREATE TABLE test (id Int32) ENGINE=MergeTree() ORDER BY id;
DROP DATABASE ${CLICKHOUSE_DATABASE_1};
"""

rm -r $dir
