select 'default format';
select toIntervalNanosecond(99);
select toIntervalNanosecond(100);
select toIntervalMillisecond(1);
select toIntervalSecond(42);
select toIntervalMinute(66);
select toIntervalHour(66);
select toIntervalDay(5);
select toIntervalWeek(1);
select toIntervalWeek(2);

select 'kql format';
set interval_format = 'kql';
select toIntervalNanosecond(99);
select toIntervalNanosecond(100);
select toIntervalMillisecond(1);
select toIntervalSecond(42);
select toIntervalMinute(66);
select toIntervalHour(66);
select toIntervalDay(5);
select toIntervalWeek(1);
select toIntervalWeek(2);
