SET output_format_write_statistics = 0;
SET output_format_json_validate_utf8 = 1;
SELECT 'JSONCompact';
SELECT '\xED\x20\xA8' AS s FORMAT JSONCompact;
SELECT 'JSON';
SELECT '\xED\x20\xA8' AS s FORMAT JSON;
SELECT 'XML';
SELECT '\xED\x20\xA8' AS s FORMAT XML;
SELECT 'JSONColumnsWithMetadata';
SELECT '\xED\x20\xA8' AS s FORMAT JSONColumnsWithMetadata;
SELECT 'JSONEachRow';
SELECT '\xED\x20\xA8' AS s FORMAT JSONEachRow;
SELECT 'JSONCompactEachRow';
SELECT '\xED\x20\xA8' AS s FORMAT JSONCompactEachRow;
SELECT 'JSONColumns';
SELECT '\xED\x20\xA8' AS s FORMAT JSONColumns;
SELECT 'JSONCompactColumns';
SELECT '\xED\x20\xA8' AS s FORMAT JSONCompactColumns;
SELECT 'JSONObjectEachRow';
SELECT '\xED\x20\xA8' AS s FORMAT JSONObjectEachRow;

SET output_format_json_validate_utf8 = 0;
SELECT 'JSONCompact';
SELECT '\xED\x20\xA8' AS s FORMAT JSONCompact;
SELECT 'JSON';
SELECT '\xED\x20\xA8' AS s FORMAT JSON;
SELECT 'XML';
SELECT '\xED\x20\xA8' AS s FORMAT XML;
SELECT 'JSONColumnsWithMetadata';
SELECT '\xED\x20\xA8' AS s FORMAT JSONColumnsWithMetadata;
SELECT 'JSONEachRow';
SELECT '\xED\x20\xA8' AS s FORMAT JSONEachRow;
SELECT 'JSONCompactEachRow';
SELECT '\xED\x20\xA8' AS s FORMAT JSONCompactEachRow;
SELECT 'JSONColumns';
SELECT '\xED\x20\xA8' AS s FORMAT JSONColumns;
SELECT 'JSONCompactColumns';
SELECT '\xED\x20\xA8' AS s FORMAT JSONCompactColumns;
SELECT 'JSONObjectEachRow';
SELECT '\xED\x20\xA8' AS s FORMAT JSONObjectEachRow;


