DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE_1:Identifier};

CREATE DATABASE {CLICKHOUSE_DATABASE_1:Identifier};

CREATE TABLE {CLICKHOUSE_DATABASE_1:Identifier}.t (x UInt8) ENGINE = MergeTree() ORDER BY x;

INSERT INTO {CLICKHOUSE_DATABASE_1:Identifier}.t SELECT number FROM numbers(10);

SELECT t.x FROM {CLICKHOUSE_DATABASE_1:Identifier}.t ORDER BY t.x;

DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE_1:Identifier};
