SET allow_experimental_analyzer = 1;

SELECT 'SET optimize_monotonous_functions_in_order_by = 1';
SET optimize_monotonous_functions_in_order_by = 1;

SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number));
SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number));
SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number));
SELECT number FROM numbers(3) ORDER BY -number;
SELECT number FROM numbers(3) ORDER BY exp(number);
SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x, toFloat32(x);
SELECT number AS x FROM numbers(3) ORDER BY toFloat32(x) as k, toFloat64(k);
SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number)) DESC;
SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number)) DESC;
SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number)) DESC;
SELECT number FROM numbers(3) ORDER BY -number DESC;
SELECT number FROM numbers(3) ORDER BY exp(number) DESC;
SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x DESC, toFloat32(x) DESC;
SELECT toFloat32(number) FROM numbers(3) GROUP BY toFloat32(number) ORDER BY toFloat32(number);
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number));
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number));
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number));
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY -number;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY exp(number);
EXPLAIN QUERY TREE SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x, toFloat32(x);
EXPLAIN QUERY TREE SELECT number AS x FROM numbers(3) ORDER BY toFloat32(x) as k, toFloat64(k);
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number)) DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number)) DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number)) DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY -number DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY exp(number) DESC;
EXPLAIN QUERY TREE SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x DESC, toFloat32(x) DESC;
EXPLAIN QUERY TREE SELECT toFloat32(number) FROM numbers(3) GROUP BY toFloat32(number) ORDER BY toFloat32(number);

SELECT 'SET optimize_monotonous_functions_in_order_by = 0';
SET optimize_monotonous_functions_in_order_by = 0;

SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number));
SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number));
SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number));
SELECT number FROM numbers(3) ORDER BY -number;
SELECT number FROM numbers(3) ORDER BY exp(number);
SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x, toFloat32(x);
SELECT number AS x FROM numbers(3) ORDER BY toFloat32(x) as k, toFloat64(k);
SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number)) DESC;
SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number)) DESC;
SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number)) DESC;
SELECT number FROM numbers(3) ORDER BY -number DESC;
SELECT number FROM numbers(3) ORDER BY exp(number) DESC;
SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x DESC, toFloat32(x) DESC;
SELECT toFloat32(number) FROM numbers(3) GROUP BY toFloat32(number) ORDER BY toFloat32(number);
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number));
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number));
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number));
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY -number;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY exp(number);
EXPLAIN QUERY TREE SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x, toFloat32(x);
EXPLAIN QUERY TREE SELECT number AS x FROM numbers(3) ORDER BY toFloat32(x) as k, toFloat64(k);
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(toFloat64(number)) DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY abs(toFloat32(number)) DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY toFloat32(abs(number)) DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY -number DESC;
EXPLAIN QUERY TREE SELECT number FROM numbers(3) ORDER BY exp(number) DESC;
EXPLAIN QUERY TREE SELECT roundToExp2(number) AS x FROM numbers(3) ORDER BY x DESC, toFloat32(x) DESC;
EXPLAIN QUERY TREE SELECT toFloat32(number) FROM numbers(3) GROUP BY toFloat32(number) ORDER BY toFloat32(number);
