SELECT 1 WINDOW x AS (PARTITION BY x); -- { serverError UNKNOWN_IDENTIFIER }
SELECT 1 WINDOW x AS (PARTITION BY dummy);
SELECT 1 WINDOW dummy AS (PARTITION BY dummy);
SELECT count() OVER dummy WINDOW dummy AS (PARTITION BY dummy);
