DROP TABLE IF EXISTS test;
CREATE TABLE test (x Nullable(String), y Nullable(Int32)) ENGINE = MergeTree() order by tuple();
INSERT INTO test VALUES ('a', 1), ('b', 2), ('c', 3), ('d', 4), (null, 0);
set allow_experimental_analyzer = 1;

select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) = 1;
select '------------------------';
select * from test where (case x when 'a' then 2 when 'a' then 1 else 3 end) = 1;
select '------------------------';
select * from test where (case x when NULL then 2 when 'a' then 1 else 3 end) = 3;
select '------------------------';
select * from test where (case x when NULL then 2 when 'a' then 1 else 3 end) = 1;
select '------------------------';
select * from test where (case x when NULL then 2 when 'a' then 1 else 3 end) = 2;
select '------------------------';
select * from test where (case x when 'c' then 5 when 'a' then 1 else 3 end) = 3;
select '------------------------';
select * from test where (case x when 'c' then 5 when 'a' then 1 else 3 end) = 4;
select '------------------------';
select * from test where (case x when 'c' then 5 when 'd' then 2 when 'a' then 1 end) = 3;
select '------------------------';
select * from test where (case x when 'c' then 1 when 'd' then 2 when 'a' then 2 end) = 2;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) = NULL;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) <> NULL;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) <> 1;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) <> 2;
select '------------------------';
select * from test where (case x when 'a' then 2 when 'b' then 2 else 3 end) <> 2;
select '------------------------';
select * from test where (case x when 'a' then 2 when 'a' then 1 else 3 end) <> 1;
select '------------------------';
select * from test where (case x when NULL then 2 when 'a' then 1 else 3 end) <> 1;
select '------------------------';
select * from test where (case x when NULL then 2 when 'a' then 1 else 3 end) <> 2;
select '------------------------';
select * from test where (case x when 'd' then 2 when 'a' then 1 else 3 end) <> 3;
select '------------------------';
select * from test where (case x when 'c' then 5 when 'd' then 2 when 'a' then 1 end) <> 3;
select '------------------------';
select * from test where (case x when 'c' then 1 when 'd' then 2 when 'a' then 2 end) <> 2;
select '------------------------';
select * from test where ((case x when 'c' then 1 when 'd' then 2 when 'a' then 2 end) <> 2) IS NULL;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) in (1,2);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) in (1);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) not in (1);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) in (3);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) not in (3);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) is null;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) is not null;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 end) is null;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 end) is not null;
select '------------------------';
select * from test where (case x when 'a' then NULL when 'b' then 2 end) is null;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then NULL end) is not null;
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) in (1,NULL);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) not in (1,NULL);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) in (NULL,NULL);
select '------------------------';
select * from test where (case x when 'a' then 1 when 'b' then 2 else 3 end) not in (NULL,NULL);
