-- Tags: no-fasttest, no-parallel

SET allow_experimental_analyzer = 1;

DROP FUNCTION IF EXISTS test_host_api;
DELETE FROM system.webassembly_modules WHERE name = 'test_host_api';

INSERT INTO system.webassembly_modules (name, code) SELECT 'test_host_api', base64Decode(concat(
    'AGFzbQEAAAABHgZgAAF+YAJ/fwBgAABgAn5/AX9gA39/fwBgAX8BfwJRAwNlbnYZY2xpY2tob3VzZV9zZXJ2ZXJfdmVyc2lvbgAA',
    'A2Vudg5jbGlja2hvdXNlX2xvZwABA2VudhRjbGlja2hvdXNlX3Rlcm1pbmF0ZQABAwUEAgMEBQUDAQACBj8KfwFBsIgEC38AQYAI',
    'C38AQagIC38AQbAIC38AQbCIBAt/AEGACAt/AEGwiAQLfwBBgIAIC38AQQALfwBBAQsHxQEOBm1lbW9yeQIAEV9fd2FzbV9jYWxs',
    'X2N0b3JzAAMKaW50X3RvX3N0cgAECGNvcHlfc3RyAAUJdGVzdF9mdW5jAAYMX19kc29faGFuZGxlAwEKX19kYXRhX2VuZAMCC19f',
    'c3RhY2tfbG93AwMMX19zdGFja19oaWdoAwQNX19nbG9iYWxfYmFzZQMFC19faGVhcF9iYXNlAwYKX19oZWFwX2VuZAMHDV9fbWVt',
    'b3J5X2Jhc2UDCAxfX3RhYmxlX2Jhc2UDCQqIBgQCAAvZAQMBfwF+BX9BACECAkAgAFANACAAIQMDQCACQQFqIQIgA0IKVCEEIANC',
    'CoAhAyAERQ0ACwJAIAINAEEADwtBfyEEIAJBf2ohBQJAIAJBAUYNACAFIAFqIQYgASACaiEHIAJBfnEhCEEAIQQDQCAGIAAgAEIK',
    'gCIDQgp+fadBMHI6AAAgByAEQX5zaiADQgqCp0EwcjoAACAGQX5qIQYgAELkAIAhACAIIARBAmoiBEcNAAsgBEF/cyEECyAFQQFx',
    'DQAgASAEaiACaiAAQgqCp0EwcjoAAAsgAgu2AQEEfwJAIAJFDQAgAkEDcSEDQQAhBAJAIAJBBEkNACACQXxxIQVBACEEA0AgASAE',
    'aiICIAAgBGoiBi0AADoAACACQQFqIAZBAWotAAA6AAAgAkECaiAGQQJqLQAAOgAAIAJBA2ogBkEDai0AADoAACAFIARBBGoiBEcN',
    'AAsLIANFDQAgACAEaiECIAEgBGohBANAIAQgAi0AADoAACACQQFqIQIgBEEBaiEEIANBf2oiAw0ACwsL7wIFAX8BfgJ/AX4FfyOA',
    'gICAAEHAAGsiASSAgICAABCAgICAACECQQAhAyABQRBqQQAvAKWIgIAAOwEAIAFBACkAnYiAgAA3AwggAUEAKQCViICAADcDACAB',
    'QRJqIQQCQCACUA0AQQAhAyACIQUDQCADQQFqIQMgBUIKVCEGIAVCCoAhBSAGRQ0ACwJAIAMNAEEAIQMMAQtBfyEGIANBf2ohBwJA',
    'IANBAUYNACABIANqIghBEWohCSADQX5xIQpBACEGA0AgCSACIAJCCoAiBUIKfn2nQTByOgAAIAggBkF+c2pBEmogBUIKgqdBMHI6',
    'AAAgCUF+aiEJIAJC5ACAIQIgCiAGQQJqIgZHDQALIAZBf3MhBgsgB0EBcQ0AIAEgBmogA2pBEmogAkIKgqdBMHI6AAALIAQgA2pB',
    'IToAACABIANBE2oQgYCAgAACQCAARQ0AQYCIgIAAQRQQgoCAgAALIAFBwABqJICAgIAAQQALCy8BAEGACAsoR29vZGJ5ZSwgQ2xp',
    'Y2tIb3VzZSEASGVsbG8sIENsaWNrSG91c2UgAACtAQRuYW1lAA4NaG9zdF9hcGkud2FzbQF2BwAZY2xpY2tob3VzZV9zZXJ2ZXJf',
    'dmVyc2lvbgEOY2xpY2tob3VzZV9sb2cCFGNsaWNraG91c2VfdGVybWluYXRlAxFfX3dhc21fY2FsbF9jdG9ycwQKaW50X3RvX3N0',
    'cgUIY29weV9zdHIGCXRlc3RfZnVuYwcSAQAPX19zdGFja19wb2ludGVyCQoBAAcucm9kYXRhAGcJcHJvZHVjZXJzAQxwcm9jZXNz',
    'ZWQtYnkBDFVidW50dSBjbGFuZ0AxOC4xLjggKCsrMjAyNDA3MzEwMjQ5NDQrM2I1YjVjMWVjNGEzLTF+ZXhwMX4yMDI0MDczMTE0',
    'NTAwMC4xNDQpACwPdGFyZ2V0X2ZlYXR1cmVzAisPbXV0YWJsZS1nbG9iYWxzKwhzaWduLWV4dA=='
));

CREATE FUNCTION test_host_api LANGUAGE WASM ABI PLAIN FROM 'test_host_api' :: 'test_func' ARGUMENTS (UInt32) RETURNS UInt32;

SELECT test_host_api(materialize(0) :: UInt32) SETTINGS log_comment = '03208_wasm_import_export_ok' FORMAT Null;
SELECT test_host_api(materialize(1) :: UInt32) SETTINGS log_comment = '03208_wasm_import_export_err' FORMAT Null; -- { serverError WASM_ERROR }

DROP FUNCTION IF EXISTS test_host_api;

SYSTEM FLUSH LOGS text_log;
SYSTEM FLUSH LOGS query_log;

SELECT count() >= 1
FROM system.text_log
WHERE event_date >= yesterday() AND query_id = (
    SELECT query_id FROM system.query_log
    WHERE event_date >= yesterday() AND query LIKE '%test_host_api%'
    AND type = 'QueryFinish' AND query_kind = 'Select'
    AND log_comment = '03208_wasm_import_export_ok'
    AND current_database = currentDatabase()
    ORDER BY event_time DESC
    LIMIT 1
)
AND message LIKE 'Hello, ClickHouse%' || (SELECT value FROM system.build_options WHERE name = 'VERSION_INTEGER') || '%!'
;

SELECT exception LIKE '%Goodbye, ClickHouse%'
FROM system.query_log
WHERE event_date >= yesterday() AND query LIKE '%test_host_api%'
AND query_kind = 'Select' AND toString(type) LIKE 'Exception%'
AND log_comment = '03208_wasm_import_export_err'
AND current_database = currentDatabase()
ORDER BY event_time DESC
LIMIT 1
;

INSERT INTO system.webassembly_modules (name, code) SELECT 'import_unknown', base64Decode(concat(
    'AGFzbQEAAAABCQJgAX8Bf2AAAAIWAQNlbnYOdW5rbm93bl9pbXBvcnQAAAMDAgEABQMBAAIGPwp/AUGAiAQLfwBBgAgLfwBBgAgL',
    'fwBBgAgLfwBBgIgEC38AQYAIC38AQYCIBAt/AEGAgAgLfwBBAAt/AEEBCwetAQwGbWVtb3J5AgARX193YXNtX2NhbGxfY3RvcnMA',
    'AQl0ZXN0X2Z1bmMAAgxfX2Rzb19oYW5kbGUDAQpfX2RhdGFfZW5kAwILX19zdGFja19sb3cDAwxfX3N0YWNrX2hpZ2gDBA1fX2ds',
    'b2JhbF9iYXNlAwULX19oZWFwX2Jhc2UDBgpfX2hlYXBfZW5kAwcNX19tZW1vcnlfYmFzZQMIDF9fdGFibGVfYmFzZQMJChICAgAL',
    'DQAgABCAgICAAEEBagsAYARuYW1lABQTaW1wb3J0X3Vua25vd24ud2FzbQEvAwAOdW5rbm93bl9pbXBvcnQBEV9fd2FzbV9jYWxs',
    'X2N0b3JzAgl0ZXN0X2Z1bmMHEgEAD19fc3RhY2tfcG9pbnRlcgBnCXByb2R1Y2VycwEMcHJvY2Vzc2VkLWJ5AQxVYnVudHUgY2xh',
    'bmdAMTguMS44ICgrKzIwMjQwNzMxMDI0OTQ0KzNiNWI1YzFlYzRhMy0xfmV4cDF+MjAyNDA3MzExNDUwMDAuMTQ0KQAsD3Rhcmdl',
    'dF9mZWF0dXJlcwIrD211dGFibGUtZ2xvYmFscysIc2lnbi1leHQ='
));

CREATE FUNCTION test_func LANGUAGE WASM ABI PLAIN FROM 'import_unknown' ARGUMENTS (UInt32) RETURNS UInt32; -- { serverError RESOURCE_NOT_FOUND }
DELETE FROM system.webassembly_modules WHERE name = 'import_unknown';

INSERT INTO system.webassembly_modules (name, code) SELECT 'import_incorrect', base64Decode(concat(
    'AGFzbQEAAAABDQNgAX8AYAAAYAF/AX8CFgEDZW52DmNsaWNraG91c2VfbG9nAAADAwIBAgUDAQACBj8KfwFBoIgEC38AQYAIC38A',
    'QZMIC38AQaAIC38AQaCIBAt/AEGACAt/AEGgiAQLfwBBgIAIC38AQQALfwBBAQsHrQEMBm1lbW9yeQIAEV9fd2FzbV9jYWxsX2N0',
    'b3JzAAEJdGVzdF9mdW5jAAIMX19kc29faGFuZGxlAwEKX19kYXRhX2VuZAMCC19fc3RhY2tfbG93AwMMX19zdGFja19oaWdoAwQN',
    'X19nbG9iYWxfYmFzZQMFC19faGVhcF9iYXNlAwYKX19oZWFwX2VuZAMHDV9fbWVtb3J5X2Jhc2UDCAxfX3RhYmxlX2Jhc2UDCQoV',
    'AgIACxAAQYCIgIAAEICAgIAAQQELCxoBAEGACAsTSGVsbG8sIENsaWNrSG91c2UhAABuBG5hbWUAFhVpbXBvcnRfaW5jb3JyZWN0',
    'Lndhc20BLwMADmNsaWNraG91c2VfbG9nARFfX3dhc21fY2FsbF9jdG9ycwIJdGVzdF9mdW5jBxIBAA9fX3N0YWNrX3BvaW50ZXIJ',
    'CgEABy5yb2RhdGEAZwlwcm9kdWNlcnMBDHByb2Nlc3NlZC1ieQEMVWJ1bnR1IGNsYW5nQDE4LjEuOCAoKysyMDI0MDczMTAyNDk0',
    'NCszYjViNWMxZWM0YTMtMX5leHAxfjIwMjQwNzMxMTQ1MDAwLjE0NCkALA90YXJnZXRfZmVhdHVyZXMCKw9tdXRhYmxlLWdsb2Jh',
    'bHMrCHNpZ24tZXh0'
));

CREATE FUNCTION test_func LANGUAGE WASM ABI PLAIN FROM 'import_incorrect' ARGUMENTS (UInt32) RETURNS UInt32;  -- { serverError BAD_ARGUMENTS }
DELETE FROM system.webassembly_modules WHERE name = 'import_incorrect';


DROP FUNCTION IF EXISTS export_faulty_malloc;
DELETE FROM system.webassembly_modules WHERE name = 'export_faulty_malloc';
DELETE FROM system.webassembly_modules WHERE name = 'export_incorrect_malloc';

INSERT INTO system.webassembly_modules (name, code) SELECT 'export_incorrect_malloc', base64Decode(concat(
    'AGFzbQEAAAABFARgAABgAX8Bf2ACf38AYAJ/fwF/AwUEAAECAwUDAQACBj8KfwFBgIgEC38AQYAIC38AQYAIC38AQYAIC38AQYCI',
    'BAt/AEGACAt/AEGAiAQLfwBBgIAIC38AQQALfwBBAQsH5AEOBm1lbW9yeQIAEV9fd2FzbV9jYWxsX2N0b3JzAAAYY2xpY2tob3Vz',
    'ZV9jcmVhdGVfYnVmZmVyAAEZY2xpY2tob3VzZV9kZXN0cm95X2J1ZmZlcgACCXRlc3RfZnVuYwADDF9fZHNvX2hhbmRsZQMBCl9f',
    'ZGF0YV9lbmQDAgtfX3N0YWNrX2xvdwMDDF9fc3RhY2tfaGlnaAMEDV9fZ2xvYmFsX2Jhc2UDBQtfX2hlYXBfYmFzZQMGCl9faGVh',
    'cF9lbmQDBw1fX21lbW9yeV9iYXNlAwgMX190YWJsZV9iYXNlAwkKEQQCAAsEAEEACwIACwQAIAALAI4BBG5hbWUAHRxleHBvcnRf',
    'aW5jb3JyZWN0X21hbGxvYy53YXNtAVQEABFfX3dhc21fY2FsbF9jdG9ycwEYY2xpY2tob3VzZV9jcmVhdGVfYnVmZmVyAhljbGlj',
    'a2hvdXNlX2Rlc3Ryb3lfYnVmZmVyAwl0ZXN0X2Z1bmMHEgEAD19fc3RhY2tfcG9pbnRlcgBnCXByb2R1Y2VycwEMcHJvY2Vzc2Vk',
    'LWJ5AQxVYnVudHUgY2xhbmdAMTguMS44ICgrKzIwMjQwNzMxMDI0OTQ0KzNiNWI1YzFlYzRhMy0xfmV4cDF+MjAyNDA3MzExNDUw',
    'MDAuMTQ0KQAsD3RhcmdldF9mZWF0dXJlcwIrD211dGFibGUtZ2xvYmFscysIc2lnbi1leHQ='
));

CREATE FUNCTION export_incorrect_malloc LANGUAGE WASM ABI UNSTABLE_V0_1 FROM 'export_incorrect_malloc' :: 'test_func' ARGUMENTS (UInt32) RETURNS UInt32; -- { serverError BAD_ARGUMENTS }
DELETE FROM system.webassembly_modules WHERE name = 'export_incorrect_malloc';

INSERT INTO system.webassembly_modules (name, code) SELECT 'export_faulty_malloc', base64Decode(concat(
    'AGFzbQEAAAABEwRgAABgAX8Bf2ABfwBgAn9/AX8DBQQAAQIDBQMBAAIGPwp/AUGQiAQLfwBBgAgLfwBBiAgLfwBBkAgLfwBBkIgE',
    'C38AQYAIC38AQZCIBAt/AEGAgAgLfwBBAAt/AEEBCwfkAQ4GbWVtb3J5AgARX193YXNtX2NhbGxfY3RvcnMAABhjbGlja2hvdXNl',
    'X2NyZWF0ZV9idWZmZXIAARljbGlja2hvdXNlX2Rlc3Ryb3lfYnVmZmVyAAIJdGVzdF9mdW5jAAMMX19kc29faGFuZGxlAwEKX19k',
    'YXRhX2VuZAMCC19fc3RhY2tfbG93AwMMX19zdGFja19oaWdoAwQNX19nbG9iYWxfYmFzZQMFC19faGVhcF9iYXNlAwYKX19oZWFw',
    'X2VuZAMHDV9fbWVtb3J5X2Jhc2UDCAxfX3RhYmxlX2Jhc2UDCQo0BAIACycBAX8/ACEBQQAgADYChIiAgABBACABQRB0NgKAiICA',
    'AEGAiICAAAsCAAsEACAACwCLAQRuYW1lABoZZXhwb3J0X2ZhdWx0eV9tYWxsb2Mud2FzbQFUBAARX193YXNtX2NhbGxfY3RvcnMB',
    'GGNsaWNraG91c2VfY3JlYXRlX2J1ZmZlcgIZY2xpY2tob3VzZV9kZXN0cm95X2J1ZmZlcgMJdGVzdF9mdW5jBxIBAA9fX3N0YWNr',
    'X3BvaW50ZXIAZwlwcm9kdWNlcnMBDHByb2Nlc3NlZC1ieQEMVWJ1bnR1IGNsYW5nQDE4LjEuOCAoKysyMDI0MDczMTAyNDk0NCsz',
    'YjViNWMxZWM0YTMtMX5leHAxfjIwMjQwNzMxMTQ1MDAwLjE0NCkALA90YXJnZXRfZmVhdHVyZXMCKw9tdXRhYmxlLWdsb2JhbHMr',
    'CHNpZ24tZXh0'
));

CREATE FUNCTION export_faulty_malloc LANGUAGE WASM ABI UNSTABLE_V0_1 FROM 'export_faulty_malloc' :: 'test_func' ARGUMENTS (UInt32) RETURNS UInt32;

SELECT export_faulty_malloc(1 :: UInt32); -- { serverError WASM_ERROR }
