CREATE TABLE IF NOT EXISTS test (a UInt64) ENGINE=MergeTree() ORDER BY a;

INSERT INTO test (a) SELECT 1 FROM numbers(1000);

ALTER TABLE test ADD COLUMN b Float64 AFTER a, MODIFY ORDER BY (a, b);
ALTER TABLE test MODIFY COLUMN b DEFAULT rand64() % 100000;
ALTER TABLE test MATERIALIZE COLUMN b;  -- { serverError CANNOT_UPDATE_COLUMN }

DROP TABLE test;