DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE:Identifier};
CREATE DATABASE {CLICKHOUSE_DATABASE:Identifier} ENGINE=Memory;
CREATE MATERIALIZED VIEW {CLICKHOUSE_DATABASE:Identifier}.v0 REFRESH AFTER 1 SECOND APPEND ENGINE = MergeTree() ORDER BY tuple() AS (SELECT 1 c0);
DETACH TABLE {CLICKHOUSE_DATABASE:Identifier}.v0 PERMANENTLY; -- { serverError NOT_IMPLEMENTED }
ALTER TABLE {CLICKHOUSE_DATABASE:Identifier}.v0 MODIFY REFRESH AFTER 1 SECOND APPEND;
DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE:Identifier};
