SET session_timezone = 'UTC';
SET use_legacy_to_time = 0;
-- Operations <Time> + <number>
SELECT toTime(12) + 1;
SELECT toTime(12) + 25;
SELECT toTime(12) + 1.1;
SELECT toTime(12) + 25.2;
-- Operations <Time> - <number>
SELECT toTime(12) - 1;
SELECT toTime(12) - 25;
SELECT toTime(12) - 1.1;
SELECT toTime(12) - 25.2;
-- Operations <Time> + <INTERVAL>
SELECT toTime(12) + INTERVAL 1 NANOSECOND; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) + INTERVAL 1 MICROSECOND; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) + INTERVAL 1 MILLISECOND; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) + INTERVAL 1 SECOND;
SELECT toTime(12) + INTERVAL 1 MINUTE;
SELECT toTime(12) + INTERVAL 1 HOUR;
SELECT toTime(12) + INTERVAL 1 DAY; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) + INTERVAL 1 WEEK; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) + INTERVAL 1 MONTH; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) + INTERVAL 1 QUARTER; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) + INTERVAL 1 YEAR; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
-- Operations <Time> - <INTERVAL>
SELECT toTime(12) - INTERVAL 1 NANOSECOND; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) - INTERVAL 1 MICROSECOND; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) - INTERVAL 1 MILLISECOND; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) - INTERVAL 1 SECOND;
SELECT toTime(72) - INTERVAL 1 MINUTE;
SELECT toTime(3610) - INTERVAL 1 HOUR;
SELECT toTime(12) - INTERVAL 1 MINUTE;
SELECT toTime(12) - INTERVAL 1 HOUR;
SELECT toTime(12) - INTERVAL 1 DAY; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) - INTERVAL 1 WEEK; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) - INTERVAL 1 MONTH; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) - INTERVAL 1 QUARTER; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
SELECT toTime(12) - INTERVAL 1 YEAR; -- { serverError ILLEGAL_TYPE_OF_ARGUMENT }
-- Operations <Time> % <number>
SELECT toTime(12) % 1;
SELECT toTime(12) % 7;
SELECT toTime(12) % 25;
SELECT toTime(12) % 7.1;
SELECT toTime(12) % 25.2;
-- Operations <Time> - <Time>
SELECT toTime(12) - toTime(11);
SELECT toTime(12) - toTime(2);
SELECT toTime(12) - toTime(20);

-- Operations <Time64> + <number>
SELECT toTime64(12, 2) + 1;
SELECT toTime64(12, 2) + 25;
SELECT toTime64(12, 2) + 1.1;
SELECT toTime64(12, 2) + 25.2;
-- Operations <Time64> - <number>
SELECT toTime64(12, 2) - 1;
SELECT toTime64(12, 2) - 25;
SELECT toTime64(12, 2) - 1.1;
SELECT toTime64(12, 2) - 25.2;
-- Operations <Time64> + <INTERVAL>
SELECT toTime64(12, 2) + INTERVAL 1 NANOSECOND;
SELECT toTime64(12, 2) + INTERVAL 1 MICROSECOND;
SELECT toTime64(12, 2) + INTERVAL 1 MILLISECOND;
SELECT toTime64(12, 2) + INTERVAL 1 SECOND;
SELECT toTime64(12, 2) + INTERVAL 1 MINUTE;
SELECT toTime64(12, 2) + INTERVAL 1 HOUR;
SELECT toTime64(12, 2) + INTERVAL 1 DAY;
SELECT toTime64(12, 2) + INTERVAL 1 WEEK;
SELECT toTime64(12, 2) + INTERVAL 1 MONTH;
SELECT toTime64(12, 2) + INTERVAL 1 QUARTER;
-- Operations <Time64> - <INTERVAL>
SELECT toTime64(12, 2) - INTERVAL 1 NANOSECOND;
SELECT toTime64(12, 2) - INTERVAL 1 MICROSECOND;
SELECT toTime64(12, 2) - INTERVAL 1 MILLISECOND;
SELECT toTime64(12, 2) - INTERVAL 1 SECOND;
SELECT toTime64(72, 2) - INTERVAL 1 MINUTE;
SELECT toTime64(3610, 2) - INTERVAL 1 HOUR;
SELECT toTime64(86412, 2) - INTERVAL 1 DAY;
SELECT toTime64(604812, 2) - INTERVAL 1 WEEK;
SELECT toTime64(12, 2) - INTERVAL 1 MONTH + INTERVAL 1 MONTH;
SELECT toTime64(12, 2) - INTERVAL 1 QUARTER + INTERVAL 1 QUARTER;
-- Operations <Time64> - <Time64>
SELECT toTime64(12, 2) - toTime64(12, 2);
SELECT toTime64(12, 2) - toTime64(10.13, 2);
SELECT toTime64(12, 2) - toTime64(20.13, 2);
