SELECT 'Test with two const arguments';
SELECT moduloOrNull(1, 0);
SELECT moduloOrNull(0, 0);
SELECT moduloOrNull(NULL, 0);
SELECT moduloOrNull(1, NULL);
SELECT moduloOrNull(NULL, 1);
SELECT moduloOrNull(NULL, NULL);
SELECT positiveModuloOrNull(1, 0);
SELECT positiveModuloOrNull(0, 0);
SELECT positiveModuloOrNull(NULL, 0);
SELECT positiveModuloOrNull(1, NULL);
SELECT positiveModuloOrNull(NULL, 1);
SELECT positiveModuloOrNull(NULL, NULL);
SELECT intDivOrNull(1, 0);
SELECT intDivOrNull(0, 0);
SELECT intDivOrNull(NULL, 0);
SELECT intDivOrNull(1, NULL);
SELECT intDivOrNull(null, 1);
SELECT intDivOrNull(NULL, NULL);
SELECT divideOrNull(1, 0);
SELECT divideOrNull(0, 0);
SELECT divideOrNull(NULL, 0);
SELECT divideOrNull(1, NULL);
SELECT divideOrNull(NULL, 1);
SELECT divideOrNull(NULL, NULL);

SELECT 'Test with one const arguments';
SELECT moduloOrNull(materialize(1), 0);
SELECT moduloOrNull(materialize(1), NULL);
SELECT moduloOrNull(1, materialize(0));
SELECT moduloOrNull(1, materialize(NULL));
SELECT moduloOrNull(materialize(NULL), 1);
SELECT moduloOrNull(materialize(NULL), 0);
SELECT positiveModuloOrNull(materialize(1), 0);
SELECT positiveModuloOrNull(materialize(1), NULL);
SELECT positiveModuloOrNull(1, materialize(0));
SELECT positiveModuloOrNull(1, materialize(NULL));
SELECT positiveModuloOrNull(materialize(NULL), 1);
SELECT positiveModuloOrNull(materialize(NULL), 0);
SELECT intDivOrNull(materialize(1), 0);
SELECT intDivOrNull(materialize(1), NULL);
SELECT intDivOrNull(1, materialize(0));
SELECT intDivOrNull(1, materialize(NULL));
SELECT intDivOrNull(materialize(NULL), 1);
SELECT intDivOrNull(materialize(NULL), 0);
SELECT divideOrNull(materialize(1), 0);
SELECT divideOrNull(materialize(1), NULL);
SELECT divideOrNull(1, materialize(0));
SELECT divideOrNull(1, materialize(NULL));
SELECT divideOrNull(materialize(NULL), 1);
SELECT divideOrNull(materialize(NULL), 0);

SELECT 'TEST with non const arguments';
SELECT moduloOrNull(materialize(1), materialize(0));
SELECT moduloOrNull(materialize(1), materialize(NULL));
SELECT moduloOrNull(materialize(NULL), materialize(0));
SELECT moduloOrNull(materialize(NULL), materialize(NULL));
SELECT positiveModuloOrNull(materialize(1), materialize(0));
SELECT positiveModuloOrNull(materialize(1), materialize(NULL));
SELECT positiveModuloOrNull(materialize(NULL), materialize(0));
SELECT positiveModuloOrNull(materialize(NULL), materialize(NULL));
SELECT intDivOrNull(materialize(1), materialize(0));
SELECT intDivOrNull(materialize(1), materialize(NULL));
SELECT intDivOrNull(materialize(NULL), materialize(0));
SELECT intDivOrNull(materialize(NULL), materialize(NULL));
SELECT divideOrNull(materialize(1), materialize(0));
SELECT divideOrNull(materialize(1), materialize(NULL));
SELECT divideOrNull(materialize(NULL), materialize(0));
SELECT divideOrNull(materialize(NULL), materialize(NULL));

SELECT 'Test with INT_MIN/-1';
SELECT 'intDivOrNull_Int64', intDivOrNull(toInt64(-9223372036854775808), toInt64(-1));
SELECT 'intDivOrNull_Int32', intDivOrNull(toInt32(-2147483648), toInt32(-1));
SELECT 'intDivOrNull_Int16', intDivOrNull(toInt16(-32768), toInt16(-1));
SELECT 'intDivOrNull_Int8', intDivOrNull(toInt8(-128), toInt8(-1));
SELECT 'moduloOrNull_Int64', moduloOrNull(toInt64(-9223372036854775808), toInt64(-1));
SELECT 'positiveModuloOrNull_Int64', positiveModuloOrNull(toInt64(-9223372036854775808), toInt64(-1));
SELECT 'intDivOrNull_mat', intDivOrNull(materialize(toInt64(-9223372036854775808)), materialize(toInt64(-1)));
SELECT 'moduloOrNull_mat', moduloOrNull(materialize(toInt64(-9223372036854775808)), materialize(toInt64(-1)));
