SELECT 'With constant values.';
SELECT tokenizeChinese('他来到了网易杭研大厦');
SELECT length(tokenizeChinese('他来到了网易杭研大厦'));
SELECT tokenizeChinese('我来自北京邮电大学。');
SELECT length(tokenizeChinese('我来自北京邮电大学。'));
SELECT tokenizeChinese('南京市长江大桥');
SELECT length(tokenizeChinese('南京市长江大桥'));
SELECT tokenizeChinese('我来自北京邮电大学。。。学号123456');
SELECT length(tokenizeChinese('我来自北京邮电大学。。。学号123456'));
SELECT tokenizeChinese('小明硕士毕业于中国科学院计算所，后在日本京都大学深造');
SELECT length(tokenizeChinese('小明硕士毕业于中国科学院计算所，后在日本京都大学深造'));

SELECT 'With materialized values.';
SELECT tokenizeChinese(materialize('他来到了网易杭研大厦'));
SELECT length(tokenizeChinese(materialize('他来到了网易杭研大厦')));
SELECT tokenizeChinese(materialize('我来自北京邮电大学。'));
SELECT length(tokenizeChinese(materialize('我来自北京邮电大学。')));
SELECT tokenizeChinese(materialize('南京市长江大桥'));
SELECT length(tokenizeChinese(materialize('南京市长江大桥')));
SELECT tokenizeChinese(materialize('我来自北京邮电大学。。。学号123456'));
SELECT length(tokenizeChinese(materialize('我来自北京邮电大学。。。学号123456')));
SELECT tokenizeChinese(materialize('小明硕士毕业于中国科学院计算所，后在日本京都大学深造'));
SELECT length(tokenizeChinese(materialize('小明硕士毕业于中国科学院计算所，后在日本京都大学深造')));

SELECT 'With fixed string values.';
SELECT tokenizeChinese(toFixedString('他来到了网易杭研大厦', 30));
SELECT length(tokenizeChinese(toFixedString('他来到了网易杭研大厦', 30)));
SELECT tokenizeChinese(toFixedString('我来自北京邮电大学。', 30));
SELECT length(tokenizeChinese(toFixedString('我来自北京邮电大学。', 30)));
SELECT tokenizeChinese(toFixedString('南京市长江大桥', 21));
SELECT length(tokenizeChinese(toFixedString('南京市长江大桥', 21)));
SELECT tokenizeChinese(toFixedString('我来自北京邮电大学。。。学号123456', 48));
SELECT length(tokenizeChinese(toFixedString('我来自北京邮电大学。。。学号123456', 48)));
SELECT tokenizeChinese(toFixedString('小明硕士毕业于中国科学院计算所，后在日本京都大学深造', 78));
SELECT length(tokenizeChinese(toFixedString('小明硕士毕业于中国科学院计算所，后在日本京都大学深造', 78)));

SELECT 'With materialized and fixed string values.';
SELECT tokenizeChinese(materialize(toFixedString('他来到了网易杭研大厦', 30)));
SELECT length(tokenizeChinese(materialize(toFixedString('他来到了网易杭研大厦', 30))));
SELECT tokenizeChinese(materialize(toFixedString('我来自北京邮电大学。', 30)));
SELECT length(tokenizeChinese(materialize(toFixedString('我来自北京邮电大学。', 30))));
SELECT tokenizeChinese(materialize(toFixedString('南京市长江大桥', 21)));
SELECT length(tokenizeChinese(materialize(toFixedString('南京市长江大桥', 21))));
SELECT tokenizeChinese(materialize(toFixedString('我来自北京邮电大学。。。学号123456', 48)));
SELECT length(tokenizeChinese(materialize(toFixedString('我来自北京邮电大学。。。学号123456', 48))));
SELECT tokenizeChinese(materialize(toFixedString('小明硕士毕业于中国科学院计算所，后在日本京都大学深造', 78)));
SELECT length(tokenizeChinese(materialize(toFixedString('小明硕士毕业于中国科学院计算所，后在日本京都大学深造', 78))));
