-- Tags: no-ordinary-database

-- Tests that various conditions are checked during creation of a ssd_cache layout of a dictionary

-- Github issue #78314

DROP DICTIONARY IF EXISTS dx;

SELECT 'SSD_CACHE: BLOCK_SIZE is a negative value.';
CREATE DICTIONARY dx (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(SSD_CACHE(BLOCK_SIZE -1)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }

SELECT 'SSD_CACHE: BLOCK_SIZE is zero.';
CREATE DICTIONARY dx (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(SSD_CACHE(BLOCK_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }

SELECT 'SSD_CACHE: WRITE_BUFFER_SIZE is zero.';
CREATE DICTIONARY dx (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(SSD_CACHE(WRITE_BUFFER_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }

SELECT 'COMPLEX_KEY_SSD_CACHE: BLOCK_SIZE is a negative value.';
CREATE DICTIONARY dx (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(COMPLEX_KEY_SSD_CACHE(BLOCK_SIZE -1)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }

SELECT 'COMPLEX_KEY_SSD_CACHE: BLOCK_SIZE is zero.';
CREATE DICTIONARY dx (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(COMPLEX_KEY_SSD_CACHE(BLOCK_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }

SELECT 'COMPLEX_KEY_SSD_CACHE: WRITE_BUFFER_SIZE is zero.';
CREATE DICTIONARY dx (col Int64 default null) PRIMARY KEY (col) SOURCE(NULL()) LAYOUT(COMPLEX_KEY_SSD_CACHE(WRITE_BUFFER_SIZE 0)) LIFETIME(1); -- { serverError BAD_ARGUMENTS }

DROP DICTIONARY IF EXISTS dx;
