DROP TABLE IF EXISTS t0;
CREATE TABLE t0 (c0 JSON) ENGINE = MergeTree() ORDER BY (c0);
INSERT INTO TABLE t0 (c0) VALUES ('{"c1":1}'), ('{"c0":1}');
SELECT c0 FROM t0 ORDER BY c0;
DELETE FROM t0 WHERE true;
SELECT c0 FROM t0 ORDER BY c0;
DROP TABLE t0;

SELECT '---';

DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (c0 JSON) ENGINE = MergeTree() ORDER BY tuple() PARTITION BY (c0);
INSERT INTO TABLE t1 (c0) VALUES ('{"c0":[null,true]}');
SELECT c0 FROM t1 ORDER BY c0;
ALTER TABLE t1 APPLY DELETED MASK;
SELECT c0 FROM t1 ORDER BY c0;
DROP TABLE t1;
