DROP DATABASE IF EXISTS d0;
CREATE DATABASE d0 ENGINE = Memory;
CREATE MATERIALIZED VIEW d0.v0 REFRESH AFTER 1 SECOND APPEND ENGINE = MergeTree() ORDER BY tuple() AS (SELECT 1 c0);
DETACH TABLE d0.v0 PERMANENTLY; -- { serverError NOT_IMPLEMENTED }
ALTER TABLE d0.v0 MODIFY REFRESH AFTER 1 SECOND APPEND;
DROP DATABASE d0;
