-- Comprehensive test for SYSTEM queries in clickhouse-local vs server mode
-- This test verifies that the changes work correctly in both environments

-- Test 1: Queries that should fail with UNSUPPORTED_METHOD in clickhouse-local
-- These used to throw LOGICAL_ERROR but now throw UNSUPPORTED_METHOD
SYSTEM RELOAD CONFIG; -- { serverError UNSUPPORTED_METHOD }
SYSTEM STOP LISTEN HTTP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM START LISTEN HTTP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM STOP LISTEN TCP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM START LISTEN TCP; -- { serverError UNSUPPORTED_METHOD }

-- Test 2: Queries that should work in both clickhouse-local and server mode
-- These should not be affected by the changes
SYSTEM DROP DNS CACHE;
SYSTEM DROP MARK CACHE;
SYSTEM DROP UNCOMPRESSED CACHE;
SYSTEM DROP QUERY CACHE;
SYSTEM DROP SCHEMA CACHE;
SYSTEM DROP FORMAT SCHEMA CACHE;
SYSTEM DROP S3 CLIENT CACHE;
SYSTEM DROP FILESYSTEM CACHE;
SYSTEM DROP PAGE CACHE;
SYSTEM DROP COMPILED EXPRESSION CACHE;

-- Test 3: Verify that the error messages are specific and helpful
-- The error should mention the specific query type and clickhouse-local
SYSTEM RELOAD CONFIG; -- { serverError UNSUPPORTED_METHOD }
SYSTEM STOP LISTEN HTTP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM START LISTEN HTTP; -- { serverError UNSUPPORTED_METHOD }

-- Test 4: Test with different server types to ensure all are handled
SYSTEM STOP LISTEN HTTP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM START LISTEN HTTP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM STOP LISTEN TCP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM START LISTEN TCP; -- { serverError UNSUPPORTED_METHOD }
SYSTEM STOP LISTEN HTTPS; -- { serverError UNSUPPORTED_METHOD }
SYSTEM START LISTEN HTTPS; -- { serverError UNSUPPORTED_METHOD }

-- Test 5: Verify that other SYSTEM queries continue to work
-- These should not be affected by the changes to RELOAD CONFIG, STOP LISTEN, START LISTEN
SYSTEM DROP DNS CACHE;
SYSTEM DROP MARK CACHE;
SYSTEM DROP UNCOMPRESSED CACHE;
SYSTEM DROP QUERY CACHE;
SYSTEM DROP SCHEMA CACHE;
SYSTEM DROP FORMAT SCHEMA CACHE;
SYSTEM DROP S3 CLIENT CACHE;
SYSTEM DROP FILESYSTEM CACHE;
SYSTEM DROP PAGE CACHE;
SYSTEM DROP COMPILED EXPRESSION CACHE;
SYSTEM DROP VECTOR SIMILARITY INDEX CACHE;
SYSTEM DROP MMAP CACHE;
SYSTEM DROP QUERY CONDITION CACHE;
SYSTEM DROP INDEX MARK CACHE;
SYSTEM DROP INDEX UNCOMPRESSED CACHE; 