DROP TABLE IF EXISTS t0;

CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() ORDER BY (c0 IN (SELECT 1)); -- { serverError DATA_TYPE_CANNOT_BE_USED_IN_KEY }

CREATE TABLE t0 (c0 Int) ENGINE = MergeTree() ORDER BY (c0 IN (1, 2));
INSERT INTO TABLE t0 (c0) VALUES (1);
SELECT * FROM t0;
