SET param_preceding_rows=1;
EXPLAIN AST SELECT sum(1) OVER (ORDER BY 1 ASC ROWS BETWEEN {preceding_rows:UInt64} PRECEDING AND CURRENT ROW);
SELECT sum(1) OVER (ORDER BY 1 ASC ROWS BETWEEN {preceding_rows:UInt64} PRECEDING AND CURRENT ROW);
