SET allow_experimental_analyzer = 1;

DROP TABLE IF EXISTS t1, t2;

CREATE TABLE t1 (x UInt32) ENGINE = Memory;
CREATE TABLE t2 (y UInt32) ENGINE = Memory;
INSERT INTO t1 VALUES (1), (2), (3);
INSERT INTO t2 VALUES (2);

SELECT sum(x) FROM t1 GROUP BY EXISTS(SELECT 1 FROM t2) ORDER BY sum(x);
SELECT count() FROM t1 GROUP BY EXISTS(SELECT 1 FROM t2 WHERE y = 2);

DROP TABLE t1, t2;
