-- Tags: no-fasttest, no-parallel

SET allow_experimental_analyzer = 1;

DROP FUNCTION IF EXISTS concatInts;

DELETE FROM system.webassembly_modules WHERE name = 'test_v128';
DELETE FROM system.webassembly_modules WHERE name = 'big_module';
DELETE FROM system.webassembly_modules WHERE name = 'test_faulty_abiv1';

INSERT INTO system.webassembly_modules (name, code) SELECT 'test_v128', base64Decode(concat(
    'AGFzbQEAAAABDwNgAABgAX4BfmACfn4BewMEAwABAgUDAQACBj8KfwFBgIgEC38AQYAIC38AQYAIC38AQYAIC38AQYCIBAt/AEGA',
    'CAt/AEGAiAQLfwBBgIAIC38AQQALfwBBAQsHtwENBm1lbW9yeQIAEV9fd2FzbV9jYWxsX2N0b3JzAAAGbW9iaXVzAAEKY29uY2F0',
    'SW50cwACDF9fZHNvX2hhbmRsZQMBCl9fZGF0YV9lbmQDAgtfX3N0YWNrX2xvdwMDDF9fc3RhY2tfaGlnaAMEDV9fZ2xvYmFsX2Jh',
    'c2UDBQtfX2hlYXBfYmFzZQMGCl9faGVhcF9lbmQDBw1fX21lbW9yeV9iYXNlAwgMX190YWJsZV9iYXNlAwkKpAEDAgALkgEDAX4B',
    'fwN+QgEhAQJAAkAgAEIBUQ0AQQAhAgJAAkAgAEIEWg0AIAAhAwwBC0ICIQEgACEDQgAhBANAAkAgAyADIAGAIgUgAX59QgBSDQAg',
    'BSABglANBCAEQgF8IQQgBSEDCyABQgF8IgEgAX4gAFgNAAsgBKdBAXEhAgtCAUJ/IAIgA0ICVHMbIQELIAEPC0IACwsAIAH9EiAA',
    '/R4BCwBOBG5hbWUACQh0dHQud2FzbQEoAwARX193YXNtX2NhbGxfY3RvcnMBBm1vYml1cwIKY29uY2F0SW50cwcSAQAPX19zdGFj',
    'a19wb2ludGVyAGcJcHJvZHVjZXJzAQxwcm9jZXNzZWQtYnkBDFVidW50dSBjbGFuZ0AxOC4xLjggKCsrMjAyNDA3MzEwMjQ5NDQr',
    'M2I1YjVjMWVjNGEzLTF+ZXhwMX4yMDI0MDczMTE0NTAwMC4xNDQpADUPdGFyZ2V0X2ZlYXR1cmVzAysPbXV0YWJsZS1nbG9iYWxz',
    'KwhzaWduLWV4dCsHc2ltZDEyOA=='

));

CREATE OR REPLACE FUNCTION concatInts LANGUAGE WASM ABI PLAIN FROM 'test_v128' ARGUMENTS (UInt64, UInt64) RETURNS UInt128;
SELECT concatInts(1 :: UInt64, 0 :: UInt64);
