#!/usr/bin/env bash
# Tags: no-fasttest

# Arrow timestamps may carry a fixed numeric UTC offset (e.g. "+05:30", "-08:00", "00:00") or the
# non-IANA marker "fixed" as their timezone. These are not loadable by cctz, so reading such a file
# used to fail with "Cannot load time zone ...". https://github.com/ClickHouse/ClickHouse/issues/73261
# Only a full [+|-]HH:MM[:SS] offset and the "fixed" marker are normalized; everything else
# (misspelled IANA names, bare-hour strings like "12" or "+05") must still raise "Cannot load time
# zone" so producer-metadata errors are not silently masked.
# All embedded files hold the single UTC instant 2024-06-06 12:00:00.

CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CUR_DIR"/../shell_config.sh

DATA_FILE=$CLICKHOUSE_TMP/test_$CLICKHOUSE_TEST_UNIQUE_NAME.arrow

run_case() {
    local label=$1
    local b64=$2
    echo "--- $label ---"
    echo "$b64" | base64 -d > "$DATA_FILE"
    $CLICKHOUSE_LOCAL -q "DESC file('$DATA_FILE', 'Arrow')"
    $CLICKHOUSE_LOCAL -q "SELECT toString(ts) FROM file('$DATA_FILE', 'Arrow')"
}

# An unsupported timezone string (a misspelled IANA name, or a bare-hour offset without minutes)
# must NOT be normalized: it has to keep raising "Cannot load time zone ..." so producer-metadata
# errors stay visible instead of silently shifting displayed values.
run_invalid_case() {
    local label=$1
    local expected=$2
    local b64=$3
    echo "--- $label ---"
    echo "$b64" | base64 -d > "$DATA_FILE"
    $CLICKHOUSE_LOCAL -q "DESC file('$DATA_FILE', 'Arrow')" 2>&1 | grep -oF "$expected"
}

# tz="+00:00"  -> Fixed/UTC+00:00:00, renders 12:00:00
run_case "+00:00" "QVJST1cxAAD/////iAAAABAAAAAAAAoADAAGAAUACAAKAAAAAAEEAAwAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAAYAAAArMDA6MDAAAAAAAAD/////iAAAABQAAAAAAAAADAAWAAYABQAIAAwADAAAAAADBAAYAAAACAAAAAAAAAAAAAoAGAAMAAQACAAKAAAAPAAAABAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAsCJsNxoGAP////8AAAAAEAAAAAwAFAAGAAgADAAQAAwAAAAAAAQAOAAAACgAAAAEAAAAAQAAAJgAAAAAAAAAkAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAIAAAABAAIAAAABAAAAAEAAAAUAAAAEAAUAAgABgAHAAwAAAAQABAAAAAAAAEKEAAAABwAAAAEAAAAAAAAAAIAAAB0cwAACAAMAAYACAAIAAAAAAACAAQAAAAGAAAAKzAwOjAwAACwAAAAQVJST1cx"

# tz="+05:30"  -> Fixed/UTC+05:30:00, sub-hour offset preserved, renders 17:30:00
run_case "+05:30" "QVJST1cxAAD/////iAAAABAAAAAAAAoADAAGAAUACAAKAAAAAAEEAAwAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAAYAAAArMDU6MzAAAAAAAAD/////iAAAABQAAAAAAAAADAAWAAYABQAIAAwADAAAAAADBAAYAAAACAAAAAAAAAAAAAoAGAAMAAQACAAKAAAAPAAAABAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAsCJsNxoGAP////8AAAAAEAAAAAwAFAAGAAgADAAQAAwAAAAAAAQAOAAAACgAAAAEAAAAAQAAAJgAAAAAAAAAkAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAIAAAABAAIAAAABAAAAAEAAAAUAAAAEAAUAAgABgAHAAwAAAAQABAAAAAAAAEKEAAAABwAAAAEAAAAAAAAAAIAAAB0cwAACAAMAAYACAAIAAAAAAACAAQAAAAGAAAAKzA1OjMwAACwAAAAQVJST1cx"

# tz="-08:00"  -> Fixed/UTC-08:00:00, negative offset, renders 04:00:00
run_case "-08:00" "QVJST1cxAAD/////iAAAABAAAAAAAAoADAAGAAUACAAKAAAAAAEEAAwAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAAYAAAAtMDg6MDAAAAAAAAD/////iAAAABQAAAAAAAAADAAWAAYABQAIAAwADAAAAAADBAAYAAAACAAAAAAAAAAAAAoAGAAMAAQACAAKAAAAPAAAABAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAsCJsNxoGAP////8AAAAAEAAAAAwAFAAGAAgADAAQAAwAAAAAAAQAOAAAACgAAAAEAAAAAQAAAJgAAAAAAAAAkAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAIAAAABAAIAAAABAAAAAEAAAAUAAAAEAAUAAgABgAHAAwAAAAQABAAAAAAAAEKEAAAABwAAAAEAAAAAAAAAAIAAAB0cwAACAAMAAYACAAIAAAAAAACAAQAAAAGAAAALTA4OjAwAACwAAAAQVJST1cx"

# tz="fixed"   -> not parseable as an offset, falls back to UTC, renders 12:00:00
run_case "fixed" "QVJST1cxAAD/////iAAAABAAAAAAAAoADAAGAAUACAAKAAAAAAEEAAwAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAAUAAABmaXhlZAAAAAAAAAD/////iAAAABQAAAAAAAAADAAWAAYABQAIAAwADAAAAAADBAAYAAAACAAAAAAAAAAAAAoAGAAMAAQACAAKAAAAPAAAABAAAAABAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAAAAAAAsCJsNxoGAP////8AAAAAEAAAAAwAFAAGAAgADAAQAAwAAAAAAAQAOAAAACgAAAAEAAAAAQAAAJgAAAAAAAAAkAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAIAAAABAAIAAAABAAAAAEAAAAUAAAAEAAUAAgABgAHAAwAAAAQABAAAAAAAAEKEAAAABwAAAAEAAAAAAAAAAIAAAB0cwAACAAMAAYACAAIAAAAAAACAAQAAAAFAAAAZml4ZWQAAACwAAAAQVJST1cx"

# tz="Europe/Amsterdm" -> a misspelled IANA name: not an offset, not "fixed", so it is passed
# through unchanged and DataTypeDateTime64 still rejects it (we do not mask producer errors).
run_invalid_case "Europe/Amsterdm (invalid)" "Cannot load time zone Europe/Amsterdm" "QVJST1cxAAD/////kAAAABAAAAAAAAoADAAGAAUACAAKAAAAAAEEAAwAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAA8AAABFdXJvcGUvQW1zdGVyZG0AAAAAAP////+IAAAAFAAAAAAAAAAMABYABgAFAAgADAAMAAAAAAMEABgAAAAIAAAAAAAAAAAACgAYAAwABAAIAAoAAAA8AAAAEAAAAAEAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAAAAAAAAACwImw3GgYA/////wAAAAAQAAAADAAUAAYACAAMABAADAAAAAAABAA4AAAAKAAAAAQAAAABAAAAoAAAAAAAAACQAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAA8AAABFdXJvcGUvQW1zdGVyZG0AuAAAAEFSUk9XMQ=="

# tz="12" -> a bare hour with no minute component. It is NOT a valid fixed-offset spelling, so it
# must pass through and be rejected rather than silently become Fixed/UTC+12:00:00.
run_invalid_case "12 (bare hour, invalid)" "Cannot load time zone 12" "QVJST1cxAAD/////gAAAABAAAAAAAAoADAAGAAUACAAKAAAAAAEEAAwAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAAIAAAAxMgAA/////4gAAAAUAAAAAAAAAAwAFgAGAAUACAAMAAwAAAAAAwQAGAAAAAgAAAAAAAAAAAAKABgADAAEAAgACgAAADwAAAAQAAAAAQAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAALAibDcaBgD/////AAAAABAAAAAMABQABgAIAAwAEAAMAAAAAAAEADQAAAAkAAAABAAAAAEAAACQAAAAAAAAAJAAAAAAAAAACAAAAAAAAAAAAAAACAAIAAAABAAIAAAABAAAAAEAAAAUAAAAEAAUAAgABgAHAAwAAAAQABAAAAAAAAEKEAAAABwAAAAEAAAAAAAAAAIAAAB0cwAACAAMAAYACAAIAAAAAAACAAQAAAACAAAAMTIAAKgAAABBUlJPVzE="

# tz="+05" -> a signed bare hour, also missing the minute component; same requirement applies.
run_invalid_case "+05 (bare hour, invalid)" "Cannot load time zone +05" "QVJST1cxAAD/////gAAAABAAAAAAAAoADAAGAAUACAAKAAAAAAEEAAwAAAAIAAgAAAAEAAgAAAAEAAAAAQAAABQAAAAQABQACAAGAAcADAAAABAAEAAAAAAAAQoQAAAAHAAAAAQAAAAAAAAAAgAAAHRzAAAIAAwABgAIAAgAAAAAAAIABAAAAAMAAAArMDUA/////4gAAAAUAAAAAAAAAAwAFgAGAAUACAAMAAwAAAAAAwQAGAAAAAgAAAAAAAAAAAAKABgADAAEAAgACgAAADwAAAAQAAAAAQAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAALAibDcaBgD/////AAAAABAAAAAMABQABgAIAAwAEAAMAAAAAAAEADQAAAAkAAAABAAAAAEAAACQAAAAAAAAAJAAAAAAAAAACAAAAAAAAAAAAAAACAAIAAAABAAIAAAABAAAAAEAAAAUAAAAEAAUAAgABgAHAAwAAAAQABAAAAAAAAEKEAAAABwAAAAEAAAAAAAAAAIAAAB0cwAACAAMAAYACAAIAAAAAAACAAQAAAADAAAAKzA1AKgAAABBUlJPVzE="

rm "$DATA_FILE"
