-- Tags: no-fasttest, no-parallel, no-msan

SET enable_analyzer = 1;

DROP FUNCTION IF EXISTS access_data;
DELETE FROM system.webassembly_modules WHERE name = 'large_module';

/*
#include <stdint.h>

#define DATA_SIZE (1024 * 1024)

static int32_t large_data[DATA_SIZE] = { 42 };

int32_t access_data(uint32_t index) {
    if (index < DATA_SIZE) {
        return large_data[index];
    }
    return -1;
}
*/
INSERT INTO system.webassembly_modules (name, hash, code) SELECT 'large_module',
    reinterpretAsUInt256(unhex('f2baf4ab3d8ee8ac876c8b317cefc977ac76bf08ffedc6de176b06f9a77b6ecb')),
    base64Decode(concat(
        'AGFzbQEAAAABCQJgAABgAX8BfwMDAgABBQMBAEIGRwp/AUGAiIQCC38AQYAIC38AQYCIgAILfwBBgIiAAgt/AEGAiIQCC38AQYAI',
        'C38AQYCIhAILfwBBgICIAgt/AEEAC38AQQELB68BDAZtZW1vcnkCABFfX3dhc21fY2FsbF9jdG9ycwAAC2FjY2Vzc19kYXRhAAEM',
        'X19kc29faGFuZGxlAwEKX19kYXRhX2VuZAMCC19fc3RhY2tfbG93AwMMX19zdGFja19oaWdoAwQNX19nbG9iYWxfYmFzZQMFC19f',
        'aGVhcF9iYXNlAwYKX19oZWFwX2VuZAMHDV9fbWVtb3J5X2Jhc2UDCAxfX3RhYmxlX2Jhc2UDCQosAgIACycBAX9BfyEBAkAgAEH/',
        '/z9LDQAgAEECdEGAiICAAGooAgAhAQsgAQsLioCAAgEAQYAIC4CAgAIqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
 repeat('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', 55921),
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
        'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFoEbmFtZQAQD2JpZ19tb2R1bGUud2FzbQEhAgAR',
        'X193YXNtX2NhbGxfY3RvcnMBC2FjY2Vzc19kYXRhBxIBAA9fX3N0YWNrX3BvaW50ZXIJCgEABy5yb2RhdGEAZwlwcm9kdWNlcnMB',
        'DHByb2Nlc3NlZC1ieQEMVWJ1bnR1IGNsYW5nQDE4LjEuOCAoKysyMDI0MDczMTAyNDk0NCszYjViNWMxZWM0YTMtMX5leHAxfjIw',
        'MjQwNzMxMTQ1MDAwLjE0NCkALA90YXJnZXRfZmVhdHVyZXMCKw9tdXRhYmxlLWdsb2JhbHMrCHNpZ24tZXh0'
));


CREATE OR REPLACE FUNCTION access_data LANGUAGE WASM ABI ROW_DIRECT FROM 'large_module' ARGUMENTS (UInt32) RETURNS Int32 SETTINGS max_memory = 655360;
SELECT access_data(0 :: UInt32) == 42; -- { serverError WASM_ERROR }

CREATE OR REPLACE FUNCTION access_data LANGUAGE WASM ABI ROW_DIRECT FROM 'large_module' ARGUMENTS (UInt32) RETURNS Int32 SETTINGS max_memory = 6553600;
SELECT access_data(0 :: UInt32);
