#!/usr/bin/env bash

CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CUR_DIR"/../shell_config.sh

SERVICE_USER="svcuser_${CLICKHOUSE_DATABASE}"
TARGET_USER="fmtuser_${CLICKHOUSE_DATABASE}"

$CLICKHOUSE_CLIENT --query "DROP USER IF EXISTS ${SERVICE_USER}, ${TARGET_USER}"
$CLICKHOUSE_CLIENT --query "CREATE USER ${SERVICE_USER}, ${TARGET_USER}"
$CLICKHOUSE_CLIENT --query "GRANT ALL ON ${CLICKHOUSE_DATABASE}.* TO ${SERVICE_USER} WITH GRANT OPTION"
$CLICKHOUSE_CLIENT --query "GRANT IMPERSONATE ON ${TARGET_USER} TO ${SERVICE_USER}"
$CLICKHOUSE_CLIENT --query "GRANT SELECT ON ${CLICKHOUSE_DATABASE}.* TO ${TARGET_USER}"

echo "--- FORMAT JSON ---"
$CLICKHOUSE_CLIENT --user ${SERVICE_USER} --query "EXECUTE AS ${TARGET_USER} SELECT 1 AS x FORMAT JSON" | grep -c '"meta"'

echo "--- FORMAT CSV ---"
$CLICKHOUSE_CLIENT --user ${SERVICE_USER} --query "EXECUTE AS ${TARGET_USER} SELECT 'hello' AS s, 42 AS n FORMAT CSV"

echo "--- FORMAT TabSeparatedWithNames ---"
$CLICKHOUSE_CLIENT --user ${SERVICE_USER} --query "EXECUTE AS ${TARGET_USER} SELECT 1 AS a, 2 AS b FORMAT TabSeparatedWithNames"

echo "--- INTO OUTFILE with FORMAT CSV ---"
OUTFILE="${CLICKHOUSE_TMP}/execute_as_outfile_${CLICKHOUSE_DATABASE}.csv"
$CLICKHOUSE_CLIENT --user ${SERVICE_USER} --query "EXECUTE AS ${TARGET_USER} SELECT 'file' AS c1, 100 AS c2 INTO OUTFILE '${OUTFILE}' FORMAT CSV"
cat "${OUTFILE}"
rm -f "${OUTFILE}"

echo "--- SETTINGS clause ---"
$CLICKHOUSE_CLIENT --user ${SERVICE_USER} --query "EXECUTE AS ${TARGET_USER} SELECT 1 AS x FORMAT TabSeparated SETTINGS max_result_rows=1"

echo "--- INTO OUTFILE with COMPRESSION ---"
OUTFILE_GZ="${CLICKHOUSE_TMP}/execute_as_outfile_${CLICKHOUSE_DATABASE}.csv.gz"
$CLICKHOUSE_CLIENT --user ${SERVICE_USER} --query "EXECUTE AS ${TARGET_USER} SELECT 'compressed' AS c1, 200 AS c2 INTO OUTFILE '${OUTFILE_GZ}' COMPRESSION 'gzip' FORMAT CSV"
zcat "${OUTFILE_GZ}"
rm -f "${OUTFILE_GZ}"

$CLICKHOUSE_CLIENT --query "DROP USER ${SERVICE_USER}, ${TARGET_USER}"
