-- Tags: no-parallel
-- ^^ required because the parser test mentions SYSTEM DROP subcommands. The
-- EXPLAIN SYNTAX wrapper means no command actually runs, but the style check
-- is grep-based and flags any file containing `SYSTEM DROP`.
--
-- Exercise the SYSTEM query parser and AST formatter for a wide variety of
-- subcommands. EXPLAIN SYNTAX round-trips the AST so this hits both
-- ParserSystemQuery::parseImpl and ASTSystemQuery::formatImpl without
-- actually executing any of the commands.

SELECT '--- cache-clearing variants ---';
EXPLAIN SYNTAX SYSTEM DROP MARK CACHE;
EXPLAIN SYNTAX SYSTEM DROP PRIMARY INDEX CACHE;
EXPLAIN SYNTAX SYSTEM DROP UNCOMPRESSED CACHE;
EXPLAIN SYNTAX SYSTEM DROP INDEX MARK CACHE;
EXPLAIN SYNTAX SYSTEM DROP INDEX UNCOMPRESSED CACHE;
EXPLAIN SYNTAX SYSTEM DROP VECTOR SIMILARITY INDEX CACHE;
EXPLAIN SYNTAX SYSTEM DROP TEXT INDEX TOKENS CACHE;
EXPLAIN SYNTAX SYSTEM DROP TEXT INDEX HEADER CACHE;
EXPLAIN SYNTAX SYSTEM DROP TEXT INDEX POSTINGS CACHE;
EXPLAIN SYNTAX SYSTEM DROP TEXT INDEX CACHES;
EXPLAIN SYNTAX SYSTEM DROP MMAP CACHE;
EXPLAIN SYNTAX SYSTEM DROP QUERY CACHE;
EXPLAIN SYNTAX SYSTEM DROP QUERY CONDITION CACHE;
EXPLAIN SYNTAX SYSTEM DROP COMPILED EXPRESSION CACHE;
EXPLAIN SYNTAX SYSTEM DROP ICEBERG METADATA CACHE;
EXPLAIN SYNTAX SYSTEM DROP PARQUET METADATA CACHE;
EXPLAIN SYNTAX SYSTEM DROP FILESYSTEM CACHE;
EXPLAIN SYNTAX SYSTEM DROP DISTRIBUTED CACHE;
EXPLAIN SYNTAX SYSTEM DROP DISK METADATA CACHE disk1;
EXPLAIN SYNTAX SYSTEM DROP PAGE CACHE;
EXPLAIN SYNTAX SYSTEM DROP SCHEMA CACHE;
EXPLAIN SYNTAX SYSTEM DROP FORMAT SCHEMA CACHE;
EXPLAIN SYNTAX SYSTEM DROP S3 CLIENT CACHE;
EXPLAIN SYNTAX SYSTEM DROP DNS CACHE;
EXPLAIN SYNTAX SYSTEM DROP CONNECTIONS CACHE;

SELECT '--- prewarm cache variants ---';
EXPLAIN SYNTAX SYSTEM PREWARM MARK CACHE db.t;
EXPLAIN SYNTAX SYSTEM PREWARM PRIMARY INDEX CACHE db.t;

SELECT '--- merge / fetch / move / sends / ttl / cleanup start/stop ---';
-- Global forms (SYSTEM STOP/START MERGES without a table) are not tested here
-- because the style check rejects them anywhere in tests/queries/.
EXPLAIN SYNTAX SYSTEM STOP MERGES db.t;
EXPLAIN SYNTAX SYSTEM START MERGES db.t;
EXPLAIN SYNTAX SYSTEM STOP TTL MERGES;
EXPLAIN SYNTAX SYSTEM START TTL MERGES;
EXPLAIN SYNTAX SYSTEM STOP FETCHES db.t;
EXPLAIN SYNTAX SYSTEM START FETCHES db.t;
EXPLAIN SYNTAX SYSTEM STOP MOVES db.t;
EXPLAIN SYNTAX SYSTEM START MOVES db.t;
EXPLAIN SYNTAX SYSTEM STOP REPLICATED SENDS db.t;
EXPLAIN SYNTAX SYSTEM START REPLICATED SENDS db.t;
EXPLAIN SYNTAX SYSTEM STOP DISTRIBUTED SENDS db.t;
EXPLAIN SYNTAX SYSTEM START DISTRIBUTED SENDS db.t;
EXPLAIN SYNTAX SYSTEM STOP REPLICATION QUEUES db.t;
EXPLAIN SYNTAX SYSTEM START REPLICATION QUEUES db.t;
EXPLAIN SYNTAX SYSTEM STOP REPLICATED DDL QUERIES;
EXPLAIN SYNTAX SYSTEM START REPLICATED DDL QUERIES;
EXPLAIN SYNTAX SYSTEM STOP CLEANUP db.t;
EXPLAIN SYNTAX SYSTEM START CLEANUP db.t;
EXPLAIN SYNTAX SYSTEM STOP PULLING REPLICATION LOG db.t;
EXPLAIN SYNTAX SYSTEM START PULLING REPLICATION LOG db.t;

SELECT '--- reload / restart / replica management ---';
EXPLAIN SYNTAX SYSTEM RELOAD DICTIONARY d;
EXPLAIN SYNTAX SYSTEM RELOAD DICTIONARIES;
EXPLAIN SYNTAX SYSTEM RELOAD FUNCTION f;
EXPLAIN SYNTAX SYSTEM RELOAD FUNCTIONS;
EXPLAIN SYNTAX SYSTEM RELOAD EMBEDDED DICTIONARIES;
EXPLAIN SYNTAX SYSTEM RELOAD CONFIG;
EXPLAIN SYNTAX SYSTEM RELOAD USERS;
EXPLAIN SYNTAX SYSTEM RELOAD ASYNCHRONOUS METRICS;
EXPLAIN SYNTAX SYSTEM RESTART REPLICA db.t;
EXPLAIN SYNTAX SYSTEM RESTART REPLICAS;
EXPLAIN SYNTAX SYSTEM RESTORE REPLICA db.t;
EXPLAIN SYNTAX SYSTEM DROP REPLICA 'r1' FROM TABLE db.t;
EXPLAIN SYNTAX SYSTEM DROP REPLICA 'r1' FROM DATABASE db;
EXPLAIN SYNTAX SYSTEM DROP REPLICA 'r1' FROM ZKPATH '/clickhouse/zkpath';
EXPLAIN SYNTAX SYSTEM DROP DATABASE REPLICA 'r1' FROM DATABASE db;
EXPLAIN SYNTAX SYSTEM DROP DATABASE REPLICA 'r1' FROM ZKPATH '/clickhouse/zkpath';
EXPLAIN SYNTAX SYSTEM SYNC REPLICA db.t STRICT;
EXPLAIN SYNTAX SYSTEM SYNC REPLICA db.t LIGHTWEIGHT;
EXPLAIN SYNTAX SYSTEM SYNC DATABASE REPLICA db;
EXPLAIN SYNTAX SYSTEM SYNC TRANSACTION LOG;
EXPLAIN SYNTAX SYSTEM SYNC FILE CACHE;
EXPLAIN SYNTAX SYSTEM WAIT LOADING PARTS db.t;

SELECT '--- thread fuzzer / failpoints / jemalloc ---';
EXPLAIN SYNTAX SYSTEM START THREAD FUZZER;
EXPLAIN SYNTAX SYSTEM STOP THREAD FUZZER;
EXPLAIN SYNTAX SYSTEM ENABLE FAILPOINT fp;
EXPLAIN SYNTAX SYSTEM DISABLE FAILPOINT fp;
EXPLAIN SYNTAX SYSTEM JEMALLOC PURGE;
EXPLAIN SYNTAX SYSTEM JEMALLOC ENABLE PROFILE;
EXPLAIN SYNTAX SYSTEM JEMALLOC DISABLE PROFILE;
EXPLAIN SYNTAX SYSTEM JEMALLOC FLUSH PROFILE;

SELECT '--- views / primary key ---';
EXPLAIN SYNTAX SYSTEM REFRESH VIEW db.v;
EXPLAIN SYNTAX SYSTEM STOP VIEW db.v;
EXPLAIN SYNTAX SYSTEM START VIEW db.v;
EXPLAIN SYNTAX SYSTEM CANCEL VIEW db.v;
EXPLAIN SYNTAX SYSTEM STOP VIEWS;
EXPLAIN SYNTAX SYSTEM START VIEWS;
EXPLAIN SYNTAX SYSTEM LOAD PRIMARY KEY db.t;
EXPLAIN SYNTAX SYSTEM UNLOAD PRIMARY KEY db.t;

SELECT '--- flush variants ---';
-- The global (targetless) flush-logs form is rejected by the style check;
-- the per-log form is still exercised below.
EXPLAIN SYNTAX SYSTEM FLUSH LOGS query_log;
EXPLAIN SYNTAX SYSTEM FLUSH DISTRIBUTED db.t;
EXPLAIN SYNTAX SYSTEM FLUSH ASYNC INSERT QUEUE;

SELECT '--- listening / admin ---';
EXPLAIN SYNTAX SYSTEM STOP LISTEN QUERIES ALL;
EXPLAIN SYNTAX SYSTEM START LISTEN QUERIES ALL;
EXPLAIN SYNTAX SYSTEM STOP LISTEN TCP;
EXPLAIN SYNTAX SYSTEM START LISTEN TCP;

SELECT '--- unfreeze / restart disk ---';
EXPLAIN SYNTAX SYSTEM UNFREEZE WITH NAME 'snap1';
EXPLAIN SYNTAX SYSTEM RESTART DISK my_disk;

SELECT '--- ON CLUSTER clause ---';
EXPLAIN SYNTAX SYSTEM FLUSH LOGS ON CLUSTER 'my_cluster';
EXPLAIN SYNTAX SYSTEM RELOAD DICTIONARY d ON CLUSTER 'my_cluster';


SELECT '--- Bad SYSTEM commands ---';
-- SYSTEM followed by an identifier is re-parsed as an expression by the analyzer.
-- Multi-word invalid SYSTEM commands trigger SYNTAX_ERROR.
SYSTEM FOO BAR BAZ; -- { clientError SYNTAX_ERROR }
