-- Tags: no-parallel
-- ^^ required because the parser test mentions SYSTEM DROP subcommands. The
-- EXPLAIN SYNTAX wrapper means no command actually runs.
--
-- Additional SYSTEM query variants not covered by 04117:
-- WAIT FAILPOINT (+ PAUSE/RESUME), TEST VIEW, REFRESH/CANCEL/WAIT VIEW,
-- START/STOP REPLICATED VIEW, ALLOCATE MEMORY, FLUSH LOGS with multiple tables,
-- RELOAD DELTA KERNEL TRACING, LISTEN protocol variants, FILESYSTEM CACHE with
-- path and key, QUERY CACHE with tag, SUSPEND, KILL/SHUTDOWN.

SELECT '--- WAIT FAILPOINT variants ---';
EXPLAIN SYNTAX SYSTEM WAIT FAILPOINT fp;
EXPLAIN SYNTAX SYSTEM WAIT FAILPOINT fp PAUSE;
EXPLAIN SYNTAX SYSTEM WAIT FAILPOINT fp RESUME;

SELECT '--- VIEW management (REFRESH / START / STOP / CANCEL / WAIT / REPLICATED) ---';
EXPLAIN SYNTAX SYSTEM REFRESH VIEW db.v;
EXPLAIN SYNTAX SYSTEM START REPLICATED VIEW db.v;
EXPLAIN SYNTAX SYSTEM STOP REPLICATED VIEW db.v;
EXPLAIN SYNTAX SYSTEM CANCEL VIEW db.v;
EXPLAIN SYNTAX SYSTEM WAIT VIEW db.v;

SELECT '--- TEST VIEW (SET / UNSET FAKE TIME) ---';
EXPLAIN SYNTAX SYSTEM TEST VIEW db.v SET FAKE TIME '2023-01-01 00:00:00';
EXPLAIN SYNTAX SYSTEM TEST VIEW db.v UNSET FAKE TIME;

SELECT '--- ALLOCATE MEMORY ---';
EXPLAIN SYNTAX SYSTEM ALLOCATE MEMORY 1024;
EXPLAIN SYNTAX SYSTEM ALLOCATE MEMORY 1048576;

SELECT '--- FLUSH LOGS with multiple log tables ---';
EXPLAIN SYNTAX SYSTEM FLUSH LOGS query_log, part_log;
-- The global (targetless) flush-logs form is rejected by the style check.
EXPLAIN SYNTAX SYSTEM FLUSH ASYNC INSERT QUEUE db.t1, db.t2;

SELECT '--- RELOAD DELTA KERNEL TRACING ---';
EXPLAIN SYNTAX SYSTEM RELOAD DELTA KERNEL TRACING WARN;
EXPLAIN SYNTAX SYSTEM RELOAD DELTA KERNEL TRACING DEBUG;

SELECT '--- RELOAD MODEL(S) ---';
EXPLAIN SYNTAX SYSTEM RELOAD MODEL my_model;
EXPLAIN SYNTAX SYSTEM RELOAD MODELS;

SELECT '--- LISTEN protocol variants ---';
EXPLAIN SYNTAX SYSTEM START LISTEN HTTP;
EXPLAIN SYNTAX SYSTEM START LISTEN HTTPS;
EXPLAIN SYNTAX SYSTEM START LISTEN TCP SECURE;
EXPLAIN SYNTAX SYSTEM START LISTEN TCP WITH PROXY;
EXPLAIN SYNTAX SYSTEM START LISTEN INTERSERVER HTTP;
EXPLAIN SYNTAX SYSTEM START LISTEN INTERSERVER HTTPS;
EXPLAIN SYNTAX SYSTEM START LISTEN MYSQL;
EXPLAIN SYNTAX SYSTEM START LISTEN POSTGRESQL;
EXPLAIN SYNTAX SYSTEM START LISTEN GRPC;
EXPLAIN SYNTAX SYSTEM START LISTEN PROMETHEUS;
EXPLAIN SYNTAX SYSTEM START LISTEN QUERIES DEFAULT;
EXPLAIN SYNTAX SYSTEM START LISTEN QUERIES CUSTOM;
EXPLAIN SYNTAX SYSTEM STOP LISTEN HTTP;

SELECT '--- FILESYSTEM CACHE with path / key ---';
EXPLAIN SYNTAX SYSTEM DROP FILESYSTEM CACHE 'my_cache';
EXPLAIN SYNTAX SYSTEM DROP FILESYSTEM CACHE 'my_cache' KEY xyz;

SELECT '--- QUERY CACHE with tag ---';
EXPLAIN SYNTAX SYSTEM DROP QUERY CACHE TAG 'mytag';

SELECT '--- SUSPEND / KILL / SHUTDOWN ---';
EXPLAIN SYNTAX SYSTEM SUSPEND FOR 1 SECOND;
EXPLAIN SYNTAX SYSTEM KILL;
EXPLAIN SYNTAX SYSTEM SHUTDOWN;
