EXPLAIN SYNTAX SYSTEM STOP db.t;
EXPLAIN SYNTAX SYSTEM START db.t;
EXPLAIN SYNTAX SYSTEM PAUSE db.t;
EXPLAIN SYNTAX SYSTEM CANCEL db.t;
EXPLAIN SYNTAX SYSTEM REFRESH db.t;

EXPLAIN SYNTAX SYSTEM STOP t;
EXPLAIN SYNTAX SYSTEM START t;
EXPLAIN SYNTAX SYSTEM PAUSE t;
EXPLAIN SYNTAX SYSTEM CANCEL t;
EXPLAIN SYNTAX SYSTEM REFRESH t;

EXPLAIN SYNTAX SYSTEM STOP ALL BACKGROUND;
EXPLAIN SYNTAX SYSTEM START ALL BACKGROUND;
EXPLAIN SYNTAX SYSTEM PAUSE ALL BACKGROUND;
EXPLAIN SYNTAX SYSTEM CANCEL ALL BACKGROUND;
EXPLAIN SYNTAX SYSTEM REFRESH ALL BACKGROUND;

EXPLAIN SYNTAX SYSTEM STOP MERGES db.t;
EXPLAIN SYNTAX SYSTEM START MERGES db.t;
EXPLAIN SYNTAX SYSTEM STOP VIEW db.v;
EXPLAIN SYNTAX SYSTEM START VIEW db.v;
EXPLAIN SYNTAX SYSTEM PAUSE VIEW db.v;
EXPLAIN SYNTAX SYSTEM CANCEL VIEW db.v;
EXPLAIN SYNTAX SYSTEM REFRESH VIEW db.v;
EXPLAIN SYNTAX SYSTEM STOP VIEWS;
EXPLAIN SYNTAX SYSTEM START VIEWS;
EXPLAIN SYNTAX SYSTEM PAUSE VIEWS;

EXPLAIN SYNTAX SYSTEM STOP db.background;
EXPLAIN SYNTAX SYSTEM STOP all;
