#!/usr/bin/env bash
# Tags: no-fasttest, no-encrypted-storage
# Tag no-fasttest: requires S3
# Tag no-encrypted-storage: DiskBackup cannot decrypt an encrypted source disk's backup

# Each `BACKUP ... TO S3` warns that s3_disable_checksum is off, and the test profile sets
# max_backup_bandwidth, so the warning always fires. `error` keeps `<Fatal>` visible.
CLICKHOUSE_CLIENT_SERVER_LOGS_LEVEL=error

CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CUR_DIR"/../shell_config.sh

SOURCE_DATABASE_NAME=${CLICKHOUSE_TEST_UNIQUE_NAME}_source
BACKUP_DATABASE_NAME=${CLICKHOUSE_TEST_UNIQUE_NAME}_backup
COLLECTION_NAME=${CLICKHOUSE_TEST_UNIQUE_NAME}_collection
FIRST_BACKUP_URL="http://localhost:11111/test/${CLICKHOUSE_TEST_UNIQUE_NAME}/first"
SECOND_BACKUP_URL="http://localhost:11111/test/${CLICKHOUSE_TEST_UNIQUE_NAME}/second"

$CLICKHOUSE_CLIENT -m -q """
DROP DATABASE IF EXISTS $BACKUP_DATABASE_NAME;
DROP DATABASE IF EXISTS $SOURCE_DATABASE_NAME;
DROP NAMED COLLECTION IF EXISTS $COLLECTION_NAME;

CREATE DATABASE $SOURCE_DATABASE_NAME;
CREATE TABLE $SOURCE_DATABASE_NAME.test_table (id UInt64) ENGINE = MergeTree ORDER BY id;

INSERT INTO $SOURCE_DATABASE_NAME.test_table SELECT number FROM numbers(2);
BACKUP DATABASE $SOURCE_DATABASE_NAME TO S3('$FIRST_BACKUP_URL', 'test', 'testtest') FORMAT Null;

TRUNCATE TABLE $SOURCE_DATABASE_NAME.test_table;
INSERT INTO $SOURCE_DATABASE_NAME.test_table SELECT number FROM numbers(3);
BACKUP DATABASE $SOURCE_DATABASE_NAME TO S3('$SECOND_BACKUP_URL', 'test', 'testtest') FORMAT Null;

CREATE NAMED COLLECTION $COLLECTION_NAME AS
    url = '$FIRST_BACKUP_URL', access_key_id = 'test', secret_access_key = 'testtest';

SELECT 'named collection points at the first backup';
CREATE DATABASE $BACKUP_DATABASE_NAME ENGINE = Backup('$SOURCE_DATABASE_NAME', S3($COLLECTION_NAME));
SELECT count() FROM $BACKUP_DATABASE_NAME.test_table;

SELECT '--';
SELECT 'named collection redirected to the second backup';
DROP DATABASE $BACKUP_DATABASE_NAME;
ALTER NAMED COLLECTION $COLLECTION_NAME SET url = '$SECOND_BACKUP_URL';
CREATE DATABASE $BACKUP_DATABASE_NAME ENGINE = Backup('$SOURCE_DATABASE_NAME', S3($COLLECTION_NAME));
SELECT count() FROM $BACKUP_DATABASE_NAME.test_table;

SELECT '--';
SELECT 'url overridden per query';
DROP DATABASE $BACKUP_DATABASE_NAME;
CREATE DATABASE $BACKUP_DATABASE_NAME ENGINE = Backup('$SOURCE_DATABASE_NAME', S3($COLLECTION_NAME, url = '$FIRST_BACKUP_URL'));
SELECT count() FROM $BACKUP_DATABASE_NAME.test_table;
DROP DATABASE $BACKUP_DATABASE_NAME;
CREATE DATABASE $BACKUP_DATABASE_NAME ENGINE = Backup('$SOURCE_DATABASE_NAME', S3($COLLECTION_NAME, url = '$SECOND_BACKUP_URL'));
SELECT count() FROM $BACKUP_DATABASE_NAME.test_table;

DROP DATABASE $BACKUP_DATABASE_NAME;
DROP DATABASE $SOURCE_DATABASE_NAME;
DROP NAMED COLLECTION $COLLECTION_NAME;
"""
