#!/usr/bin/env python3

import base64
from pathlib import Path
import sys

table_path = Path(sys.argv[1])

# Spark generated the three binary files below. Listing each file separately keeps the Iceberg
# layout visible and prevents platform metadata files from entering the fixture.
binary_files = {
    'data/00000-0-96cd03f6-c98c-4730-9d32-6ba8261f2736-0-00001.parquet': (
        'UEFSMRUAFQgVIBWR0sChBRwVAhUAFQgVCAAAKLUv/QBYIAAAAQAAAAEAABUAFSAVOBXB77vDAxwVAhUAFQgVCAAAKLUv/QBYgAAA'
        'AAACEh1RuiuPLwhugAAAAAEAABkRAhkYBAEAAAAZGAQBAAAAFQIZFgAZFgIZFgIAGRECGRgQAAACEh1RuiuPLwhugAAAABkYEAAA'
        'AhIdUborjy8IboAAAAAVAhkWABkWAhkWAgAZHBYIFU4WAAAAGRwWVhVmFgAAABUCGTxIBXRhYmxlFQQAFQIlABgCaWRVAgAVDhUg'
        'FQAYAWQlChU8FUwVBBxcFTwVTAAAABYCGRwZLCYAHBUCGSUIABkYAmlkFQwWAhY2Fk4mCDwYBAEAAAAYBAEAAAAWACgEAQAAABgE'
        'AQAAAAAZHBUAFQAVAgA8KRYCGRYCAAAW4AIVFBa8ARU6ACYAHBUOGSUIABkYAWQVDBYCFk4WZiZWPBgQAAACEh1RuiuPLwhugAAA'
        'ABgQAAACEh1RuiuPLwhugAAAABYAKBAAAAISHVG6K48vCG6AAAAAGBAAAAISHVG6K48vCG6AAAAAABkcFQAVABUCADwpFgIZFgIA'
        'ABb0AhUUFvYBFWoAFoQBFgImCBa0ARQAABkcGA5pY2ViZXJnLnNjaGVtYRiZAXsidHlwZSI6InN0cnVjdCIsInNjaGVtYS1pZCI6'
        'MCwiZmllbGRzIjpbeyJpZCI6MSwibmFtZSI6ImlkIiwicmVxdWlyZWQiOnRydWUsInR5cGUiOiJpbnQifSx7ImlkIjoyLCJuYW1l'
        'IjoiZCIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoiZGVjaW1hbCgzOCwgMzApIn1dfQAYSnBhcnF1ZXQtbXIgdmVyc2lvbiAxLjE1'
        'LjAgKGJ1aWxkIDQ2NjU0MDFkMzZlNDY4Yzk4ODMyMmY3ODYyMWRhN2MyZDFjMjJlZGUpGSwcAAAcAAAAGwIAAFBBUjE='
    ),
    'metadata/9e3f1059-756c-4ec7-8cab-54a68f8107fe-m0.avro': (
        'T2JqARAMc2NoZW1htgJ7InR5cGUiOiJzdHJ1Y3QiLCJzY2hlbWEtaWQiOjAsImZpZWxkcyI6W3siaWQiOjEsIm5hbWUiOiJpZCIs'
        'InJlcXVpcmVkIjpmYWxzZSwidHlwZSI6ImludCJ9LHsiaWQiOjIsIm5hbWUiOiJkIiwicmVxdWlyZWQiOmZhbHNlLCJ0eXBlIjoi'
        'ZGVjaW1hbCgzOCwgMzApIn1dfRZhdnJvLnNjaGVtYYA4eyJ0eXBlIjoicmVjb3JkIiwibmFtZSI6Im1hbmlmZXN0X2VudHJ5Iiwi'
        'ZmllbGRzIjpbeyJuYW1lIjoic3RhdHVzIiwidHlwZSI6ImludCIsImZpZWxkLWlkIjowfSx7Im5hbWUiOiJzbmFwc2hvdF9pZCIs'
        'InR5cGUiOlsibnVsbCIsImxvbmciXSwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjF9LHsibmFtZSI6InNlcXVlbmNlX251bWJl'
        'ciIsInR5cGUiOlsibnVsbCIsImxvbmciXSwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjN9LHsibmFtZSI6ImZpbGVfc2VxdWVu'
        'Y2VfbnVtYmVyIiwidHlwZSI6WyJudWxsIiwibG9uZyJdLCJkZWZhdWx0IjpudWxsLCJmaWVsZC1pZCI6NH0seyJuYW1lIjoiZGF0'
        'YV9maWxlIiwidHlwZSI6eyJ0eXBlIjoicmVjb3JkIiwibmFtZSI6InIyIiwiZmllbGRzIjpbeyJuYW1lIjoiY29udGVudCIsInR5'
        'cGUiOiJpbnQiLCJkb2MiOiJDb250ZW50cyBvZiB0aGUgZmlsZTogMD1kYXRhLCAxPXBvc2l0aW9uIGRlbGV0ZXMsIDI9ZXF1YWxp'
        'dHkgZGVsZXRlcyIsImZpZWxkLWlkIjoxMzR9LHsibmFtZSI6ImZpbGVfcGF0aCIsInR5cGUiOiJzdHJpbmciLCJkb2MiOiJMb2Nh'
        'dGlvbiBVUkkgd2l0aCBGUyBzY2hlbWUiLCJmaWVsZC1pZCI6MTAwfSx7Im5hbWUiOiJmaWxlX2Zvcm1hdCIsInR5cGUiOiJzdHJp'
        'bmciLCJkb2MiOiJGaWxlIGZvcm1hdCBuYW1lOiBhdnJvLCBvcmMsIG9yIHBhcnF1ZXQiLCJmaWVsZC1pZCI6MTAxfSx7Im5hbWUi'
        'OiJwYXJ0aXRpb24iLCJ0eXBlIjp7InR5cGUiOiJyZWNvcmQiLCJuYW1lIjoicjEwMiIsImZpZWxkcyI6W119LCJkb2MiOiJQYXJ0'
        'aXRpb24gZGF0YSB0dXBsZSwgc2NoZW1hIGJhc2VkIG9uIHRoZSBwYXJ0aXRpb24gc3BlYyIsImZpZWxkLWlkIjoxMDJ9LHsibmFt'
        'ZSI6InJlY29yZF9jb3VudCIsInR5cGUiOiJsb25nIiwiZG9jIjoiTnVtYmVyIG9mIHJlY29yZHMgaW4gdGhlIGZpbGUiLCJmaWVs'
        'ZC1pZCI6MTAzfSx7Im5hbWUiOiJmaWxlX3NpemVfaW5fYnl0ZXMiLCJ0eXBlIjoibG9uZyIsImRvYyI6IlRvdGFsIGZpbGUgc2l6'
        'ZSBpbiBieXRlcyIsImZpZWxkLWlkIjoxMDR9LHsibmFtZSI6ImNvbHVtbl9zaXplcyIsInR5cGUiOlsibnVsbCIseyJ0eXBlIjoi'
        'YXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoicmVjb3JkIiwibmFtZSI6ImsxMTdfdjExOCIsImZpZWxkcyI6W3sibmFtZSI6ImtleSIs'
        'InR5cGUiOiJpbnQiLCJmaWVsZC1pZCI6MTE3fSx7Im5hbWUiOiJ2YWx1ZSIsInR5cGUiOiJsb25nIiwiZmllbGQtaWQiOjExOH1d'
        'fSwibG9naWNhbFR5cGUiOiJtYXAifV0sImRvYyI6Ik1hcCBvZiBjb2x1bW4gaWQgdG8gdG90YWwgc2l6ZSBvbiBkaXNrIiwiZGVm'
        'YXVsdCI6bnVsbCwiZmllbGQtaWQiOjEwOH0seyJuYW1lIjoidmFsdWVfY291bnRzIiwidHlwZSI6WyJudWxsIix7InR5cGUiOiJh'
        'cnJheSIsIml0ZW1zIjp7InR5cGUiOiJyZWNvcmQiLCJuYW1lIjoiazExOV92MTIwIiwiZmllbGRzIjpbeyJuYW1lIjoia2V5Iiwi'
        'dHlwZSI6ImludCIsImZpZWxkLWlkIjoxMTl9LHsibmFtZSI6InZhbHVlIiwidHlwZSI6ImxvbmciLCJmaWVsZC1pZCI6MTIwfV19'
        'LCJsb2dpY2FsVHlwZSI6Im1hcCJ9XSwiZG9jIjoiTWFwIG9mIGNvbHVtbiBpZCB0byB0b3RhbCBjb3VudCwgaW5jbHVkaW5nIG51'
        'bGwgYW5kIE5hTiIsImRlZmF1bHQiOm51bGwsImZpZWxkLWlkIjoxMDl9LHsibmFtZSI6Im51bGxfdmFsdWVfY291bnRzIiwidHlw'
        'ZSI6WyJudWxsIix7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJyZWNvcmQiLCJuYW1lIjoiazEyMV92MTIyIiwiZmll'
        'bGRzIjpbeyJuYW1lIjoia2V5IiwidHlwZSI6ImludCIsImZpZWxkLWlkIjoxMjF9LHsibmFtZSI6InZhbHVlIiwidHlwZSI6Imxv'
        'bmciLCJmaWVsZC1pZCI6MTIyfV19LCJsb2dpY2FsVHlwZSI6Im1hcCJ9XSwiZG9jIjoiTWFwIG9mIGNvbHVtbiBpZCB0byBudWxs'
        'IHZhbHVlIGNvdW50IiwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjExMH0seyJuYW1lIjoibmFuX3ZhbHVlX2NvdW50cyIsInR5'
        'cGUiOlsibnVsbCIseyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoicmVjb3JkIiwibmFtZSI6ImsxMzhfdjEzOSIsImZp'
        'ZWxkcyI6W3sibmFtZSI6ImtleSIsInR5cGUiOiJpbnQiLCJmaWVsZC1pZCI6MTM4fSx7Im5hbWUiOiJ2YWx1ZSIsInR5cGUiOiJs'
        'b25nIiwiZmllbGQtaWQiOjEzOX1dfSwibG9naWNhbFR5cGUiOiJtYXAifV0sImRvYyI6Ik1hcCBvZiBjb2x1bW4gaWQgdG8gbnVt'
        'YmVyIG9mIE5hTiB2YWx1ZXMgaW4gdGhlIGNvbHVtbiIsImRlZmF1bHQiOm51bGwsImZpZWxkLWlkIjoxMzd9LHsibmFtZSI6Imxv'
        'd2VyX2JvdW5kcyIsInR5cGUiOlsibnVsbCIseyJ0eXBlIjoiYXJyYXkiLCJpdGVtcyI6eyJ0eXBlIjoicmVjb3JkIiwibmFtZSI6'
        'ImsxMjZfdjEyNyIsImZpZWxkcyI6W3sibmFtZSI6ImtleSIsInR5cGUiOiJpbnQiLCJmaWVsZC1pZCI6MTI2fSx7Im5hbWUiOiJ2'
        'YWx1ZSIsInR5cGUiOiJieXRlcyIsImZpZWxkLWlkIjoxMjd9XX0sImxvZ2ljYWxUeXBlIjoibWFwIn1dLCJkb2MiOiJNYXAgb2Yg'
        'Y29sdW1uIGlkIHRvIGxvd2VyIGJvdW5kIiwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjEyNX0seyJuYW1lIjoidXBwZXJfYm91'
        'bmRzIiwidHlwZSI6WyJudWxsIix7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJyZWNvcmQiLCJuYW1lIjoiazEyOV92'
        'MTMwIiwiZmllbGRzIjpbeyJuYW1lIjoia2V5IiwidHlwZSI6ImludCIsImZpZWxkLWlkIjoxMjl9LHsibmFtZSI6InZhbHVlIiwi'
        'dHlwZSI6ImJ5dGVzIiwiZmllbGQtaWQiOjEzMH1dfSwibG9naWNhbFR5cGUiOiJtYXAifV0sImRvYyI6Ik1hcCBvZiBjb2x1bW4g'
        'aWQgdG8gdXBwZXIgYm91bmQiLCJkZWZhdWx0IjpudWxsLCJmaWVsZC1pZCI6MTI4fSx7Im5hbWUiOiJrZXlfbWV0YWRhdGEiLCJ0'
        'eXBlIjpbIm51bGwiLCJieXRlcyJdLCJkb2MiOiJFbmNyeXB0aW9uIGtleSBtZXRhZGF0YSBibG9iIiwiZGVmYXVsdCI6bnVsbCwi'
        'ZmllbGQtaWQiOjEzMX0seyJuYW1lIjoic3BsaXRfb2Zmc2V0cyIsInR5cGUiOlsibnVsbCIseyJ0eXBlIjoiYXJyYXkiLCJpdGVt'
        'cyI6ImxvbmciLCJlbGVtZW50LWlkIjoxMzN9XSwiZG9jIjoiU3BsaXR0YWJsZSBvZmZzZXRzIiwiZGVmYXVsdCI6bnVsbCwiZmll'
        'bGQtaWQiOjEzMn0seyJuYW1lIjoiZXF1YWxpdHlfaWRzIiwidHlwZSI6WyJudWxsIix7InR5cGUiOiJhcnJheSIsIml0ZW1zIjoi'
        'aW50IiwiZWxlbWVudC1pZCI6MTM2fV0sImRvYyI6IkVxdWFsaXR5IGNvbXBhcmlzb24gZmllbGQgSURzIiwiZGVmYXVsdCI6bnVs'
        'bCwiZmllbGQtaWQiOjEzNX0seyJuYW1lIjoic29ydF9vcmRlcl9pZCIsInR5cGUiOlsibnVsbCIsImludCJdLCJkb2MiOiJTb3J0'
        'IG9yZGVyIElEIiwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjE0MH0seyJuYW1lIjoicmVmZXJlbmNlZF9kYXRhX2ZpbGUiLCJ0'
        'eXBlIjpbIm51bGwiLCJzdHJpbmciXSwiZG9jIjoiRnVsbHkgcXVhbGlmaWVkIGxvY2F0aW9uIChVUkkgd2l0aCBGUyBzY2hlbWUp'
        'IG9mIGEgZGF0YSBmaWxlIHRoYXQgYWxsIGRlbGV0ZXMgcmVmZXJlbmNlIiwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjE0M31d'
        'fSwiZmllbGQtaWQiOjJ9XX0UYXZyby5jb2RlYw5kZWZsYXRlHGZvcm1hdC12ZXJzaW9uAjIicGFydGl0aW9uLXNwZWMtaWQCMBxp'
        'Y2ViZXJnLnNjaGVtYZ4ueyJ0eXBlIjoic3RydWN0Iiwic2NoZW1hLWlkIjowLCJmaWVsZHMiOlt7ImlkIjowLCJuYW1lIjoic3Rh'
        'dHVzIiwicmVxdWlyZWQiOnRydWUsInR5cGUiOiJpbnQifSx7ImlkIjoxLCJuYW1lIjoic25hcHNob3RfaWQiLCJyZXF1aXJlZCI6'
        'ZmFsc2UsInR5cGUiOiJsb25nIn0seyJpZCI6MywibmFtZSI6InNlcXVlbmNlX251bWJlciIsInJlcXVpcmVkIjpmYWxzZSwidHlw'
        'ZSI6ImxvbmcifSx7ImlkIjo0LCJuYW1lIjoiZmlsZV9zZXF1ZW5jZV9udW1iZXIiLCJyZXF1aXJlZCI6ZmFsc2UsInR5cGUiOiJs'
        'b25nIn0seyJpZCI6MiwibmFtZSI6ImRhdGFfZmlsZSIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjp7InR5cGUiOiJzdHJ1Y3QiLCJm'
        'aWVsZHMiOlt7ImlkIjoxMzQsIm5hbWUiOiJjb250ZW50IiwicmVxdWlyZWQiOnRydWUsInR5cGUiOiJpbnQiLCJkb2MiOiJDb250'
        'ZW50cyBvZiB0aGUgZmlsZTogMD1kYXRhLCAxPXBvc2l0aW9uIGRlbGV0ZXMsIDI9ZXF1YWxpdHkgZGVsZXRlcyJ9LHsiaWQiOjEw'
        'MCwibmFtZSI6ImZpbGVfcGF0aCIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoic3RyaW5nIiwiZG9jIjoiTG9jYXRpb24gVVJJIHdp'
        'dGggRlMgc2NoZW1lIn0seyJpZCI6MTAxLCJuYW1lIjoiZmlsZV9mb3JtYXQiLCJyZXF1aXJlZCI6dHJ1ZSwidHlwZSI6InN0cmlu'
        'ZyIsImRvYyI6IkZpbGUgZm9ybWF0IG5hbWU6IGF2cm8sIG9yYywgb3IgcGFycXVldCJ9LHsiaWQiOjEwMiwibmFtZSI6InBhcnRp'
        'dGlvbiIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjp7InR5cGUiOiJzdHJ1Y3QiLCJmaWVsZHMiOltdfSwiZG9jIjoiUGFydGl0aW9u'
        'IGRhdGEgdHVwbGUsIHNjaGVtYSBiYXNlZCBvbiB0aGUgcGFydGl0aW9uIHNwZWMifSx7ImlkIjoxMDMsIm5hbWUiOiJyZWNvcmRf'
        'Y291bnQiLCJyZXF1aXJlZCI6dHJ1ZSwidHlwZSI6ImxvbmciLCJkb2MiOiJOdW1iZXIgb2YgcmVjb3JkcyBpbiB0aGUgZmlsZSJ9'
        'LHsiaWQiOjEwNCwibmFtZSI6ImZpbGVfc2l6ZV9pbl9ieXRlcyIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoibG9uZyIsImRvYyI6'
        'IlRvdGFsIGZpbGUgc2l6ZSBpbiBieXRlcyJ9LHsiaWQiOjEwOCwibmFtZSI6ImNvbHVtbl9zaXplcyIsInJlcXVpcmVkIjpmYWxz'
        'ZSwidHlwZSI6eyJ0eXBlIjoibWFwIiwia2V5LWlkIjoxMTcsImtleSI6ImludCIsInZhbHVlLWlkIjoxMTgsInZhbHVlIjoibG9u'
        'ZyIsInZhbHVlLXJlcXVpcmVkIjp0cnVlfSwiZG9jIjoiTWFwIG9mIGNvbHVtbiBpZCB0byB0b3RhbCBzaXplIG9uIGRpc2sifSx7'
        'ImlkIjoxMDksIm5hbWUiOiJ2YWx1ZV9jb3VudHMiLCJyZXF1aXJlZCI6ZmFsc2UsInR5cGUiOnsidHlwZSI6Im1hcCIsImtleS1p'
        'ZCI6MTE5LCJrZXkiOiJpbnQiLCJ2YWx1ZS1pZCI6MTIwLCJ2YWx1ZSI6ImxvbmciLCJ2YWx1ZS1yZXF1aXJlZCI6dHJ1ZX0sImRv'
        'YyI6Ik1hcCBvZiBjb2x1bW4gaWQgdG8gdG90YWwgY291bnQsIGluY2x1ZGluZyBudWxsIGFuZCBOYU4ifSx7ImlkIjoxMTAsIm5h'
        'bWUiOiJudWxsX3ZhbHVlX2NvdW50cyIsInJlcXVpcmVkIjpmYWxzZSwidHlwZSI6eyJ0eXBlIjoibWFwIiwia2V5LWlkIjoxMjEs'
        'ImtleSI6ImludCIsInZhbHVlLWlkIjoxMjIsInZhbHVlIjoibG9uZyIsInZhbHVlLXJlcXVpcmVkIjp0cnVlfSwiZG9jIjoiTWFw'
        'IG9mIGNvbHVtbiBpZCB0byBudWxsIHZhbHVlIGNvdW50In0seyJpZCI6MTM3LCJuYW1lIjoibmFuX3ZhbHVlX2NvdW50cyIsInJl'
        'cXVpcmVkIjpmYWxzZSwidHlwZSI6eyJ0eXBlIjoibWFwIiwia2V5LWlkIjoxMzgsImtleSI6ImludCIsInZhbHVlLWlkIjoxMzks'
        'InZhbHVlIjoibG9uZyIsInZhbHVlLXJlcXVpcmVkIjp0cnVlfSwiZG9jIjoiTWFwIG9mIGNvbHVtbiBpZCB0byBudW1iZXIgb2Yg'
        'TmFOIHZhbHVlcyBpbiB0aGUgY29sdW1uIn0seyJpZCI6MTI1LCJuYW1lIjoibG93ZXJfYm91bmRzIiwicmVxdWlyZWQiOmZhbHNl'
        'LCJ0eXBlIjp7InR5cGUiOiJtYXAiLCJrZXktaWQiOjEyNiwia2V5IjoiaW50IiwidmFsdWUtaWQiOjEyNywidmFsdWUiOiJiaW5h'
        'cnkiLCJ2YWx1ZS1yZXF1aXJlZCI6dHJ1ZX0sImRvYyI6Ik1hcCBvZiBjb2x1bW4gaWQgdG8gbG93ZXIgYm91bmQifSx7ImlkIjox'
        'MjgsIm5hbWUiOiJ1cHBlcl9ib3VuZHMiLCJyZXF1aXJlZCI6ZmFsc2UsInR5cGUiOnsidHlwZSI6Im1hcCIsImtleS1pZCI6MTI5'
        'LCJrZXkiOiJpbnQiLCJ2YWx1ZS1pZCI6MTMwLCJ2YWx1ZSI6ImJpbmFyeSIsInZhbHVlLXJlcXVpcmVkIjp0cnVlfSwiZG9jIjoi'
        'TWFwIG9mIGNvbHVtbiBpZCB0byB1cHBlciBib3VuZCJ9LHsiaWQiOjEzMSwibmFtZSI6ImtleV9tZXRhZGF0YSIsInJlcXVpcmVk'
        'IjpmYWxzZSwidHlwZSI6ImJpbmFyeSIsImRvYyI6IkVuY3J5cHRpb24ga2V5IG1ldGFkYXRhIGJsb2IifSx7ImlkIjoxMzIsIm5h'
        'bWUiOiJzcGxpdF9vZmZzZXRzIiwicmVxdWlyZWQiOmZhbHNlLCJ0eXBlIjp7InR5cGUiOiJsaXN0IiwiZWxlbWVudC1pZCI6MTMz'
        'LCJlbGVtZW50IjoibG9uZyIsImVsZW1lbnQtcmVxdWlyZWQiOnRydWV9LCJkb2MiOiJTcGxpdHRhYmxlIG9mZnNldHMifSx7Imlk'
        'IjoxMzUsIm5hbWUiOiJlcXVhbGl0eV9pZHMiLCJyZXF1aXJlZCI6ZmFsc2UsInR5cGUiOnsidHlwZSI6Imxpc3QiLCJlbGVtZW50'
        'LWlkIjoxMzYsImVsZW1lbnQiOiJpbnQiLCJlbGVtZW50LXJlcXVpcmVkIjp0cnVlfSwiZG9jIjoiRXF1YWxpdHkgY29tcGFyaXNv'
        'biBmaWVsZCBJRHMifSx7ImlkIjoxNDAsIm5hbWUiOiJzb3J0X29yZGVyX2lkIiwicmVxdWlyZWQiOmZhbHNlLCJ0eXBlIjoiaW50'
        'IiwiZG9jIjoiU29ydCBvcmRlciBJRCJ9LHsiaWQiOjE0MywibmFtZSI6InJlZmVyZW5jZWRfZGF0YV9maWxlIiwicmVxdWlyZWQi'
        'OmZhbHNlLCJ0eXBlIjoic3RyaW5nIiwiZG9jIjoiRnVsbHkgcXVhbGlmaWVkIGxvY2F0aW9uIChVUkkgd2l0aCBGUyBzY2hlbWUp'
        'IG9mIGEgZGF0YSBmaWxlIHRoYXQgYWxsIGRlbGV0ZXMgcmVmZXJlbmNlIn1dfX1dfRxwYXJ0aXRpb24tc3BlYwRbXQ5jb250ZW50'
        'CGRhdGEAYdDxfohJIbpjq8w4CNr71gLAAmNiurOle8fzo/cnn2JkYGDYwahfnliUmpFfWpyqn5KalliaUwKkk+NzM/P0UxJLEvUN'
        'QEDXQNfSLDnFwDjNTDfZ0iJZ18TcGCiUYmyka5aUaGFkZphmZG5sBlQGUm2oV5BYVFiaWsIX4BgUGOoawnSOm4mFyY8ljQFIARGI'
        'YmBhYAAzOEDuYJFhEpIN3KXdr8+R1wDk45ZgYGLiAOlkAABh0PF+iEkhumOrzDgI2vvW'
    ),
    'metadata/snap-7283375128891714862-1-9e3f1059-756c-4ec7-8cab-54a68f8107fe.avro': (
        'T2JqAQ4WYXZyby5zY2hlbWHmH3sidHlwZSI6InJlY29yZCIsIm5hbWUiOiJtYW5pZmVzdF9maWxlIiwiZmllbGRzIjpbeyJuYW1l'
        'IjoibWFuaWZlc3RfcGF0aCIsInR5cGUiOiJzdHJpbmciLCJkb2MiOiJMb2NhdGlvbiBVUkkgd2l0aCBGUyBzY2hlbWUiLCJmaWVs'
        'ZC1pZCI6NTAwfSx7Im5hbWUiOiJtYW5pZmVzdF9sZW5ndGgiLCJ0eXBlIjoibG9uZyIsImRvYyI6IlRvdGFsIGZpbGUgc2l6ZSBp'
        'biBieXRlcyIsImZpZWxkLWlkIjo1MDF9LHsibmFtZSI6InBhcnRpdGlvbl9zcGVjX2lkIiwidHlwZSI6ImludCIsImRvYyI6IlNw'
        'ZWMgSUQgdXNlZCB0byB3cml0ZSIsImZpZWxkLWlkIjo1MDJ9LHsibmFtZSI6ImNvbnRlbnQiLCJ0eXBlIjoiaW50IiwiZG9jIjoi'
        'Q29udGVudHMgb2YgdGhlIG1hbmlmZXN0OiAwPWRhdGEsIDE9ZGVsZXRlcyIsImZpZWxkLWlkIjo1MTd9LHsibmFtZSI6InNlcXVl'
        'bmNlX251bWJlciIsInR5cGUiOiJsb25nIiwiZG9jIjoiU2VxdWVuY2UgbnVtYmVyIHdoZW4gdGhlIG1hbmlmZXN0IHdhcyBhZGRl'
        'ZCIsImZpZWxkLWlkIjo1MTV9LHsibmFtZSI6Im1pbl9zZXF1ZW5jZV9udW1iZXIiLCJ0eXBlIjoibG9uZyIsImRvYyI6Ikxvd2Vz'
        'dCBzZXF1ZW5jZSBudW1iZXIgaW4gdGhlIG1hbmlmZXN0IiwiZmllbGQtaWQiOjUxNn0seyJuYW1lIjoiYWRkZWRfc25hcHNob3Rf'
        'aWQiLCJ0eXBlIjoibG9uZyIsImRvYyI6IlNuYXBzaG90IElEIHRoYXQgYWRkZWQgdGhlIG1hbmlmZXN0IiwiZmllbGQtaWQiOjUw'
        'M30seyJuYW1lIjoiYWRkZWRfZmlsZXNfY291bnQiLCJ0eXBlIjoiaW50IiwiZG9jIjoiQWRkZWQgZW50cnkgY291bnQiLCJmaWVs'
        'ZC1pZCI6NTA0fSx7Im5hbWUiOiJleGlzdGluZ19maWxlc19jb3VudCIsInR5cGUiOiJpbnQiLCJkb2MiOiJFeGlzdGluZyBlbnRy'
        'eSBjb3VudCIsImZpZWxkLWlkIjo1MDV9LHsibmFtZSI6ImRlbGV0ZWRfZmlsZXNfY291bnQiLCJ0eXBlIjoiaW50IiwiZG9jIjoi'
        'RGVsZXRlZCBlbnRyeSBjb3VudCIsImZpZWxkLWlkIjo1MDZ9LHsibmFtZSI6ImFkZGVkX3Jvd3NfY291bnQiLCJ0eXBlIjoibG9u'
        'ZyIsImRvYyI6IkFkZGVkIHJvd3MgY291bnQiLCJmaWVsZC1pZCI6NTEyfSx7Im5hbWUiOiJleGlzdGluZ19yb3dzX2NvdW50Iiwi'
        'dHlwZSI6ImxvbmciLCJkb2MiOiJFeGlzdGluZyByb3dzIGNvdW50IiwiZmllbGQtaWQiOjUxM30seyJuYW1lIjoiZGVsZXRlZF9y'
        'b3dzX2NvdW50IiwidHlwZSI6ImxvbmciLCJkb2MiOiJEZWxldGVkIHJvd3MgY291bnQiLCJmaWVsZC1pZCI6NTE0fSx7Im5hbWUi'
        'OiJwYXJ0aXRpb25zIiwidHlwZSI6WyJudWxsIix7InR5cGUiOiJhcnJheSIsIml0ZW1zIjp7InR5cGUiOiJyZWNvcmQiLCJuYW1l'
        'IjoicjUwOCIsImZpZWxkcyI6W3sibmFtZSI6ImNvbnRhaW5zX251bGwiLCJ0eXBlIjoiYm9vbGVhbiIsImRvYyI6IlRydWUgaWYg'
        'YW55IGZpbGUgaGFzIGEgbnVsbCBwYXJ0aXRpb24gdmFsdWUiLCJmaWVsZC1pZCI6NTA5fSx7Im5hbWUiOiJjb250YWluc19uYW4i'
        'LCJ0eXBlIjpbIm51bGwiLCJib29sZWFuIl0sImRvYyI6IlRydWUgaWYgYW55IGZpbGUgaGFzIGEgbmFuIHBhcnRpdGlvbiB2YWx1'
        'ZSIsImRlZmF1bHQiOm51bGwsImZpZWxkLWlkIjo1MTh9LHsibmFtZSI6Imxvd2VyX2JvdW5kIiwidHlwZSI6WyJudWxsIiwiYnl0'
        'ZXMiXSwiZG9jIjoiUGFydGl0aW9uIGxvd2VyIGJvdW5kIGZvciBhbGwgZmlsZXMiLCJkZWZhdWx0IjpudWxsLCJmaWVsZC1pZCI6'
        'NTEwfSx7Im5hbWUiOiJ1cHBlcl9ib3VuZCIsInR5cGUiOlsibnVsbCIsImJ5dGVzIl0sImRvYyI6IlBhcnRpdGlvbiB1cHBlciBi'
        'b3VuZCBmb3IgYWxsIGZpbGVzIiwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjUxMX1dfSwiZWxlbWVudC1pZCI6NTA4fV0sImRv'
        'YyI6IlN1bW1hcnkgZm9yIGVhY2ggcGFydGl0aW9uIiwiZGVmYXVsdCI6bnVsbCwiZmllbGQtaWQiOjUwN30seyJuYW1lIjoia2V5'
        'X21ldGFkYXRhIiwidHlwZSI6WyJudWxsIiwiYnl0ZXMiXSwiZG9jIjoiRW5jcnlwdGlvbiBrZXkgbWV0YWRhdGEgYmxvYiIsImRl'
        'ZmF1bHQiOm51bGwsImZpZWxkLWlkIjo1MTl9XX0UYXZyby5jb2RlYw5kZWZsYXRlFnNuYXBzaG90LWlkJjcyODMzNzUxMjg4OTE3'
        'MTQ4NjIcZm9ybWF0LXZlcnNpb24CMh5zZXF1ZW5jZS1udW1iZXICMRxpY2ViZXJnLnNjaGVtYYYheyJ0eXBlIjoic3RydWN0Iiwi'
        'c2NoZW1hLWlkIjowLCJmaWVsZHMiOlt7ImlkIjo1MDAsIm5hbWUiOiJtYW5pZmVzdF9wYXRoIiwicmVxdWlyZWQiOnRydWUsInR5'
        'cGUiOiJzdHJpbmciLCJkb2MiOiJMb2NhdGlvbiBVUkkgd2l0aCBGUyBzY2hlbWUifSx7ImlkIjo1MDEsIm5hbWUiOiJtYW5pZmVz'
        'dF9sZW5ndGgiLCJyZXF1aXJlZCI6dHJ1ZSwidHlwZSI6ImxvbmciLCJkb2MiOiJUb3RhbCBmaWxlIHNpemUgaW4gYnl0ZXMifSx7'
        'ImlkIjo1MDIsIm5hbWUiOiJwYXJ0aXRpb25fc3BlY19pZCIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoiaW50IiwiZG9jIjoiU3Bl'
        'YyBJRCB1c2VkIHRvIHdyaXRlIn0seyJpZCI6NTE3LCJuYW1lIjoiY29udGVudCIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoiaW50'
        'IiwiZG9jIjoiQ29udGVudHMgb2YgdGhlIG1hbmlmZXN0OiAwPWRhdGEsIDE9ZGVsZXRlcyJ9LHsiaWQiOjUxNSwibmFtZSI6InNl'
        'cXVlbmNlX251bWJlciIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoibG9uZyIsImRvYyI6IlNlcXVlbmNlIG51bWJlciB3aGVuIHRo'
        'ZSBtYW5pZmVzdCB3YXMgYWRkZWQifSx7ImlkIjo1MTYsIm5hbWUiOiJtaW5fc2VxdWVuY2VfbnVtYmVyIiwicmVxdWlyZWQiOnRy'
        'dWUsInR5cGUiOiJsb25nIiwiZG9jIjoiTG93ZXN0IHNlcXVlbmNlIG51bWJlciBpbiB0aGUgbWFuaWZlc3QifSx7ImlkIjo1MDMs'
        'Im5hbWUiOiJhZGRlZF9zbmFwc2hvdF9pZCIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoibG9uZyIsImRvYyI6IlNuYXBzaG90IElE'
        'IHRoYXQgYWRkZWQgdGhlIG1hbmlmZXN0In0seyJpZCI6NTA0LCJuYW1lIjoiYWRkZWRfZmlsZXNfY291bnQiLCJyZXF1aXJlZCI6'
        'dHJ1ZSwidHlwZSI6ImludCIsImRvYyI6IkFkZGVkIGVudHJ5IGNvdW50In0seyJpZCI6NTA1LCJuYW1lIjoiZXhpc3RpbmdfZmls'
        'ZXNfY291bnQiLCJyZXF1aXJlZCI6dHJ1ZSwidHlwZSI6ImludCIsImRvYyI6IkV4aXN0aW5nIGVudHJ5IGNvdW50In0seyJpZCI6'
        'NTA2LCJuYW1lIjoiZGVsZXRlZF9maWxlc19jb3VudCIsInJlcXVpcmVkIjp0cnVlLCJ0eXBlIjoiaW50IiwiZG9jIjoiRGVsZXRl'
        'ZCBlbnRyeSBjb3VudCJ9LHsiaWQiOjUxMiwibmFtZSI6ImFkZGVkX3Jvd3NfY291bnQiLCJyZXF1aXJlZCI6dHJ1ZSwidHlwZSI6'
        'ImxvbmciLCJkb2MiOiJBZGRlZCByb3dzIGNvdW50In0seyJpZCI6NTEzLCJuYW1lIjoiZXhpc3Rpbmdfcm93c19jb3VudCIsInJl'
        'cXVpcmVkIjp0cnVlLCJ0eXBlIjoibG9uZyIsImRvYyI6IkV4aXN0aW5nIHJvd3MgY291bnQifSx7ImlkIjo1MTQsIm5hbWUiOiJk'
        'ZWxldGVkX3Jvd3NfY291bnQiLCJyZXF1aXJlZCI6dHJ1ZSwidHlwZSI6ImxvbmciLCJkb2MiOiJEZWxldGVkIHJvd3MgY291bnQi'
        'fSx7ImlkIjo1MDcsIm5hbWUiOiJwYXJ0aXRpb25zIiwicmVxdWlyZWQiOmZhbHNlLCJ0eXBlIjp7InR5cGUiOiJsaXN0IiwiZWxl'
        'bWVudC1pZCI6NTA4LCJlbGVtZW50Ijp7InR5cGUiOiJzdHJ1Y3QiLCJmaWVsZHMiOlt7ImlkIjo1MDksIm5hbWUiOiJjb250YWlu'
        'c19udWxsIiwicmVxdWlyZWQiOnRydWUsInR5cGUiOiJib29sZWFuIiwiZG9jIjoiVHJ1ZSBpZiBhbnkgZmlsZSBoYXMgYSBudWxs'
        'IHBhcnRpdGlvbiB2YWx1ZSJ9LHsiaWQiOjUxOCwibmFtZSI6ImNvbnRhaW5zX25hbiIsInJlcXVpcmVkIjpmYWxzZSwidHlwZSI6'
        'ImJvb2xlYW4iLCJkb2MiOiJUcnVlIGlmIGFueSBmaWxlIGhhcyBhIG5hbiBwYXJ0aXRpb24gdmFsdWUifSx7ImlkIjo1MTAsIm5h'
        'bWUiOiJsb3dlcl9ib3VuZCIsInJlcXVpcmVkIjpmYWxzZSwidHlwZSI6ImJpbmFyeSIsImRvYyI6IlBhcnRpdGlvbiBsb3dlciBi'
        'b3VuZCBmb3IgYWxsIGZpbGVzIn0seyJpZCI6NTExLCJuYW1lIjoidXBwZXJfYm91bmQiLCJyZXF1aXJlZCI6ZmFsc2UsInR5cGUi'
        'OiJiaW5hcnkiLCJkb2MiOiJQYXJ0aXRpb24gdXBwZXIgYm91bmQgZm9yIGFsbCBmaWxlcyJ9XX0sImVsZW1lbnQtcmVxdWlyZWQi'
        'OnRydWV9LCJkb2MiOiJTdW1tYXJ5IGZvciBlYWNoIHBhcnRpdGlvbiJ9LHsiaWQiOjUxOSwibmFtZSI6ImtleV9tZXRhZGF0YSIs'
        'InJlcXVpcmVkIjpmYWxzZSwidHlwZSI6ImJpbmFyeSIsImRvYyI6IkVuY3J5cHRpb24ga2V5IG1ldGFkYXRhIGJsb2IifV19JHBh'
        'cmVudC1zbmFwc2hvdC1pZAhudWxsAHbQhPDcnIUyPhf0Tst6SmgC0AFbwKhfnliUmpFfWpyqn5KalliaUwKkk+NzM/P0c1NLElMS'
        'SxL1LVON0wwNTC11zU3NknVNUpPNdS2SE5N0TU0SzSzSLAwNzNNSdXMN9BLLivKf5DIwMDHd2dK94/nR+5NPMTIBuWAEAHbQhPDc'
        'nIUyPhf0Tst6Smg='
    ),
}

text_files = {
    'metadata/v1.metadata.json': '{\n  "format-version" : 2,\n  "table-uuid" : "ff9abdad-1a15-45d6-afff-60e974178bab",\n  "location" : "/warehouse/default/dec_min",\n  "last-sequence-number" : 0,\n  "last-updated-ms" : 1786764090440,\n  "last-column-id" : 2,\n  "current-schema-id" : 0,\n  "schemas" : [ {\n    "type" : "struct",\n    "schema-id" : 0,\n    "fields" : [ {\n      "id" : 1,\n      "name" : "id",\n      "required" : false,\n      "type" : "int"\n    }, {\n      "id" : 2,\n      "name" : "d",\n      "required" : false,\n      "type" : "decimal(38, 30)"\n    } ]\n  } ],\n  "default-spec-id" : 0,\n  "partition-specs" : [ {\n    "spec-id" : 0,\n    "fields" : [ ]\n  } ],\n  "last-partition-id" : 999,\n  "default-sort-order-id" : 0,\n  "sort-orders" : [ {\n    "order-id" : 0,\n    "fields" : [ ]\n  } ],\n  "properties" : {\n    "owner" : "root",\n    "write.format.default" : "Parquet",\n    "write.parquet.compression-codec" : "zstd"\n  },\n  "current-snapshot-id" : -1,\n  "refs" : { },\n  "snapshots" : [ ],\n  "statistics" : [ ],\n  "partition-statistics" : [ ],\n  "snapshot-log" : [ ],\n  "metadata-log" : [ ]\n}',
    'metadata/v2.metadata.json': '{\n  "format-version" : 2,\n  "table-uuid" : "ff9abdad-1a15-45d6-afff-60e974178bab",\n  "location" : "/warehouse/default/dec_min",\n  "last-sequence-number" : 1,\n  "last-updated-ms" : 1786764092225,\n  "last-column-id" : 2,\n  "current-schema-id" : 0,\n  "schemas" : [ {\n    "type" : "struct",\n    "schema-id" : 0,\n    "fields" : [ {\n      "id" : 1,\n      "name" : "id",\n      "required" : false,\n      "type" : "int"\n    }, {\n      "id" : 2,\n      "name" : "d",\n      "required" : false,\n      "type" : "decimal(38, 30)"\n    } ]\n  } ],\n  "default-spec-id" : 0,\n  "partition-specs" : [ {\n    "spec-id" : 0,\n    "fields" : [ ]\n  } ],\n  "last-partition-id" : 999,\n  "default-sort-order-id" : 0,\n  "sort-orders" : [ {\n    "order-id" : 0,\n    "fields" : [ ]\n  } ],\n  "properties" : {\n    "owner" : "root",\n    "write.format.default" : "Parquet",\n    "write.parquet.compression-codec" : "zstd"\n  },\n  "current-snapshot-id" : 7283375128891714862,\n  "refs" : {\n    "main" : {\n      "snapshot-id" : 7283375128891714862,\n      "type" : "branch"\n    }\n  },\n  "snapshots" : [ {\n    "sequence-number" : 1,\n    "snapshot-id" : 7283375128891714862,\n    "timestamp-ms" : 1786764092225,\n    "summary" : {\n      "operation" : "append",\n      "spark.app.id" : "local-1786764088572",\n      "added-data-files" : "1",\n      "added-records" : "1",\n      "added-files-size" : "743",\n      "changed-partition-count" : "1",\n      "total-records" : "1",\n      "total-files-size" : "743",\n      "total-data-files" : "1",\n      "total-delete-files" : "0",\n      "total-position-deletes" : "0",\n      "total-equality-deletes" : "0",\n      "engine-version" : "3.5.5",\n      "app-id" : "local-1786764088572",\n      "engine-name" : "spark",\n      "iceberg-version" : "Apache Iceberg 1.8.1 (commit 9ce0fcf0af7becf25ad9fc996c3bad2afdcfd33d)"\n    },\n    "manifest-list" : "/warehouse/default/dec_min/metadata/snap-7283375128891714862-1-9e3f1059-756c-4ec7-8cab-54a68f8107fe.avro",\n    "schema-id" : 0\n  } ],\n  "statistics" : [ ],\n  "partition-statistics" : [ ],\n  "snapshot-log" : [ {\n    "timestamp-ms" : 1786764092225,\n    "snapshot-id" : 7283375128891714862\n  } ],\n  "metadata-log" : [ {\n    "timestamp-ms" : 1786764090440,\n    "metadata-file" : "/warehouse/default/dec_min/metadata/v1.metadata.json"\n  } ]\n}',
    'metadata/version-hint.text': '2',
}

for relative_path, encoded in binary_files.items():
    destination = table_path / relative_path
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(base64.b64decode(encoded))

for relative_path, contents in text_files.items():
    destination = table_path / relative_path
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(contents)
