-- Parse and format SYSTEM DROP/RESET SERIAL ID without talking to Keeper.

EXPLAIN SYNTAX SYSTEM DROP SERIAL ID 'foo';
EXPLAIN SYNTAX SYSTEM DROP SERIAL ID IF EXISTS 'foo';
EXPLAIN SYNTAX SYSTEM DROP SERIAL ID foo;
EXPLAIN SYNTAX SYSTEM RESET SERIAL ID 'foo';
EXPLAIN SYNTAX SYSTEM RESET SERIAL ID 'foo' TO 10;
EXPLAIN SYNTAX SYSTEM RESET SERIAL ID foo;

-- Both user form (ON CLUSTER at the end) and the formatted/DDL form (after the type).
EXPLAIN SYNTAX SYSTEM DROP SERIAL ID 'foo' ON CLUSTER my_cluster;
EXPLAIN SYNTAX SYSTEM DROP SERIAL ID ON CLUSTER my_cluster 'foo';
EXPLAIN SYNTAX SYSTEM DROP SERIAL ID IF EXISTS 'foo' ON CLUSTER my_cluster;
EXPLAIN SYNTAX SYSTEM RESET SERIAL ID 'foo' ON CLUSTER my_cluster;
EXPLAIN SYNTAX SYSTEM RESET SERIAL ID 'foo' TO 10 ON CLUSTER my_cluster;
