SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1 FOR INTERVAL 1 HOUR MAX queries = 100 TO u');
SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1 FOR INTERVAL 1 HOUR MAX queries = 100 TO u') = formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1, FOR INTERVAL 1 HOUR MAX queries = 100 TO u');

SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1 KEYED BY user_name FOR INTERVAL 1 HOUR MAX queries = 100');
SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1 FOR INTERVAL 1 HOUR MAX queries = 100 FOR INTERVAL 1 DAY MAX queries = 1000');
SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE TRACKING ONLY FOR INTERVAL 1 HOUR MAX queries = 5');
SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE NO LIMITS FOR INTERVAL 1 HOUR MAX queries = 5');
SELECT formatQuery('CREATE QUOTA q FOR RANDOMIZED INTERVAL 1 MINUTE MAX queries = 1 FOR INTERVAL 1 HOUR MAX queries = 5');
SELECT formatQuery('ALTER QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 7 FOR INTERVAL 1 HOUR MAX queries = 8');
SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1 FOR INTERVAL 1 MINUTE MAX errors = 5');

SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1');
SELECT formatQuery('CREATE QUOTA q KEYED BY user_name FOR INTERVAL 1 MINUTE MAX queries = 1, FOR INTERVAL 1 HOUR MAX queries = 2, FOR INTERVAL 1 DAY MAX queries = 3');
SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE NO LIMITS, FOR INTERVAL 1 HOUR TRACKING ONLY, FOR RANDOMIZED INTERVAL 1 DAY MAX queries = 3');
SELECT formatQuery('ALTER QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 7, FOR INTERVAL 1 HOUR MAX queries = 8');

SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1, TO u'); -- { serverError SYNTAX_ERROR }
SELECT formatQuery('CREATE QUOTA q FOR INTERVAL 1 MINUTE MAX queries = 1 errors = 2'); -- { serverError SYNTAX_ERROR }
