-- Conformance queries derived from the scalar-function tests of Presto
-- (https://github.com/prestodb/presto, presto-main-base operator/scalar tests, Apache License 2.0),
-- covering the shared Presto/Trino function surface.
-- Expected results verified against the assertions of the original tests.

SET allow_experimental_trino_dialect = 1;
SET dialect = 'trino';


SELECT '-- AbstractTestRegexpFunctions';
SELECT REGEXP_LIKE('Stephen', 'Ste(v|ph)en');
SELECT REGEXP_LIKE('Stevens', 'Ste(v|ph)en');
SELECT REGEXP_LIKE('Stephen', '^Ste(v|ph)en$');
SELECT REGEXP_LIKE('Stevens', '^Ste(v|ph)en$');
SELECT REGEXP_LIKE('hello world', '[a-z]');
SELECT REGEXP_LIKE('hello world', '.*hello world.*');
SELECT REGEXP_LIKE('Hello', '^[a-z]+$');
SELECT REGEXP_LIKE('Hello', '^(?i)[a-z]+$');
SELECT REGEXP_LIKE('Hello', '^[a-zA-Z]+$');
SELECT REGEXP_LIKE('test', 'test\b');
SELECT REGEXP_LIKE('ala', CHAR 'ala  ');
SELECT REGEXP_LIKE('ala  ', CHAR 'ala  ');
SELECT REGEXP_REPLACE('fun stuff.', '[a-z]');
SELECT REGEXP_REPLACE('fun stuff.', '[a-z]', '*');
SELECT REGEXP_REPLACE('xxx xxx xxx', 'x', 'x');
SELECT REGEXP_REPLACE('xxx xxx xxx', 'x', '\x');
SELECT REGEXP_REPLACE('xxx xxx xxx', 'x', '$0');
SELECT REGEXP_REPLACE('xxx', 'x', '$05');
SELECT REGEXP_REPLACE('123456789', '(1)(2)(3)(4)(5)(6)(7)(8)(9)', '$10');
SELECT REGEXP_REPLACE('1234567890', '(1)(2)(3)(4)(5)(6)(7)(8)(9)(0)', '$11');
SELECT REGEXP_REPLACE('1234567890', '(1)(2)(3)(4)(5)(6)(7)(8)(9)(0)', '$1a');
SELECT REGEXP_REPLACE(VARCHAR 'x', '.*', 'xxxxx');
SELECT REGEXP_EXTRACT('Hello world bye', '\b[a-z]([a-z]*)', 1);

SELECT '-- TestArrayExceptFunction';
SELECT array_except(ARRAY[NULL], NULL);
SELECT array_except(NULL, NULL);
SELECT array_except(NULL, ARRAY[NULL]);

SELECT '-- TestArrayIntersectFunction';
SELECT ARRAY_INTERSECT(NULL, NULL);
SELECT ARRAY_INTERSECT(ARRAY[NULL], NULL);
SELECT ARRAY_INTERSECT(NULL, ARRAY[NULL]);
SELECT array_intersect(null);

SELECT '-- TestArrayMatchFunctions';
SELECT all_match(ARRAY [5, 7, 9], x -> x % 2 = 1);
SELECT all_match(ARRAY [true, false, true], x -> x);
SELECT all_match(ARRAY ['abc', 'ade', 'afg'], x -> substr(x, 1, 1) = 'a');
SELECT all_match(ARRAY [], x -> true);
SELECT all_match(ARRAY [true, false, NULL], x -> x);
SELECT all_match(ARRAY [NULL, NULL, NULL], x -> x IS NULL);
SELECT all_match(ARRAY [MAP(ARRAY[1,2], ARRAY[3,4]), MAP(ARRAY[1,2,3], ARRAY[3,4,5])], x -> cardinality(x) > 1);
SELECT any_match(ARRAY [5, 8, 10], x -> x % 2 = 1);
SELECT any_match(ARRAY [false, false, false], x -> x);
SELECT any_match(ARRAY ['abc', 'def', 'ghi'], x -> substr(x, 1, 1) = 'a');
SELECT any_match(ARRAY [], x -> true);
SELECT any_match(ARRAY [true, false, NULL], x -> x);
SELECT any_match(ARRAY [true, false, NULL], x -> x IS NULL);
SELECT any_match(ARRAY [MAP(ARRAY[1,2], ARRAY[3,4]), MAP(ARRAY[1,2,3], ARRAY[3,4,5])], x -> cardinality(x) > 4);
SELECT none_match(ARRAY [5, 8, 10], x -> x % 2 = 1);
SELECT none_match(ARRAY [false, false, false], x -> x);
SELECT none_match(ARRAY ['abc', 'def', 'ghi'], x -> substr(x, 1, 1) = 'a');
SELECT none_match(ARRAY [], x -> true);
SELECT none_match(ARRAY [true, false, NULL], x -> x);
SELECT none_match(ARRAY [true, false, NULL], x -> x IS NULL);
SELECT none_match(ARRAY [MAP(ARRAY[1,2], ARRAY[3,4]), MAP(ARRAY[1,2,3], ARRAY[3,4,5])], x -> cardinality(x) > 4);

SELECT '-- TestArrayReduceFunction';
SELECT reduce(ARRAY [5, 20, 50], CAST (0 AS BIGINT), (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [5 + RANDOM(1), 20, 50], CAST (0 AS BIGINT), (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [5, 6, 10, 20], 0.0E0, (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [NULL, NULL, NULL], CAST (0 AS BIGINT), (s, x) -> coalesce(x, 1) + s, s -> s);
SELECT reduce(ARRAY [5, NULL, 50], CAST (0 AS BIGINT), (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [5, NULL, 50], CAST (0 AS BIGINT), (s, x) -> coalesce(x, 0) + s, s -> s);
SELECT reduce(ARRAY [NULL], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);
SELECT reduce(ARRAY [NULL, NULL, NULL], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);
SELECT reduce(ARRAY [NULL, 6, 10, NULL, 8], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);
SELECT reduce(ARRAY [5, NULL, 6, 10, NULL, 8], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);

SELECT '-- TestBitwiseFunctions';
SELECT bit_count(0, 64);
SELECT bit_count(7, 64);
SELECT bit_count(24, 64);
SELECT bit_count(-8, 64);
SELECT bit_count(0, 32);
SELECT bit_count(CAST (-8 AS SMALLINT), 6);
SELECT bit_count(7, 32);
SELECT bit_count(24, 32);
SELECT bit_count(-8, 32);
SELECT bit_count(1152921504598458367, 62);
SELECT bit_count(-1, 62);
SELECT bit_count(33554132, 26);
SELECT bit_count(-1, 26);
SELECT bitwise_and(0, -1);
SELECT bitwise_or(0, -1);
SELECT bitwise_xor(0, -1);
SELECT bitwise_left_shift(TINYINT '-128', 1);
SELECT bitwise_left_shift(TINYINT '-7', 64);
SELECT bitwise_left_shift(TINYINT '-128', 0);
SELECT bitwise_left_shift(SMALLINT '-32768', 1);
SELECT bitwise_left_shift(SMALLINT '-7', 64);
SELECT bitwise_left_shift(SMALLINT '-32768', 0);
SELECT bitwise_left_shift(INTEGER '-2147483648', 1);
SELECT bitwise_left_shift(INTEGER '-7', 64);
SELECT bitwise_left_shift(INTEGER '-2147483648', 0);
SELECT bitwise_left_shift(BIGINT '-7', 64);
SELECT bitwise_right_shift(TINYINT '-7', 2);
SELECT bitwise_right_shift(TINYINT '-7', 64);
SELECT bitwise_right_shift(SMALLINT '-7', 2);
SELECT bitwise_right_shift(SMALLINT '-7', 64);
SELECT bitwise_right_shift(INTEGER '-7', 2);
SELECT bitwise_right_shift(INTEGER '-7', 64);
SELECT bitwise_right_shift(BIGINT '-7', 64);
SELECT bitwise_right_shift_arithmetic(TINYINT '7', 64);
SELECT bitwise_right_shift_arithmetic(TINYINT '-128', 0);
SELECT bitwise_right_shift_arithmetic(SMALLINT '7', 64);
SELECT bitwise_right_shift_arithmetic(SMALLINT '-32768', 0);
SELECT bitwise_right_shift_arithmetic(INTEGER '7', 64);
SELECT bitwise_right_shift_arithmetic(INTEGER '-2147483648', 0);
SELECT bitwise_right_shift_arithmetic(BIGINT '7', 64);

SELECT '-- TestConditions';
SELECT '_monkey_' like 'X_monkeyX_' escape 'X';
SELECT 'monkey' like 'monkey';
SELECT 'monkey' like 'mon%';
SELECT 'monkey' like 'mon_ey';
SELECT 'monkey' like 'm____y';
SELECT 'monkey' like 'dain';
SELECT 'monkey' like 'key';
SELECT '_monkey_' like '\_monkey\_';
SELECT '_monkey_' like '_monkey_';
SELECT null like 'monkey';
SELECT 'monkey' like null;
SELECT '_monkey_' not like 'X_monkeyX_' escape 'X';
SELECT 'monkey' not like 'monkey';
SELECT 'monkey' not like 'mon%';
SELECT 'monkey' not like 'mon_ey';
SELECT 'monkey' not like 'm____y';
SELECT 'monkey' not like 'dain';
SELECT 'monkey' not like 'key';
SELECT '_monkey_' not like '\_monkey\_';
SELECT '_monkey_' not like '_monkey_';
SELECT null not like 'monkey';
SELECT 'monkey' not like null;
SELECT '你好a世界' like '你好%';
SELECT '你好a世界' like '你好a%';
SELECT '你好a世界' like '%世界';
SELECT '你好a世界' like '%好a世%';
SELECT '你好a世界' not like '你好b%';
SELECT '你好a世界' not like null;
SELECT NULL IS DISTINCT FROM NULL;
SELECT NULL IS DISTINCT FROM 1;
SELECT 1 IS DISTINCT FROM NULL;
SELECT 1 IS DISTINCT FROM 1;
SELECT 1 IS DISTINCT FROM 2;
SELECT NULL IS NOT DISTINCT FROM NULL;
SELECT NULL IS NOT DISTINCT FROM 1;
SELECT 1 IS NOT DISTINCT FROM NULL;
SELECT 1 IS NOT DISTINCT FROM 1;
SELECT 1 IS NOT DISTINCT FROM 2;
SELECT 3 between 2 and 4;
SELECT 3 between 3 and 3;
SELECT 3 between 2 and 3;
SELECT 3 between 3 and 4;
SELECT 3 between 4 and 2;
SELECT 2 between 3 and 4;
SELECT 5 between 3 and 4;
SELECT null between 2 and 4;
SELECT 3 between null and 4;
SELECT 3 between 2 and null;
SELECT 3 between 3 and 4000000000;
SELECT 5 between 3 and 4000000000;
SELECT 3 between BIGINT '3' and 4;
SELECT BIGINT '3' between 3 and 4;
SELECT 'c' between 'b' and 'd';
SELECT 'c' between 'c' and 'c';
SELECT 'c' between 'b' and 'c';
SELECT 'c' between 'c' and 'd';
SELECT 'c' between 'd' and 'b';
SELECT 'b' between 'c' and 'd';
SELECT 'e' between 'c' and 'd';
SELECT null between 'b' and 'd';
SELECT 'c' between null and 'd';
SELECT 'c' between 'b' and null;
SELECT 3 not between 2 and 4;
SELECT 3 not between 3 and 3;
SELECT 3 not between 2 and 3;
SELECT 3 not between 3 and 4;
SELECT 3 not between 4 and 2;
SELECT 2 not between 3 and 4;
SELECT 5 not between 3 and 4;
SELECT null not between 2 and 4;
SELECT 3 not between null and 4;
SELECT 3 not between 2 and null;
SELECT 'c' not between 'b' and 'd';
SELECT 'c' not between 'c' and 'c';
SELECT 'c' not between 'b' and 'c';
SELECT 'c' not between 'c' and 'd';
SELECT 'c' not between 'd' and 'b';
SELECT 'b' not between 'c' and 'd';
SELECT 'e' not between 'c' and 'd';
SELECT null not between 'b' and 'd';
SELECT 'c' not between null and 'd';
SELECT 'c' not between 'b' and null;
SELECT 3 in (2, 4, 3, 5);
SELECT 3 not in (2, 4, 3, 5);
SELECT 3 in (2, 4, 9, 5);
SELECT 3 in (2, null, 3, 5);
SELECT 'foo' in ('bar', 'baz', 'foo', 'blah');
SELECT 'foo' in ('bar', 'baz', 'buz', 'blah');
SELECT 'foo' in ('bar', null, 'foo', 'blah');
SELECT (null in (2, null, 3, 5)) is null;
SELECT (null not in (2, null, 3, 5)) is null;
SELECT case when true then 33 end;
SELECT case when true then BIGINT '33' end;
SELECT case when false then 1 else 33 end;
SELECT case when false then 10000000000 else 33 end;
SELECT case when false then 1 when false then 1 when true then 33 else 1 end;
SELECT case when false then BIGINT '1' when false then 1 when true then 33 else 1 end;
SELECT case when false then 10000000000 when false then 1 when true then 33 else 1 end;
SELECT case when false then 1 end;
SELECT case when true then null else 'foo' end;
SELECT case when null then 1 when true then 33 end;
SELECT case when null then 10000000000 when true then 33 end;
SELECT case when false then 1.0E0 when true then 33 end;
SELECT case when false then 1.1 when true then 33.0E0 end;
SELECT case true when true then cast(null as varchar) else 'foo' end;
SELECT case true when true then 33 end;
SELECT case true when true then BIGINT '33' end;
SELECT case true when false then 1 else 33 end;
SELECT case true when false then 10000000000 else 33 end;
SELECT case true when false then 1 when false then 1 when true then 33 else 1 end;
SELECT case true when false then 1 end;
SELECT case true when true then null else 'foo' end;
SELECT case true when null then 10000000000 when true then 33 end;
SELECT case true when null then 1 when true then 33 end;
SELECT case null when true then 1 else 33 end;
SELECT case true when false then 1.0E0 when true then 33 end;
SELECT case true when false then 1.1 when true then 33.0E0 end;

SELECT '-- TestDateTimeFunctionsBase';
SELECT year_of_week(DATE '2001-08-22');
SELECT yow(DATE '2001-08-22');
SELECT year_of_week(DATE '2005-01-02');
SELECT year_of_week(DATE '2008-12-28');
SELECT year_of_week(DATE '2008-12-29');
SELECT year_of_week(DATE '2009-12-31');
SELECT year_of_week(DATE '2010-01-03');
SELECT year_of_week(TIMESTAMP '2001-08-22 03:04:05.321 +07:09');
SELECT year_of_week(TIMESTAMP '2010-01-03 03:04:05.321');
SELECT extract(quarter FROM DATE '2001-01-01');
SELECT extract(quarter FROM DATE '2001-03-31');
SELECT extract(quarter FROM DATE '2001-04-01');
SELECT extract(quarter FROM DATE '2001-06-30');
SELECT extract(quarter FROM DATE '2001-07-01');
SELECT extract(quarter FROM DATE '2001-09-30');
SELECT extract(quarter FROM DATE '2001-10-01');
SELECT extract(quarter FROM DATE '2001-12-31');
SELECT extract(quarter FROM TIMESTAMP '2001-01-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-03-31 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-04-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-06-30 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-07-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-09-30 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-10-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-12-31 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-03-31 23:59:59.999 +06:00');
SELECT extract(quarter FROM TIMESTAMP '2001-06-30 23:59:59.999 +06:00');
SELECT extract(quarter FROM TIMESTAMP '2001-09-30 23:59:59.999 +06:00');
SELECT extract(quarter FROM TIMESTAMP '2001-12-31 23:59:59.999 +06:00');
SELECT extract(second FROM INTERVAL '5' SECOND);
SELECT extract(minute FROM INTERVAL '4' MINUTE);
SELECT extract(hour FROM INTERVAL '3' HOUR);
SELECT extract(day FROM INTERVAL '2' DAY);
SELECT extract(month FROM INTERVAL '3' MONTH);
SELECT extract(year FROM INTERVAL '2' YEAR);
SELECT date_format(TIMESTAMP '2001-01-09 13:04:05.32', '%f');
SELECT date_format(TIMESTAMP '2001-01-09 00:04:05.32', '%k');
SELECT date '2012-12-31';
SELECT timestamp '1234-05-06 23:23:23.233';

SELECT '-- TestJsonFunctions';
SELECT IS_JSON_SCALAR(null);
SELECT IS_JSON_SCALAR(JSON 'null');
SELECT IS_JSON_SCALAR(JSON 'true');
SELECT IS_JSON_SCALAR(JSON '1');
SELECT IS_JSON_SCALAR(JSON '"str"');
SELECT IS_JSON_SCALAR('null');
SELECT IS_JSON_SCALAR('true');
SELECT IS_JSON_SCALAR('1');
SELECT IS_JSON_SCALAR('"str"');
SELECT IS_JSON_SCALAR(JSON '[1, 2, 3]');
SELECT IS_JSON_SCALAR(JSON '{"a": 1, "b": 2}');
SELECT IS_JSON_SCALAR('[1, 2, 3]');
SELECT IS_JSON_SCALAR('{"a": 1, "b": 2}');
SELECT JSON_ARRAY_LENGTH('[]');
SELECT JSON_ARRAY_LENGTH('[1]');
SELECT JSON_ARRAY_LENGTH('[1, "foo", null]');
SELECT JSON_ARRAY_LENGTH('[2, 4, {"a": [8, 9]}, [], [5], 4]');
SELECT JSON_ARRAY_LENGTH(null);
SELECT JSON_ARRAY_CONTAINS('[]', true);
SELECT JSON_ARRAY_CONTAINS('[true]', true);
SELECT JSON_ARRAY_CONTAINS('[false]', false);
SELECT JSON_ARRAY_CONTAINS('[true, false]', false);
SELECT JSON_ARRAY_CONTAINS('[false, true]', true);
SELECT JSON_ARRAY_CONTAINS('[[true]]', true);
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], false]', false);
SELECT JSON_ARRAY_CONTAINS(JSON '[]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[true]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[false]', false);
SELECT JSON_ARRAY_CONTAINS(JSON '[true, false]', false);
SELECT JSON_ARRAY_CONTAINS(JSON '[false, true]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[[true]]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], false]', false);
SELECT JSON_ARRAY_CONTAINS('[]', 1);
SELECT JSON_ARRAY_CONTAINS('[3]', 3);
SELECT JSON_ARRAY_CONTAINS('[-4]', -4);
SELECT JSON_ARRAY_CONTAINS('[[2]]', 2);
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], 6]', 6);
SELECT JSON_ARRAY_CONTAINS('[92233720368547758071]', -9);
SELECT JSON_ARRAY_CONTAINS(JSON '[]', 1);
SELECT JSON_ARRAY_CONTAINS(JSON '[3]', 3);
SELECT JSON_ARRAY_CONTAINS(JSON '[-4]', -4);
SELECT JSON_ARRAY_CONTAINS(JSON '[[2]]', 2);
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], 6]', 6);
SELECT JSON_ARRAY_CONTAINS(JSON '[92233720368547758071]', -9);
SELECT JSON_ARRAY_CONTAINS('[1.5]', 1.5);
SELECT JSON_ARRAY_CONTAINS('[-9.5]', -9.5);
SELECT JSON_ARRAY_CONTAINS('[[2.5]]', 2.5);
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], 6.1]', 6.1);
SELECT JSON_ARRAY_CONTAINS('[9.6E400]', 4.2);
SELECT JSON_ARRAY_CONTAINS(JSON '[1.5]', 1.5);
SELECT JSON_ARRAY_CONTAINS(JSON '[-9.5]', -9.5);
SELECT JSON_ARRAY_CONTAINS(JSON '[[2.5]]', 2.5);
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], 6.1]', 6.1);
SELECT JSON_ARRAY_CONTAINS(JSON '[9.6E400]', 4.2);
SELECT JSON_ARRAY_CONTAINS('[]', 'x');
SELECT JSON_ARRAY_CONTAINS('["foo"]', 'foo');
SELECT JSON_ARRAY_CONTAINS('["8"]', '8');
SELECT JSON_ARRAY_CONTAINS('[1, "foo", null]', 'foo');
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], "6"]', '6');
SELECT JSON_ARRAY_CONTAINS(JSON '[]', 'x');
SELECT JSON_ARRAY_CONTAINS(JSON '["foo"]', 'foo');
SELECT JSON_ARRAY_CONTAINS(JSON '["8"]', '8');
SELECT JSON_ARRAY_CONTAINS(JSON '[1, "foo", null]', 'foo');
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], "6"]', '6');
SELECT JSON_ARRAY_CONTAINS('[""]', '');
SELECT JSON_ARRAY_CONTAINS('[""]', 'x');
SELECT JSON_ARRAY_GET('["jhfa", null]', 1);
SELECT JSON_ARRAY_GET(JSON '["jhfa", null]', 1);
SELECT JSON_ARRAY_GET('[null]', 0);
SELECT JSON_ARRAY_GET('[3.14, null]', 1);
SELECT JSON_ARRAY_GET(JSON '[3.14, null]', 1);
SELECT JSON_ARRAY_GET('[true, null]', 1);
SELECT JSON_ARRAY_GET(JSON '[true, null]', 1);

SELECT '-- TestMathFunctions';
SELECT abs(TINYINT'123');
SELECT abs(TINYINT'-123');
SELECT abs(CAST(NULL AS TINYINT));
SELECT abs(SMALLINT'123');
SELECT abs(SMALLINT'-123');
SELECT abs(CAST(NULL AS SMALLINT));
SELECT abs(123);
SELECT abs(-123);
SELECT abs(CAST(NULL AS INTEGER));
SELECT abs(BIGINT '123');
SELECT abs(BIGINT '-123');
SELECT abs(12300000000);
SELECT abs(-12300000000);
SELECT abs(CAST(NULL AS BIGINT));
SELECT abs(123.0E0);
SELECT abs(-123.0E0);
SELECT abs(123.45E0);
SELECT abs(-123.45E0);
SELECT abs(CAST(NULL AS DOUBLE));
SELECT abs(REAL '-754.1985');
SELECT abs(CAST(NULL AS DECIMAL(1,0)));
SELECT acos(NULL);
SELECT asin(NULL);
SELECT atan(NULL);
SELECT atan2(NULL, NULL);
SELECT atan2(1.0E0, NULL);
SELECT atan2(NULL, 1.0E0);
SELECT cbrt(NULL);
SELECT ceil(TINYINT'123');
SELECT ceil(TINYINT'-123');
SELECT ceil(CAST(NULL AS TINYINT));
SELECT ceil(SMALLINT'123');
SELECT ceil(SMALLINT'-123');
SELECT ceil(CAST(NULL AS SMALLINT));
SELECT ceil(123);
SELECT ceil(-123);
SELECT ceil(CAST(NULL AS INTEGER));
SELECT ceil(BIGINT '123');
SELECT ceil(BIGINT '-123');
SELECT ceil(12300000000);
SELECT ceil(-12300000000);
SELECT ceil(CAST(NULL as BIGINT));
SELECT ceil(123.0E0);
SELECT ceil(-123.0E0);
SELECT ceil(123.45E0);
SELECT ceil(-123.45E0);
SELECT ceil(CAST(NULL as DOUBLE));
SELECT ceil(REAL '123.0');
SELECT ceil(REAL '-123.0');
SELECT ceil(REAL '123.45');
SELECT ceil(REAL '-123.45');
SELECT ceiling(12300000000);
SELECT ceiling(-12300000000);
SELECT ceiling(CAST(NULL AS BIGINT));
SELECT ceiling(123.0E0);
SELECT ceiling(-123.0E0);
SELECT ceiling(123.45E0);
SELECT ceiling(-123.45E0);
SELECT ceiling(REAL '123.0');
SELECT ceiling(REAL '-123.0');
SELECT ceiling(REAL '123.45');
SELECT ceiling(REAL '-123.45');
SELECT ceiling(CAST(NULL AS DOUBLE));
SELECT ceiling(CAST(NULL AS REAL));
SELECT ceiling(CAST(NULL AS DECIMAL(1,0)));
SELECT ceiling(CAST(NULL AS DECIMAL(25,5)));
SELECT truncate(17.18E0);
SELECT truncate(-17.18E0);
SELECT truncate(17.88E0);
SELECT truncate(-17.88E0);
SELECT truncate(REAL '17.18');
SELECT truncate(REAL '-17.18');
SELECT truncate(REAL '17.88');
SELECT truncate(REAL '-17.88');
SELECT truncate(CAST(NULL AS DOUBLE));
SELECT truncate(CAST(NULL AS DECIMAL(1,0)), -1);
SELECT truncate(CAST(NULL AS DECIMAL(1,0)));
SELECT truncate(CAST(NULL AS DECIMAL(18,5)));
SELECT truncate(CAST(NULL AS DECIMAL(25,2)));
SELECT truncate(NULL, NULL);
SELECT cos(NULL);
SELECT cosh(NULL);
SELECT degrees(NULL);
SELECT exp(NULL);
SELECT floor(TINYINT'123');
SELECT floor(TINYINT'-123');
SELECT floor(CAST(NULL AS TINYINT));
SELECT floor(SMALLINT'123');
SELECT floor(SMALLINT'-123');
SELECT floor(CAST(NULL AS SMALLINT));
SELECT floor(123);
SELECT floor(-123);
SELECT floor(CAST(NULL AS INTEGER));
SELECT floor(BIGINT '123');
SELECT floor(BIGINT '-123');
SELECT floor(12300000000);
SELECT floor(-12300000000);
SELECT floor(CAST(NULL as BIGINT));
SELECT floor(123.0E0);
SELECT floor(-123.0E0);
SELECT floor(123.45E0);
SELECT floor(-123.45E0);
SELECT floor(REAL '123.0');
SELECT floor(REAL '-123.0');
SELECT floor(REAL '123.45');
SELECT floor(REAL '-123.45');
SELECT floor(CAST(NULL as REAL));
SELECT floor(CAST(NULL as DOUBLE));
SELECT floor(CAST(NULL as DECIMAL(1,0)));
SELECT floor(CAST(NULL as DECIMAL(25,5)));
SELECT ln(NULL);
SELECT log2(NULL);
SELECT log10(NULL);
SELECT log(NULL, NULL);
SELECT log(5.0E0, NULL);
SELECT log(NULL, 5.0E0);
SELECT mod(5.0E0, NULL);
SELECT mod(NULL, 5.0E0);
SELECT mod(DECIMAL '5.0', CAST(NULL as DECIMAL(1,0)));
SELECT mod(CAST(NULL as DECIMAL(1,0)), DECIMAL '5.0');
SELECT pmod(9, 3);
SELECT pmod(10, 3);
SELECT pmod(-7, 3);
SELECT pmod(0, 3);
SELECT pmod(-9, 3);
SELECT pmod(TINYINT '-7', TINYINT '3');
SELECT pmod(SMALLINT '-7', SMALLINT '3');
SELECT pmod(INTEGER '-7', INTEGER '3');
SELECT pmod(BIGINT '-7', BIGINT '3');
SELECT pmod(0.0E0, 1.0E0);
SELECT pmod(6.0E0, 2.0E0);
SELECT pmod(-7.0E0, 3.0E0);
SELECT pmod(10.0E0, 3.0E0);
SELECT pmod(-10.0E0, 3.0E0);
SELECT pmod(REAL '-7.0', REAL '3.0');
SELECT pmod(5.0E0, NULL);
SELECT pmod(NULL, 5.0E0);
SELECT is_infinite(1.0E0 / 0.0E0);
SELECT is_infinite(0.0E0 / 0.0E0);
SELECT is_infinite(1.0E0 / 1.0E0);
SELECT is_infinite(REAL '1.0' / REAL '0.0');
SELECT is_infinite(REAL '0.0' / REAL '0.0');
SELECT is_infinite(REAL '1.0' / REAL '1.0');
SELECT is_infinite(NULL);
SELECT is_finite(100000);
SELECT is_finite(rand() / 0.0E0);
SELECT is_finite(REAL '754.2008E0');
SELECT is_finite(rand() / REAL '0.0E0');
SELECT is_finite(NULL);
SELECT is_nan(0.0E0 / 0.0E0);
SELECT is_nan(0.0E0 / 1.0E0);
SELECT is_nan(infinity() / infinity());
SELECT is_nan(nan());
SELECT is_nan(REAL '0.0' / REAL '0.0');
SELECT is_nan(REAL '0.0' / 1.0E0);
SELECT is_nan(NULL);
SELECT power(NULL, NULL);
SELECT power(5.0E0, NULL);
SELECT power(NULL, 5.0E0);
SELECT pow(5.0E0, 2.0E0);
SELECT radians(NULL);
SELECT round(REAL '1.0E19', 1);
SELECT round(REAL '1.0E19', 10);
SELECT round(REAL '1.0E19', 100);
SELECT round(REAL '9999999999999999999.9', 1);
SELECT round(REAL '9999999999999999999.99', 10);
SELECT round(REAL '9999999999999999999.999', 100);
SELECT round(TINYINT '3');
SELECT round(TINYINT '-3');
SELECT round(CAST(NULL as TINYINT));
SELECT round(SMALLINT '3');
SELECT round(SMALLINT '-3');
SELECT round(CAST(NULL as SMALLINT));
SELECT round(3);
SELECT round(-3);
SELECT round(CAST(NULL as INTEGER));
SELECT round(BIGINT '3');
SELECT round(BIGINT '-3');
SELECT round(CAST(NULL as BIGINT));
SELECT round( 3000000000);
SELECT round(-3000000000);
SELECT round(3.0E0);
SELECT round(-3.0E0);
SELECT round(3.499E0);
SELECT round(-3.499E0);
SELECT round(3.5E0);
SELECT round(-3.5E0);
SELECT round(-3.5001E0);
SELECT round(-3.99E0);
SELECT round(REAL '3.0');
SELECT round(REAL '-3.0');
SELECT round(REAL '3.499');
SELECT round(REAL '-3.499');
SELECT round(REAL '3.5');
SELECT round(REAL '-3.5');
SELECT round(REAL '-3.5001');
SELECT round(REAL '-3.99');
SELECT round(CAST(NULL as DOUBLE));
SELECT round(TINYINT '3', TINYINT '0');
SELECT round(TINYINT '3', 0);
SELECT round(SMALLINT '3', SMALLINT '0');
SELECT round(SMALLINT '3', 0);
SELECT round(3, 0);
SELECT round(-3, 0);
SELECT round(-3, INTEGER '0');
SELECT round(BIGINT '3', 0);
SELECT round( 3000000000, 0);
SELECT round(-3000000000, 0);
SELECT round(3.0E0, 0);
SELECT round(-3.0E0, 0);
SELECT round(3.499E0, 0);
SELECT round(-3.499E0, 0);
SELECT round(3.5E0, 0);
SELECT round(-3.5E0, 0);
SELECT round(-3.5001E0, 0);
SELECT round(-3.99E0, 0);
SELECT round(0.3E0);
SELECT round(-0.3E0);
SELECT round(TINYINT '3', TINYINT '1');
SELECT round(TINYINT '3', 1);
SELECT round(SMALLINT '3', SMALLINT '1');
SELECT round(SMALLINT '3', 1);
SELECT round(REAL '3.0', 0);
SELECT round(REAL '-3.0', 0);
SELECT round(REAL '3.499', 0);
SELECT round(REAL '-3.499', 0);
SELECT round(REAL '3.5', 0);
SELECT round(REAL '-3.5', 0);
SELECT round(REAL '-3.5001', 0);
SELECT round(REAL '-3.99', 0);
SELECT round(3, 1);
SELECT round(-3, 1);
SELECT round(-3, INTEGER '1');
SELECT round(-3, CAST(NULL as INTEGER));
SELECT round(BIGINT '3', 1);
SELECT round( 3000000000, 1);
SELECT round(-3000000000, 1);
SELECT round(CAST(NULL as BIGINT), CAST(NULL as INTEGER));
SELECT round(CAST(NULL as BIGINT), 1);
SELECT round(3.0E0, 1);
SELECT round(-3.0E0, 1);
SELECT round(3.499E0, 1);
SELECT round(-3.499E0, 1);
SELECT round(3.5E0, 1);
SELECT round(-3.5E0, 1);
SELECT round(-3.5001E0, 1);
SELECT round(-3.99E0, 1);
SELECT round(REAL '3.0', 1);
SELECT round(REAL '-3.0', 1);
SELECT round(REAL '3.499', 1);
SELECT round(REAL '-3.499', 1);
SELECT round(REAL '3.5', 1);
SELECT round(REAL '-3.5', 1);
SELECT round(REAL '-3.5001', 1);
SELECT round(REAL '-3.99', 1);
SELECT round(REAL '9000000000000000000.0');
SELECT round(REAL '300000000.0', 1);
SELECT round(REAL '-300000000.0', 1);
SELECT round(REAL '90000000.0', 1000);
SELECT round(REAL '300000000.0', 100);
SELECT round(REAL '-300000000.0', 100);
SELECT round(DOUBLE '9223372036854775900.0');
SELECT round(DOUBLE '3574559470676000000.0', 1);
SELECT round(DOUBLE '-3574559470676000000.0', 1);
SELECT round(DOUBLE '92233720368547759.0', 100);
SELECT round(DOUBLE '35745594706760000.0', 100);
SELECT round(DOUBLE '-35745594706760000.0', 100);
SELECT round(CAST(NULL as DOUBLE), CAST(NULL as INTEGER));
SELECT round(-3.0E0, CAST(NULL as INTEGER));
SELECT round(CAST(NULL as DOUBLE), 1);
SELECT round(CAST(NULL as DECIMAL(1,0)), CAST(NULL as INTEGER));
SELECT round(DECIMAL '-3.0', CAST(NULL as INTEGER));
SELECT round(CAST(NULL as DECIMAL(1,0)), 1);
SELECT round(CAST(NULL as DECIMAL(17,2)), 1);
SELECT round(CAST(NULL as DECIMAL(20,2)), 1);
SELECT sign(CAST(NULL as TINYINT));
SELECT sign(CAST(NULL as SMALLINT));
SELECT sign(CAST(NULL as INTEGER));
SELECT sign(CAST(NULL as BIGINT));
SELECT sign(CAST(NULL as DOUBLE));
SELECT sign(CAST(NULL as DECIMAL(2,1)));
SELECT sign(CAST(NULL as DECIMAL(38,0)));
SELECT sign(DOUBLE '+Infinity');
SELECT sign(DOUBLE '-Infinity');
SELECT sin(NULL);
SELECT sqrt(NULL);
SELECT tan(NULL);
SELECT tanh(NULL);
SELECT greatest(TINYINT'1', TINYINT'2');
SELECT greatest(TINYINT'-1', TINYINT'-2');
SELECT greatest(TINYINT'5', TINYINT'4', TINYINT'3', TINYINT'2', TINYINT'1', TINYINT'2', TINYINT'3', TINYINT'4', TINYINT'1', TINYINT'5');
SELECT greatest(TINYINT'-1');
SELECT greatest(TINYINT'5', TINYINT'4', CAST(NULL AS TINYINT), TINYINT'3');
SELECT greatest(SMALLINT'1', SMALLINT'2');
SELECT greatest(SMALLINT'-1', SMALLINT'-2');
SELECT greatest(SMALLINT'5', SMALLINT'4', SMALLINT'3', SMALLINT'2', SMALLINT'1', SMALLINT'2', SMALLINT'3', SMALLINT'4', SMALLINT'1', SMALLINT'5');
SELECT greatest(SMALLINT'-1');
SELECT greatest(SMALLINT'5', SMALLINT'4', CAST(NULL AS SMALLINT), SMALLINT'3');
SELECT greatest(1, 2);
SELECT greatest(-1, -2);
SELECT greatest(5, 4, 3, 2, 1, 2, 3, 4, 1, 5);
SELECT greatest(-1);
SELECT greatest(5, 4, CAST(NULL AS INTEGER), 3);
SELECT greatest(10000000000, 20000000000);
SELECT greatest(-10000000000, -20000000000);
SELECT greatest(5000000000, 4, 3, 2, 1000000000, 2, 3, 4, 1, 5000000000);
SELECT greatest(-10000000000);
SELECT greatest(5000000000, 4000000000, CAST(NULL as BIGINT), 3000000000);
SELECT greatest(1.5E0, 2.3E0);
SELECT greatest(-1.5E0, -2.3E0);
SELECT greatest(5, 4, CAST(NULL as DOUBLE), 3);
SELECT greatest(REAL '1.5', 2.3E0);
SELECT greatest(REAL '-1.5', -2.3E0);
SELECT greatest(5, REAL '4', CAST(NULL as DOUBLE), 3);
SELECT greatest(1, 20000000000);
SELECT greatest(1, BIGINT '2');
SELECT greatest(1.0E0, 2);
SELECT greatest(1, 2.0E0);
SELECT greatest(5.0E0, 4, CAST(NULL as DOUBLE), 3);
SELECT greatest(5.0E0, 4, CAST(NULL as BIGINT), 3);
SELECT greatest(1.0, 2.0E0);
SELECT least(TINYINT'1', TINYINT'2');
SELECT least(TINYINT'-1', TINYINT'-2');
SELECT least(TINYINT'5', TINYINT'4', TINYINT'3', TINYINT'2', TINYINT'1', TINYINT'2', TINYINT'3', TINYINT'4', TINYINT'1', TINYINT'5');
SELECT least(TINYINT'-1');
SELECT least(TINYINT'5', TINYINT'4', CAST(NULL AS TINYINT), TINYINT'3');
SELECT least(SMALLINT'1', SMALLINT'2');
SELECT least(SMALLINT'-1', SMALLINT'-2');
SELECT least(SMALLINT'5', SMALLINT'4', SMALLINT'3', SMALLINT'2', SMALLINT'1', SMALLINT'2', SMALLINT'3', SMALLINT'4', SMALLINT'1', SMALLINT'5');
SELECT least(SMALLINT'-1');
SELECT least(SMALLINT'5', SMALLINT'4', CAST(NULL AS SMALLINT), SMALLINT'3');
SELECT least(1, 2);
SELECT least(-1, -2);
SELECT least(5, 4, 3, 2, 1, 2, 3, 4, 1, 5);
SELECT least(-1);
SELECT least(5, 4, CAST(NULL AS INTEGER), 3);
SELECT least(10000000000, 20000000000);
SELECT least(-10000000000, -20000000000);
SELECT least(50000000000, 40000000000, 30000000000, 20000000000, 50000000000);
SELECT least(-10000000000);
SELECT least(500000000, 400000000, CAST(NULL as BIGINT), 300000000);
SELECT least(1.5E0, 2.3E0);
SELECT least(-1.5E0, -2.3E0);
SELECT least(-1.5E0, -2.3E0, -5/3);
SELECT least(5, 4, CAST(NULL as DOUBLE), 3);
SELECT least(REAL '1.5', 2.3E0);
SELECT least(REAL '-1.5', -2.3E0);
SELECT least(-2.3E0, REAL '-0.4', -5/3);
SELECT least(REAL '5', 4, CAST(NULL as DOUBLE), 3);
SELECT least(1, 20000000000);
SELECT least(1, BIGINT '2');
SELECT least(1.0E0, 2);
SELECT least(1, 2.0E0);
SELECT least(5.0E0, 4, CAST(NULL as DOUBLE), 3);
SELECT least(5.0E0, 4, CAST(NULL as BIGINT), 3);
SELECT least(1.0, 2.0E0);
SELECT width_bucket(3.14E0, 0, 4, 3);
SELECT width_bucket(2, 0, 4, 3);
SELECT width_bucket(infinity(), 0, 4, 3);
SELECT width_bucket(-1, 0, 3.2E0, 4);
SELECT width_bucket(infinity(), 4, 0, 3);
SELECT width_bucket(3.14E0, array[0.0E0, 2.0E0, 4.0E0]);
SELECT width_bucket(infinity(), array[0.0E0, 2.0E0, 4.0E0]);
SELECT width_bucket(-1, array[0.0E0, 1.2E0, 3.3E0, 4.5E0]);
SELECT width_bucket(3.145E0, array[0.0E0]);
SELECT width_bucket(-3.145E0, array[0.0E0]);
SELECT cosine_similarity(null, map(array ['c', 'b'], array [1.0E0, 3.0E0]));
SELECT cosine_similarity(map(), null);
SELECT cosine_similarity(null, array [1.0E0, 3.0E0]);
SELECT cosine_similarity(null, null);
SELECT cosine_similarity(array [], null);
SELECT dot_product(array[DOUBLE '1.0', DOUBLE '2.0', DOUBLE '3.0'], array[DOUBLE '1.0', DOUBLE '2.0', DOUBLE '3.0']);
SELECT dot_product(array[DOUBLE '1.0', DOUBLE '2.0', DOUBLE '3.0'], array[DOUBLE '4.0', DOUBLE '5.0', DOUBLE '6.0']);
SELECT dot_product(array[DOUBLE '-1.0', DOUBLE '-2.0', DOUBLE '-3.0'], array[DOUBLE '1.0', DOUBLE '2.0', DOUBLE '3.0']);
SELECT dot_product(array[DOUBLE '0.0', DOUBLE '0.0', DOUBLE '0.0'], array[DOUBLE '0.0', DOUBLE '0.0', DOUBLE '0.0']);
SELECT dot_product(array[REAL '1.0', REAL '2.0', REAL '3.0'], array[REAL '1.0', REAL '2.0', REAL '3.0']);
SELECT dot_product(array[REAL '1.0', REAL '2.0', REAL '3.0'], array[REAL '4.0', REAL '5.0', REAL '6.0']);
SELECT dot_product(array[REAL '-1.0', REAL '-2.0', REAL '-3.0'], array[REAL '1.0', REAL '2.0', REAL '3.0']);
SELECT dot_product(array[REAL '0.0', REAL '0.0', REAL '0.0'], array[REAL '0.0', REAL '0.0', REAL '0.0']);
SELECT factorial(1);
SELECT factorial(2);
SELECT factorial(3);
SELECT factorial(4);
SELECT factorial(5);
SELECT factorial(0);
SELECT factorial(20);

SELECT '-- TestStringFunctions';
SELECT CONCAT('hello', ' world');
SELECT CONCAT('', '');
SELECT CONCAT('what', '');
SELECT CONCAT('', 'what');
SELECT CONCAT(CONCAT('this', ' is'), ' cool');
SELECT CONCAT('this', CONCAT(' is', ' cool'));
SELECT CONCAT('hello naïve', ' world');
SELECT CONCAT('𐐭', 'end');
SELECT CONCAT('𐐭', 'end', '𐐭');
SELECT CONCAT(CONCAT('信念', ',爱'), ',希望');
SELECT LENGTH('');
SELECT LENGTH('hello');
SELECT LENGTH('Quadratically');
SELECT LENGTH('hello naïve world');
SELECT LENGTH('𐐭end');
SELECT LENGTH('信念,爱,希望');
SELECT LENGTH(CAST('hello' AS CHAR(5)));
SELECT LENGTH(CAST('Quadratically' AS CHAR(13)));
SELECT LENGTH(CAST('hello naïve world' AS CHAR(17)));
SELECT LENGTH(CAST('𐐭end' AS CHAR(4)));
SELECT LENGTH(CAST('信念,爱,希望' AS CHAR(7)));
SELECT LEVENSHTEIN_DISTANCE('', '');
SELECT LEVENSHTEIN_DISTANCE('', 'hello');
SELECT LEVENSHTEIN_DISTANCE('hello', '');
SELECT LEVENSHTEIN_DISTANCE('hello', 'hello');
SELECT LEVENSHTEIN_DISTANCE('hello', 'hello world');
SELECT LEVENSHTEIN_DISTANCE('hello world', 'hel wold');
SELECT LEVENSHTEIN_DISTANCE('hello world', 'hellq wodld');
SELECT LEVENSHTEIN_DISTANCE('helo word', 'hello world');
SELECT LEVENSHTEIN_DISTANCE('hello word', 'dello world');
SELECT LEVENSHTEIN_DISTANCE('hello naïve world', 'hello naive world');
SELECT LEVENSHTEIN_DISTANCE('hello naïve world', 'hello na:ive world');
SELECT LEVENSHTEIN_DISTANCE('信念,爱,希望', '信仰,爱,希望');
SELECT LEVENSHTEIN_DISTANCE('休念,爱,希望', '信念,爱,希望');
SELECT LEVENSHTEIN_DISTANCE('信念,爱,希望', '信念希望');
SELECT LEVENSHTEIN_DISTANCE('信念,爱,希望', '信念,love,希望');
SELECT HAMMING_DISTANCE('', '');
SELECT HAMMING_DISTANCE('hello', 'hello');
SELECT HAMMING_DISTANCE('hello', 'jello');
SELECT HAMMING_DISTANCE('like', 'hate');
SELECT HAMMING_DISTANCE('hello', 'world');
SELECT HAMMING_DISTANCE(NULL, NULL);
SELECT HAMMING_DISTANCE('hello', NULL);
SELECT HAMMING_DISTANCE(NULL, 'world');
SELECT REPLACE('aaa', 'a', 'aa');
SELECT REPLACE('abcdefabcdef', 'cd', 'XX');
SELECT REPLACE('abcdefabcdef', 'cd');
SELECT REPLACE('123123tech', '123');
SELECT REPLACE('123tech123', '123');
SELECT REPLACE('222tech', '2', '3');
SELECT REPLACE('0000123', '0');
SELECT REPLACE('0000123', '0', ' ');
SELECT REPLACE('foo', '');
SELECT REPLACE('foo', '', '');
SELECT REPLACE('foo', 'foo', '');
SELECT REPLACE('', '');
SELECT REPLACE('', '', '');
SELECT REPLACE('::𐐭::', ':', '');
SELECT REPLACE('Österreich', 'Ö', 'Oe');
SELECT REVERSE('');
SELECT REVERSE('hello');
SELECT REVERSE('Quadratically');
SELECT REVERSE('racecar');
SELECT SUBSTR('Quadratically', 5);
SELECT SUBSTR('Quadratically', 50);
SELECT SUBSTR('Quadratically', -5);
SELECT SUBSTR('Quadratically', 0);
SELECT SUBSTR('Quadratically', 5, 6);
SELECT SUBSTR('Quadratically', 5, 10);
SELECT SUBSTR('Quadratically', 5, 50);
SELECT SUBSTR('Quadratically', 50, 10);
SELECT SUBSTR('Quadratically', -5, 4);
SELECT SUBSTR('Quadratically', -5, 40);
SELECT SUBSTR('Quadratically', -50, 4);
SELECT SUBSTR('Quadratically', 0, 4);
SELECT SUBSTR('Quadratically', 5, 0);
SELECT SUBSTRING('Quadratically' FROM 5);
SELECT SUBSTRING('Quadratically' FROM 50);
SELECT SUBSTRING('Quadratically' FROM -5);
SELECT SUBSTRING('Quadratically' FROM 0);
SELECT SUBSTRING('Quadratically' FROM 5 FOR 6);
SELECT SUBSTRING('Quadratically' FROM 5 FOR 50);
SELECT SUBSTRING('信念,爱,希望' FROM 1 FOR 1);
SELECT SUBSTRING('信念,爱,希望' FROM 3 FOR 5);
SELECT SUBSTRING('信念,爱,希望' FROM 4);
SELECT SUBSTRING('信念,爱,希望' FROM -2);
SELECT SUBSTRING('𐐭end' FROM 1 FOR 1);
SELECT SUBSTRING('𐐭end' FROM 2 FOR 3);
SELECT SPLIT_PART('abc-@-def-@-ghi', '-@-', 1);
SELECT SPLIT_PART('abc-@-def-@-ghi', '-@-', 2);
SELECT SPLIT_PART('abc-@-def-@-ghi', '-@-', 3);
SELECT SPLIT_PART('abc-@-def-@-ghi', '-@-', 4);
SELECT SPLIT_PART('abc-@-def-@-ghi', '-@-', 99);
SELECT SPLIT_PART('abc', 'abc', 1);
SELECT SPLIT_PART('abc', 'abc', 2);
SELECT SPLIT_PART('abc', 'abc', 3);
SELECT SPLIT_PART('abc', '-@-', 1);
SELECT SPLIT_PART('abc', '-@-', 2);
SELECT SPLIT_PART('', 'abc', 1);
SELECT SPLIT_PART('', '', 1);
SELECT SPLIT_PART('abc', '', 1);
SELECT SPLIT_PART('abc', '', 2);
SELECT SPLIT_PART('abc', '', 3);
SELECT SPLIT_PART('abc', '', 4);
SELECT SPLIT_PART('abc', '', 99);
SELECT SPLIT_PART('abc', 'abcd', 1);
SELECT SPLIT_PART('abc', 'abcd', 2);
SELECT SPLIT_PART('abc-@-@-@-def', '-@-', 1);
SELECT SPLIT_PART('abc-@-@-@-def', '-@-', 2);
SELECT SPLIT_PART('abc-@-@-@-def', '-@-', 3);
SELECT SPLIT_PART(' ', ' ', 1);
SELECT SPLIT_PART('abcdddddef', 'dd', 1);
SELECT SPLIT_PART('abcdddddef', 'dd', 2);
SELECT SPLIT_PART('abcdddddef', 'dd', 3);
SELECT SPLIT_PART('a/b/c', '/', 4);
SELECT SPLIT_PART('a/b/c/', '/', 4);
SELECT SPLIT_PART('信念,爱,希望', ',', 1);
SELECT SPLIT_PART('信念,爱,希望', ',', 2);
SELECT SPLIT_PART('信念,爱,希望', ',', 3);
SELECT SPLIT_PART('信念,爱,希望', ',', 4);
SELECT SPLIT_PART('證证証', '证', 1);
SELECT SPLIT_PART('證证証', '证', 2);
SELECT SPLIT_PART('證证証', '证', 3);
SELECT LTRIM('');
SELECT LTRIM('   ');
SELECT LTRIM('  hello  ');
SELECT LTRIM('  hello');
SELECT LTRIM('hello  ');
SELECT LTRIM(' hello world ');
SELECT LTRIM('信念 爱 希望  ');
SELECT LTRIM(' 信念 爱 希望 ');
SELECT LTRIM('  信念 爱 希望');
SELECT LTRIM('   信念 爱 希望');
SELECT RTRIM('');
SELECT RTRIM('   ');
SELECT RTRIM('  hello  ');
SELECT RTRIM('  hello');
SELECT RTRIM('hello  ');
SELECT RTRIM(' hello world ');
SELECT RTRIM('信念 爱 希望   ');
SELECT RTRIM('信念 爱 希望  ');
SELECT RTRIM(' 信念 爱 希望 ');
SELECT RTRIM('  信念 爱 希望');
SELECT TRIM('');
SELECT TRIM('   ');
SELECT TRIM('  hello  ');
SELECT TRIM('  hello');
SELECT TRIM('hello  ');
SELECT TRIM(' hello world ');
SELECT TRIM('信念 爱 希望   ');
SELECT TRIM('信念 爱 希望  ');
SELECT TRIM(' 信念 爱 希望 ');
SELECT TRIM('  信念 爱 希望');
SELECT TRIM('   信念 爱 希望');
SELECT TRIM(CAST('abc ' AS VARCHAR));
SELECT LTRIM(CAST(' abc' AS VARCHAR));
SELECT RTRIM(CAST('abc ' AS VARCHAR));
SELECT TRIM(CAST(' abc ' AS VARCHAR), ' ');
SELECT LTRIM(CAST(' abc' AS VARCHAR), ' ');
SELECT RTRIM(CAST('abc ' AS VARCHAR), ' ');
SELECT LTRIM('', '');
SELECT LTRIM('   ', '');
SELECT LTRIM('  hello  ', '');
SELECT LTRIM('  hello  ', ' ');
SELECT LTRIM('  hello  ', CHAR ' ');
SELECT LTRIM('  hello  ', 'he ');
SELECT LTRIM('  hello', ' ');
SELECT LTRIM('  hello', 'e h');
SELECT LTRIM('hello  ', 'l');
SELECT LTRIM(' hello world ', ' ');
SELECT LTRIM(' hello world ', ' eh');
SELECT LTRIM(' hello world ', ' ehlowrd');
SELECT LTRIM(' hello world ', ' x');
SELECT RTRIM('', '');
SELECT RTRIM('   ', '');
SELECT RTRIM('  hello  ', '');
SELECT RTRIM('  hello  ', ' ');
SELECT RTRIM('  hello  ', 'lo ');
SELECT RTRIM('hello  ', ' ');
SELECT RTRIM('hello  ', 'l o');
SELECT RTRIM('hello  ', 'l');
SELECT RTRIM(' hello world ', ' ');
SELECT RTRIM(' hello world ', ' ld');
SELECT RTRIM(' hello world ', ' ehlowrd');
SELECT RTRIM(' hello world ', ' x');
SELECT RTRIM('źółć', 'ćł');
SELECT TRIM('', '');
SELECT TRIM('   ', '');
SELECT TRIM('  hello  ', '');
SELECT TRIM('  hello  ', ' ');
SELECT TRIM('  hello  ', 'he ');
SELECT TRIM('  hello  ', 'lo ');
SELECT TRIM('  hello', ' ');
SELECT TRIM('hello  ', ' ');
SELECT TRIM('hello  ', 'l o');
SELECT TRIM('hello  ', 'l');
SELECT TRIM(' hello world ', ' ');
SELECT TRIM(' hello world ', ' ld');
SELECT TRIM(' hello world ', ' eh');
SELECT TRIM(' hello world ', ' ehlowrd');
SELECT TRIM(' hello world ', ' x');
SELECT TRIM('źółć', 'ćź');
SELECT LOWER(CAST('HELLO' AS VARCHAR));
SELECT LOWER('');
SELECT LOWER('Hello World');
SELECT LOWER('WHAT!!');
SELECT UPPER('');
SELECT UPPER('Hello World');
SELECT UPPER('what!!');
SELECT LPAD('text', 5, 'x');
SELECT LPAD('text', 4, 'x');
SELECT LPAD('text', 6, 'xy');
SELECT LPAD('text', 7, 'xy');
SELECT LPAD('text', 9, 'xyz');
SELECT LPAD('信念 爱 希望  ', 10, '望');
SELECT LPAD('信念 爱 希望  ', 11, '望');
SELECT LPAD('信念 爱 希望  ', 12, '希望');
SELECT LPAD('信念 爱 希望  ', 13, '希望');
SELECT LPAD('', 3, 'a');
SELECT LPAD('abc', 0, 'e');
SELECT LPAD('text', 3, 'xy');
SELECT LPAD('信念 爱 希望  ', 5, '望');
SELECT RPAD('text', 5, 'x');
SELECT RPAD('text', 4, 'x');
SELECT RPAD('text', 6, 'xy');
SELECT RPAD('text', 7, 'xy');
SELECT RPAD('text', 9, 'xyz');
SELECT RPAD('信念 爱 希望  ', 10, '望');
SELECT RPAD('信念 爱 希望  ', 11, '望');
SELECT RPAD('信念 爱 希望  ', 12, '希望');
SELECT RPAD('信念 爱 希望  ', 13, '希望');
SELECT RPAD('', 3, 'a');
SELECT RPAD('abc', 0, 'e');
SELECT RPAD('text', 3, 'xy');
SELECT RPAD('信念 爱 希望  ', 5, '望');
SELECT normalize('schön', NFD);
SELECT normalize('schön');
SELECT normalize('schön', NFC);
SELECT normalize('schön', NFKD);
SELECT normalize('schön', NFKC);
SELECT normalize('㈱㌧㌦Ⅲ', NFKC);
SELECT normalize('ﾊﾝｶｸｶﾅ', NFKC);
SELECT from_utf8(to_utf8('hello'));
SELECT concat('ab ', cast(' ' as char(1)));
SELECT concat('ab ', cast('a' as char(2)));
SELECT concat('ab ', cast('a' as char(2))) = 'ab a';
SELECT concat('ab ', cast('' as char(0)));
SELECT concat('hello naïve', cast(' world' as char(6)));
SELECT concat(cast(null as char(1)), cast(' ' as char(1)));
SELECT starts_with('abcd', 'ab');
SELECT starts_with('abcd', '');
SELECT starts_with('abcd', 'ba');
SELECT starts_with('', 'ba');
SELECT starts_with(NULL, 'ba');
SELECT starts_with('abcd', NULL);
SELECT starts_with('', NULL);
SELECT starts_with(NULL, '');
SELECT starts_with(NULL, NULL);
SELECT ends_with('abcd', 'cd');
SELECT ends_with('abcd', '');
SELECT ends_with('abcd', 'zs');
SELECT ends_with('', 'zs');
SELECT ends_with(NULL, 'ba');
SELECT ends_with('abcd', NULL);
SELECT ends_with('', NULL);
SELECT ends_with(NULL, '');
SELECT ends_with(NULL, NULL);

SELECT '-- TestTruncateWithPrecision';
SELECT truncate(DOUBLE '17.1', -1);
SELECT truncate(DOUBLE '1234.56', 1);
SELECT truncate(DOUBLE '1234.56', 0);
SELECT truncate(DOUBLE '-1234.56', 0);
SELECT truncate(DOUBLE '-1234.56', -500);
SELECT truncate(DOUBLE '1234.567', 2);
SELECT truncate(REAL '12.333', 0);
SELECT truncate(REAL '-12.333', 0);
SELECT truncate(REAL '12.123456789011234567892', 10);
SELECT truncate(REAL '12.333', -1);
SELECT truncate(REAL '12.333', -500);

SELECT '-- TestUrlFunctions';
SELECT url_extract_parameter('http://example.com/path1/p.php?k1=v1&k2=v2&k3&k4#Ref1', 'k1');
SELECT url_extract_parameter('http://example.com/path1/p.php?k1=v1&k2=v2&k3&k4#Ref1', 'k2');
SELECT url_extract_parameter('http://example.com/path1/p.php?k1=v1&k2=v2&k3&k4#Ref1', 'k3');
SELECT url_extract_parameter('http://example.com/path1/p.php?k1=v1&k2=v2&k3&k4#Ref1', 'k4');
SELECT url_extract_parameter('http://example.com/path1/p.php?k1=v1&k1=v2&k1&k1#Ref1', 'k1');
SELECT url_extract_parameter('http://example.com/path1/p.php?k=a=b=c&x=y#Ref1', 'k');
SELECT url_encode('𩸽');

SELECT '-- TestVarbinaryFunctions';
SELECT length(CAST('' AS VARBINARY));
SELECT length(CAST('a' AS VARBINARY));
SELECT length(CAST('abc' AS VARBINARY));
SELECT to_base64(CAST('hello world' AS VARBINARY));
SELECT to_base32(CAST('hello world' AS VARBINARY));
SELECT to_base32(NULL);
SELECT from_base32(CAST(NULL AS VARCHAR));
SELECT from_base32(CAST(NULL AS VARBINARY));
SELECT to_hex(CAST('hello world' AS VARBINARY));
SELECT from_big_endian_64(from_hex('0000000000000000'));
SELECT from_big_endian_64(from_hex('0000000000000001'));
SELECT from_big_endian_64(from_hex('7FFFFFFFFFFFFFFF'));
SELECT from_big_endian_64(from_hex('8000000000000001'));
SELECT from_big_endian_32(from_hex('00000000'));
SELECT from_big_endian_32(from_hex('00000001'));
SELECT from_big_endian_32(from_hex('7FFFFFFF'));
SELECT from_big_endian_32(from_hex('80000001'));
SELECT from_ieee754_32(from_hex('3F800000'));
SELECT from_ieee754_32(to_ieee754_32(CAST(1.0 AS REAL)));
SELECT from_ieee754_32(from_hex('4048F5C3'));
SELECT from_ieee754_32(to_ieee754_32(CAST(3.14 AS REAL)));
SELECT from_ieee754_32(to_ieee754_32(CAST(3.4028235E38 AS REAL)));
SELECT from_ieee754_32(to_ieee754_32(CAST(-3.4028235E38 AS REAL)));
SELECT from_ieee754_64(from_hex('0000000000000000'));
SELECT from_ieee754_64(from_hex('3FF0000000000000'));
SELECT from_ieee754_64(to_ieee754_64(3.1415926));
SELECT from_ieee754_64(to_ieee754_64(1.7976931348623157E308));
SELECT from_ieee754_64(to_ieee754_64(-1.7976931348623157E308));
SELECT from_ieee754_64(to_ieee754_64(4.9E-324));
SELECT from_ieee754_64(to_ieee754_64(-4.9E-324));
SELECT crc32(to_utf8('CRC me!'));
SELECT crc32(to_utf8('1234567890'));
SELECT crc32(to_utf8(CAST(1234567890 AS VARCHAR)));
SELECT crc32(to_utf8('ABCDEFGHIJK'));
SELECT crc32(to_utf8('ABCDEFGHIJKLM'));
SELECT REVERSE(CAST(null AS VARBINARY));

SELECT '-- TestWordStemFunction';
SELECT word_stem('');
SELECT word_stem('x');
SELECT word_stem('abc');
SELECT word_stem('generally');
SELECT word_stem('useful');
SELECT word_stem('runs');
SELECT word_stem('run');
SELECT word_stem('authorized', 'en');
SELECT word_stem('accessories', 'en');
SELECT word_stem('intensifying', 'en');
SELECT word_stem('resentment');
SELECT word_stem('faithfulness');
SELECT word_stem('continuerait', 'fr');
SELECT word_stem('torpedearon', 'es');
SELECT word_stem('quilomtricos', 'pt');
SELECT word_stem('pronunziare', 'it');
SELECT word_stem('auferstnde', 'de');
