-- Conformance queries derived from the scalar-function tests of Presto
-- (https://github.com/prestodb/presto, presto-main-base operator/scalar tests, Apache License 2.0),
-- covering the shared Presto/Trino function surface.
-- Expected results verified against the assertions of the original tests.
-- Split over several test files so that a single test stays fast enough in the
-- debug and sanitizer builds; this part covers the regexp, array, bitwise, conditional, date/time and JSON functions.

SET allow_experimental_trino_dialect = 1;
SET dialect = 'trino';

SELECT '-- AbstractTestRegexpFunctions';
SELECT REGEXP_LIKE('Stephen', 'Ste(v|ph)en');
SELECT REGEXP_LIKE('Stevens', 'Ste(v|ph)en');
SELECT REGEXP_LIKE('Stephen', '^Ste(v|ph)en$');
SELECT REGEXP_LIKE('Stevens', '^Ste(v|ph)en$');
SELECT REGEXP_LIKE('hello world', '[a-z]');
SELECT REGEXP_LIKE('hello world', '.*hello world.*');
SELECT REGEXP_LIKE('Hello', '^[a-z]+$');
SELECT REGEXP_LIKE('Hello', '^(?i)[a-z]+$');
SELECT REGEXP_LIKE('Hello', '^[a-zA-Z]+$');
SELECT REGEXP_LIKE('test', 'test\b');
SELECT REGEXP_LIKE('ala', CHAR 'ala  ');
SELECT REGEXP_LIKE('ala  ', CHAR 'ala  ');
SELECT REGEXP_REPLACE('fun stuff.', '[a-z]');
SELECT REGEXP_REPLACE('fun stuff.', '[a-z]', '*');
SELECT REGEXP_REPLACE('xxx xxx xxx', 'x', 'x');
SELECT REGEXP_REPLACE('xxx xxx xxx', 'x', '\x');
SELECT REGEXP_REPLACE('xxx xxx xxx', 'x', '$0');
SELECT REGEXP_REPLACE('xxx', 'x', '$05');
SELECT REGEXP_REPLACE('123456789', '(1)(2)(3)(4)(5)(6)(7)(8)(9)', '$10');
SELECT REGEXP_REPLACE('1234567890', '(1)(2)(3)(4)(5)(6)(7)(8)(9)(0)', '$11');
SELECT REGEXP_REPLACE('1234567890', '(1)(2)(3)(4)(5)(6)(7)(8)(9)(0)', '$1a');
SELECT REGEXP_REPLACE(VARCHAR 'x', '.*', 'xxxxx');
SELECT REGEXP_EXTRACT('Hello world bye', '\b[a-z]([a-z]*)', 1);

SELECT '-- TestArrayExceptFunction';
SELECT array_except(ARRAY[NULL], NULL);
SELECT array_except(NULL, NULL);
SELECT array_except(NULL, ARRAY[NULL]);

SELECT '-- TestArrayIntersectFunction';
SELECT ARRAY_INTERSECT(NULL, NULL);
SELECT ARRAY_INTERSECT(ARRAY[NULL], NULL);
SELECT ARRAY_INTERSECT(NULL, ARRAY[NULL]);
SELECT array_intersect(null);

SELECT '-- TestArrayMatchFunctions';
SELECT all_match(ARRAY [5, 7, 9], x -> x % 2 = 1);
SELECT all_match(ARRAY [true, false, true], x -> x);
SELECT all_match(ARRAY ['abc', 'ade', 'afg'], x -> substr(x, 1, 1) = 'a');
SELECT all_match(ARRAY [], x -> true);
SELECT all_match(ARRAY [true, false, NULL], x -> x);
SELECT all_match(ARRAY [NULL, NULL, NULL], x -> x IS NULL);
SELECT all_match(ARRAY [MAP(ARRAY[1,2], ARRAY[3,4]), MAP(ARRAY[1,2,3], ARRAY[3,4,5])], x -> cardinality(x) > 1);
SELECT any_match(ARRAY [5, 8, 10], x -> x % 2 = 1);
SELECT any_match(ARRAY [false, false, false], x -> x);
SELECT any_match(ARRAY ['abc', 'def', 'ghi'], x -> substr(x, 1, 1) = 'a');
SELECT any_match(ARRAY [], x -> true);
SELECT any_match(ARRAY [true, false, NULL], x -> x);
SELECT any_match(ARRAY [true, false, NULL], x -> x IS NULL);
SELECT any_match(ARRAY [MAP(ARRAY[1,2], ARRAY[3,4]), MAP(ARRAY[1,2,3], ARRAY[3,4,5])], x -> cardinality(x) > 4);
SELECT none_match(ARRAY [5, 8, 10], x -> x % 2 = 1);
SELECT none_match(ARRAY [false, false, false], x -> x);
SELECT none_match(ARRAY ['abc', 'def', 'ghi'], x -> substr(x, 1, 1) = 'a');
SELECT none_match(ARRAY [], x -> true);
SELECT none_match(ARRAY [true, false, NULL], x -> x);
SELECT none_match(ARRAY [true, false, NULL], x -> x IS NULL);
SELECT none_match(ARRAY [MAP(ARRAY[1,2], ARRAY[3,4]), MAP(ARRAY[1,2,3], ARRAY[3,4,5])], x -> cardinality(x) > 4);

SELECT '-- TestArrayReduceFunction';
SELECT reduce(ARRAY [5, 20, 50], CAST (0 AS BIGINT), (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [5 + RANDOM(1), 20, 50], CAST (0 AS BIGINT), (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [5, 6, 10, 20], 0.0E0, (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [NULL, NULL, NULL], CAST (0 AS BIGINT), (s, x) -> coalesce(x, 1) + s, s -> s);
SELECT reduce(ARRAY [5, NULL, 50], CAST (0 AS BIGINT), (s, x) -> s + x, s -> s);
SELECT reduce(ARRAY [5, NULL, 50], CAST (0 AS BIGINT), (s, x) -> coalesce(x, 0) + s, s -> s);
SELECT reduce(ARRAY [NULL], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);
SELECT reduce(ARRAY [NULL, NULL, NULL], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);
SELECT reduce(ARRAY [NULL, 6, 10, NULL, 8], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);
SELECT reduce(ARRAY [5, NULL, 6, 10, NULL, 8], CAST (NULL AS BIGINT), (s, x) -> IF(s IS NULL OR x > s, x, s), s -> s);

SELECT '-- TestBitwiseFunctions';
SELECT bit_count(0, 64);
SELECT bit_count(7, 64);
SELECT bit_count(24, 64);
SELECT bit_count(-8, 64);
SELECT bit_count(0, 32);
SELECT bit_count(CAST (-8 AS SMALLINT), 6);
SELECT bit_count(7, 32);
SELECT bit_count(24, 32);
SELECT bit_count(-8, 32);
SELECT bit_count(1152921504598458367, 62);
SELECT bit_count(-1, 62);
SELECT bit_count(33554132, 26);
SELECT bit_count(-1, 26);
SELECT bitwise_and(0, -1);
SELECT bitwise_or(0, -1);
SELECT bitwise_xor(0, -1);
SELECT bitwise_left_shift(TINYINT '-128', 1);
SELECT bitwise_left_shift(TINYINT '-7', 64);
SELECT bitwise_left_shift(TINYINT '-128', 0);
SELECT bitwise_left_shift(SMALLINT '-32768', 1);
SELECT bitwise_left_shift(SMALLINT '-7', 64);
SELECT bitwise_left_shift(SMALLINT '-32768', 0);
SELECT bitwise_left_shift(INTEGER '-2147483648', 1);
SELECT bitwise_left_shift(INTEGER '-7', 64);
SELECT bitwise_left_shift(INTEGER '-2147483648', 0);
SELECT bitwise_left_shift(BIGINT '-7', 64);
SELECT bitwise_right_shift(TINYINT '-7', 2);
SELECT bitwise_right_shift(TINYINT '-7', 64);
SELECT bitwise_right_shift(SMALLINT '-7', 2);
SELECT bitwise_right_shift(SMALLINT '-7', 64);
SELECT bitwise_right_shift(INTEGER '-7', 2);
SELECT bitwise_right_shift(INTEGER '-7', 64);
SELECT bitwise_right_shift(BIGINT '-7', 64);
SELECT bitwise_right_shift_arithmetic(TINYINT '7', 64);
SELECT bitwise_right_shift_arithmetic(TINYINT '-128', 0);
SELECT bitwise_right_shift_arithmetic(SMALLINT '7', 64);
SELECT bitwise_right_shift_arithmetic(SMALLINT '-32768', 0);
SELECT bitwise_right_shift_arithmetic(INTEGER '7', 64);
SELECT bitwise_right_shift_arithmetic(INTEGER '-2147483648', 0);
SELECT bitwise_right_shift_arithmetic(BIGINT '7', 64);

SELECT '-- TestConditions';
SELECT '_monkey_' like 'X_monkeyX_' escape 'X';
SELECT 'monkey' like 'monkey';
SELECT 'monkey' like 'mon%';
SELECT 'monkey' like 'mon_ey';
SELECT 'monkey' like 'm____y';
SELECT 'monkey' like 'dain';
SELECT 'monkey' like 'key';
SELECT '_monkey_' like '\_monkey\_';
SELECT '_monkey_' like '_monkey_';
SELECT null like 'monkey';
SELECT 'monkey' like null;
SELECT '_monkey_' not like 'X_monkeyX_' escape 'X';
SELECT 'monkey' not like 'monkey';
SELECT 'monkey' not like 'mon%';
SELECT 'monkey' not like 'mon_ey';
SELECT 'monkey' not like 'm____y';
SELECT 'monkey' not like 'dain';
SELECT 'monkey' not like 'key';
SELECT '_monkey_' not like '\_monkey\_';
SELECT '_monkey_' not like '_monkey_';
SELECT null not like 'monkey';
SELECT 'monkey' not like null;
SELECT '你好a世界' like '你好%';
SELECT '你好a世界' like '你好a%';
SELECT '你好a世界' like '%世界';
SELECT '你好a世界' like '%好a世%';
SELECT '你好a世界' not like '你好b%';
SELECT '你好a世界' not like null;
SELECT NULL IS DISTINCT FROM NULL;
SELECT NULL IS DISTINCT FROM 1;
SELECT 1 IS DISTINCT FROM NULL;
SELECT 1 IS DISTINCT FROM 1;
SELECT 1 IS DISTINCT FROM 2;
SELECT NULL IS NOT DISTINCT FROM NULL;
SELECT NULL IS NOT DISTINCT FROM 1;
SELECT 1 IS NOT DISTINCT FROM NULL;
SELECT 1 IS NOT DISTINCT FROM 1;
SELECT 1 IS NOT DISTINCT FROM 2;
SELECT 3 between 2 and 4;
SELECT 3 between 3 and 3;
SELECT 3 between 2 and 3;
SELECT 3 between 3 and 4;
SELECT 3 between 4 and 2;
SELECT 2 between 3 and 4;
SELECT 5 between 3 and 4;
SELECT null between 2 and 4;
SELECT 3 between null and 4;
SELECT 3 between 2 and null;
SELECT 3 between 3 and 4000000000;
SELECT 5 between 3 and 4000000000;
SELECT 3 between BIGINT '3' and 4;
SELECT BIGINT '3' between 3 and 4;
SELECT 'c' between 'b' and 'd';
SELECT 'c' between 'c' and 'c';
SELECT 'c' between 'b' and 'c';
SELECT 'c' between 'c' and 'd';
SELECT 'c' between 'd' and 'b';
SELECT 'b' between 'c' and 'd';
SELECT 'e' between 'c' and 'd';
SELECT null between 'b' and 'd';
SELECT 'c' between null and 'd';
SELECT 'c' between 'b' and null;
SELECT 3 not between 2 and 4;
SELECT 3 not between 3 and 3;
SELECT 3 not between 2 and 3;
SELECT 3 not between 3 and 4;
SELECT 3 not between 4 and 2;
SELECT 2 not between 3 and 4;
SELECT 5 not between 3 and 4;
SELECT null not between 2 and 4;
SELECT 3 not between null and 4;
SELECT 3 not between 2 and null;
SELECT 'c' not between 'b' and 'd';
SELECT 'c' not between 'c' and 'c';
SELECT 'c' not between 'b' and 'c';
SELECT 'c' not between 'c' and 'd';
SELECT 'c' not between 'd' and 'b';
SELECT 'b' not between 'c' and 'd';
SELECT 'e' not between 'c' and 'd';
SELECT null not between 'b' and 'd';
SELECT 'c' not between null and 'd';
SELECT 'c' not between 'b' and null;
SELECT 3 in (2, 4, 3, 5);
SELECT 3 not in (2, 4, 3, 5);
SELECT 3 in (2, 4, 9, 5);
SELECT 3 in (2, null, 3, 5);
SELECT 'foo' in ('bar', 'baz', 'foo', 'blah');
SELECT 'foo' in ('bar', 'baz', 'buz', 'blah');
SELECT 'foo' in ('bar', null, 'foo', 'blah');
SELECT (null in (2, null, 3, 5)) is null;
SELECT (null not in (2, null, 3, 5)) is null;
SELECT case when true then 33 end;
SELECT case when true then BIGINT '33' end;
SELECT case when false then 1 else 33 end;
SELECT case when false then 10000000000 else 33 end;
SELECT case when false then 1 when false then 1 when true then 33 else 1 end;
SELECT case when false then BIGINT '1' when false then 1 when true then 33 else 1 end;
SELECT case when false then 10000000000 when false then 1 when true then 33 else 1 end;
SELECT case when false then 1 end;
SELECT case when true then null else 'foo' end;
SELECT case when null then 1 when true then 33 end;
SELECT case when null then 10000000000 when true then 33 end;
SELECT case when false then 1.0E0 when true then 33 end;
SELECT case when false then 1.1 when true then 33.0E0 end;
SELECT case true when true then cast(null as varchar) else 'foo' end;
SELECT case true when true then 33 end;
SELECT case true when true then BIGINT '33' end;
SELECT case true when false then 1 else 33 end;
SELECT case true when false then 10000000000 else 33 end;
SELECT case true when false then 1 when false then 1 when true then 33 else 1 end;
SELECT case true when false then 1 end;
SELECT case true when true then null else 'foo' end;
SELECT case true when null then 10000000000 when true then 33 end;
SELECT case true when null then 1 when true then 33 end;
SELECT case null when true then 1 else 33 end;
SELECT case true when false then 1.0E0 when true then 33 end;
SELECT case true when false then 1.1 when true then 33.0E0 end;

SELECT '-- TestDateTimeFunctionsBase';
SELECT year_of_week(DATE '2001-08-22');
SELECT yow(DATE '2001-08-22');
SELECT year_of_week(DATE '2005-01-02');
SELECT year_of_week(DATE '2008-12-28');
SELECT year_of_week(DATE '2008-12-29');
SELECT year_of_week(DATE '2009-12-31');
SELECT year_of_week(DATE '2010-01-03');
SELECT year_of_week(TIMESTAMP '2001-08-22 03:04:05.321 +07:09');
SELECT year_of_week(TIMESTAMP '2010-01-03 03:04:05.321');
SELECT extract(quarter FROM DATE '2001-01-01');
SELECT extract(quarter FROM DATE '2001-03-31');
SELECT extract(quarter FROM DATE '2001-04-01');
SELECT extract(quarter FROM DATE '2001-06-30');
SELECT extract(quarter FROM DATE '2001-07-01');
SELECT extract(quarter FROM DATE '2001-09-30');
SELECT extract(quarter FROM DATE '2001-10-01');
SELECT extract(quarter FROM DATE '2001-12-31');
SELECT extract(quarter FROM TIMESTAMP '2001-01-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-03-31 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-04-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-06-30 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-07-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-09-30 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-10-01 00:00:00.000');
SELECT extract(quarter FROM TIMESTAMP '2001-12-31 23:59:59.999');
SELECT extract(quarter FROM TIMESTAMP '2001-03-31 23:59:59.999 +06:00');
SELECT extract(quarter FROM TIMESTAMP '2001-06-30 23:59:59.999 +06:00');
SELECT extract(quarter FROM TIMESTAMP '2001-09-30 23:59:59.999 +06:00');
SELECT extract(quarter FROM TIMESTAMP '2001-12-31 23:59:59.999 +06:00');
SELECT extract(second FROM INTERVAL '5' SECOND);
SELECT extract(minute FROM INTERVAL '4' MINUTE);
SELECT extract(hour FROM INTERVAL '3' HOUR);
SELECT extract(day FROM INTERVAL '2' DAY);
SELECT extract(month FROM INTERVAL '3' MONTH);
SELECT extract(year FROM INTERVAL '2' YEAR);
SELECT date_format(TIMESTAMP '2001-01-09 13:04:05.32', '%f');
SELECT date_format(TIMESTAMP '2001-01-09 00:04:05.32', '%k');
SELECT date '2012-12-31';
SELECT timestamp '1234-05-06 23:23:23.233';

SELECT '-- TestJsonFunctions';
SELECT IS_JSON_SCALAR(null);
SELECT IS_JSON_SCALAR(JSON 'null');
SELECT IS_JSON_SCALAR(JSON 'true');
SELECT IS_JSON_SCALAR(JSON '1');
SELECT IS_JSON_SCALAR(JSON '"str"');
SELECT IS_JSON_SCALAR('null');
SELECT IS_JSON_SCALAR('true');
SELECT IS_JSON_SCALAR('1');
SELECT IS_JSON_SCALAR('"str"');
SELECT IS_JSON_SCALAR(JSON '[1, 2, 3]');
SELECT IS_JSON_SCALAR(JSON '{"a": 1, "b": 2}');
SELECT IS_JSON_SCALAR('[1, 2, 3]');
SELECT IS_JSON_SCALAR('{"a": 1, "b": 2}');
SELECT JSON_ARRAY_LENGTH('[]');
SELECT JSON_ARRAY_LENGTH('[1]');
SELECT JSON_ARRAY_LENGTH('[1, "foo", null]');
SELECT JSON_ARRAY_LENGTH('[2, 4, {"a": [8, 9]}, [], [5], 4]');
SELECT JSON_ARRAY_LENGTH(null);
SELECT JSON_ARRAY_CONTAINS('[]', true);
SELECT JSON_ARRAY_CONTAINS('[true]', true);
SELECT JSON_ARRAY_CONTAINS('[false]', false);
SELECT JSON_ARRAY_CONTAINS('[true, false]', false);
SELECT JSON_ARRAY_CONTAINS('[false, true]', true);
SELECT JSON_ARRAY_CONTAINS('[[true]]', true);
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], false]', false);
SELECT JSON_ARRAY_CONTAINS(JSON '[]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[true]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[false]', false);
SELECT JSON_ARRAY_CONTAINS(JSON '[true, false]', false);
SELECT JSON_ARRAY_CONTAINS(JSON '[false, true]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[[true]]', true);
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], false]', false);
SELECT JSON_ARRAY_CONTAINS('[]', 1);
SELECT JSON_ARRAY_CONTAINS('[3]', 3);
SELECT JSON_ARRAY_CONTAINS('[-4]', -4);
SELECT JSON_ARRAY_CONTAINS('[[2]]', 2);
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], 6]', 6);
SELECT JSON_ARRAY_CONTAINS('[92233720368547758071]', -9);
SELECT JSON_ARRAY_CONTAINS(JSON '[]', 1);
SELECT JSON_ARRAY_CONTAINS(JSON '[3]', 3);
SELECT JSON_ARRAY_CONTAINS(JSON '[-4]', -4);
SELECT JSON_ARRAY_CONTAINS(JSON '[[2]]', 2);
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], 6]', 6);
SELECT JSON_ARRAY_CONTAINS(JSON '[92233720368547758071]', -9);
SELECT JSON_ARRAY_CONTAINS('[1.5]', 1.5);
SELECT JSON_ARRAY_CONTAINS('[-9.5]', -9.5);
SELECT JSON_ARRAY_CONTAINS('[[2.5]]', 2.5);
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], 6.1]', 6.1);
SELECT JSON_ARRAY_CONTAINS('[9.6E400]', 4.2);
SELECT JSON_ARRAY_CONTAINS(JSON '[1.5]', 1.5);
SELECT JSON_ARRAY_CONTAINS(JSON '[-9.5]', -9.5);
SELECT JSON_ARRAY_CONTAINS(JSON '[[2.5]]', 2.5);
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], 6.1]', 6.1);
SELECT JSON_ARRAY_CONTAINS(JSON '[9.6E400]', 4.2);
SELECT JSON_ARRAY_CONTAINS('[]', 'x');
SELECT JSON_ARRAY_CONTAINS('["foo"]', 'foo');
SELECT JSON_ARRAY_CONTAINS('["8"]', '8');
SELECT JSON_ARRAY_CONTAINS('[1, "foo", null]', 'foo');
SELECT JSON_ARRAY_CONTAINS('[2, 4, {"a": [8, 9]}, [], [5], "6"]', '6');
SELECT JSON_ARRAY_CONTAINS(JSON '[]', 'x');
SELECT JSON_ARRAY_CONTAINS(JSON '["foo"]', 'foo');
SELECT JSON_ARRAY_CONTAINS(JSON '["8"]', '8');
SELECT JSON_ARRAY_CONTAINS(JSON '[1, "foo", null]', 'foo');
SELECT JSON_ARRAY_CONTAINS(JSON '[2, 4, {"a": [8, 9]}, [], [5], "6"]', '6');
SELECT JSON_ARRAY_CONTAINS('[""]', '');
SELECT JSON_ARRAY_CONTAINS('[""]', 'x');
SELECT JSON_ARRAY_GET('["jhfa", null]', 1);
SELECT JSON_ARRAY_GET(JSON '["jhfa", null]', 1);
SELECT JSON_ARRAY_GET('[null]', 0);
SELECT JSON_ARRAY_GET('[3.14, null]', 1);
SELECT JSON_ARRAY_GET(JSON '[3.14, null]', 1);
SELECT JSON_ARRAY_GET('[true, null]', 1);
SELECT JSON_ARRAY_GET(JSON '[true, null]', 1);
