EXPLAIN TEXT (SELECT 1 LIMIT 0.75) PAGE 3; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 0.5) PAGE 1; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 0.5) PAGE 2; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 10) MODIFY LIMIT 0.75, PAGE 3; -- { serverError BAD_ARGUMENTS }

EXPLAIN TEXT (SELECT 1 LIMIT 0.75) ONELINE;
EXPLAIN TEXT (SELECT 1 LIMIT 0.75) MODIFY LIMIT 2, PAGE 3, ONELINE;
EXPLAIN TEXT (SELECT 1 LIMIT 0) PAGE 3, ONELINE;
EXPLAIN TEXT (SELECT 1 LIMIT 2.0) PAGE 3, ONELINE;
EXPLAIN TEXT (SELECT 1 LIMIT 2 + 1) PAGE 3, ONELINE;
