-- `MODIFY OFFSET` rejects either range boundary, including a zero offset.
EXPLAIN TEXT (SELECT 1 LIMIT 3 AFTER 1) MODIFY OFFSET 1; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 UNTIL 0) MODIFY OFFSET 1; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 AFTER 1) MODIFY OFFSET 0; -- { serverError BAD_ARGUMENTS }

-- Every `PAGE` path rejects range limits.
EXPLAIN TEXT (SELECT 1 LIMIT 3 AFTER 1) PAGE 1; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 AFTER 1) PAGE 2; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 AFTER 1) PAGE 3; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 UNTIL 0) PAGE 1; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 UNTIL 0) PAGE 2; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 UNTIL 0) PAGE 3; -- { serverError BAD_ARGUMENTS }

-- Combined boundaries are rejected too.
EXPLAIN TEXT (SELECT 1 LIMIT 3 AFTER 1 UNTIL 0) MODIFY OFFSET 1; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (SELECT 1 LIMIT 3 AFTER 1 UNTIL 0) PAGE 2; -- { serverError BAD_ARGUMENTS }
