SET union_default_mode = '';
SET intersect_default_mode = '';
SET except_default_mode = '';
SET enable_global_with_statement = 1;

EXECUTE AS default EXPLAIN TEXT (SELECT 1 UNION SELECT 2) ONELINE;
EXECUTE AS default EXPLAIN TEXT (SELECT 1 INTERSECT SELECT 2) ONELINE;
EXECUTE AS default EXPLAIN TEXT (SELECT 1 EXCEPT SELECT 2) ONELINE;
EXECUTE AS default EXPLAIN TEXT (WITH 1 AS x SELECT x UNION ALL SELECT 2) ONELINE;

EXPLAIN AST EXPLAIN TEXT (SELECT 1 UNION SELECT 2) ONELINE;
EXPLAIN AST EXPLAIN TEXT (SELECT 1 INTERSECT SELECT 2) ONELINE;
EXPLAIN AST EXPLAIN TEXT (SELECT 1 EXCEPT SELECT 2) ONELINE;

SELECT 1 UNION SELECT 2; -- { serverError EXPECTED_ALL_OR_DISTINCT }
SELECT 1 INTERSECT SELECT 2; -- { serverError EXPECTED_ALL_OR_DISTINCT }
SELECT 1 EXCEPT SELECT 2; -- { serverError EXPECTED_ALL_OR_DISTINCT }
