SELECT formatQuery('EXPLAIN TEXT (SELECT 1) MODIFY LIMIT 1 MODIFY OFFSET 2'); -- { serverError SYNTAX_ERROR }
SELECT formatQuerySingleLine('EXPLAIN TEXT SELECT 1 ONELINE SETTINGS max_threads = 1');

SELECT formatQuerySingleLine('EXPLAIN TEXT (SELECT 1) UNION ALL (SELECT 2) FORMAT CSV');
SELECT formatQuerySingleLine('EXPLAIN TEXT (SELECT 1) EXCEPT SELECT 2 ONELINE');
EXPLAIN TEXT (EXECUTE AS default SELECT 1) MODIFY FORMAT CSV, ONELINE;
EXPLAIN TEXT (EXECUTE AS default SELECT 1 FORMAT TSV) MODIFY FORMAT CSV, ONELINE;
EXPLAIN TEXT (SELECT 1 PARALLEL WITH SELECT 2) MODIFY FORMAT CSV, ONELINE;
EXPLAIN TEXT (EXECUTE AS default SET max_threads = 1) MODIFY FORMAT CSV; -- { serverError BAD_ARGUMENTS }
EXPLAIN TEXT (EXECUTE AS default INSERT INTO t SELECT 1) MODIFY FORMAT CSV; -- { serverError BAD_ARGUMENTS }
EXPLAIN AST optimize = 1 EXPLAIN TEXT (SELECT * FROM __explain_text_missing_table) ONELINE;
EXPLAIN AST optimize = 1 EXPLAIN TEXT (SELECT {p:UInt64}) ONELINE;
