EXPLAIN TEXT EXPLAIN AST INSERT INTO t SELECT 1 FORMAT JSONEachRow;

SELECT formatQuerySingleLine(q) = formatQuerySingleLine(expected)
FROM values('q String, expected String',
    (
        'EXPLAIN TEXT EXPLAIN AST INSERT INTO t SELECT 1 FORMAT JSONEachRow',
        'EXPLAIN TEXT (EXPLAIN AST INSERT INTO t SELECT 1) FORMAT JSONEachRow'
    ),
    (
        'EXPLAIN TEXT EXPLAIN PLAN INSERT INTO t SELECT 1 FORMAT JSONEachRow',
        'EXPLAIN TEXT (EXPLAIN PLAN INSERT INTO t SELECT 1) FORMAT JSONEachRow'
    ),
    (
        'EXPLAIN TEXT EXPLAIN AST EXPLAIN AST INSERT INTO t SELECT 1 FORMAT JSONEachRow',
        'EXPLAIN TEXT (EXPLAIN AST EXPLAIN AST INSERT INTO t SELECT 1) FORMAT JSONEachRow'
    ),
    (
        'EXPLAIN TEXT EXECUTE AS default EXPLAIN AST INSERT INTO t SELECT 1 FORMAT JSONEachRow',
        'EXPLAIN TEXT (EXECUTE AS default EXPLAIN AST INSERT INTO t SELECT 1) FORMAT JSONEachRow'
    ),
    (
        'EXPLAIN TEXT EXPLAIN AST SELECT 1 FORMAT JSONEachRow',
        'EXPLAIN TEXT (EXPLAIN AST SELECT 1) FORMAT JSONEachRow'
    ),
    (
        'EXPLAIN TEXT EXPLAIN AST (INSERT INTO t SELECT 1 FORMAT CSV)',
        'EXPLAIN TEXT (EXPLAIN AST INSERT INTO t SELECT 1 FORMAT CSV)'
    ),
    (
        'EXPLAIN TEXT EXPLAIN AST INSERT INTO t SELECT 1 FORMAT CSV FORMAT JSONEachRow',
        'EXPLAIN TEXT (EXPLAIN AST INSERT INTO t SELECT 1 FORMAT CSV) FORMAT JSONEachRow'
    ));
