-- Window frame definitions that must be rejected, and the borderline ones that are accepted.

SELECT '-- RANGE with an offset needs exactly one ORDER BY column';
SELECT count() OVER (RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number, number % 2 RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number, number % 2 RANGE BETWEEN UNBOUNDED PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number, number % 2 RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS c FROM numbers(3));

SELECT '-- ORDER BY key types without RANGE offset support';
SELECT count() OVER (ORDER BY toString(number) RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toFixedString(toString(number), 1) RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toDecimal32(number, 2) RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toDecimal128(number, 2) RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toDateTime64(number, 3, 'UTC') RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toUInt128(number) RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toInt256(number) RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toLowCardinality(number) RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }
SELECT count() OVER (ORDER BY toUUID('00000000-0000-0000-0000-000000000001') RANGE BETWEEN 1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError NOT_IMPLEMENTED }

SELECT '-- Offsets must be non-negative integer constants';
SELECT count() OVER (ORDER BY number RANGE BETWEEN 'a' PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN NULL PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN CURRENT ROW AND NULL FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN 1.5 PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN 1.0 PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY toFloat64(number) RANGE BETWEEN 0.5 PRECEDING AND 0.5 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN number PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN CURRENT ROW AND number FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN number PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }

SELECT '-- Negative offsets in every position';
SELECT count() OVER (ORDER BY number ROWS BETWEEN -1 PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN -1 FOLLOWING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN CURRENT ROW AND -1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN 2 PRECEDING AND -1 PRECEDING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN -1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number DESC RANGE BETWEEN -1 PRECEDING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN 1 PRECEDING AND -1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number DESC RANGE BETWEEN 1 PRECEDING AND -1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN -1 PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN 1 PRECEDING AND -1 PRECEDING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }

SELECT '-- Offsets that do not fit into 32 bits';
SELECT count() OVER (ORDER BY number ROWS BETWEEN 4294967296 PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN CURRENT ROW AND 4294967296 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN 4294967296 PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN 4294967296 PRECEDING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }

SELECT '-- Constant expressions are accepted as offsets';
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number RANGE BETWEEN 1 + 1 PRECEDING AND CURRENT ROW) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number ROWS BETWEEN toUInt8(2) PRECEDING AND CURRENT ROW) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number GROUPS BETWEEN CURRENT ROW AND (SELECT 1) FOLLOWING) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number RANGE BETWEEN 2147483646 PRECEDING AND CURRENT ROW) AS c FROM numbers(4));

SELECT '-- The frame start must not be after the frame end';
SELECT count() OVER (ORDER BY number ROWS BETWEEN UNBOUNDED FOLLOWING AND UNBOUNDED PRECEDING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED PRECEDING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN UNBOUNDED FOLLOWING AND UNBOUNDED FOLLOWING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN UNBOUNDED FOLLOWING AND CURRENT ROW) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN CURRENT ROW AND UNBOUNDED PRECEDING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN CURRENT ROW AND 1 PRECEDING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN 1 FOLLOWING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN 2 FOLLOWING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS BETWEEN 1 PRECEDING AND 2 PRECEDING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number ROWS UNBOUNDED FOLLOWING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN UNBOUNDED FOLLOWING AND CURRENT ROW) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN CURRENT ROW AND UNBOUNDED PRECEDING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN 1 FOLLOWING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN CURRENT ROW AND 1 PRECEDING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN 2 FOLLOWING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE BETWEEN 1 PRECEDING AND 2 PRECEDING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number RANGE UNBOUNDED FOLLOWING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN UNBOUNDED FOLLOWING AND CURRENT ROW) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN CURRENT ROW AND UNBOUNDED PRECEDING) FROM numbers(3); -- { clientError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN 1 FOLLOWING AND CURRENT ROW) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN 2 FOLLOWING AND 1 FOLLOWING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }
SELECT count() OVER (ORDER BY number GROUPS BETWEEN 1 PRECEDING AND 2 PRECEDING) FROM numbers(3); -- { serverError BAD_ARGUMENTS }

SELECT '-- Equal bounds and the one-sided shorthand are accepted';
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number ROWS BETWEEN CURRENT ROW AND CURRENT ROW) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number RANGE BETWEEN 1 PRECEDING AND 1 PRECEDING) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number GROUPS BETWEEN 1 FOLLOWING AND 1 FOLLOWING) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number ROWS 1 PRECEDING) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number ROWS CURRENT ROW) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number RANGE 2 PRECEDING) AS c FROM numbers(4));
SELECT groupArray(c) FROM (SELECT count() OVER (ORDER BY number GROUPS UNBOUNDED PRECEDING) AS c FROM numbers(4));
