-- In a `Memory` database the name of a detached table, view or dictionary stays reserved: `CREATE`, `CREATE OR REPLACE` and a full `ATTACH` are refused before anything is built, and a short `ATTACH` restores the original definition.

DROP DATABASE IF EXISTS {CLICKHOUSE_DATABASE_1:Identifier};
CREATE DATABASE {CLICKHOUSE_DATABASE_1:Identifier} ENGINE = Memory;
USE {CLICKHOUSE_DATABASE_1:Identifier};

CREATE TABLE src (x UInt64) ENGINE = Null;
CREATE TABLE dst (x UInt64) ENGINE = Null;

CREATE VIEW v AS SELECT 1 AS a;
DETACH TABLE v;
CREATE VIEW v AS SELECT 2 AS b; -- { serverError TABLE_ALREADY_EXISTS }
CREATE OR REPLACE VIEW v AS SELECT 2 AS b; -- { serverError TABLE_ALREADY_EXISTS }
CREATE VIEW IF NOT EXISTS v AS SELECT 2 AS b;
ATTACH TABLE v;
SHOW CREATE TABLE v;

CREATE MATERIALIZED VIEW mv TO dst AS SELECT x FROM src;
DETACH TABLE mv;
CREATE OR REPLACE MATERIALIZED VIEW mv REFRESH EVERY 1 HOUR APPEND TO dst EMPTY AS SELECT x FROM src; -- { serverError TABLE_ALREADY_EXISTS }
CREATE TABLE mv (x UInt64) ENGINE = Null; -- { serverError TABLE_ALREADY_EXISTS }
ATTACH TABLE mv;
ALTER TABLE mv MODIFY COMMENT 'c';
SHOW CREATE TABLE mv;

CREATE VIEW w AS SELECT 1 AS a;
DETACH TABLE w;
ATTACH TABLE w (x UInt64) ENGINE = MergeTree ORDER BY x; -- { serverError TABLE_ALREADY_EXISTS }
ATTACH TABLE w;
DROP TABLE w;
CREATE TABLE w (x UInt64) ENGINE = MergeTree ORDER BY x;
DROP TABLE w;

CREATE TABLE u (a Int32) ENGINE = Null;
DETACH TABLE u;
ATTACH TABLE u (b String) ENGINE = Null; -- { serverError TABLE_ALREADY_EXISTS }
ATTACH TABLE IF NOT EXISTS u (b String) ENGINE = Null;
ATTACH TABLE u;
SHOW CREATE TABLE u;

CREATE DICTIONARY dict (k UInt64, v String) PRIMARY KEY k SOURCE(NULL()) LAYOUT(FLAT()) LIFETIME(0);
DETACH DICTIONARY dict;
CREATE DICTIONARY dict (k UInt64, v2 String) PRIMARY KEY k SOURCE(NULL()) LAYOUT(FLAT()) LIFETIME(0); -- { serverError TABLE_ALREADY_EXISTS }
CREATE DICTIONARY IF NOT EXISTS dict (k UInt64, v2 String) PRIMARY KEY k SOURCE(NULL()) LAYOUT(FLAT()) LIFETIME(0);
ATTACH DICTIONARY dict;
SHOW CREATE DICTIONARY dict;

DROP DATABASE {CLICKHOUSE_DATABASE_1:Identifier};
