#!/usr/bin/env bash
# Tags: no-fasttest

CUR_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=../shell_config.sh
. "$CUR_DIR"/../shell_config.sh

# Parquet files with 200 rows in one dictionary-encoded String column s.
ZSTD='UEFSMRUEFYQCFaQBTBUoFQASAAAotS/9IIJNAgBkAgIAAAB2MAIAAAB2MTIzNDU2Nzg5AzEwMTIzNDU2NzgDAAAAdjE5EQBgCBgHBgNDwDgwGBhCZTAIBMdAEyAHjoEmQA4cS1voFQAVjAIVZiwVkAMVEBUGFQYcAAAAKLUv/SCGVQEAJAIDAAAAkAMBBTMgiEGKOSipxZp7MMoJghikmIOSWqy5B6OcAQAKnM4nFQQZLDUAGAZzY2hlbWEVAgAVDCUCGAFzJQBMHAAAABaQAxkcGRwmABwVDBk1AAYQGRgBcxUMFpADFtoEFtQCJswBJggpLBUEFQAVAgAVABUQFQIAPBboBxkGGSYAkAMAAAAW2gQWkAMmCBbUAgAZHBgMQVJST1c6c2NoZW1hGKABLy8vLy8zQUFBQUFRQUFBQUFBQUtBQXdBQmdBRkFBZ0FDZ0FBQUFBQkJBQU1BQUFBQ0FBSUFBQUFCQUFJQUFBQUJBQUFBQUVBQUFBVUFBQUFFQUFVQUFnQUJnQUhBQXdBQUFBUUFCQUFBQUFBQUFFRkVBQUFBQmdBQUFBRUFBQUFBQUFBQUFFQUFBQnpBQUFBQkFBRUFBUUFBQUFBQUFBQQAYIHBhcnF1ZXQtY3BwLWFycm93IHZlcnNpb24gMjQuMC4wGRwcAAAASgEAAFBBUjE='
BROTLI='UEFSMRUEFYQCFVRMFSgVABIAABuBAABEL0Y7YjH+XFBMbn5PgWIcWVUcTwC8RS6k0sbO6dHEvCirumn3ABUAFYwCFW4sFZADFRAVBhUGHAAAABuFAABk6uaPCRaG4aIw0UizMamLpo0N0vkOEKMCjwEABYbUUlMnt7X1ajz9l74yVEHpHifvOwIVBBksNQAYBnNjaGVtYRUCABUMJQIYAXMlAEwcAAAAFpADGRwZHCYAHBUMGTUABhAZGAFzFQgWkAMW2AQWigImeiYIKSwVBBUAFQIAFQAVEBUCADwW6AcZBhkmAJADAAAAFtgEFpADJggWigIAGRwYDEFSUk9XOnNjaGVtYRigAS8vLy8vM0FBQUFBUUFBQUFBQUFLQUF3QUJnQUZBQWdBQ2dBQUFBQUJCQUFNQUFBQUNBQUlBQUFBQkFBSUFBQUFCQUFBQUFFQUFBQVVBQUFBRUFBVUFBZ0FCZ0FIQUF3QUFBQVFBQkFBQUFBQUFBRUZFQUFBQUJnQUFBQUVBQUFBQUFBQUFBRUFBQUJ6QUFBQUJBQUVBQVFBQUFBQUFBQUEAGCBwYXJxdWV0LWNwcC1hcnJvdyB2ZXJzaW9uIDI0LjAuMBkcHAAAAEkBAABQQVIx'

${CLICKHOUSE_LOCAL} --query "SELECT count() FROM format(Parquet, base64Decode('$ZSTD')) WHERE s != ''"
${CLICKHOUSE_LOCAL} --query "SELECT count() FROM format(Parquet, base64Decode('$BROTLI')) WHERE s != ''"

# A page that decompresses to fewer bytes than its header declares must fail with INCORRECT_DATA instead of looping
# forever. Patched dictionary page headers: ZSTD compressed_page_size 82 -> 81 (#123274), Brotli uncompressed_page_size
# 130 -> 131.
for DATA in "overlay(base64Decode('$ZSTD'), '\\xA2', 11)" "overlay(base64Decode('$BROTLI'), '\\x86', 8)"; do
    timeout -k 10 60 ${CLICKHOUSE_LOCAL} --query "SELECT count() FROM format(Parquet, $DATA) WHERE s != ''" 2>&1 \
        | grep -o -m1 'INCORRECT_DATA'
done
