DROP TABLE IF EXISTS A;
DROP TABLE IF EXISTS B;

CREATE TABLE A (ID UInt32, COL_1 String, COL_2 String) ENGINE = MergeTree() ORDER BY(ID);
INSERT INTO A VALUES(0, 'Hello', 'Country');
INSERT INTO A VALUES(1, 'XYZ', 'ABC');
INSERT INTO A VALUES(2, 'Hello', 'Island');

CREATE TABLE B (ID UInt32, COL_1 String, COL_2 String) ENGINE = MergeTree() ORDER BY(ID);
INSERT INTO B VALUES(0, 'Hello', 'Ocean');

SELECT A.COL_1, A.COL_2, B.COL_2 FROM A JOIN B ON A.COL_1 = B.COL_1
