name: Common setup
description: Setup necessary environments
inputs:
  job_type:
    description: the name to use in the TEMP_PATH and REPO_COPY
    default: common
    type: string
  nested_job:
    description: the fuse for unintended use inside of the reusable callable jobs
    default: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Setup and check ENV
      shell: bash
      run: |
          echo "Setup the common ENV variables"
          cat >> "$GITHUB_ENV" << 'EOF'
          TEMP_PATH=${{runner.temp}}/${{inputs.job_type}}
          EOF
          if [ -z "${{env.GITHUB_JOB_OVERRIDDEN}}" ] && [ "true" == "${{inputs.nested_job}}" ]; then
            echo "The GITHUB_JOB_OVERRIDDEN ENV is unset, and must be set for the nested jobs"
            exit 1
          fi
    - name: Setup $TEMP_PATH
      shell: bash
      run: |
          # to remove every leftovers
          sudo rm -fr "$TEMP_PATH" && mkdir -p "$TEMP_PATH"
    - name: Setup zram
      shell: bash
      run: |
          sudo modprobe zram
          MemTotal=$(grep -Po "(?<=MemTotal:)\s+\d+" /proc/meminfo) # KiB
          Percent=200
          ZRAM_SIZE=$(($MemTotal / 1024 / 1024 * $Percent / 100)) # Convert to GiB
          .github/retry.sh 30 2 sudo zramctl --size ${ZRAM_SIZE}GiB --algorithm zstd /dev/zram0
          sudo mkswap /dev/zram0 && sudo swapon -p 100 /dev/zram0
          sudo sysctl vm.swappiness=200
    - name: Tune vm.mmap_rnd_bits for sanitizers
      shell: bash
      run: |
          sudo sysctl vm.mmap_rnd_bits
          # https://github.com/google/sanitizers/issues/856
          echo "Tune vm.mmap_rnd_bits for sanitizers"
          sudo sysctl vm.mmap_rnd_bits=28
