name: Common setup
description: Setup necessary environments
inputs:
  job_type:
    description: the name to use in the TEMP_PATH and REPO_COPY
    default: common
    type: string
  nested_job:
    description: the fuse for unintended use inside of the reusable callable jobs
    default: true
    type: boolean
runs:
  using: "composite"
  steps:
    - name: Setup and check ENV
      shell: bash
      run: |
          echo "Setup the common ENV variables"
          cat >> "$GITHUB_ENV" << 'EOF'
          TEMP_PATH=${{runner.temp}}/${{inputs.job_type}}
          EOF
          if [ -z "${{env.GITHUB_JOB_OVERRIDDEN}}" ] && [ "true" == "${{inputs.nested_job}}" ]; then
            echo "The GITHUB_JOB_OVERRIDDEN ENV is unset, and must be set for the nested jobs"
            exit 1
          fi
    - name: Setup $TEMP_PATH
      shell: bash
      run: |
          # to remove every leftovers
          sudo rm -fr "$TEMP_PATH" && mkdir -p "$TEMP_PATH"
    # https://github.com/google/sanitizers/issues/856
    - name: Tune vm.mmap_rnd_bits for sanitizers
      shell: bash
      run: |
          sudo sysctl vm.mmap_rnd_bits
          sudo sysctl vm.mmap_rnd_bits=28
    - name: Tune kernel.task_delayacct=1 for OSIOWaitMicroseconds
      shell: bash
      run: |
          sudo sysctl kernel.task_delayacct
          sudo sysctl kernel.task_delayacct=1
    - name: Avoid relying on internal AWS DNS
      shell: bash
      run: |
          fqdn=$(hostname --fqdn)
          echo "Current FQDN: $fqdn"
          echo "127.0.0.1 $fqdn" | sudo tee -a /etc/hosts
          resolvectl flush-caches
          resolvectl query "$fqdn"
          # Sometimes it tries to resolve the address using NSes:
          #
          #     ip-172-31-33-98.ec2.internal has address 127.0.0.1
          #     Host ip-172-31-33-98.ec2.internal not found: 3(NXDOMAIN)
          #
          # So let's ignore the error
          host "$fqdn" || true
