#define NO_METRIKA
#include <common/Test.h>
#include <vector>
#include <string>
#include <common/JSON.h>

#include <boost/range/irange.hpp>

using namespace std::literals::string_literals;

enum class ResultType
{
	Return,
	Throw
};

struct GetStringTestRecord
{
	std::string input;
	ResultType result_type;
	std::string result;
};

void get_string()
{
	/// Inspired by http://robthedoodler.deviantart.com/art/Coo-man-407376198
	std::vector<GetStringTestRecord> test_data =
	{
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Вафельница Vitek WX-1102 FL")COO"s, ResultType::Return, R"MAN(Вафельница Vitek WX-1102 FL)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("184509")COO"s, ResultType::Return, R"MAN(184509)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("Все для детей/Детская техника/Vitek")COO"s, ResultType::Return, R"MAN(Все для детей/Детская техника/Vitek)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("В наличии")COO"s, ResultType::Return, R"MAN(В наличии)MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("2390.00")COO"s, ResultType::Return, R"MAN(2390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("Карточка")COO"s, ResultType::Return, R"MAN(Карточка)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("detail")COO"s, ResultType::Return, R"MAN(detail)MAN"s },
		{ R"COO("actionField")COO"s, ResultType::Return, R"MAN(actionField)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("http://www.techport.ru/q/?t=вафельница&sort=price&sdim=asc")COO"s, ResultType::Return, R"MAN(http://www.techport.ru/q/?t=вафельница&sort=price&sdim=asc)MAN"s },
		{ R"COO("action")COO"s, ResultType::Return, R"MAN(action)MAN"s },
		{ R"COO("detail")COO"s, ResultType::Return, R"MAN(detail)MAN"s },
		{ R"COO("products")COO"s, ResultType::Return, R"MAN(products)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Вафельница Vitek WX-1102 FL")COO"s, ResultType::Return, R"MAN(Вафельница Vitek WX-1102 FL)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("184509")COO"s, ResultType::Return, R"MAN(184509)MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("2390.00")COO"s, ResultType::Return, R"MAN(2390.00)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("Vitek")COO"s, ResultType::Return, R"MAN(Vitek)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("Все для детей/Детская техника/Vitek")COO"s, ResultType::Return, R"MAN(Все для детей/Детская техника/Vitek)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("В наличии")COO"s, ResultType::Return, R"MAN(В наличии)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("isAuthorized")COO"s, ResultType::Return, R"MAN(isAuthorized)MAN"s },
		{ R"COO("isSubscriber")COO"s, ResultType::Return, R"MAN(isSubscriber)MAN"s },
		{ R"COO("postType")COO"s, ResultType::Return, R"MAN(postType)MAN"s },
		{ R"COO("Новости")COO"s, ResultType::Return, R"MAN(Новости)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("Электроплита GEFEST Брест ЭПНД 5140-01 0001")COO"s, ResultType::Return, R"MAN(Электроплита GEFEST Брест ЭПНД 5140-01 0001)MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("currencyCode")COO"s, ResultType::Return, R"MAN(currencyCode)MAN"s },
		{ R"COO("RUB")COO"s, ResultType::Return, R"MAN(RUB)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("trash_login")COO"s, ResultType::Return, R"MAN(trash_login)MAN"s },
		{ R"COO("novikoff")COO"s, ResultType::Return, R"MAN(novikoff)MAN"s },
		{ R"COO("trash_cat_link")COO"s, ResultType::Return, R"MAN(trash_cat_link)MAN"s },
		{ R"COO("progs")COO"s, ResultType::Return, R"MAN(progs)MAN"s },
		{ R"COO("trash_parent_link")COO"s, ResultType::Return, R"MAN(trash_parent_link)MAN"s },
		{ R"COO("content")COO"s, ResultType::Return, R"MAN(content)MAN"s },
		{ R"COO("trash_posted_parent")COO"s, ResultType::Return, R"MAN(trash_posted_parent)MAN"s },
		{ R"COO("content.01.2016")COO"s, ResultType::Return, R"MAN(content.01.2016)MAN"s },
		{ R"COO("trash_posted_cat")COO"s, ResultType::Return, R"MAN(trash_posted_cat)MAN"s },
		{ R"COO("progs.01.2016")COO"s, ResultType::Return, R"MAN(progs.01.2016)MAN"s },
		{ R"COO("trash_virus_count")COO"s, ResultType::Return, R"MAN(trash_virus_count)MAN"s },
		{ R"COO("trash_is_android")COO"s, ResultType::Return, R"MAN(trash_is_android)MAN"s },
		{ R"COO("trash_is_wp8")COO"s, ResultType::Return, R"MAN(trash_is_wp8)MAN"s },
		{ R"COO("trash_is_ios")COO"s, ResultType::Return, R"MAN(trash_is_ios)MAN"s },
		{ R"COO("trash_posted")COO"s, ResultType::Return, R"MAN(trash_posted)MAN"s },
		{ R"COO("01.2016")COO"s, ResultType::Return, R"MAN(01.2016)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("merchantId")COO"s, ResultType::Return, R"MAN(merchantId)MAN"s },
		{ R"COO("13694_49246")COO"s, ResultType::Return, R"MAN(13694_49246)MAN"s },
		{ R"COO("cps-source")COO"s, ResultType::Return, R"MAN(cps-source)MAN"s },
		{ R"COO("wargaming")COO"s, ResultType::Return, R"MAN(wargaming)MAN"s },
		{ R"COO("cps_provider")COO"s, ResultType::Return, R"MAN(cps_provider)MAN"s },
		{ R"COO("default")COO"s, ResultType::Return, R"MAN(default)MAN"s },
		{ R"COO("errorReason")COO"s, ResultType::Return, R"MAN(errorReason)MAN"s },
		{ R"COO("no errors")COO"s, ResultType::Return, R"MAN(no errors)MAN"s },
		{ R"COO("scid")COO"s, ResultType::Return, R"MAN(scid)MAN"s },
		{ R"COO("isAuthPayment")COO"s, ResultType::Return, R"MAN(isAuthPayment)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("rubric")COO"s, ResultType::Return, R"MAN(rubric)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("rubric")COO"s, ResultType::Return, R"MAN(rubric)MAN"s },
		{ R"COO("Мир")COO"s, ResultType::Return, R"MAN(Мир)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("__ym")COO"s, ResultType::Return, R"MAN(__ym)MAN"s },
		{ R"COO("ecommerce")COO"s, ResultType::Return, R"MAN(ecommerce)MAN"s },
		{ R"COO("impressions")COO"s, ResultType::Return, R"MAN(impressions)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("863813")COO"s, ResultType::Return, R"MAN(863813)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Happy, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Happy, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("863839")COO"s, ResultType::Return, R"MAN(863839)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Pretty kitten, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Pretty kitten, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("863847")COO"s, ResultType::Return, R"MAN(863847)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Little tiger, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Little tiger, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911480")COO"s, ResultType::Return, R"MAN(911480)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Puppy, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Puppy, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911484")COO"s, ResultType::Return, R"MAN(911484)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Little bears, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Little bears, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911489")COO"s, ResultType::Return, R"MAN(911489)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Dolphin, возраст 2-4 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Dolphin, возраст 2-4 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911496")COO"s, ResultType::Return, R"MAN(911496)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Pretty, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Pretty, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911504")COO"s, ResultType::Return, R"MAN(911504)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Fairytale, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Fairytale, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911508")COO"s, ResultType::Return, R"MAN(911508)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Kittens, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Kittens, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911512")COO"s, ResultType::Return, R"MAN(911512)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Sunshine, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Sunshine, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911516")COO"s, ResultType::Return, R"MAN(911516)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Dog in bag, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Dog in bag, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911520")COO"s, ResultType::Return, R"MAN(911520)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Cute puppy, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Cute puppy, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911524")COO"s, ResultType::Return, R"MAN(911524)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Rabbit, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Rabbit, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("911528")COO"s, ResultType::Return, R"MAN(911528)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Футболка детская 3D Turtle, возраст 1-2 года, трикотаж")COO"s, ResultType::Return, R"MAN(Футболка детская 3D Turtle, возраст 1-2 года, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("390.00")COO"s, ResultType::Return, R"MAN(390.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("888616")COO"s, ResultType::Return, R"MAN(888616)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("3Д Футболка мужская \"Collorista\" Светлое завтра р-р XL(52-54), 100% хлопок, трикотаж")COO"s, ResultType::Return, R"MAN(3Д Футболка мужская "Collorista" Светлое завтра р-р XL(52-54), 100% хлопок, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Одежда и обувь/Мужская одежда/Футболки/")COO"s, ResultType::Return, R"MAN(/Одежда и обувь/Мужская одежда/Футболки/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("406.60")COO"s, ResultType::Return, R"MAN(406.60)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("913361")COO"s, ResultType::Return, R"MAN(913361)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("3Д Футболка детская World р-р 8-10, 100% хлопок, трикотаж")COO"s, ResultType::Return, R"MAN(3Д Футболка детская World р-р 8-10, 100% хлопок, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("470.00")COO"s, ResultType::Return, R"MAN(470.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("913364")COO"s, ResultType::Return, R"MAN(913364)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("3Д Футболка детская Force р-р 8-10, 100% хлопок, трикотаж")COO"s, ResultType::Return, R"MAN(3Д Футболка детская Force р-р 8-10, 100% хлопок, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("470.00")COO"s, ResultType::Return, R"MAN(470.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("913367")COO"s, ResultType::Return, R"MAN(913367)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("3Д Футболка детская Winter tale р-р 8-10, 100% хлопок, трикотаж")COO"s, ResultType::Return, R"MAN(3Д Футболка детская Winter tale р-р 8-10, 100% хлопок, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("470.00")COO"s, ResultType::Return, R"MAN(470.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("913385")COO"s, ResultType::Return, R"MAN(913385)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("3Д Футболка детская Moonshine р-р 8-10, 100% хлопок, трикотаж")COO"s, ResultType::Return, R"MAN(3Д Футболка детская Moonshine р-р 8-10, 100% хлопок, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("470.00")COO"s, ResultType::Return, R"MAN(470.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("913391")COO"s, ResultType::Return, R"MAN(913391)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("3Д Футболка детская Shaman р-р 8-10, 100% хлопок, трикотаж")COO"s, ResultType::Return, R"MAN(3Д Футболка детская Shaman р-р 8-10, 100% хлопок, трикотаж)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("/Летние товары/Летний текстиль/")COO"s, ResultType::Return, R"MAN(/Летние товары/Летний текстиль/)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("")COO"s, ResultType::Return, R"MAN()MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("470.00")COO"s, ResultType::Return, R"MAN(470.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("/retailrocket/")COO"s, ResultType::Return, R"MAN(/retailrocket/)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/")COO"s, ResultType::Return, R"MAN(/911488/futbolka-detskaya-3d-dolphin-vozrast-1-2-goda-trikotazh/)MAN"s },
		{ R"COO("usertype")COO"s, ResultType::Return, R"MAN(usertype)MAN"s },
		{ R"COO("visitor")COO"s, ResultType::Return, R"MAN(visitor)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("__ym")COO"s, ResultType::Return, R"MAN(__ym)MAN"s },
		{ R"COO("ecommerce")COO"s, ResultType::Return, R"MAN(ecommerce)MAN"s },
		{ R"COO("impressions")COO"s, ResultType::Return, R"MAN(impressions)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("experiments")COO"s, ResultType::Return, R"MAN(experiments)MAN"s },
		{ R"COO("lang")COO"s, ResultType::Return, R"MAN(lang)MAN"s },
		{ R"COO("ru")COO"s, ResultType::Return, R"MAN(ru)MAN"s },
		{ R"COO("los_portal")COO"s, ResultType::Return, R"MAN(los_portal)MAN"s },
		{ R"COO("los_level")COO"s, ResultType::Return, R"MAN(los_level)MAN"s },
		{ R"COO("none")COO"s, ResultType::Return, R"MAN(none)MAN"s },
		{ R"COO("__ym")COO"s, ResultType::Return, R"MAN(__ym)MAN"s },
		{ R"COO("ecommerce")COO"s, ResultType::Return, R"MAN(ecommerce)MAN"s },
		{ R"COO("currencyCode")COO"s, ResultType::Return, R"MAN(currencyCode)MAN"s },
		{ R"COO("RUR")COO"s, ResultType::Return, R"MAN(RUR)MAN"s },
		{ R"COO("impressions")COO"s, ResultType::Return, R"MAN(impressions)MAN"s },
		{ R"COO("name")COO"s, ResultType::Return, R"MAN(name)MAN"s },
		{ R"COO("Чайник электрический Mystery MEK-1627, белый")COO"s, ResultType::Return, R"MAN(Чайник электрический Mystery MEK-1627, белый)MAN"s },
		{ R"COO("brand")COO"s, ResultType::Return, R"MAN(brand)MAN"s },
		{ R"COO("Mystery")COO"s, ResultType::Return, R"MAN(Mystery)MAN"s },
		{ R"COO("id")COO"s, ResultType::Return, R"MAN(id)MAN"s },
		{ R"COO("187180")COO"s, ResultType::Return, R"MAN(187180)MAN"s },
		{ R"COO("category")COO"s, ResultType::Return, R"MAN(category)MAN"s },
		{ R"COO("Мелкая бытовая техника/Мелкие кухонные приборы/Чайники электрические/Mystery")COO"s, ResultType::Return, R"MAN(Мелкая бытовая техника/Мелкие кухонные приборы/Чайники электрические/Mystery)MAN"s },
		{ R"COO("variant")COO"s, ResultType::Return, R"MAN(variant)MAN"s },
		{ R"COO("В наличии")COO"s, ResultType::Return, R"MAN(В наличии)MAN"s },
		{ R"COO("price")COO"s, ResultType::Return, R"MAN(price)MAN"s },
		{ R"COO("1630.00")COO"s, ResultType::Return, R"MAN(1630.00)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO("Карточка")COO"s, ResultType::Return, R"MAN(Карточка)MAN"s },
		{ R"COO("position")COO"s, ResultType::Return, R"MAN(position)MAN"s },
		{ R"COO("detail")COO"s, ResultType::Return, R"MAN(detail)MAN"s },
		{ R"COO("actionField")COO"s, ResultType::Return, R"MAN(actionField)MAN"s },
		{ R"COO("list")COO"s, ResultType::Return, R"MAN(list)MAN"s },
		{ R"COO( ")COO"s, ResultType::Throw, R"MAN(JSON: expected ", got  )MAN"s },
		{ R"COO("/igrushki/konstruktory )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/1290414/komplekt-zhenskiy-dzhemper-plusbryuki-m-254-09-malina-plustemno-siniy- a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Творчество/Рисование/Инструменты и кра a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Строительство и ремонт/Силовая техника/Зарядные устройства для автомобильных аккумуляторов/Пуско-зарядные устр  a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Строительство и ремонт/Силовая техника/Зарядные устройств  t)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Строительство и ремонт/Силовая техника/Зарядные устройства для автомобиль k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO( t)COO"s, ResultType::Throw, R"MAN(JSON: expected ", got  )MAN"s },
		{ R"COO("/Хозтовары/Хранение вещей и организа  t)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Хозтовары/Товары для стир a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("li a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/734859/samolet-radioupravlyaemyy-istrebitel-rabotaet-o k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/kosmetika-i-parfyum/parfyumeriya/mu t)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/ko )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO()COO"s, ResultType::Throw, R"MAN(JSON: expected ", got  )MAN"s },
		{ R"COO("/stroitelstvo-i-remont/stroit t)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/stroitelstvo-i-remont/stroitelnyy-instrument/av k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/s a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Строительство и ремонт/Строительный инструмент/Изм e)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/avto/soputstvuy l)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/str  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Отвертка 2 в 1 \"TUNDRA basic\" 5х75 мм (+,-)   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/stroitelstvo-i-remont/stroitelnyy-instrument/avtoinstrumen  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Мелкая бытовая техника/Мелки   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Пряжа \"Бамбук стрейч\   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Карандаш чёрнографитны   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Творчество/Рукоделие, аппликации/Пряжа и шерсть для   l)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/1071547/karandash-chernografitnyy-volshebstvo-nv-kruglyy-d-7-2mm-dl-176mm-plast-tuba/ e)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("ca e)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("ca e)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/1165424/chipbord-vyrubnoy-dlya-skrapbukinga-malyshi-mikki-maus-disney-bebi t)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/posuda/kuhonnye-prinadlezhnosti-i-i d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Канцтовары/Ежедневники и блокн   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/kanctovary/ezhednevniki-i-blok a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Стакан   a)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Набор бумаги для скрапбукинга \"Мои первый годик\": Микки Маус, Дисней бэби, 12 листов 29.5 х 29.5 см, 160  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("c  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Органайзер для хранения аксессуаров,   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("quantity 0)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Сменный блок для тетрадей на кольцах А5, 160 листов клетка, офсет    =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Сувениры/Ф   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO(" ")COO"s, ResultType::Return, R"MAN( )MAN"s },
		{ R"COO(" )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("va  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("ca  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("В  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/letnie-tovary/z )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Посудомоечная машина Ha =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Крупная бытов  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Полочная акустическая система Magnat Needl  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("brand 0)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO(" d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("pos  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("c o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("var  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Телевизоры и видеотехника/Всё для домашних кинотеатр =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Флеш-диск Transcend JetFlash 620 8GB (TS8GJF62  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Табурет Мег  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("variant )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Катал  ")COO"s, ResultType::Return, R"MAN(Катал  )MAN"s },
		{ R"COO("К  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Полочная акустическая система Magnat Needl  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("brand 0)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO(" d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("pos  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("c o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("17 o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/igrushki/razvivayusc  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Ключница \"  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Игр   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Игрушки/Игрушки для девочек/Игровые модули дл  o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Крупная бытовая техника/Стиральные машины/С фронт  o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO(  )COO"s, ResultType::Throw, R"MAN(JSON: expected ", got  )MAN"s },
		{ R"COO("Светодиодная лента SMD3528, 5 м. IP33, 60LED, зеленый, 4,8W/мет   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Сантехника/Мебель для ванных комнат/Стол o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO( o)COO"s, ResultType::Throw, R"MAN(JSON: expected ", got  )MAN"s },
		{ R"COO("/igrushki/konstruktory  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/posuda/kuhonnye-prinadlezhnosti-i-instrumenty/kuhonnye-pr  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/1290414/komplekt-zhenskiy-dzhemper-plusbryuki-m-254-09-malina-plustemno-siniy- o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Творчество/Рисование/Инструменты и кра o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Строительство и ремонт/Силовая техника/Зарядные устройства для автомобильных аккумуляторов/Пуско-зарядные устр  o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Строительство и ремонт/Силовая техника/Зарядные устройств   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Строительство и ремонт/Силовая техника/Зарядные устройства для автомобиль d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO(  )COO"s, ResultType::Throw, R"MAN(JSON: expected ", got  )MAN"s },
		{ R"COO("/Хозтовары/Хранение вещей и организа   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Хозтовары/Товары для стир o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("li o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/igrushki/igrus d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/734859/samolet-radioupravlyaemyy-istrebitel-rabotaet-o  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/kosmetika-i-parfyum/parfyumeriya/mu 0)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/ko  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/avto/avtomobilnyy  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/stroitelstvo-i-remont/stroit 0)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/stroitelstvo-i-remont/stroitelnyy-instrument/av  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/s d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Строительство и ремонт/Строительный инструмент/Изм o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/avto/soputstvuy ")COO"s, ResultType::Return, R"MAN(/avto/soputstvuy )MAN"s },
		{ R"COO("/str k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Отвертка 2 в 1 \"TUNDRA basic\" 5х75 мм (+,-)   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/stroitelstvo-i-remont/stroitelnyy-instrument/avtoinstrumen =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Чайник электрический Vitesse =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Мелкая бытовая техника/Мелки   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Пряжа \"Бамбук стрейч\ о)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Карандаш чёрнографитны  k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Творчество/Рукоделие, аппликации/Пряжа и шерсть для   ")COO"s, ResultType::Return, R"MAN(/Творчество/Рукоделие, аппликации/Пряжа и шерсть для   )MAN"s },
		{ R"COO("/1071547/karandash-chernografitnyy-volshebstvo-nv-kruglyy-d-7-2mm-dl-176mm-plast-tuba/ o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("ca o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Подаро o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Средство для прочис  o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("i o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/p ")COO"s, ResultType::Return, R"MAN(/p )MAN"s },
		{ R"COO("/Сувениры/Магниты, н  k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Дерев  =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/prazdniki/svadba/svadebnaya-c  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Канцт d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Праздники/То   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("v  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Косметика   d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Спорт и отдых/Настольные игры/Покер, руле   )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("categ =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/retailr k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/retailrocket k)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Ежедневник недат А5 140л кл,ляссе,обл пв =)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/432809/ezhednevnik-organayzer-sredniy-s-remeshkom-na-knopke-v-oblozhke-kalkulyator-kalendar-do-  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/1165424/chipbord-vyrubnoy-dlya-skrapbukinga-malyshi-mikki-maus-disney-bebi d)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/posuda/kuhonnye-prinadlezhnosti-i-i  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/Канцтовары/Ежедневники и блокн  o)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("/kanctovary/ezhednevniki-i-blok 0)COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Стакан    )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("Набор бумаги для скрапбукинга \"Мои первый годик\": Микки Маус, Дисней бэби, 12 листов 29.5 х 29.5 см, 160  )COO"s, ResultType::Throw, R"MAN(JSON: incorrect syntax (expected end of string, found end of JSON).)MAN"s },
		{ R"COO("c ")COO"s, ResultType::Return, R"MAN(c )MAN"s }
	};

	for (auto i : boost::irange(0, 1/*00000*/))
	{
		static_cast<void>(i);

		for (auto &r : test_data)
		{
			JSON j(r.input.c_str(), r.input.c_str() + r.input.size());
			try
			{
				Test::compare(j.getString(), r.result);
				Test::compare(r.result_type == ResultType::Return, true);
			}
			catch (JSONException &e)
			{
				Test::compare(r.result_type == ResultType::Throw, true);
				Test::compare(e.message(), r.result);
			}
		}
	}
}

int main()
{
	get_string();
	return 0;
}
