#
# Makefile
#
# $Id: //poco/Main/Data/samples/Tuple/Makefile#2 $
#
# Makefile for Poco Data Tuple sample
#

include $(POCO_BASE)/build/rules/global

objects = Tuple

target         = Tuple
target_version = 1
target_libs    = PocoDataSQLite PocoData PocoFoundation 

include $(POCO_BASE)/build/rules/exec
