if (OS_FREEBSD)
    find_library (EXECINFO_LIBRARY execinfo)
    find_library (ELF_LIBRARY elf)
    message (STATUS "Using execinfo: ${EXECINFO_LIBRARY}")
    message (STATUS "Using elf: ${ELF_LIBRARY}")
else ()
    set (EXECINFO_LIBRARY "")
    set (ELF_LIBRARY "")
endif ()
