include_directories ("/usr/local/opt/icu4c/include")
set (ICU_HINTS "/usr/local/opt/icu4c/lib")
if (USE_STATIC_LIBRARIES)
	find_library (ICUI18N libicui18n.a HINTS ${ICU_HINTS})
	find_library (ICUUC libicuuc.a HINTS ${ICU_HINTS})
	find_library (ICUDATA libicudata.a HINTS ${ICU_HINTS})
else ()
	find_library (ICUI18N icui18n HINTS ${ICU_HINTS})
	find_library (ICUUC icuuc HINTS ${ICU_HINTS})
	find_library (ICUDATA icudata HINTS ${ICU_HINTS})
endif ()
set (ICU_LIBS ${ICUI18N} ${ICUUC} ${ICUDATA})
