#include "getResource.h"
#include <boost/algorithm/string/replace.hpp>
#include <Common/SymbolIndex.h>


std::string_view getResource(std::string_view name)
{
    // Convert the resource file name into the form generated by `ld -r -b binary`.
    std::string name_replaced(name);
    std::replace(name_replaced.begin(), name_replaced.end(), '/', '_');
    std::replace(name_replaced.begin(), name_replaced.end(), '-', '_');
    std::replace(name_replaced.begin(), name_replaced.end(), '.', '_');
    boost::replace_all(name_replaced, "+", "_PLUS_");

    /// If static linking is used, we cannot use dlsym and have to parse ELF symbol table by ourself.
    return DB::SymbolIndex::instance()->getResource(name_replaced);
}
