#
# Makefile
#
# $Id: Makefile 580 2008-06-01 20:56:01Z ryppka $
#
# Makefile for Poco LogRotation
#

include $(POCO_BASE)/build/rules/global

objects = LogRotation

target         = LogRotation
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
