name: DebugInfo
description: Prints workflow debug info

runs:
  using: "composite"
  steps:
    - name: Print envs
      shell: bash
      run: |
          echo "::group::Envs"
          env
          echo "::endgroup::"
    - name: Print Event.json
      shell: bash
      run: |
          echo "::group::Event.json"
          python3 -m json.tool "$GITHUB_EVENT_PATH"
          echo "::endgroup::"
