ATTACH VIEW columns
(
    `table_catalog` String,
    `table_schema` String,
    `table_name` String,
    `column_name` String,
    `ordinal_position` UInt64,
    `column_default` String,
    `is_nullable` String,
    `data_type` String,
    `character_maximum_length` Nullable(UInt64),
    `character_octet_length` Nullable(UInt64),
    `numeric_precision` Nullable(UInt64),
    `numeric_precision_radix` Nullable(UInt64),
    `numeric_scale` Nullable(UInt64),
    `datetime_precision` Nullable(UInt64),
    `character_set_catalog` Nullable(String),
    `character_set_schema` Nullable(String),
    `character_set_name` Nullable(String),
    `collation_catalog` Nullable(String),
    `collation_schema` Nullable(String),
    `collation_name` Nullable(String),
    `domain_catalog` Nullable(String),
    `domain_schema` Nullable(String),
    `domain_name` Nullable(String),
    `column_comment` String,
    `column_type` String,
    `TABLE_CATALOG` String,
    `TABLE_SCHEMA` String,
    `TABLE_NAME` String,
    `COLUMN_NAME` String,
    `ORDINAL_POSITION` UInt64,
    `COLUMN_DEFAULT` String,
    `IS_NULLABLE` String,
    `DATA_TYPE` String,
    `CHARACTER_MAXIMUM_LENGTH` Nullable(UInt64),
    `CHARACTER_OCTET_LENGTH` Nullable(UInt64),
    `NUMERIC_PRECISION` Nullable(UInt64),
    `NUMERIC_PRECISION_RADIX` Nullable(UInt64),
    `NUMERIC_SCALE` Nullable(UInt64),
    `DATETIME_PRECISION` Nullable(UInt64),
    `CHARACTER_SET_CATALOG` Nullable(String),
    `CHARACTER_SET_SCHEMA` Nullable(String),
    `CHARACTER_SET_NAME` Nullable(String),
    `COLLATION_CATALOG` Nullable(String),
    `COLLATION_SCHEMA` Nullable(String),
    `COLLATION_NAME` Nullable(String),
    `DOMAIN_CATALOG` Nullable(String),
    `DOMAIN_SCHEMA` Nullable(String),
    `DOMAIN_NAME` Nullable(String),
    `COLUMN_COMMENT` String,
    `COLUMN_TYPE` String
) AS
SELECT
    database AS table_catalog,
    database AS table_schema,
    table AS table_name,
    name AS column_name,
    position AS ordinal_position,
    default_expression AS column_default,
    type LIKE 'Nullable(%)' AS is_nullable,
    type AS data_type,
    character_octet_length AS character_maximum_length,
    character_octet_length,
    numeric_precision,
    numeric_precision_radix,
    numeric_scale,
    datetime_precision,
    NULL AS character_set_catalog,
    NULL AS character_set_schema,
    NULL AS character_set_name,
    NULL AS collation_catalog,
    NULL AS collation_schema,
    NULL AS collation_name,
    NULL AS domain_catalog,
    NULL AS domain_schema,
    NULL AS domain_name,
    comment AS column_comment,
    type AS column_type,
    table_catalog AS TABLE_CATALOG,
    table_schema AS TABLE_SCHEMA,
    table_name AS TABLE_NAME,
    column_name AS COLUMN_NAME,
    ordinal_position AS ORDINAL_POSITION,
    column_default AS COLUMN_DEFAULT,
    is_nullable AS IS_NULLABLE,
    data_type AS DATA_TYPE,
    character_maximum_length AS CHARACTER_MAXIMUM_LENGTH,
    character_octet_length AS CHARACTER_OCTET_LENGTH,
    numeric_precision AS NUMERIC_PRECISION,
    numeric_precision_radix AS NUMERIC_PRECISION_RADIX,
    numeric_scale AS NUMERIC_SCALE,
    datetime_precision AS DATETIME_PRECISION,
    character_set_catalog AS CHARACTER_SET_CATALOG,
    character_set_schema AS CHARACTER_SET_SCHEMA,
    character_set_name AS CHARACTER_SET_NAME,
    collation_catalog AS COLLATION_CATALOG,
    collation_schema AS COLLATION_SCHEMA,
    collation_name AS COLLATION_NAME,
    domain_catalog AS DOMAIN_CATALOG,
    domain_schema AS DOMAIN_SCHEMA,
    domain_name AS DOMAIN_NAME,
    column_comment AS COLUMN_COMMENT,
    column_type AS COLUMN_TYPE
FROM system.columns
