ATTACH VIEW key_column_usage
    (
     `constraint_catalog` String,
     `constraint_schema` String,
     `constraint_name` Nullable(String),
     `table_catalog` String,
     `table_schema` String,
     `table_name` String,
     `column_name` Nullable(String),
     `ordinal_position` UInt32,
     `position_in_unique_constraint` Nullable(UInt32),
     `referenced_table_schema` Nullable(String),
     `referenced_table_name` Nullable(String),
     `referenced_column_name` Nullable(String),
     `CONSTRAINT_CATALOG` Nullable(String) ALIAS constraint_catalog, 
     `CONSTRAINT_SCHEMA` Nullable(String) ALIAS constraint_schema,
     `CONSTRAINT_NAME` Nullable(String) ALIAS constraint_name,
     `TABLE_CATALOG` String ALIAS table_catalog,
     `TABLE_SCHEMA` String ALIAS table_schema,
     `TABLE_NAME` String ALIAS table_name,
     `COLUMN_NAME` Nullable(String) ALIAS column_name,
     `ORDINAL_POSITION` UInt32 ALIAS ordinal_position,
     `POSITION_IN_UNIQUE_CONSTRAINT` Nullable(UInt32) ALIAS position_in_unique_constraint,
     `REFERENCED_TABLE_SCHEMA` Nullable(String) ALIAS referenced_table_schema,
     `REFERENCED_TABLE_NAME` Nullable(String) ALIAS referenced_table_name,
     `REFERENCED_COLUMN_NAME` Nullable(String) ALIAS referenced_column_name
) AS
SELECT 'def'     AS `constraint_catalog`,
       database  AS `constraint_schema`,
       'PRIMARY' AS `constraint_name`,
       'def'     AS `table_catalog`,
       database  AS `table_schema`,
       table     AS `table_name`,
       name      AS `column_name`,
       position  AS `ordinal_position`,
       NULL      AS `position_in_unique_constraint`,
       NULL      AS `referenced_table_schema`,
       NULL      AS `referenced_table_name`,
       NULL      AS `referenced_column_name`
FROM system.columns
WHERE is_in_primary_key;
