ATTACH VIEW key_column_usage
    (
     `constraint_catalog` String,
     `constraint_schema` String,
     `constraint_name` Nullable(String),
     `table_catalog` String,
     `table_schema` String,
     `table_name` String,
     `column_name` Nullable(String),
     `ordinal_position` UInt32,
     `position_in_unique_constraint` Nullable(UInt32),
     `referenced_table_schema` Nullable(String),
     `referenced_table_name` Nullable(String),
     `referenced_column_name` Nullable(String),
     `CONSTRAINT_CATALOG` Nullable(String), 
     `CONSTRAINT_SCHEMA` Nullable(String),
     `CONSTRAINT_NAME` Nullable(String),
     `TABLE_CATALOG` String,
     `TABLE_SCHEMA` String,
     `TABLE_NAME` String,
     `COLUMN_NAME` Nullable(String),
     `ORDINAL_POSITION` UInt32,
     `POSITION_IN_UNIQUE_CONSTRAINT` Nullable(UInt32),
     `REFERENCED_TABLE_SCHEMA` Nullable(String),
     `REFERENCED_TABLE_NAME` Nullable(String),
     `REFERENCED_COLUMN_NAME` Nullable(String)
) AS
SELECT 
    'def'                         AS constraint_catalog,
    database                      AS constraint_schema,
    'PRIMARY'                     AS constraint_name,
    'def'                         AS table_catalog,
    database                      AS table_schema,
    table                         AS table_name,
    name                          AS column_name,
    1                             AS ordinal_position,
    NULL                          AS position_in_unique_constraint,
    NULL                          AS referenced_table_schema,
    NULL                          AS referenced_table_name,
    NULL                          AS referenced_column_name,
    constraint_catalog            AS CONSTRAINT_CATALOG,
    constraint_schema             AS CONSTRAINT_SCHEMA,
    constraint_name               AS CONSTRAINT_NAME,
    table_catalog                 AS TABLE_CATALOG,
    table_schema                  AS TABLE_SCHEMA,
    table_name                    AS TABLE_NAME,
    column_name                   AS COLUMN_NAME,
    ordinal_position              AS ORDINAL_POSITION,
    position_in_unique_constraint AS POSITION_IN_UNIQUE_CONSTRAINT,
    referenced_table_schema       AS REFERENCED_TABLE_SCHEMA,
    referenced_table_name         AS REFERENCED_TABLE_NAME,
    referenced_column_name        AS REFERENCED_COLUMN_NAME
FROM system.columns
WHERE is_in_primary_key;
