CREATE TABLE referential_constraints
    (
     `constraint_catalog` String,
     `constraint_schema` String,
     `constraint_name` Nullable(String),
     `unique_constraint_catalog` String,
     `unique_constraint_schema` String,
     `unique_constraint_name` Nullable(String),
     `match_option` String,
     `update_rule` String,
     `delete_rule` String,
     `table_name` String,
     `referenced_table_name` String,
     `CONSTRAINT_CATALOG` String,
     `CONSTRAINT_SCHEMA` String,
     `CONSTRAINT_NAME` Nullable(String),
     `UNIQUE_CONSTRAINT_CATALOG` String,
     `UNIQUE_CONSTRAINT_SCHEMA` String,
     `UNIQUE_CONSTRAINT_NAME` Nullable(String),
     `MATCH_OPTION` String,
     `UPDATE_RULE` String,
     `DELETE_RULE` String,
     `TABLE_NAME` String,
     `REFERENCED_TABLE_NAME` String
) ENGINE Memory;
