name: CherryPick
concurrency:
  group: cherry-pick
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 */3 * * *'
jobs:
  CherryPick:
    runs-on: [self-hosted, style-checker]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN}}
          fetch-depth: 0
      - name: Cherry pick
        env:
          TEMP_PATH: ${{runner.temp}}/cherry_pick
          ROBOT_CLICKHOUSE_SSH_KEY: ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
          REPO_OWNER: "ClickHouse"
          REPO_NAME: "ClickHouse"
          REPO_TEAM: "core"
        run: |
          sudo pip install GitPython
          cd $GITHUB_WORKSPACE/tests/ci
          python3 cherry_pick.py
      - name: Cleanup
        if: always()
        run: |
          docker kill $(docker ps -q) ||:
          docker rm -f $(docker ps -a -q) ||:
          sudo rm -fr $TEMP_PATH
