name: CherryPick

env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1

concurrency:
  group: cherry-pick
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 */3 * * *'
jobs:
  CherryPick:
    runs-on: [self-hosted, style-checker]
    steps:
      - name: Set envs
        # https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#multiline-strings
        run: |
          cat >> "$GITHUB_ENV" << 'EOF'
          TEMP_PATH=${{runner.temp}}/cherry_pick
          ROBOT_CLICKHOUSE_SSH_KEY<<RCSK
          ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
          RCSK
          REPO_OWNER=ClickHouse
          REPO_NAME=ClickHouse
          REPO_TEAM=core
          EOF
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.ROBOT_CLICKHOUSE_COMMIT_TOKEN}}
          fetch-depth: 0
      - name: Cherry pick
        run: |
          sudo pip install GitPython
          cd "$GITHUB_WORKSPACE/tests/ci"
          python3 cherry_pick.py
      - name: Cleanup
        if: always()
        run: |
          docker kill "$(docker ps -q)" ||:
          docker rm -f "$(docker ps -a -q)" ||:
          sudo rm -fr "$TEMP_PATH"
