name: CherryPick
concurrency:
  group: cherry-pick
on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - labeled
    branches:
      - master
  schedule:
    - cron: '0 */3 * * *'
jobs:
  CherryPick:
    runs-on: [self-hosted, style-checker]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Cherry pick
        env:
          TEMP_PATH: ${{runner.temp}}/cherry_pick
          REPO_COPY: ${{runner.temp}}/cherry_pick/ClickHouse
          ROBOT_CLICKHOUSE_SSH_KEY: ${{secrets.ROBOT_CLICKHOUSE_SSH_KEY}}
          REPO_OWNER: "ClickHouse"
          REPO_NAME: "ClickHouse"
          REPO_TEAM: "core"
        run: |
          ls -la "$GITHUB_WORKSPACE"
          ls -la "$GITHUB_WORKSPACE/tests/ci"
          cp -r $GITHUB_WORKSPACE $TEMP_PATH
          ls -la "$TEMP_PATH"
          ls -la "$REPO_COPY"
          cd $REPO_COPY/tests/ci
          python3 cherry_pick.py
      - name: Cleanup
        if: always()
        run: |
          docker kill $(docker ps -q) ||:
          docker rm -f $(docker ps -a -q) ||:
          sudo rm -fr $TEMP_PATH
