env:
  PYTHONUNBUFFERED: 1

name: StageWF

'on':
  workflow_call:
    inputs:
      stage:
        description: stage name
        type: string
        required: true
      data:
        description: ci data
        type: string
        required: true
    secrets:
      robot_git_token:
        required: false
      ci_db_url:
        required: false
      ci_db_password:
        required: false

jobs:
  s:
    if: ${{ !failure() && !cancelled() }}
    strategy:
      fail-fast: false
      matrix:
        job_name_and_runner_type: ${{ fromJson(inputs.data).stages_data[inputs.stage] }}
    uses: ./.github/workflows/reusable_test.yml
    with:
      test_name: ${{ matrix.job_name_and_runner_type.job_name }}
      runner_type: ${{ matrix.job_name_and_runner_type.runner_type }}
      data: ${{ inputs.data }}
    secrets:
      robot_git_token: ${{ secrets.robot_git_token }}
      ci_db_url: ${{ secrets.ci_db_url }}
      ci_db_password: ${{ secrets.ci_db_password }}
