name: Scheduled Altinity Stable Builds

on:
  schedule:
    - cron: '0 0 * * 6' #Weekly run for stable versions 
    - cron: '0 0 * * *' #Daily run for antalya versions
  # Make sure that any changes to this file is actually tested with PRs
  pull_request:
    types:
      - synchronize
      - reopened
      - opened
    paths:
      - '**/scheduled_runs.yml'

jobs:
  DailyRuns:
    strategy:
      fail-fast: false
      matrix:
        branch: 
          - antalya
    name: ${{ matrix.branch }}
    if: github.event.schedule != '0 0 * * 6'
    runs-on: ubuntu-latest
    steps:
     - name: Run ${{ matrix.branch }} workflow
       run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Altinity/ClickHouse/actions/workflows/release_branches.yml/dispatches \
          -d '{"ref":"${{ matrix.branch }}"}'

  WeeklyRuns:
    strategy:
      fail-fast: false
      matrix:
        branch: 
          - customizations/24.8.14
    name: ${{ matrix.branch }}
    if: github.event.schedule != '0 0 * * *'
    runs-on: ubuntu-latest
    steps:
     - name: Run ${{ matrix.branch }} workflow
       run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Altinity/ClickHouse/actions/workflows/release_branches.yml/dispatches \
          -d '{"ref":"${{ matrix.branch }}"}'
