name: Ligthweight GithubActions
on: # yamllint disable-line rule:truthy
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - reopened
      - opened
    branches:
      - master
jobs:
  CheckLabels:
    runs-on: [self-hosted]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Labels check
        run: cd $GITHUB_WORKSPACE/tests/ci && python3 run_check.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DockerHubPush:
    needs: CheckLabels
    runs-on: [self-hosted]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Images check
        run: echo "Hello world"
  Style-Check:
    needs: DockerHubPush
    runs-on: [self-hosted]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Style Check
        env:
          YANDEX_S3_ACCESS_KEY_ID: ${{ secrets.YANDEX_S3_ACCESS_KEY_ID }}
          YANDEX_S3_ACCESS_SECRET_KEY: ${{ secrets.YANDEX_S3_ACCESS_SECRET_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd $GITHUB_WORKSPACE/tests/ci && python3 style_check.py
