#
# Makefile
#
# $Id: //poco/1.4/Foundation/samples/uuidgen/Makefile#1 $
#
# Makefile for Poco uuidgen
#

include $(POCO_BASE)/build/rules/global

objects = uuidgen

target         = uuidgen
target_version = 1
target_libs    = PocoFoundation

include $(POCO_BASE)/build/rules/exec
